
# Experiment 18 — Strong Official PatchTST Baselines on Weather and Electricity

## 목적

이번 실험에서는 retrieval을 붙이지 않습니다.

먼저 Weather와 Electricity에서 공식 PatchTST supervised recipe를 사용하여
강한 direct forecasting baseline을 확정합니다.

$$
H \in \{96, 192, 336, 720\}
$$

그리고 이후 Experiment 19에서 이 checkpoint를 **그대로 고정한 상태로**
기존 frozen historical-memory module을 적용합니다.

---

## 왜 이 실험을 분리하는가?

이전 screening에서는 모든 데이터셋에 거의 동일한 PatchTST 설정을 사용했습니다.
하지만 공식 PatchTST는 데이터셋마다 capacity와 optimization recipe가 다릅니다.

따라서 다음 비교를 하기 전에

$$
\boxed{
\text{Strong PatchTST} + \text{Historical Memory}
\quad \text{vs.} \quad
\text{Strong PatchTST}
}
$$

먼저 Strong PatchTST 자체를 독립적으로 확정해야 합니다.

---

## Official Weather recipe

공식 `weather.sh`를 따릅니다.

$$
L = 336
$$

- channels: 21
- encoder layers: 3
- heads: 16
- model dimension: 128
- FFN dimension: 256
- dropout: 0.2
- FC dropout: 0.2
- patch length: 16
- stride: 8
- batch size: 128
- learning rate: \(10^{-4}\)
- epochs: 100
- patience: 20
- seed: 2021
- LR schedule: default `type3`
- RevIN: on
- RevIN affine: off

---

## Official Electricity recipe

공식 `electricity.sh`를 따릅니다.

$$
L = 336
$$

- channels: 321
- encoder layers: 3
- heads: 16
- model dimension: 128
- FFN dimension: 256
- dropout: 0.2
- FC dropout: 0.2
- patch length: 16
- stride: 8
- batch size: 32
- learning rate: \(10^{-4}\)
- epochs: 100
- patience: 10
- seed: 2021
- LR schedule: `TST`
- OneCycleLR `pct_start=0.2`
- RevIN: on
- RevIN affine: off

---

## Data protocol

두 데이터셋 모두 공식 `Dataset_Custom` protocol을 재현합니다.

전체 길이를 \(N\)이라 할 때,

$$
N_{\text{train}} = \lfloor 0.7N \rfloor
$$

$$
N_{\text{test}} = \lfloor 0.2N \rfloor
$$

$$
N_{\text{val}}
=
N-N_{\text{train}}-N_{\text{test}}
$$

StandardScaler는 **train 구간에만 fit**합니다.

Validation/test에서는 input context가 split boundary 이전으로 이어질 수 있도록
공식 구현처럼 `seq_len`만큼 border를 뒤로 확장합니다.

---

## 두 종류의 test metric

### OfficialStyle

공식 `data_factory.py`와 동일하게

- `shuffle=False`
- `drop_last=True`

로 평가합니다.

### FullStride1

향후 retrieval augmentation과 동일한 sample set 비교를 위해

- 모든 valid test origin
- stride 1
- `drop_last=False`

로도 평가합니다.

Experiment 19의 direct baseline으로는 반드시 **FullStride1**을 사용합니다.

In [1]:

from pathlib import Path
from types import SimpleNamespace
import gc
import importlib
import json
import os
import random
import subprocess
import sys
import time
import warnings

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from sklearn.preprocessing import StandardScaler
from torch.utils.data import Dataset, DataLoader

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 420)

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

DATASETS = ["Weather", "Electricity"]
HORIZONS = [96, 192, 336, 720]

SEQ_LEN = 336
LABEL_LEN = 48
SEED = 2021

RESULT_ROOT = Path(
    "/data/dataset/strong_forecaster/"
    "weather_electricity_official_patchtst_baselines"
)

CHECKPOINT_DIR = RESULT_ROOT / "full_direct"
HISTORY_DIR = RESULT_ROOT / "history"
ARTIFACT_DIR = RESULT_ROOT / "artifacts"

for p in [
    RESULT_ROOT,
    CHECKPOINT_DIR,
    HISTORY_DIR,
    ARTIFACT_DIR,
]:
    p.mkdir(parents=True, exist_ok=True)

RESUME = True
FORCE_RETRAIN = False

print("Device:", DEVICE)
print("PyTorch:", torch.__version__)
print("Output:", RESULT_ROOT)

Device: cuda
PyTorch: 2.12.1+cu126
Output: /data/dataset/strong_forecaster/weather_electricity_official_patchtst_baselines

## 1. Locate the official PatchTST repository

In [2]:

OFFICIAL_REPO_CANDIDATES = [
    Path(
        "/code/stock_regime_retrieval/"
        "strong_forecaster/PatchTST_official"
    ),
    Path("/code/PatchTST_official"),
    Path("/data/PatchTST_official"),
    Path("/data/PatchTST"),
]

OFFICIAL_REPO = next(
    (
        p for p in OFFICIAL_REPO_CANDIDATES
        if (
            p
            / "PatchTST_supervised"
            / "models"
            / "PatchTST.py"
        ).exists()
    ),
    None,
)

if OFFICIAL_REPO is None:
    OFFICIAL_REPO = OFFICIAL_REPO_CANDIDATES[0]
    OFFICIAL_REPO.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    print(
        "Official repository not found. Cloning:",
        OFFICIAL_REPO,
    )

    subprocess.run(
        [
            "git",
            "clone",
            "--depth",
            "1",
            "https://github.com/yuqinie98/PatchTST.git",
            str(OFFICIAL_REPO),
        ],
        check=True,
    )

SUPERVISED_ROOT = (
    OFFICIAL_REPO
    / "PatchTST_supervised"
)

if not (
    SUPERVISED_ROOT
    / "models"
    / "PatchTST.py"
).exists():
    raise FileNotFoundError(
        f"Official supervised model not found: {SUPERVISED_ROOT}"
    )

try:
    commit = subprocess.check_output(
        [
            "git",
            "-C",
            str(OFFICIAL_REPO),
            "rev-parse",
            "HEAD",
        ],
        text=True,
    ).strip()
except Exception:
    commit = "unknown"

print("Official repo:", OFFICIAL_REPO)
print("Supervised root:", SUPERVISED_ROOT)
print("Git commit:", commit)

(ARTIFACT_DIR / "official_repo_commit.txt").write_text(
    commit + "\n"
)

Official repo: /code/stock_regime_retrieval/strong_forecaster/PatchTST_official
Supervised root: /code/stock_regime_retrieval/strong_forecaster/PatchTST_official/PatchTST_supervised
Git commit: 204c21efe0b39603ad6e2ca640ef5896646ab1a9

41

## 2. Import the official PatchTST model only

In [3]:

# Avoid accidental import of Time-Series-Library modules
# with the same top-level names.
for module_name in list(sys.modules.keys()):
    if (
        module_name == "models"
        or module_name.startswith("models.")
        or module_name == "layers"
        or module_name.startswith("layers.")
    ):
        del sys.modules[module_name]

if str(SUPERVISED_ROOT) in sys.path:
    sys.path.remove(str(SUPERVISED_ROOT))

sys.path.insert(0, str(SUPERVISED_ROOT))

patchtst_module = importlib.import_module(
    "models.PatchTST"
)

OfficialPatchTST = patchtst_module.Model

actual_model_file = Path(
    patchtst_module.__file__
).resolve()

expected_model_file = (
    SUPERVISED_ROOT
    / "models"
    / "PatchTST.py"
).resolve()

print("Imported model:", actual_model_file)

if actual_model_file != expected_model_file:
    raise RuntimeError(
        "Wrong PatchTST implementation imported.\n"
        f"Expected: {expected_model_file}\n"
        f"Actual:   {actual_model_file}"
    )

print(
    "PASS: official PatchTST supervised implementation is active."
)

Imported model: /code/stock_regime_retrieval/strong_forecaster/PatchTST_official/PatchTST_supervised/models/PatchTST.py
PASS: official PatchTST supervised implementation is active.


## 3. Dataset paths

아래 셀은 recursive filesystem search를 하지 않습니다.
기존 실험에서 사용한 일반적인 데이터 위치만 확인하므로 빠르게 실행됩니다.

데이터를 다른 위치에 두었다면 `DATA_PATH_CANDIDATES`에 해당 경로만 추가하면 됩니다.

In [4]:

DATA_PATH_CANDIDATES = {
    "Weather": [
        Path("/data/dataset/weather.csv"),
        Path("/data/dataset/weather/weather.csv"),
        Path("/data/Time-Series-Library/dataset/weather/weather.csv"),
        Path("/data/Time-Series-Library/dataset/weather.csv"),
        Path("/data/Time-Series-Library_v2/dataset/weather/weather.csv"),
        Path("/data/Time-Series-Library_v2/dataset/weather.csv"),
        Path("/code/stock_regime_retrieval/strong_forecaster/data/weather.csv"),
    ],
    "Electricity": [
        Path("/data/dataset/electricity.csv"),
        Path("/data/dataset/electricity/electricity.csv"),
        Path("/data/Time-Series-Library/dataset/electricity/electricity.csv"),
        Path("/data/Time-Series-Library/dataset/electricity.csv"),
        Path("/data/Time-Series-Library_v2/dataset/electricity/electricity.csv"),
        Path("/data/Time-Series-Library_v2/dataset/electricity.csv"),
        Path("/code/stock_regime_retrieval/strong_forecaster/data/electricity.csv"),
    ],
}

DATA_PATHS = {}

for name, candidates in DATA_PATH_CANDIDATES.items():
    hit = next(
        (p for p in candidates if p.is_file()),
        None,
    )

    DATA_PATHS[name] = hit

    print(
        f"{name:11s}:",
        hit if hit is not None else "NOT FOUND",
    )

missing = [
    name
    for name, path in DATA_PATHS.items()
    if path is None
]

if missing:
    print("\nAttempted paths:")
    for name in missing:
        print(f"\n{name}")
        for p in DATA_PATH_CANDIDATES[name]:
            print(" -", p)

    raise FileNotFoundError(
        "Dataset file(s) not found: "
        + ", ".join(missing)
        + ". Add the actual path to DATA_PATH_CANDIDATES."
    )

Weather    : /data/Time-Series-Library/dataset/weather/weather.csv
Electricity: /data/Time-Series-Library/dataset/electricity/electricity.csv

## 4. Reproduce the official `Dataset_Custom` data protocol

In [5]:

EXPECTED_CHANNELS = {
    "Weather": 21,
    "Electricity": 321,
}


def prepare_custom_data(name):
    path = DATA_PATHS[name]
    df_raw = pd.read_csv(path)

    if "date" not in df_raw.columns:
        raise ValueError(
            f"{name}: official Dataset_Custom requires a 'date' column."
        )

    # Official Dataset_Custom moves target 'OT' to the final column.
    # For M forecasting this preserves the exact official column ordering.
    if "OT" not in df_raw.columns:
        raise ValueError(
            f"{name}: official script uses the default target='OT', "
            "but the CSV has no OT column. "
            f"First columns: {df_raw.columns.tolist()[:10]}"
        )

    cols = list(df_raw.columns)
    cols.remove("OT")
    cols.remove("date")

    ordered = df_raw[
        ["date"] + cols + ["OT"]
    ].copy()

    value_cols = list(
        ordered.columns[1:]
    )

    raw = ordered[
        value_cols
    ].to_numpy(
        dtype=np.float32
    )

    n = len(raw)

    num_train = int(n * 0.7)
    num_test = int(n * 0.2)
    num_val = n - num_train - num_test

    train_end = num_train
    val_end = num_train + num_val
    test_end = n

    scaler = StandardScaler()
    scaler.fit(
        raw[:train_end]
    )

    z = scaler.transform(
        raw
    ).astype(
        np.float32
    )

    expected_c = EXPECTED_CHANNELS[name]

    if raw.shape[1] != expected_c:
        raise ValueError(
            f"{name}: expected {expected_c} channels from the official "
            f"script but found {raw.shape[1]}."
        )

    return {
        "name": name,
        "path": path,
        "df": ordered,
        "columns": value_cols,
        "raw": raw,
        "z": z,
        "mean": scaler.mean_.astype(np.float32),
        "scale": scaler.scale_.astype(np.float32),
        "n_channels": raw.shape[1],
        "n": n,
        "train_end": train_end,
        "val_end": val_end,
        "test_end": test_end,
        "num_train": num_train,
        "num_val": num_val,
        "num_test": num_test,
    }


DATA = {
    name: prepare_custom_data(name)
    for name in DATASETS
}

protocol_df = pd.DataFrame([
    {
        "Dataset": name,
        "Path": str(d["path"]),
        "Rows": d["n"],
        "Channels": d["n_channels"],
        "TrainRows": d["num_train"],
        "ValRows": d["num_val"],
        "TestRows": d["num_test"],
        "TrainEnd": d["train_end"],
        "ValEnd": d["val_end"],
        "TestEnd": d["test_end"],
    }
    for name, d in DATA.items()
])

display(protocol_df)

protocol_df.to_csv(
    ARTIFACT_DIR / "dataset_protocol.csv",
    index=False,
)

       Dataset                                               Path   Rows  Channels  TrainRows  ValRows  TestRows  TrainEnd  ValEnd  TestEnd
0      Weather  /data/Time-Series-Library/dataset/weather/weat...  52696        21      36887     5270     10539     36887   42157    52696
1  Electricity  /data/Time-Series-Library/dataset/electricity/...  26304       321      18412     2632      5260     18412   21044    26304

## 5. Official recipes

In [6]:

RECIPES = {
    "Weather": {
        "enc_in": 21,
        "e_layers": 3,
        "n_heads": 16,
        "d_model": 128,
        "d_ff": 256,
        "dropout": 0.2,
        "fc_dropout": 0.2,
        "head_dropout": 0.0,
        "patch_len": 16,
        "stride": 8,
        "batch_size": 128,
        "train_epochs": 100,
        "patience": 20,
        "learning_rate": 1e-4,
        # weather.sh does not override these parser defaults.
        "lradj": "type3",
        "pct_start": 0.3,
        "seed": 2021,
    },
    "Electricity": {
        "enc_in": 321,
        "e_layers": 3,
        "n_heads": 16,
        "d_model": 128,
        "d_ff": 256,
        "dropout": 0.2,
        "fc_dropout": 0.2,
        "head_dropout": 0.0,
        "patch_len": 16,
        "stride": 8,
        "batch_size": 32,
        "train_epochs": 100,
        "patience": 10,
        "learning_rate": 1e-4,
        "lradj": "TST",
        "pct_start": 0.2,
        "seed": 2021,
    },
}

display(
    pd.DataFrame(RECIPES).T
)

            enc_in e_layers n_heads d_model d_ff dropout fc_dropout head_dropout patch_len stride batch_size train_epochs patience learning_rate  lradj pct_start  seed
Weather         21        3      16     128  256     0.2        0.2          0.0        16      8        128          100       20        0.0001  type3       0.3  2021
Electricity    321        3      16     128  256     0.2        0.2          0.0        16      8         32          100       10        0.0001    TST       0.2  2021


## 6. Local Dataset class with exact official borders

Validation과 test는 split boundary에서 바로 시작하는 forecast origin을 포함하기 위해
context만 이전 split에 걸쳐 사용합니다.

예를 들어 validation의 `border1`은

$$
N_{\text{train}} - L
$$

입니다.

하지만 target은 validation boundary 이후에만 위치하므로 label leakage는 없습니다.

In [7]:

class CustomForecastDataset(Dataset):
    def __init__(
        self,
        name,
        flag,
        horizon,
    ):
        super().__init__()

        if flag not in {
            "train",
            "val",
            "test",
        }:
            raise ValueError(flag)

        self.name = name
        self.flag = flag
        self.horizon = int(horizon)

        d = DATA[name]
        z = d["z"]

        border1s = [
            0,
            d["train_end"] - SEQ_LEN,
            d["val_end"] - SEQ_LEN,
        ]

        border2s = [
            d["train_end"],
            d["val_end"],
            d["test_end"],
        ]

        idx = {
            "train": 0,
            "val": 1,
            "test": 2,
        }[flag]

        self.border1 = int(border1s[idx])
        self.border2 = int(border2s[idx])

        self.data_x = z[
            self.border1:
            self.border2
        ]

    def __getitem__(self, index):
        s_begin = index
        s_end = s_begin + SEQ_LEN

        r_begin = s_end - LABEL_LEN
        r_end = (
            r_begin
            + LABEL_LEN
            + self.horizon
        )

        seq_x = self.data_x[
            s_begin:s_end
        ]

        seq_y = self.data_x[
            r_begin:r_end
        ]

        return (
            torch.from_numpy(seq_x),
            torch.from_numpy(seq_y),
        )

    def __len__(self):
        return (
            len(self.data_x)
            - SEQ_LEN
            - self.horizon
            + 1
        )


window_rows = []

for name in DATASETS:
    for h in HORIZONS:
        for flag in [
            "train",
            "val",
            "test",
        ]:
            ds = CustomForecastDataset(
                name,
                flag,
                h,
            )

            window_rows.append({
                "Dataset": name,
                "Horizon": h,
                "Split": flag,
                "Windows": len(ds),
                "Border1": ds.border1,
                "Border2": ds.border2,
            })

display(
    pd.DataFrame(window_rows)
)

        Dataset  Horizon  Split  Windows  Border1  Border2
0       Weather       96  train    36456        0    36887
1       Weather       96    val     5175    36551    42157
2       Weather       96   test    10444    41821    52696
3       Weather      192  train    36360        0    36887
4       Weather      192    val     5079    36551    42157
5       Weather      192   test    10348    41821    52696
6       Weather      336  train    36216        0    36887
7       Weather      336    val     4935    36551    42157
8       Weather      336   test    10204    41821    52696
9       Weather      720  train    35832        0    36887
10      Weather      720    val     4551    36551    42157
11      Weather      720   test     9820    41821    52696
12  Electricity       96  train    17981        0    18412
13  Electricity       96    val     2537    18076    21044
14  Electricity       96   test     5165    20708    26304
15  Electricity      192  train    17885        0    18412
16  Electricity      192    val     2441    18076    21044
17  Electricity      192   test     5069    20708    26304
18  Electricity      336  train    17741        0    18412
19  Electricity      336    val     2297    18076    21044
20  Electricity      336   test     4925    20708    26304
21  Electricity      720  train    17357        0    18412
22  Electricity      720    val     1913    18076    21044
23  Electricity      720   test     4541    20708    26304

## 7. Build official PatchTST

In [8]:

def make_config(name, horizon):
    r = RECIPES[name]

    return SimpleNamespace(
        enc_in=r["enc_in"],
        seq_len=SEQ_LEN,
        pred_len=int(horizon),
        e_layers=r["e_layers"],
        n_heads=r["n_heads"],
        d_model=r["d_model"],
        d_ff=r["d_ff"],
        dropout=r["dropout"],
        fc_dropout=r["fc_dropout"],
        head_dropout=r["head_dropout"],
        individual=0,
        patch_len=r["patch_len"],
        stride=r["stride"],
        padding_patch="end",
        revin=1,
        affine=0,
        subtract_last=0,
        decomposition=0,
        kernel_size=25,
    )


def build_model(name, horizon):
    model = OfficialPatchTST(
        make_config(
            name,
            horizon,
        )
    ).float().to(DEVICE)

    return model


param_rows = []

for name in DATASETS:
    for h in HORIZONS:
        model = build_model(name, h)

        params = sum(
            p.numel()
            for p in model.parameters()
            if p.requires_grad
        )

        param_rows.append({
            "Dataset": name,
            "Horizon": h,
            "TrainableParams": params,
            "TrainableParams_M": params / 1e6,
        })

        del model

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()

display(
    pd.DataFrame(param_rows)
)

       Dataset  Horizon  TrainableParams  TrainableParams_M
0      Weather       96           921184           0.921184
1      Weather      192          1437376           1.437376
2      Weather      336          2211664           2.211664
3      Weather      720          4276432           4.276432
4  Electricity       96           921184           0.921184
5  Electricity      192          1437376           1.437376
6  Electricity      336          2211664           2.211664
7  Electricity      720          4276432           4.276432

## 8. DataLoaders

In [9]:

def make_loaders(name, horizon):
    r = RECIPES[name]

    train_ds = CustomForecastDataset(
        name,
        "train",
        horizon,
    )

    val_ds = CustomForecastDataset(
        name,
        "val",
        horizon,
    )

    test_ds = CustomForecastDataset(
        name,
        "test",
        horizon,
    )

    # Official data_factory:
    # train/val: shuffle=True, drop_last=True
    # test: shuffle=False, drop_last=True
    train_loader = DataLoader(
        train_ds,
        batch_size=r["batch_size"],
        shuffle=True,
        num_workers=0,
        drop_last=True,
    )

    val_loader = DataLoader(
        val_ds,
        batch_size=r["batch_size"],
        shuffle=True,
        num_workers=0,
        drop_last=True,
    )

    official_test_loader = DataLoader(
        test_ds,
        batch_size=r["batch_size"],
        shuffle=False,
        num_workers=0,
        drop_last=True,
    )

    # Our matched evaluation for Experiment 19.
    full_test_loader = DataLoader(
        test_ds,
        batch_size=r["batch_size"],
        shuffle=False,
        num_workers=0,
        drop_last=False,
    )

    return {
        "train_ds": train_ds,
        "val_ds": val_ds,
        "test_ds": test_ds,
        "train": train_loader,
        "val": val_loader,
        "official_test": official_test_loader,
        "full_test": full_test_loader,
    }

## 9. Evaluation

In [10]:

@torch.no_grad()
def evaluate_loader(
    model,
    loader,
    horizon,
):
    model.eval()

    batch_mse = []

    sse = 0.0
    sae = 0.0
    count = 0
    windows = 0

    for batch_x, batch_y in loader:
        x = batch_x.float().to(DEVICE)

        y = batch_y[
            :,
            -horizon:,
            :
        ].float().to(DEVICE)

        pred = model(x)[
            :,
            -horizon:,
            :
        ]

        err = pred - y

        batch_mse.append(
            float(
                (err ** 2).mean().item()
            )
        )

        sse += float(
            (err ** 2).sum().item()
        )

        sae += float(
            err.abs().sum().item()
        )

        count += err.numel()
        windows += len(x)

        del x, y, pred, err

    return {
        "BatchAverageMSE": float(
            np.mean(batch_mse)
        ),
        "MSE": sse / count,
        "MAE": sae / count,
        "Elements": count,
        "Batches": len(batch_mse),
        "Windows": windows,
    }

## 10. Official learning-rate behavior

In [11]:

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    # Keep behavior close to the official script.
    torch.backends.cudnn.benchmark = False


def adjust_type3_lr(
    optimizer,
    base_lr,
    epoch,
):
    # Official PatchTST utils/tools.py type3 rule.
    lr = (
        base_lr
        if epoch < 3
        else base_lr
        * (
            0.9
            ** (
                epoch - 3
            )
        )
    )

    for group in optimizer.param_groups:
        group["lr"] = lr

    return lr

## 11. Checkpoint paths

In [12]:

def checkpoint_path(
    name,
    horizon,
):
    safe = name.lower()

    return (
        CHECKPOINT_DIR
        / (
            f"{safe}_L336_H{horizon}_"
            "official_recipe_seed2021.pt"
        )
    )


def history_path(
    name,
    horizon,
):
    safe = name.lower()

    return (
        HISTORY_DIR
        / (
            f"{safe}_L336_H{horizon}_"
            "official_recipe_seed2021.csv"
        )
    )


## 12. Training loop

Model selection에는 validation loss만 사용합니다.

공식 training code는 epoch마다 test loss도 출력하지만,
이번 notebook에서는 test를 training 중에 평가하지 않습니다.

이는 optimization이나 checkpoint selection을 바꾸지 않으면서
test inspection을 피하기 위한 더 엄격한 protocol입니다.

In [13]:

def train_or_load(
    name,
    horizon,
):
    r = RECIPES[name]
    ckpt_path = checkpoint_path(
        name,
        horizon,
    )

    if (
        RESUME
        and ckpt_path.exists()
        and not FORCE_RETRAIN
    ):
        ckpt = torch.load(
            ckpt_path,
            map_location=DEVICE,
        )

        model = build_model(
            name,
            horizon,
        )

        model.load_state_dict(
            ckpt["StateDict"]
        )

        model.eval()

        print(
            f"Loaded {name} H={horizon}: "
            f"best={ckpt['BestValMSE']:.6f}"
            f"@{ckpt['BestEpoch']}"
        )

        return (
            model,
            ckpt,
            make_loaders(
                name,
                horizon,
            ),
        )

    set_seed(
        r["seed"]
    )

    loaders = make_loaders(
        name,
        horizon,
    )

    model = build_model(
        name,
        horizon,
    )

    # Official exp_main.py uses Adam.
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=r["learning_rate"],
    )

    onecycle = torch.optim.lr_scheduler.OneCycleLR(
        optimizer=optimizer,
        steps_per_epoch=len(
            loaders["train"]
        ),
        pct_start=r["pct_start"],
        epochs=r["train_epochs"],
        max_lr=r["learning_rate"],
    )

    best_val = float("inf")
    best_epoch = -1
    best_state = None
    wait = 0
    history = []

    for epoch in range(
        1,
        r["train_epochs"] + 1,
    ):
        model.train()

        losses = []
        t0 = time.time()

        for batch_x, batch_y in loaders["train"]:
            x = batch_x.float().to(DEVICE)

            y = batch_y[
                :,
                -horizon:,
                :
            ].float().to(DEVICE)

            optimizer.zero_grad(
                set_to_none=True
            )

            pred = model(x)[
                :,
                -horizon:,
                :
            ]

            loss = F.mse_loss(
                pred,
                y,
            )

            loss.backward()
            optimizer.step()

            losses.append(
                float(
                    loss.item()
                )
            )

            if r["lradj"] == "TST":
                # Match official PatchTST ordering:
                # read current OneCycle LR, assign it,
                # then advance scheduler.
                current = onecycle.get_last_lr()[0]

                for group in optimizer.param_groups:
                    group["lr"] = current

                onecycle.step()

            del x, y, pred, loss

        train_mse = float(
            np.mean(losses)
        )

        val = evaluate_loader(
            model,
            loaders["val"],
            horizon,
        )

        # Official EarlyStopping receives mean validation batch MSE.
        val_for_selection = val[
            "BatchAverageMSE"
        ]

        if (
            val_for_selection
            < best_val
            - 1e-12
        ):
            best_val = val_for_selection
            best_epoch = epoch

            best_state = {
                k:
                    v.detach()
                    .cpu()
                    .clone()
                for k, v
                in model.state_dict().items()
            }

            wait = 0
        else:
            wait += 1

        if r["lradj"] != "TST":
            lr = adjust_type3_lr(
                optimizer,
                r["learning_rate"],
                epoch,
            )
        else:
            lr = onecycle.get_last_lr()[0]

        history.append({
            "Epoch": epoch,
            "TrainMSE": train_mse,
            "ValBatchAverageMSE": val_for_selection,
            "ValGlobalMSE": val["MSE"],
            "ValMAE": val["MAE"],
            "BestValMSE": best_val,
            "BestEpoch": best_epoch,
            "LR": lr,
            "Seconds": time.time() - t0,
        })

        print(
            f"{name:11s} H={horizon:3d} "
            f"ep={epoch:03d}/{r['train_epochs']} | "
            f"train={train_mse:.6f} | "
            f"val={val_for_selection:.6f} | "
            f"best={best_val:.6f}@{best_epoch} | "
            f"lr={lr:.3e} | "
            f"wait={wait}/{r['patience']}"
        )

        pd.DataFrame(
            history
        ).to_csv(
            history_path(
                name,
                horizon,
            ),
            index=False,
        )

        if wait >= r["patience"]:
            print(
                f"Early stopping: {name} H={horizon} "
                f"at epoch {epoch}."
            )
            break

    if best_state is None:
        raise RuntimeError(
            f"{name} H={horizon}: no checkpoint selected."
        )

    model.load_state_dict(
        best_state
    )

    model.eval()

    ckpt = {
        "Dataset": name,
        "SeqLen": SEQ_LEN,
        "PredLen": int(horizon),
        "Seed": r["seed"],
        "Recipe": r,
        "OfficialRepoCommit": commit,
        "BestEpoch": int(best_epoch),
        "BestValMSE": float(best_val),
        "StateDict": best_state,
    }

    torch.save(
        ckpt,
        ckpt_path,
    )

    return (
        model,
        ckpt,
        loaders,
    )


## 13. Run all eight strong baselines

실행 순서는 다음과 같습니다.

$$
\text{Weather: }96 \rightarrow 192 \rightarrow 336 \rightarrow 720
$$

$$
\text{Electricity: }96 \rightarrow 192 \rightarrow 336 \rightarrow 720
$$

각 조건이 완료될 때마다 checkpoint와 summary를 저장합니다.
따라서 중간에 커널이 종료되어도 `RESUME=True`로 이어갈 수 있습니다.

In [14]:

SUMMARY_PATH = (
    RESULT_ROOT
    / "summary.csv"
)

existing = (
    pd.read_csv(
        SUMMARY_PATH
    )
    if (
        RESUME
        and SUMMARY_PATH.exists()
    )
    else pd.DataFrame()
)

result_rows = (
    existing.to_dict("records")
    if len(existing)
    else []
)


def already_done(
    name,
    horizon,
):
    if not len(existing):
        return False

    return bool(
        (
            (existing["Dataset"] == name)
            & (
                existing["Horizon"]
                == horizon
            )
        ).any()
    )


for name in DATASETS:
    for horizon in HORIZONS:
        if already_done(
            name,
            horizon,
        ):
            print(
                f"SKIP completed: {name} H={horizon}"
            )
            continue

        print(
            "\n"
            + "=" * 140
        )

        print(
            f"OFFICIAL PATCHTST | "
            f"{name} | L=336 | H={horizon}"
        )

        print(
            "=" * 140
        )

        t0 = time.time()

        model, ckpt, loaders = train_or_load(
            name,
            horizon,
        )

        official_style = evaluate_loader(
            model,
            loaders["official_test"],
            horizon,
        )

        full_stride1 = evaluate_loader(
            model,
            loaders["full_test"],
            horizon,
        )

        row = {
            "Dataset": name,
            "Horizon": horizon,
            "SeqLen": SEQ_LEN,
            "Channels": DATA[name]["n_channels"],
            "BestEpoch": ckpt["BestEpoch"],
            "BestValMSE": ckpt["BestValMSE"],
            "OfficialStyle_MSE": official_style["MSE"],
            "OfficialStyle_MAE": official_style["MAE"],
            "OfficialStyle_BatchAverageMSE": (
                official_style["BatchAverageMSE"]
            ),
            "OfficialStyle_Windows": (
                official_style["Windows"]
            ),
            "FullStride1_MSE": full_stride1["MSE"],
            "FullStride1_MAE": full_stride1["MAE"],
            "FullStride1_Windows": (
                full_stride1["Windows"]
            ),
            "ExcludedByOfficialDropLast": (
                full_stride1["Windows"]
                - official_style["Windows"]
            ),
            "RuntimeMinutes": (
                time.time() - t0
            ) / 60.0,
            "Checkpoint": str(
                checkpoint_path(
                    name,
                    horizon,
                )
            ),
            "OfficialRepoCommit": commit,
        }

        result_rows.append(row)

        pd.DataFrame(
            result_rows
        ).to_csv(
            SUMMARY_PATH,
            index=False,
        )

        display(
            pd.DataFrame([row])[
                [
                    "Dataset",
                    "Horizon",
                    "BestEpoch",
                    "BestValMSE",
                    "OfficialStyle_MSE",
                    "OfficialStyle_MAE",
                    "FullStride1_MSE",
                    "FullStride1_MAE",
                    "FullStride1_Windows",
                    "ExcludedByOfficialDropLast",
                ]
            ]
        )

        del (
            model,
            ckpt,
            loaders,
        )

        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()


summary_df = (
    pd.DataFrame(result_rows)
    .sort_values(
        [
            "Dataset",
            "Horizon",
        ]
    )
    .reset_index(drop=True)
)

display(summary_df)

============================================================================================================================================
OFFICIAL PATCHTST | Weather | L=336 | H=96
============================================================================================================================================
Weather     H= 96 ep=001/100 | train=0.747358 | val=0.542040 | best=0.542040@1 | lr=1.000e-04 | wait=0/20
Weather     H= 96 ep=002/100 | train=0.492498 | val=0.418392 | best=0.418392@2 | lr=1.000e-04 | wait=0/20
Weather     H= 96 ep=003/100 | train=0.448917 | val=0.403692 | best=0.403692@3 | lr=1.000e-04 | wait=0/20
Weather     H= 96 ep=004/100 | train=0.441734 | val=0.395931 | best=0.395931@4 | lr=9.000e-05 | wait=0/20
Weather     H= 96 ep=005/100 | train=0.436128 | val=0.396592 | best=0.395931@4 | lr=8.100e-05 | wait=1/20
Weather     H= 96 ep=006/100 | train=0.432803 | val=0.395598 | best=0.395598@6 | lr=7.290e-05 | wait=0/20
Weather     H= 96 ep=007/100 | train=0.430140 | val=0.393127 | best=0.393127@7 | lr=6.561e-05 | wait=0/20
Weather     H= 96 ep=008/100 | train=0.427260 | val=0.397539 | best=0.393127@7 | lr=5.905e-05 | wait=1/20
Weather     H= 96 ep=009/100 | train=0.425754 | val=0.396876 | best=0.393127@7 | lr=5.314e-05 | wait=2/20
Weather     H= 96 ep=010/100 | train=0.423172 | val=0.393948 | best=0.393127@7 | lr=4.783e-05 | wait=3/20
Weather     H= 96 ep=011/100 | train=0.422045 | val=0.397582 | best=0.393127@7 | lr=4.305e-05 | wait=4/20
Weather     H= 96 ep=012/100 | train=0.420552 | val=0.394982 | best=0.393127@7 | lr=3.874e-05 | wait=5/20
Weather     H= 96 ep=013/100 | train=0.419936 | val=0.393292 | best=0.393127@7 | lr=3.487e-05 | wait=6/20
Weather     H= 96 ep=014/100 | train=0.418762 | val=0.394820 | best=0.393127@7 | lr=3.138e-05 | wait=7/20
Weather     H= 96 ep=015/100 | train=0.417163 | val=0.394842 | best=0.393127@7 | lr=2.824e-05 | wait=8/20
Weather     H= 96 ep=016/100 | train=0.416056 | val=0.392680 | best=0.392680@16 | lr=2.542e-05 | wait=0/20
Weather     H= 96 ep=017/100 | train=0.415778 | val=0.396365 | best=0.392680@16 | lr=2.288e-05 | wait=1/20
Weather     H= 96 ep=018/100 | train=0.414247 | val=0.395735 | best=0.392680@16 | lr=2.059e-05 | wait=2/20
Weather     H= 96 ep=019/100 | train=0.414842 | val=0.395050 | best=0.392680@16 | lr=1.853e-05 | wait=3/20
Weather     H= 96 ep=020/100 | train=0.413512 | val=0.395437 | best=0.392680@16 | lr=1.668e-05 | wait=4/20
Weather     H= 96 ep=021/100 | train=0.413149 | val=0.394927 | best=0.392680@16 | lr=1.501e-05 | wait=5/20
Weather     H= 96 ep=022/100 | train=0.413168 | val=0.395433 | best=0.392680@16 | lr=1.351e-05 | wait=6/20
Weather     H= 96 ep=023/100 | train=0.412171 | val=0.392359 | best=0.392359@23 | lr=1.216e-05 | wait=0/20
Weather     H= 96 ep=024/100 | train=0.412273 | val=0.395213 | best=0.392359@23 | lr=1.094e-05 | wait=1/20
Weather     H= 96 ep=025/100 | train=0.410837 | val=0.396490 | best=0.392359@23 | lr=9.848e-06 | wait=2/20
Weather     H= 96 ep=026/100 | train=0.411110 | val=0.396583 | best=0.392359@23 | lr=8.863e-06 | wait=3/20
Weather     H= 96 ep=027/100 | train=0.409959 | val=0.392127 | best=0.392127@27 | lr=7.977e-06 | wait=0/20
Weather     H= 96 ep=028/100 | train=0.410275 | val=0.394191 | best=0.392127@27 | lr=7.179e-06 | wait=1/20
Weather     H= 96 ep=029/100 | train=0.410428 | val=0.392858 | best=0.392127@27 | lr=6.461e-06 | wait=2/20
Weather     H= 96 ep=030/100 | train=0.410184 | val=0.393974 | best=0.392127@27 | lr=5.815e-06 | wait=3/20
Weather     H= 96 ep=031/100 | train=0.409721 | val=0.393540 | best=0.392127@27 | lr=5.233e-06 | wait=4/20
Weather     H= 96 ep=032/100 | train=0.409657 | val=0.393478 | best=0.392127@27 | lr=4.710e-06 | wait=5/20
Weather     H= 96 ep=033/100 | train=0.409746 | val=0.395748 | best=0.392127@27 | lr=4.239e-06 | wait=6/20
Weather     H= 96 ep=034/100 | train=0.409607 | val=0.393851 | best=0.392127@27 | lr=3.815e-06 | wait=7/20
Weather     H= 96 ep=035/100 | train=0.409736 | val=0.394600 | best=0.392127@27 | lr=3.434e-06 | wait=8/20
Weather     H= 96 ep=036/100 | train=0.409125 | val=0.393677 | best=0.392127@27 | lr=3.090e-06 | wait=9/20
Weather     H= 96 ep=037/100 | train=0.409361 | val=0.393207 | best=0.392127@27 | lr=2.781e-06 | wait=10/20
Weather     H= 96 ep=038/100 | train=0.408860 | val=0.394636 | best=0.392127@27 | lr=2.503e-06 | wait=11/20
Weather     H= 96 ep=039/100 | train=0.408995 | val=0.393322 | best=0.392127@27 | lr=2.253e-06 | wait=12/20
Weather     H= 96 ep=040/100 | train=0.408789 | val=0.394326 | best=0.392127@27 | lr=2.028e-06 | wait=13/20
Weather     H= 96 ep=041/100 | train=0.408225 | val=0.394298 | best=0.392127@27 | lr=1.825e-06 | wait=14/20
Weather     H= 96 ep=042/100 | train=0.408734 | val=0.395190 | best=0.392127@27 | lr=1.642e-06 | wait=15/20
Weather     H= 96 ep=043/100 | train=0.408948 | val=0.391574 | best=0.391574@43 | lr=1.478e-06 | wait=0/20
Weather     H= 96 ep=044/100 | train=0.408797 | val=0.394414 | best=0.391574@43 | lr=1.330e-06 | wait=1/20
Weather     H= 96 ep=045/100 | train=0.408515 | val=0.392255 | best=0.391574@43 | lr=1.197e-06 | wait=2/20
Weather     H= 96 ep=046/100 | train=0.408760 | val=0.392996 | best=0.391574@43 | lr=1.078e-06 | wait=3/20
Weather     H= 96 ep=047/100 | train=0.408604 | val=0.393859 | best=0.391574@43 | lr=9.698e-07 | wait=4/20
Weather     H= 96 ep=048/100 | train=0.408320 | val=0.395281 | best=0.391574@43 | lr=8.728e-07 | wait=5/20
Weather     H= 96 ep=049/100 | train=0.408546 | val=0.394735 | best=0.391574@43 | lr=7.855e-07 | wait=6/20
Weather     H= 96 ep=050/100 | train=0.408281 | val=0.391766 | best=0.391574@43 | lr=7.070e-07 | wait=7/20
Weather     H= 96 ep=051/100 | train=0.407438 | val=0.393009 | best=0.391574@43 | lr=6.363e-07 | wait=8/20
Weather     H= 96 ep=052/100 | train=0.408583 | val=0.391995 | best=0.391574@43 | lr=5.726e-07 | wait=9/20
Weather     H= 96 ep=053/100 | train=0.408407 | val=0.391052 | best=0.391052@53 | lr=5.154e-07 | wait=0/20
Weather     H= 96 ep=054/100 | train=0.407290 | val=0.393443 | best=0.391052@53 | lr=4.638e-07 | wait=1/20
Weather     H= 96 ep=055/100 | train=0.408765 | val=0.394813 | best=0.391052@53 | lr=4.175e-07 | wait=2/20
Weather     H= 96 ep=056/100 | train=0.408559 | val=0.394322 | best=0.391052@53 | lr=3.757e-07 | wait=3/20
Weather     H= 96 ep=057/100 | train=0.408087 | val=0.394750 | best=0.391052@53 | lr=3.381e-07 | wait=4/20
Weather     H= 96 ep=058/100 | train=0.408344 | val=0.393710 | best=0.391052@53 | lr=3.043e-07 | wait=5/20
Weather     H= 96 ep=059/100 | train=0.407588 | val=0.394523 | best=0.391052@53 | lr=2.739e-07 | wait=6/20
Weather     H= 96 ep=060/100 | train=0.408070 | val=0.391586 | best=0.391052@53 | lr=2.465e-07 | wait=7/20
Weather     H= 96 ep=061/100 | train=0.407059 | val=0.390797 | best=0.390797@61 | lr=2.219e-07 | wait=0/20
Weather     H= 96 ep=062/100 | train=0.408252 | val=0.393920 | best=0.390797@61 | lr=1.997e-07 | wait=1/20
Weather     H= 96 ep=063/100 | train=0.407666 | val=0.394293 | best=0.390797@61 | lr=1.797e-07 | wait=2/20
Weather     H= 96 ep=064/100 | train=0.407755 | val=0.392918 | best=0.390797@61 | lr=1.617e-07 | wait=3/20
Weather     H= 96 ep=065/100 | train=0.408362 | val=0.390229 | best=0.390229@65 | lr=1.456e-07 | wait=0/20
Weather     H= 96 ep=066/100 | train=0.408398 | val=0.392106 | best=0.390229@65 | lr=1.310e-07 | wait=1/20
Weather     H= 96 ep=067/100 | train=0.408280 | val=0.392398 | best=0.390229@65 | lr=1.179e-07 | wait=2/20
Weather     H= 96 ep=068/100 | train=0.407134 | val=0.394201 | best=0.390229@65 | lr=1.061e-07 | wait=3/20
Weather     H= 96 ep=069/100 | train=0.408578 | val=0.393273 | best=0.390229@65 | lr=9.550e-08 | wait=4/20
Weather     H= 96 ep=070/100 | train=0.408199 | val=0.393944 | best=0.390229@65 | lr=8.595e-08 | wait=5/20
Weather     H= 96 ep=071/100 | train=0.407612 | val=0.394259 | best=0.390229@65 | lr=7.736e-08 | wait=6/20
Weather     H= 96 ep=072/100 | train=0.407326 | val=0.394234 | best=0.390229@65 | lr=6.962e-08 | wait=7/20
Weather     H= 96 ep=073/100 | train=0.408415 | val=0.393670 | best=0.390229@65 | lr=6.266e-08 | wait=8/20
Weather     H= 96 ep=074/100 | train=0.408346 | val=0.394321 | best=0.390229@65 | lr=5.639e-08 | wait=9/20
Weather     H= 96 ep=075/100 | train=0.408376 | val=0.391962 | best=0.390229@65 | lr=5.075e-08 | wait=10/20
Weather     H= 96 ep=076/100 | train=0.408326 | val=0.393533 | best=0.390229@65 | lr=4.568e-08 | wait=11/20
Weather     H= 96 ep=077/100 | train=0.408633 | val=0.392569 | best=0.390229@65 | lr=4.111e-08 | wait=12/20
Weather     H= 96 ep=078/100 | train=0.408192 | val=0.393365 | best=0.390229@65 | lr=3.700e-08 | wait=13/20
Weather     H= 96 ep=079/100 | train=0.408342 | val=0.394026 | best=0.390229@65 | lr=3.330e-08 | wait=14/20
Weather     H= 96 ep=080/100 | train=0.408360 | val=0.392827 | best=0.390229@65 | lr=2.997e-08 | wait=15/20
Weather     H= 96 ep=081/100 | train=0.408633 | val=0.394268 | best=0.390229@65 | lr=2.697e-08 | wait=16/20
Weather     H= 96 ep=082/100 | train=0.408626 | val=0.393379 | best=0.390229@65 | lr=2.427e-08 | wait=17/20
Weather     H= 96 ep=083/100 | train=0.408096 | val=0.393745 | best=0.390229@65 | lr=2.185e-08 | wait=18/20
Weather     H= 96 ep=084/100 | train=0.408400 | val=0.395308 | best=0.390229@65 | lr=1.966e-08 | wait=19/20
Weather     H= 96 ep=085/100 | train=0.408388 | val=0.392312 | best=0.390229@65 | lr=1.770e-08 | wait=20/20
Early stopping: Weather H=96 at epoch 85.

   Dataset  Horizon  BestEpoch  BestValMSE  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  FullStride1_Windows  ExcludedByOfficialDropLast
0  Weather       96         65    0.390229           0.150419           0.198269          0.14969         0.197816                10444                          76

============================================================================================================================================
OFFICIAL PATCHTST | Weather | L=336 | H=192
============================================================================================================================================
Weather     H=192 ep=001/100 | train=0.779212 | val=0.597681 | best=0.597681@1 | lr=1.000e-04 | wait=0/20
Weather     H=192 ep=002/100 | train=0.537527 | val=0.489016 | best=0.489016@2 | lr=1.000e-04 | wait=0/20
Weather     H=192 ep=003/100 | train=0.501410 | val=0.471943 | best=0.471943@3 | lr=1.000e-04 | wait=0/20
Weather     H=192 ep=004/100 | train=0.494108 | val=0.470940 | best=0.470940@4 | lr=9.000e-05 | wait=0/20
Weather     H=192 ep=005/100 | train=0.489733 | val=0.463755 | best=0.463755@5 | lr=8.100e-05 | wait=0/20
Weather     H=192 ep=006/100 | train=0.487068 | val=0.461682 | best=0.461682@6 | lr=7.290e-05 | wait=0/20
Weather     H=192 ep=007/100 | train=0.484677 | val=0.462775 | best=0.461682@6 | lr=6.561e-05 | wait=1/20
Weather     H=192 ep=008/100 | train=0.482582 | val=0.463055 | best=0.461682@6 | lr=5.905e-05 | wait=2/20
Weather     H=192 ep=009/100 | train=0.480784 | val=0.466814 | best=0.461682@6 | lr=5.314e-05 | wait=3/20
Weather     H=192 ep=010/100 | train=0.479099 | val=0.463895 | best=0.461682@6 | lr=4.783e-05 | wait=4/20
Weather     H=192 ep=011/100 | train=0.477957 | val=0.467812 | best=0.461682@6 | lr=4.305e-05 | wait=5/20
Weather     H=192 ep=012/100 | train=0.476686 | val=0.465253 | best=0.461682@6 | lr=3.874e-05 | wait=6/20
Weather     H=192 ep=013/100 | train=0.475189 | val=0.464782 | best=0.461682@6 | lr=3.487e-05 | wait=7/20
Weather     H=192 ep=014/100 | train=0.474422 | val=0.463288 | best=0.461682@6 | lr=3.138e-05 | wait=8/20
Weather     H=192 ep=015/100 | train=0.473293 | val=0.463051 | best=0.461682@6 | lr=2.824e-05 | wait=9/20
Weather     H=192 ep=016/100 | train=0.472415 | val=0.464011 | best=0.461682@6 | lr=2.542e-05 | wait=10/20
Weather     H=192 ep=017/100 | train=0.471690 | val=0.461369 | best=0.461369@17 | lr=2.288e-05 | wait=0/20
Weather     H=192 ep=018/100 | train=0.470844 | val=0.464769 | best=0.461369@17 | lr=2.059e-05 | wait=1/20
Weather     H=192 ep=019/100 | train=0.469862 | val=0.464310 | best=0.461369@17 | lr=1.853e-05 | wait=2/20
Weather     H=192 ep=020/100 | train=0.469449 | val=0.460419 | best=0.460419@20 | lr=1.668e-05 | wait=0/20
Weather     H=192 ep=021/100 | train=0.468954 | val=0.460802 | best=0.460419@20 | lr=1.501e-05 | wait=1/20
Weather     H=192 ep=022/100 | train=0.468048 | val=0.459749 | best=0.459749@22 | lr=1.351e-05 | wait=0/20
Weather     H=192 ep=023/100 | train=0.467500 | val=0.460464 | best=0.459749@22 | lr=1.216e-05 | wait=1/20
Weather     H=192 ep=024/100 | train=0.467292 | val=0.462274 | best=0.459749@22 | lr=1.094e-05 | wait=2/20
Weather     H=192 ep=025/100 | train=0.466735 | val=0.462297 | best=0.459749@22 | lr=9.848e-06 | wait=3/20
Weather     H=192 ep=026/100 | train=0.466444 | val=0.460886 | best=0.459749@22 | lr=8.863e-06 | wait=4/20
Weather     H=192 ep=027/100 | train=0.466211 | val=0.459080 | best=0.459080@27 | lr=7.977e-06 | wait=0/20
Weather     H=192 ep=028/100 | train=0.465835 | val=0.461614 | best=0.459080@27 | lr=7.179e-06 | wait=1/20
Weather     H=192 ep=029/100 | train=0.465820 | val=0.461307 | best=0.459080@27 | lr=6.461e-06 | wait=2/20
Weather     H=192 ep=030/100 | train=0.465378 | val=0.460644 | best=0.459080@27 | lr=5.815e-06 | wait=3/20
Weather     H=192 ep=031/100 | train=0.465139 | val=0.460004 | best=0.459080@27 | lr=5.233e-06 | wait=4/20
Weather     H=192 ep=032/100 | train=0.465126 | val=0.461906 | best=0.459080@27 | lr=4.710e-06 | wait=5/20
Weather     H=192 ep=033/100 | train=0.464993 | val=0.462222 | best=0.459080@27 | lr=4.239e-06 | wait=6/20
Weather     H=192 ep=034/100 | train=0.464498 | val=0.461609 | best=0.459080@27 | lr=3.815e-06 | wait=7/20
Weather     H=192 ep=035/100 | train=0.464532 | val=0.458956 | best=0.458956@35 | lr=3.434e-06 | wait=0/20
Weather     H=192 ep=036/100 | train=0.464430 | val=0.460697 | best=0.458956@35 | lr=3.090e-06 | wait=1/20
Weather     H=192 ep=037/100 | train=0.464390 | val=0.458667 | best=0.458667@37 | lr=2.781e-06 | wait=0/20
Weather     H=192 ep=038/100 | train=0.464209 | val=0.460772 | best=0.458667@37 | lr=2.503e-06 | wait=1/20
Weather     H=192 ep=039/100 | train=0.464132 | val=0.458644 | best=0.458644@39 | lr=2.253e-06 | wait=0/20
Weather     H=192 ep=040/100 | train=0.463996 | val=0.459915 | best=0.458644@39 | lr=2.028e-06 | wait=1/20
Weather     H=192 ep=041/100 | train=0.463971 | val=0.458657 | best=0.458644@39 | lr=1.825e-06 | wait=2/20
Weather     H=192 ep=042/100 | train=0.463866 | val=0.458973 | best=0.458644@39 | lr=1.642e-06 | wait=3/20
Weather     H=192 ep=043/100 | train=0.463786 | val=0.458540 | best=0.458540@43 | lr=1.478e-06 | wait=0/20
Weather     H=192 ep=044/100 | train=0.463851 | val=0.461060 | best=0.458540@43 | lr=1.330e-06 | wait=1/20
Weather     H=192 ep=045/100 | train=0.463859 | val=0.456669 | best=0.456669@45 | lr=1.197e-06 | wait=0/20
Weather     H=192 ep=046/100 | train=0.463718 | val=0.458031 | best=0.456669@45 | lr=1.078e-06 | wait=1/20
Weather     H=192 ep=047/100 | train=0.463725 | val=0.460211 | best=0.456669@45 | lr=9.698e-07 | wait=2/20
Weather     H=192 ep=048/100 | train=0.463617 | val=0.458657 | best=0.456669@45 | lr=8.728e-07 | wait=3/20
Weather     H=192 ep=049/100 | train=0.463525 | val=0.458307 | best=0.456669@45 | lr=7.855e-07 | wait=4/20
Weather     H=192 ep=050/100 | train=0.463590 | val=0.459938 | best=0.456669@45 | lr=7.070e-07 | wait=5/20
Weather     H=192 ep=051/100 | train=0.463543 | val=0.458773 | best=0.456669@45 | lr=6.363e-07 | wait=6/20
Weather     H=192 ep=052/100 | train=0.463527 | val=0.459366 | best=0.456669@45 | lr=5.726e-07 | wait=7/20
Weather     H=192 ep=053/100 | train=0.463489 | val=0.460508 | best=0.456669@45 | lr=5.154e-07 | wait=8/20
Weather     H=192 ep=054/100 | train=0.463450 | val=0.460114 | best=0.456669@45 | lr=4.638e-07 | wait=9/20
Weather     H=192 ep=055/100 | train=0.463456 | val=0.459422 | best=0.456669@45 | lr=4.175e-07 | wait=10/20
Weather     H=192 ep=056/100 | train=0.463486 | val=0.459605 | best=0.456669@45 | lr=3.757e-07 | wait=11/20
Weather     H=192 ep=057/100 | train=0.463491 | val=0.458149 | best=0.456669@45 | lr=3.381e-07 | wait=12/20
Weather     H=192 ep=058/100 | train=0.463392 | val=0.458423 | best=0.456669@45 | lr=3.043e-07 | wait=13/20
Weather     H=192 ep=059/100 | train=0.463522 | val=0.459200 | best=0.456669@45 | lr=2.739e-07 | wait=14/20
Weather     H=192 ep=060/100 | train=0.463524 | val=0.459915 | best=0.456669@45 | lr=2.465e-07 | wait=15/20
Weather     H=192 ep=061/100 | train=0.463324 | val=0.458473 | best=0.456669@45 | lr=2.219e-07 | wait=16/20
Weather     H=192 ep=062/100 | train=0.463506 | val=0.458506 | best=0.456669@45 | lr=1.997e-07 | wait=17/20
Weather     H=192 ep=063/100 | train=0.463306 | val=0.459389 | best=0.456669@45 | lr=1.797e-07 | wait=18/20
Weather     H=192 ep=064/100 | train=0.463476 | val=0.461231 | best=0.456669@45 | lr=1.617e-07 | wait=19/20
Weather     H=192 ep=065/100 | train=0.463359 | val=0.460366 | best=0.456669@45 | lr=1.456e-07 | wait=20/20
Early stopping: Weather H=192 at epoch 65.

   Dataset  Horizon  BestEpoch  BestValMSE  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  FullStride1_Windows  ExcludedByOfficialDropLast
0  Weather      192         45    0.456669           0.195386           0.241418         0.194775         0.240853                10348                         108

============================================================================================================================================
OFFICIAL PATCHTST | Weather | L=336 | H=336
============================================================================================================================================
Weather     H=336 ep=001/100 | train=0.823969 | val=0.673787 | best=0.673787@1 | lr=1.000e-04 | wait=0/20
Weather     H=336 ep=002/100 | train=0.589323 | val=0.570568 | best=0.570568@2 | lr=1.000e-04 | wait=0/20
Weather     H=336 ep=003/100 | train=0.557555 | val=0.561700 | best=0.561700@3 | lr=1.000e-04 | wait=0/20
Weather     H=336 ep=004/100 | train=0.550439 | val=0.552647 | best=0.552647@4 | lr=9.000e-05 | wait=0/20
Weather     H=336 ep=005/100 | train=0.546296 | val=0.551869 | best=0.551869@5 | lr=8.100e-05 | wait=0/20
Weather     H=336 ep=006/100 | train=0.543647 | val=0.551974 | best=0.551869@5 | lr=7.290e-05 | wait=1/20
Weather     H=336 ep=007/100 | train=0.541770 | val=0.552601 | best=0.551869@5 | lr=6.561e-05 | wait=2/20
Weather     H=336 ep=008/100 | train=0.539138 | val=0.550212 | best=0.550212@8 | lr=5.905e-05 | wait=0/20
Weather     H=336 ep=009/100 | train=0.537121 | val=0.547726 | best=0.547726@9 | lr=5.314e-05 | wait=0/20
Weather     H=336 ep=010/100 | train=0.535095 | val=0.549684 | best=0.547726@9 | lr=4.783e-05 | wait=1/20
Weather     H=336 ep=011/100 | train=0.533736 | val=0.549804 | best=0.547726@9 | lr=4.305e-05 | wait=2/20
Weather     H=336 ep=012/100 | train=0.532266 | val=0.549596 | best=0.547726@9 | lr=3.874e-05 | wait=3/20
Weather     H=336 ep=013/100 | train=0.531224 | val=0.551186 | best=0.547726@9 | lr=3.487e-05 | wait=4/20
Weather     H=336 ep=014/100 | train=0.528775 | val=0.550870 | best=0.547726@9 | lr=3.138e-05 | wait=5/20
Weather     H=336 ep=015/100 | train=0.528766 | val=0.548150 | best=0.547726@9 | lr=2.824e-05 | wait=6/20
Weather     H=336 ep=016/100 | train=0.527455 | val=0.551297 | best=0.547726@9 | lr=2.542e-05 | wait=7/20
Weather     H=336 ep=017/100 | train=0.526467 | val=0.551042 | best=0.547726@9 | lr=2.288e-05 | wait=8/20
Weather     H=336 ep=018/100 | train=0.525533 | val=0.549696 | best=0.547726@9 | lr=2.059e-05 | wait=9/20
Weather     H=336 ep=019/100 | train=0.525018 | val=0.547002 | best=0.547002@19 | lr=1.853e-05 | wait=0/20
Weather     H=336 ep=020/100 | train=0.523607 | val=0.551573 | best=0.547002@19 | lr=1.668e-05 | wait=1/20
Weather     H=336 ep=021/100 | train=0.523412 | val=0.551243 | best=0.547002@19 | lr=1.501e-05 | wait=2/20
Weather     H=336 ep=022/100 | train=0.523013 | val=0.551688 | best=0.547002@19 | lr=1.351e-05 | wait=3/20
Weather     H=336 ep=023/100 | train=0.523004 | val=0.550489 | best=0.547002@19 | lr=1.216e-05 | wait=4/20
Weather     H=336 ep=024/100 | train=0.521919 | val=0.550521 | best=0.547002@19 | lr=1.094e-05 | wait=5/20
Weather     H=336 ep=025/100 | train=0.521824 | val=0.550622 | best=0.547002@19 | lr=9.848e-06 | wait=6/20
Weather     H=336 ep=026/100 | train=0.521338 | val=0.551455 | best=0.547002@19 | lr=8.863e-06 | wait=7/20
Weather     H=336 ep=027/100 | train=0.521627 | val=0.551713 | best=0.547002@19 | lr=7.977e-06 | wait=8/20
Weather     H=336 ep=028/100 | train=0.521124 | val=0.550303 | best=0.547002@19 | lr=7.179e-06 | wait=9/20
Weather     H=336 ep=029/100 | train=0.520403 | val=0.551742 | best=0.547002@19 | lr=6.461e-06 | wait=10/20
Weather     H=336 ep=030/100 | train=0.520862 | val=0.549771 | best=0.547002@19 | lr=5.815e-06 | wait=11/20
Weather     H=336 ep=031/100 | train=0.520222 | val=0.552626 | best=0.547002@19 | lr=5.233e-06 | wait=12/20
Weather     H=336 ep=032/100 | train=0.519914 | val=0.553300 | best=0.547002@19 | lr=4.710e-06 | wait=13/20
Weather     H=336 ep=033/100 | train=0.520419 | val=0.550477 | best=0.547002@19 | lr=4.239e-06 | wait=14/20
Weather     H=336 ep=034/100 | train=0.519797 | val=0.551789 | best=0.547002@19 | lr=3.815e-06 | wait=15/20
Weather     H=336 ep=035/100 | train=0.519943 | val=0.550822 | best=0.547002@19 | lr=3.434e-06 | wait=16/20
Weather     H=336 ep=036/100 | train=0.519342 | val=0.551913 | best=0.547002@19 | lr=3.090e-06 | wait=17/20
Weather     H=336 ep=037/100 | train=0.519368 | val=0.553432 | best=0.547002@19 | lr=2.781e-06 | wait=18/20
Weather     H=336 ep=038/100 | train=0.519074 | val=0.551693 | best=0.547002@19 | lr=2.503e-06 | wait=19/20
Weather     H=336 ep=039/100 | train=0.518994 | val=0.550009 | best=0.547002@19 | lr=2.253e-06 | wait=20/20
Early stopping: Weather H=336 at epoch 39.

   Dataset  Horizon  BestEpoch  BestValMSE  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  FullStride1_Windows  ExcludedByOfficialDropLast
0  Weather      336         19    0.547002            0.24737           0.282072           0.2469         0.281548                10204                          92

============================================================================================================================================
OFFICIAL PATCHTST | Weather | L=336 | H=720
============================================================================================================================================
Weather     H=720 ep=001/100 | train=0.881778 | val=0.766157 | best=0.766157@1 | lr=1.000e-04 | wait=0/20
Weather     H=720 ep=002/100 | train=0.656568 | val=0.672743 | best=0.672743@2 | lr=1.000e-04 | wait=0/20
Weather     H=720 ep=003/100 | train=0.628240 | val=0.669438 | best=0.669438@3 | lr=1.000e-04 | wait=0/20
Weather     H=720 ep=004/100 | train=0.621355 | val=0.658709 | best=0.658709@4 | lr=9.000e-05 | wait=0/20
Weather     H=720 ep=005/100 | train=0.616100 | val=0.659608 | best=0.658709@4 | lr=8.100e-05 | wait=1/20
Weather     H=720 ep=006/100 | train=0.613376 | val=0.658970 | best=0.658709@4 | lr=7.290e-05 | wait=2/20
Weather     H=720 ep=007/100 | train=0.610845 | val=0.658036 | best=0.658036@7 | lr=6.561e-05 | wait=0/20
Weather     H=720 ep=008/100 | train=0.609437 | val=0.658538 | best=0.658036@7 | lr=5.905e-05 | wait=1/20
Weather     H=720 ep=009/100 | train=0.607551 | val=0.661408 | best=0.658036@7 | lr=5.314e-05 | wait=2/20
Weather     H=720 ep=010/100 | train=0.605881 | val=0.656101 | best=0.656101@10 | lr=4.783e-05 | wait=0/20
Weather     H=720 ep=011/100 | train=0.604491 | val=0.657974 | best=0.656101@10 | lr=4.305e-05 | wait=1/20
Weather     H=720 ep=012/100 | train=0.603017 | val=0.659705 | best=0.656101@10 | lr=3.874e-05 | wait=2/20
Weather     H=720 ep=013/100 | train=0.601650 | val=0.654394 | best=0.654394@13 | lr=3.487e-05 | wait=0/20
Weather     H=720 ep=014/100 | train=0.600809 | val=0.656641 | best=0.654394@13 | lr=3.138e-05 | wait=1/20
Weather     H=720 ep=015/100 | train=0.599147 | val=0.660512 | best=0.654394@13 | lr=2.824e-05 | wait=2/20
Weather     H=720 ep=016/100 | train=0.598274 | val=0.657105 | best=0.654394@13 | lr=2.542e-05 | wait=3/20
Weather     H=720 ep=017/100 | train=0.597227 | val=0.659271 | best=0.654394@13 | lr=2.288e-05 | wait=4/20
Weather     H=720 ep=018/100 | train=0.595846 | val=0.656964 | best=0.654394@13 | lr=2.059e-05 | wait=5/20
Weather     H=720 ep=019/100 | train=0.595307 | val=0.657307 | best=0.654394@13 | lr=1.853e-05 | wait=6/20
Weather     H=720 ep=020/100 | train=0.594561 | val=0.656626 | best=0.654394@13 | lr=1.668e-05 | wait=7/20
Weather     H=720 ep=021/100 | train=0.593906 | val=0.655202 | best=0.654394@13 | lr=1.501e-05 | wait=8/20
Weather     H=720 ep=022/100 | train=0.593248 | val=0.655390 | best=0.654394@13 | lr=1.351e-05 | wait=9/20
Weather     H=720 ep=023/100 | train=0.592525 | val=0.653166 | best=0.653166@23 | lr=1.216e-05 | wait=0/20
Weather     H=720 ep=024/100 | train=0.592297 | val=0.655050 | best=0.653166@23 | lr=1.094e-05 | wait=1/20
Weather     H=720 ep=025/100 | train=0.591531 | val=0.657118 | best=0.653166@23 | lr=9.848e-06 | wait=2/20
Weather     H=720 ep=026/100 | train=0.591563 | val=0.656836 | best=0.653166@23 | lr=8.863e-06 | wait=3/20
Weather     H=720 ep=027/100 | train=0.591109 | val=0.656586 | best=0.653166@23 | lr=7.977e-06 | wait=4/20
Weather     H=720 ep=028/100 | train=0.591033 | val=0.656412 | best=0.653166@23 | lr=7.179e-06 | wait=5/20
Weather     H=720 ep=029/100 | train=0.590833 | val=0.657208 | best=0.653166@23 | lr=6.461e-06 | wait=6/20
Weather     H=720 ep=030/100 | train=0.590211 | val=0.656289 | best=0.653166@23 | lr=5.815e-06 | wait=7/20
Weather     H=720 ep=031/100 | train=0.590149 | val=0.656781 | best=0.653166@23 | lr=5.233e-06 | wait=8/20
Weather     H=720 ep=032/100 | train=0.589975 | val=0.656361 | best=0.653166@23 | lr=4.710e-06 | wait=9/20
Weather     H=720 ep=033/100 | train=0.589953 | val=0.657689 | best=0.653166@23 | lr=4.239e-06 | wait=10/20
Weather     H=720 ep=034/100 | train=0.589724 | val=0.656949 | best=0.653166@23 | lr=3.815e-06 | wait=11/20
Weather     H=720 ep=035/100 | train=0.589479 | val=0.656371 | best=0.653166@23 | lr=3.434e-06 | wait=12/20
Weather     H=720 ep=036/100 | train=0.589317 | val=0.656832 | best=0.653166@23 | lr=3.090e-06 | wait=13/20
Weather     H=720 ep=037/100 | train=0.589107 | val=0.656671 | best=0.653166@23 | lr=2.781e-06 | wait=14/20
Weather     H=720 ep=038/100 | train=0.588951 | val=0.654353 | best=0.653166@23 | lr=2.503e-06 | wait=15/20
Weather     H=720 ep=039/100 | train=0.588757 | val=0.656611 | best=0.653166@23 | lr=2.253e-06 | wait=16/20
Weather     H=720 ep=040/100 | train=0.588808 | val=0.656091 | best=0.653166@23 | lr=2.028e-06 | wait=17/20
Weather     H=720 ep=041/100 | train=0.588831 | val=0.656180 | best=0.653166@23 | lr=1.825e-06 | wait=18/20
Weather     H=720 ep=042/100 | train=0.588684 | val=0.657730 | best=0.653166@23 | lr=1.642e-06 | wait=19/20
Weather     H=720 ep=043/100 | train=0.588605 | val=0.656638 | best=0.653166@23 | lr=1.478e-06 | wait=20/20
Early stopping: Weather H=720 at epoch 43.

   Dataset  Horizon  BestEpoch  BestValMSE  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  FullStride1_Windows  ExcludedByOfficialDropLast
0  Weather      720         23    0.653166           0.319053           0.334466         0.320894         0.334351                 9820                          92

============================================================================================================================================
OFFICIAL PATCHTST | Electricity | L=336 | H=96
============================================================================================================================================
Electricity H= 96 ep=001/100 | train=0.397474 | val=0.183661 | best=0.183661@1 | lr=4.591e-06 | wait=0/10
Electricity H= 96 ep=002/100 | train=0.240256 | val=0.149946 | best=0.149946@2 | lr=6.350e-06 | wait=0/10
Electricity H= 96 ep=003/100 | train=0.200391 | val=0.135726 | best=0.135726@3 | lr=9.233e-06 | wait=0/10
Electricity H= 96 ep=004/100 | train=0.180236 | val=0.129312 | best=0.129312@4 | lr=1.317e-05 | wait=0/10
Electricity H= 96 ep=005/100 | train=0.170339 | val=0.126552 | best=0.126552@5 | lr=1.806e-05 | wait=0/10
Electricity H= 96 ep=006/100 | train=0.164269 | val=0.124101 | best=0.124101@6 | lr=2.379e-05 | wait=0/10
Electricity H= 96 ep=007/100 | train=0.160126 | val=0.124368 | best=0.124101@6 | lr=3.021e-05 | wait=1/10
Electricity H= 96 ep=008/100 | train=0.156916 | val=0.121802 | best=0.121802@8 | lr=3.717e-05 | wait=0/10
Electricity H= 96 ep=009/100 | train=0.154206 | val=0.121142 | best=0.121142@9 | lr=4.450e-05 | wait=0/10
Electricity H= 96 ep=010/100 | train=0.151737 | val=0.120296 | best=0.120296@10 | lr=5.201e-05 | wait=0/10
Electricity H= 96 ep=011/100 | train=0.149555 | val=0.120195 | best=0.120195@11 | lr=5.952e-05 | wait=0/10
Electricity H= 96 ep=012/100 | train=0.147652 | val=0.119470 | best=0.119470@12 | lr=6.684e-05 | wait=0/10
Electricity H= 96 ep=013/100 | train=0.145993 | val=0.121509 | best=0.119470@12 | lr=7.380e-05 | wait=1/10
Electricity H= 96 ep=014/100 | train=0.144487 | val=0.119117 | best=0.119117@14 | lr=8.022e-05 | wait=0/10
Electricity H= 96 ep=015/100 | train=0.143204 | val=0.117778 | best=0.117778@15 | lr=8.595e-05 | wait=0/10
Electricity H= 96 ep=016/100 | train=0.142283 | val=0.118274 | best=0.117778@15 | lr=9.084e-05 | wait=1/10
Electricity H= 96 ep=017/100 | train=0.141378 | val=0.118395 | best=0.117778@15 | lr=9.477e-05 | wait=2/10
Electricity H= 96 ep=018/100 | train=0.140175 | val=0.117572 | best=0.117572@18 | lr=9.765e-05 | wait=0/10
Electricity H= 96 ep=019/100 | train=0.139555 | val=0.116698 | best=0.116698@19 | lr=9.941e-05 | wait=0/10
Electricity H= 96 ep=020/100 | train=0.138587 | val=0.117439 | best=0.116698@19 | lr=1.000e-04 | wait=1/10
Electricity H= 96 ep=021/100 | train=0.137833 | val=0.116374 | best=0.116374@21 | lr=9.996e-05 | wait=0/10
Electricity H= 96 ep=022/100 | train=0.137154 | val=0.116597 | best=0.116374@21 | lr=9.985e-05 | wait=1/10
Electricity H= 96 ep=023/100 | train=0.136535 | val=0.116315 | best=0.116315@23 | lr=9.965e-05 | wait=0/10
Electricity H= 96 ep=024/100 | train=0.135921 | val=0.116532 | best=0.116315@23 | lr=9.938e-05 | wait=1/10
Electricity H= 96 ep=025/100 | train=0.135215 | val=0.115713 | best=0.115713@25 | lr=9.904e-05 | wait=0/10
Electricity H= 96 ep=026/100 | train=0.134815 | val=0.114720 | best=0.114720@26 | lr=9.862e-05 | wait=0/10
Electricity H= 96 ep=027/100 | train=0.134349 | val=0.115000 | best=0.114720@26 | lr=9.812e-05 | wait=1/10
Electricity H= 96 ep=028/100 | train=0.134009 | val=0.115088 | best=0.114720@26 | lr=9.755e-05 | wait=2/10
Electricity H= 96 ep=029/100 | train=0.133402 | val=0.114559 | best=0.114559@29 | lr=9.691e-05 | wait=0/10
Electricity H= 96 ep=030/100 | train=0.133152 | val=0.115209 | best=0.114559@29 | lr=9.619e-05 | wait=1/10
Electricity H= 96 ep=031/100 | train=0.132658 | val=0.113812 | best=0.113812@31 | lr=9.541e-05 | wait=0/10
Electricity H= 96 ep=032/100 | train=0.132331 | val=0.114332 | best=0.113812@31 | lr=9.455e-05 | wait=1/10
Electricity H= 96 ep=033/100 | train=0.131935 | val=0.113943 | best=0.113812@31 | lr=9.362e-05 | wait=2/10
Electricity H= 96 ep=034/100 | train=0.131642 | val=0.113777 | best=0.113777@34 | lr=9.263e-05 | wait=0/10
Electricity H= 96 ep=035/100 | train=0.131438 | val=0.114401 | best=0.113777@34 | lr=9.157e-05 | wait=1/10
Electricity H= 96 ep=036/100 | train=0.131090 | val=0.113818 | best=0.113777@34 | lr=9.045e-05 | wait=2/10
Electricity H= 96 ep=037/100 | train=0.130819 | val=0.113697 | best=0.113697@37 | lr=8.926e-05 | wait=0/10
Electricity H= 96 ep=038/100 | train=0.130613 | val=0.113239 | best=0.113239@38 | lr=8.802e-05 | wait=0/10
Electricity H= 96 ep=039/100 | train=0.130349 | val=0.112792 | best=0.112792@39 | lr=8.671e-05 | wait=0/10
Electricity H= 96 ep=040/100 | train=0.130131 | val=0.113090 | best=0.112792@39 | lr=8.535e-05 | wait=1/10
Electricity H= 96 ep=041/100 | train=0.129892 | val=0.113083 | best=0.112792@39 | lr=8.394e-05 | wait=2/10
Electricity H= 96 ep=042/100 | train=0.129572 | val=0.112468 | best=0.112468@42 | lr=8.247e-05 | wait=0/10
Electricity H= 96 ep=043/100 | train=0.129378 | val=0.112461 | best=0.112461@43 | lr=8.095e-05 | wait=0/10
Electricity H= 96 ep=044/100 | train=0.129168 | val=0.112275 | best=0.112275@44 | lr=7.939e-05 | wait=0/10
Electricity H= 96 ep=045/100 | train=0.128947 | val=0.112456 | best=0.112275@44 | lr=7.778e-05 | wait=1/10
Electricity H= 96 ep=046/100 | train=0.128809 | val=0.112274 | best=0.112274@46 | lr=7.612e-05 | wait=0/10
Electricity H= 96 ep=047/100 | train=0.128563 | val=0.112132 | best=0.112132@47 | lr=7.443e-05 | wait=0/10
Electricity H= 96 ep=048/100 | train=0.128448 | val=0.111888 | best=0.111888@48 | lr=7.270e-05 | wait=0/10
Electricity H= 96 ep=049/100 | train=0.128208 | val=0.112338 | best=0.111888@48 | lr=7.093e-05 | wait=1/10
Electricity H= 96 ep=050/100 | train=0.128059 | val=0.111932 | best=0.111888@48 | lr=6.913e-05 | wait=2/10
Electricity H= 96 ep=051/100 | train=0.127847 | val=0.111641 | best=0.111641@51 | lr=6.730e-05 | wait=0/10
Electricity H= 96 ep=052/100 | train=0.127728 | val=0.111546 | best=0.111546@52 | lr=6.545e-05 | wait=0/10
Electricity H= 96 ep=053/100 | train=0.127497 | val=0.111550 | best=0.111546@52 | lr=6.357e-05 | wait=1/10
Electricity H= 96 ep=054/100 | train=0.127418 | val=0.111366 | best=0.111366@54 | lr=6.167e-05 | wait=0/10
Electricity H= 96 ep=055/100 | train=0.127264 | val=0.111517 | best=0.111366@54 | lr=5.975e-05 | wait=1/10
Electricity H= 96 ep=056/100 | train=0.127104 | val=0.111609 | best=0.111366@54 | lr=5.782e-05 | wait=2/10
Electricity H= 96 ep=057/100 | train=0.126913 | val=0.111392 | best=0.111366@54 | lr=5.587e-05 | wait=3/10
Electricity H= 96 ep=058/100 | train=0.126860 | val=0.111576 | best=0.111366@54 | lr=5.392e-05 | wait=4/10
Electricity H= 96 ep=059/100 | train=0.126636 | val=0.110956 | best=0.110956@59 | lr=5.196e-05 | wait=0/10
Electricity H= 96 ep=060/100 | train=0.126548 | val=0.111448 | best=0.110956@59 | lr=5.000e-05 | wait=1/10
Electricity H= 96 ep=061/100 | train=0.126500 | val=0.111791 | best=0.110956@59 | lr=4.803e-05 | wait=2/10
Electricity H= 96 ep=062/100 | train=0.126312 | val=0.111314 | best=0.110956@59 | lr=4.607e-05 | wait=3/10
Electricity H= 96 ep=063/100 | train=0.126261 | val=0.111464 | best=0.110956@59 | lr=4.412e-05 | wait=4/10
Electricity H= 96 ep=064/100 | train=0.126025 | val=0.111466 | best=0.110956@59 | lr=4.218e-05 | wait=5/10
Electricity H= 96 ep=065/100 | train=0.126021 | val=0.111590 | best=0.110956@59 | lr=4.024e-05 | wait=6/10
Electricity H= 96 ep=066/100 | train=0.125869 | val=0.110807 | best=0.110807@66 | lr=3.832e-05 | wait=0/10
Electricity H= 96 ep=067/100 | train=0.125770 | val=0.111184 | best=0.110807@66 | lr=3.642e-05 | wait=1/10
Electricity H= 96 ep=068/100 | train=0.125786 | val=0.111193 | best=0.110807@66 | lr=3.455e-05 | wait=2/10
Electricity H= 96 ep=069/100 | train=0.125629 | val=0.111052 | best=0.110807@66 | lr=3.269e-05 | wait=3/10
Electricity H= 96 ep=070/100 | train=0.125505 | val=0.110894 | best=0.110807@66 | lr=3.086e-05 | wait=4/10
Electricity H= 96 ep=071/100 | train=0.125506 | val=0.110742 | best=0.110742@71 | lr=2.906e-05 | wait=0/10
Electricity H= 96 ep=072/100 | train=0.125332 | val=0.110757 | best=0.110742@71 | lr=2.730e-05 | wait=1/10
Electricity H= 96 ep=073/100 | train=0.125297 | val=0.110635 | best=0.110635@73 | lr=2.557e-05 | wait=0/10
Electricity H= 96 ep=074/100 | train=0.125188 | val=0.111322 | best=0.110635@73 | lr=2.387e-05 | wait=1/10
Electricity H= 96 ep=075/100 | train=0.125121 | val=0.111041 | best=0.110635@73 | lr=2.222e-05 | wait=2/10
Electricity H= 96 ep=076/100 | train=0.125011 | val=0.110734 | best=0.110635@73 | lr=2.061e-05 | wait=3/10
Electricity H= 96 ep=077/100 | train=0.124976 | val=0.110804 | best=0.110635@73 | lr=1.904e-05 | wait=4/10
Electricity H= 96 ep=078/100 | train=0.124900 | val=0.110590 | best=0.110590@78 | lr=1.753e-05 | wait=0/10
Electricity H= 96 ep=079/100 | train=0.124846 | val=0.110521 | best=0.110521@79 | lr=1.606e-05 | wait=0/10
Electricity H= 96 ep=080/100 | train=0.124778 | val=0.110575 | best=0.110521@79 | lr=1.464e-05 | wait=1/10
Electricity H= 96 ep=081/100 | train=0.124753 | val=0.110571 | best=0.110521@79 | lr=1.328e-05 | wait=2/10
Electricity H= 96 ep=082/100 | train=0.124702 | val=0.110496 | best=0.110496@82 | lr=1.198e-05 | wait=0/10
Electricity H= 96 ep=083/100 | train=0.124669 | val=0.110455 | best=0.110455@83 | lr=1.073e-05 | wait=0/10
Electricity H= 96 ep=084/100 | train=0.124604 | val=0.110582 | best=0.110455@83 | lr=9.547e-06 | wait=1/10
Electricity H= 96 ep=085/100 | train=0.124569 | val=0.110551 | best=0.110455@83 | lr=8.425e-06 | wait=2/10
Electricity H= 96 ep=086/100 | train=0.124502 | val=0.110607 | best=0.110455@83 | lr=7.367e-06 | wait=3/10
Electricity H= 96 ep=087/100 | train=0.124485 | val=0.110507 | best=0.110455@83 | lr=6.374e-06 | wait=4/10
Electricity H= 96 ep=088/100 | train=0.124458 | val=0.110508 | best=0.110455@83 | lr=5.448e-06 | wait=5/10
Electricity H= 96 ep=089/100 | train=0.124448 | val=0.110380 | best=0.110380@89 | lr=4.592e-06 | wait=0/10
Electricity H= 96 ep=090/100 | train=0.124392 | val=0.110444 | best=0.110380@89 | lr=3.805e-06 | wait=1/10
Electricity H= 96 ep=091/100 | train=0.124399 | val=0.110413 | best=0.110380@89 | lr=3.090e-06 | wait=2/10
Electricity H= 96 ep=092/100 | train=0.124385 | val=0.110358 | best=0.110358@92 | lr=2.446e-06 | wait=0/10
Electricity H= 96 ep=093/100 | train=0.124357 | val=0.110405 | best=0.110358@92 | lr=1.877e-06 | wait=1/10
Electricity H= 96 ep=094/100 | train=0.124288 | val=0.110333 | best=0.110333@94 | lr=1.381e-06 | wait=0/10
Electricity H= 96 ep=095/100 | train=0.124317 | val=0.110331 | best=0.110331@95 | lr=9.604e-07 | wait=0/10
Electricity H= 96 ep=096/100 | train=0.124326 | val=0.110398 | best=0.110331@95 | lr=6.154e-07 | wait=1/10
Electricity H= 96 ep=097/100 | train=0.124298 | val=0.110311 | best=0.110311@97 | lr=3.466e-07 | wait=0/10
Electricity H= 96 ep=098/100 | train=0.124271 | val=0.110326 | best=0.110311@97 | lr=1.543e-07 | wait=1/10
Electricity H= 96 ep=099/100 | train=0.124302 | val=0.110390 | best=0.110311@97 | lr=3.881e-08 | wait=2/10
Electricity H= 96 ep=100/100 | train=0.124246 | val=0.110328 | best=0.110311@97 | lr=4.001e-10 | wait=3/10

       Dataset  Horizon  BestEpoch  BestValMSE  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  FullStride1_Windows  ExcludedByOfficialDropLast
0  Electricity       96         97    0.110311           0.129935           0.222482         0.129977         0.222527                 5165                          13

============================================================================================================================================
OFFICIAL PATCHTST | Electricity | L=336 | H=192
============================================================================================================================================
Electricity H=192 ep=001/100 | train=0.407719 | val=0.193592 | best=0.193592@1 | lr=4.591e-06 | wait=0/10
Electricity H=192 ep=002/100 | train=0.251665 | val=0.161079 | best=0.161079@2 | lr=6.350e-06 | wait=0/10
Electricity H=192 ep=003/100 | train=0.213055 | val=0.147487 | best=0.147487@3 | lr=9.233e-06 | wait=0/10
Electricity H=192 ep=004/100 | train=0.194410 | val=0.141418 | best=0.141418@4 | lr=1.317e-05 | wait=0/10
Electricity H=192 ep=005/100 | train=0.185027 | val=0.138102 | best=0.138102@5 | lr=1.806e-05 | wait=0/10
Electricity H=192 ep=006/100 | train=0.179259 | val=0.136278 | best=0.136278@6 | lr=2.379e-05 | wait=0/10
Electricity H=192 ep=007/100 | train=0.175353 | val=0.135172 | best=0.135172@7 | lr=3.021e-05 | wait=0/10
Electricity H=192 ep=008/100 | train=0.172438 | val=0.135490 | best=0.135172@7 | lr=3.717e-05 | wait=1/10
Electricity H=192 ep=009/100 | train=0.170035 | val=0.134598 | best=0.134598@9 | lr=4.450e-05 | wait=0/10
Electricity H=192 ep=010/100 | train=0.167837 | val=0.132590 | best=0.132590@10 | lr=5.201e-05 | wait=0/10
Electricity H=192 ep=011/100 | train=0.166028 | val=0.132357 | best=0.132357@11 | lr=5.952e-05 | wait=0/10
Electricity H=192 ep=012/100 | train=0.164053 | val=0.133418 | best=0.132357@11 | lr=6.684e-05 | wait=1/10
Electricity H=192 ep=013/100 | train=0.162515 | val=0.131473 | best=0.131473@13 | lr=7.380e-05 | wait=0/10
Electricity H=192 ep=014/100 | train=0.161230 | val=0.133362 | best=0.131473@13 | lr=8.022e-05 | wait=1/10
Electricity H=192 ep=015/100 | train=0.159997 | val=0.133431 | best=0.131473@13 | lr=8.595e-05 | wait=2/10
Electricity H=192 ep=016/100 | train=0.158771 | val=0.131465 | best=0.131465@16 | lr=9.084e-05 | wait=0/10
Electricity H=192 ep=017/100 | train=0.157938 | val=0.131009 | best=0.131009@17 | lr=9.477e-05 | wait=0/10
Electricity H=192 ep=018/100 | train=0.157174 | val=0.130946 | best=0.130946@18 | lr=9.765e-05 | wait=0/10
Electricity H=192 ep=019/100 | train=0.156568 | val=0.131662 | best=0.130946@18 | lr=9.941e-05 | wait=1/10
Electricity H=192 ep=020/100 | train=0.155579 | val=0.130321 | best=0.130321@20 | lr=1.000e-04 | wait=0/10
Electricity H=192 ep=021/100 | train=0.154897 | val=0.129999 | best=0.129999@21 | lr=9.996e-05 | wait=0/10
Electricity H=192 ep=022/100 | train=0.154251 | val=0.129869 | best=0.129869@22 | lr=9.985e-05 | wait=0/10
Electricity H=192 ep=023/100 | train=0.153736 | val=0.129186 | best=0.129186@23 | lr=9.965e-05 | wait=0/10
Electricity H=192 ep=024/100 | train=0.153138 | val=0.129658 | best=0.129186@23 | lr=9.938e-05 | wait=1/10
Electricity H=192 ep=025/100 | train=0.152461 | val=0.129450 | best=0.129186@23 | lr=9.904e-05 | wait=2/10
Electricity H=192 ep=026/100 | train=0.151903 | val=0.129565 | best=0.129186@23 | lr=9.862e-05 | wait=3/10
Electricity H=192 ep=027/100 | train=0.151328 | val=0.128787 | best=0.128787@27 | lr=9.812e-05 | wait=0/10
Electricity H=192 ep=028/100 | train=0.150827 | val=0.128509 | best=0.128509@28 | lr=9.755e-05 | wait=0/10
Electricity H=192 ep=029/100 | train=0.150354 | val=0.127573 | best=0.127573@29 | lr=9.691e-05 | wait=0/10
Electricity H=192 ep=030/100 | train=0.149790 | val=0.128536 | best=0.127573@29 | lr=9.619e-05 | wait=1/10
Electricity H=192 ep=031/100 | train=0.149451 | val=0.128405 | best=0.127573@29 | lr=9.541e-05 | wait=2/10
Electricity H=192 ep=032/100 | train=0.149108 | val=0.127652 | best=0.127573@29 | lr=9.455e-05 | wait=3/10
Electricity H=192 ep=033/100 | train=0.148584 | val=0.127588 | best=0.127573@29 | lr=9.362e-05 | wait=4/10
Electricity H=192 ep=034/100 | train=0.148379 | val=0.127104 | best=0.127104@34 | lr=9.263e-05 | wait=0/10
Electricity H=192 ep=035/100 | train=0.148005 | val=0.127559 | best=0.127104@34 | lr=9.157e-05 | wait=1/10
Electricity H=192 ep=036/100 | train=0.147777 | val=0.127681 | best=0.127104@34 | lr=9.045e-05 | wait=2/10
Electricity H=192 ep=037/100 | train=0.147419 | val=0.127600 | best=0.127104@34 | lr=8.926e-05 | wait=3/10
Electricity H=192 ep=038/100 | train=0.147134 | val=0.126777 | best=0.126777@38 | lr=8.802e-05 | wait=0/10
Electricity H=192 ep=039/100 | train=0.146842 | val=0.127496 | best=0.126777@38 | lr=8.671e-05 | wait=1/10
Electricity H=192 ep=040/100 | train=0.146629 | val=0.127105 | best=0.126777@38 | lr=8.535e-05 | wait=2/10
Electricity H=192 ep=041/100 | train=0.146286 | val=0.127258 | best=0.126777@38 | lr=8.394e-05 | wait=3/10
Electricity H=192 ep=042/100 | train=0.146066 | val=0.127651 | best=0.126777@38 | lr=8.247e-05 | wait=4/10
Electricity H=192 ep=043/100 | train=0.145846 | val=0.127323 | best=0.126777@38 | lr=8.095e-05 | wait=5/10
Electricity H=192 ep=044/100 | train=0.145535 | val=0.126983 | best=0.126777@38 | lr=7.939e-05 | wait=6/10
Electricity H=192 ep=045/100 | train=0.145357 | val=0.126993 | best=0.126777@38 | lr=7.778e-05 | wait=7/10
Electricity H=192 ep=046/100 | train=0.145141 | val=0.126627 | best=0.126627@46 | lr=7.612e-05 | wait=0/10
Electricity H=192 ep=047/100 | train=0.144831 | val=0.127459 | best=0.126627@46 | lr=7.443e-05 | wait=1/10
Electricity H=192 ep=048/100 | train=0.144686 | val=0.126097 | best=0.126097@48 | lr=7.270e-05 | wait=0/10
Electricity H=192 ep=049/100 | train=0.144487 | val=0.126266 | best=0.126097@48 | lr=7.093e-05 | wait=1/10
Electricity H=192 ep=050/100 | train=0.144256 | val=0.127454 | best=0.126097@48 | lr=6.913e-05 | wait=2/10
Electricity H=192 ep=051/100 | train=0.144141 | val=0.126370 | best=0.126097@48 | lr=6.730e-05 | wait=3/10
Electricity H=192 ep=052/100 | train=0.143850 | val=0.126307 | best=0.126097@48 | lr=6.545e-05 | wait=4/10
Electricity H=192 ep=053/100 | train=0.143767 | val=0.126535 | best=0.126097@48 | lr=6.357e-05 | wait=5/10
Electricity H=192 ep=054/100 | train=0.143586 | val=0.126667 | best=0.126097@48 | lr=6.167e-05 | wait=6/10
Electricity H=192 ep=055/100 | train=0.143414 | val=0.126238 | best=0.126097@48 | lr=5.975e-05 | wait=7/10
Electricity H=192 ep=056/100 | train=0.143208 | val=0.126284 | best=0.126097@48 | lr=5.782e-05 | wait=8/10
Electricity H=192 ep=057/100 | train=0.143034 | val=0.126359 | best=0.126097@48 | lr=5.587e-05 | wait=9/10
Electricity H=192 ep=058/100 | train=0.142877 | val=0.126150 | best=0.126097@48 | lr=5.392e-05 | wait=10/10
Early stopping: Electricity H=192 at epoch 58.

       Dataset  Horizon  BestEpoch  BestValMSE  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  FullStride1_Windows  ExcludedByOfficialDropLast
0  Electricity      192         48    0.126097           0.148336           0.241681         0.149116         0.242038                 5069                          13

============================================================================================================================================
OFFICIAL PATCHTST | Electricity | L=336 | H=336
============================================================================================================================================
Electricity H=336 ep=001/100 | train=0.425764 | val=0.208078 | best=0.208078@1 | lr=4.591e-06 | wait=0/10
Electricity H=336 ep=002/100 | train=0.270780 | val=0.176862 | best=0.176862@2 | lr=6.350e-06 | wait=0/10
Electricity H=336 ep=003/100 | train=0.233985 | val=0.163517 | best=0.163517@3 | lr=9.233e-06 | wait=0/10
Electricity H=336 ep=004/100 | train=0.216319 | val=0.157306 | best=0.157306@4 | lr=1.317e-05 | wait=0/10
Electricity H=336 ep=005/100 | train=0.207416 | val=0.154013 | best=0.154013@5 | lr=1.806e-05 | wait=0/10
Electricity H=336 ep=006/100 | train=0.201879 | val=0.152332 | best=0.152332@6 | lr=2.379e-05 | wait=0/10
Electricity H=336 ep=007/100 | train=0.198015 | val=0.151333 | best=0.151333@7 | lr=3.021e-05 | wait=0/10
Electricity H=336 ep=008/100 | train=0.195158 | val=0.150490 | best=0.150490@8 | lr=3.717e-05 | wait=0/10
Electricity H=336 ep=009/100 | train=0.192871 | val=0.151096 | best=0.150490@8 | lr=4.450e-05 | wait=1/10
Electricity H=336 ep=010/100 | train=0.190739 | val=0.149268 | best=0.149268@10 | lr=5.201e-05 | wait=0/10
Electricity H=336 ep=011/100 | train=0.188844 | val=0.149109 | best=0.149109@11 | lr=5.952e-05 | wait=0/10
Electricity H=336 ep=012/100 | train=0.186917 | val=0.149969 | best=0.149109@11 | lr=6.684e-05 | wait=1/10
Electricity H=336 ep=013/100 | train=0.185593 | val=0.148374 | best=0.148374@13 | lr=7.380e-05 | wait=0/10
Electricity H=336 ep=014/100 | train=0.184209 | val=0.148477 | best=0.148374@13 | lr=8.022e-05 | wait=1/10
Electricity H=336 ep=015/100 | train=0.182798 | val=0.150461 | best=0.148374@13 | lr=8.595e-05 | wait=2/10
Electricity H=336 ep=016/100 | train=0.181934 | val=0.148003 | best=0.148003@16 | lr=9.084e-05 | wait=0/10
Electricity H=336 ep=017/100 | train=0.180756 | val=0.146919 | best=0.146919@17 | lr=9.477e-05 | wait=0/10
Electricity H=336 ep=018/100 | train=0.180050 | val=0.148098 | best=0.146919@17 | lr=9.765e-05 | wait=1/10
Electricity H=336 ep=019/100 | train=0.179124 | val=0.146457 | best=0.146457@19 | lr=9.941e-05 | wait=0/10
Electricity H=336 ep=020/100 | train=0.178330 | val=0.147638 | best=0.146457@19 | lr=1.000e-04 | wait=1/10
Electricity H=336 ep=021/100 | train=0.177587 | val=0.146848 | best=0.146457@19 | lr=9.996e-05 | wait=2/10
Electricity H=336 ep=022/100 | train=0.176769 | val=0.147211 | best=0.146457@19 | lr=9.985e-05 | wait=3/10
Electricity H=336 ep=023/100 | train=0.176099 | val=0.147100 | best=0.146457@19 | lr=9.965e-05 | wait=4/10
Electricity H=336 ep=024/100 | train=0.175623 | val=0.146269 | best=0.146269@24 | lr=9.938e-05 | wait=0/10
Electricity H=336 ep=025/100 | train=0.174814 | val=0.146082 | best=0.146082@25 | lr=9.904e-05 | wait=0/10
Electricity H=336 ep=026/100 | train=0.174139 | val=0.145213 | best=0.145213@26 | lr=9.862e-05 | wait=0/10
Electricity H=336 ep=027/100 | train=0.173530 | val=0.145407 | best=0.145213@26 | lr=9.812e-05 | wait=1/10
Electricity H=336 ep=028/100 | train=0.173001 | val=0.145552 | best=0.145213@26 | lr=9.755e-05 | wait=2/10
Electricity H=336 ep=029/100 | train=0.172462 | val=0.142602 | best=0.142602@29 | lr=9.691e-05 | wait=0/10
Electricity H=336 ep=030/100 | train=0.171962 | val=0.143852 | best=0.142602@29 | lr=9.619e-05 | wait=1/10
Electricity H=336 ep=031/100 | train=0.171563 | val=0.143128 | best=0.142602@29 | lr=9.541e-05 | wait=2/10
Electricity H=336 ep=032/100 | train=0.171001 | val=0.144018 | best=0.142602@29 | lr=9.455e-05 | wait=3/10
Electricity H=336 ep=033/100 | train=0.170597 | val=0.143797 | best=0.142602@29 | lr=9.362e-05 | wait=4/10
Electricity H=336 ep=034/100 | train=0.170020 | val=0.143653 | best=0.142602@29 | lr=9.263e-05 | wait=5/10
Electricity H=336 ep=035/100 | train=0.169740 | val=0.143396 | best=0.142602@29 | lr=9.157e-05 | wait=6/10
Electricity H=336 ep=036/100 | train=0.169322 | val=0.143213 | best=0.142602@29 | lr=9.045e-05 | wait=7/10
Electricity H=336 ep=037/100 | train=0.168880 | val=0.142649 | best=0.142602@29 | lr=8.926e-05 | wait=8/10
Electricity H=336 ep=038/100 | train=0.168585 | val=0.143025 | best=0.142602@29 | lr=8.802e-05 | wait=9/10
Electricity H=336 ep=039/100 | train=0.168179 | val=0.142499 | best=0.142499@39 | lr=8.671e-05 | wait=0/10
Electricity H=336 ep=040/100 | train=0.167835 | val=0.143135 | best=0.142499@39 | lr=8.535e-05 | wait=1/10
Electricity H=336 ep=041/100 | train=0.167535 | val=0.143787 | best=0.142499@39 | lr=8.394e-05 | wait=2/10
Electricity H=336 ep=042/100 | train=0.167277 | val=0.141604 | best=0.141604@42 | lr=8.247e-05 | wait=0/10
Electricity H=336 ep=043/100 | train=0.166888 | val=0.142817 | best=0.141604@42 | lr=8.095e-05 | wait=1/10
Electricity H=336 ep=044/100 | train=0.166633 | val=0.142207 | best=0.141604@42 | lr=7.939e-05 | wait=2/10
Electricity H=336 ep=045/100 | train=0.166431 | val=0.142164 | best=0.141604@42 | lr=7.778e-05 | wait=3/10
Electricity H=336 ep=046/100 | train=0.166122 | val=0.142831 | best=0.141604@42 | lr=7.612e-05 | wait=4/10
Electricity H=336 ep=047/100 | train=0.165821 | val=0.141359 | best=0.141359@47 | lr=7.443e-05 | wait=0/10
Electricity H=336 ep=048/100 | train=0.165617 | val=0.142747 | best=0.141359@47 | lr=7.270e-05 | wait=1/10
Electricity H=336 ep=049/100 | train=0.165371 | val=0.142740 | best=0.141359@47 | lr=7.093e-05 | wait=2/10
Electricity H=336 ep=050/100 | train=0.165215 | val=0.141386 | best=0.141359@47 | lr=6.913e-05 | wait=3/10
Electricity H=336 ep=051/100 | train=0.164929 | val=0.142144 | best=0.141359@47 | lr=6.730e-05 | wait=4/10
Electricity H=336 ep=052/100 | train=0.164668 | val=0.142080 | best=0.141359@47 | lr=6.545e-05 | wait=5/10
Electricity H=336 ep=053/100 | train=0.164436 | val=0.141866 | best=0.141359@47 | lr=6.357e-05 | wait=6/10
Electricity H=336 ep=054/100 | train=0.164242 | val=0.141168 | best=0.141168@54 | lr=6.167e-05 | wait=0/10
Electricity H=336 ep=055/100 | train=0.164028 | val=0.141345 | best=0.141168@54 | lr=5.975e-05 | wait=1/10
Electricity H=336 ep=056/100 | train=0.163828 | val=0.141138 | best=0.141138@56 | lr=5.782e-05 | wait=0/10
Electricity H=336 ep=057/100 | train=0.163687 | val=0.141278 | best=0.141138@56 | lr=5.587e-05 | wait=1/10
Electricity H=336 ep=058/100 | train=0.163462 | val=0.141009 | best=0.141009@58 | lr=5.392e-05 | wait=0/10
Electricity H=336 ep=059/100 | train=0.163299 | val=0.141425 | best=0.141009@58 | lr=5.196e-05 | wait=1/10
Electricity H=336 ep=060/100 | train=0.163156 | val=0.140739 | best=0.140739@60 | lr=5.000e-05 | wait=0/10
Electricity H=336 ep=061/100 | train=0.162938 | val=0.141088 | best=0.140739@60 | lr=4.803e-05 | wait=1/10
Electricity H=336 ep=062/100 | train=0.162805 | val=0.141470 | best=0.140739@60 | lr=4.607e-05 | wait=2/10
Electricity H=336 ep=063/100 | train=0.162672 | val=0.140947 | best=0.140739@60 | lr=4.412e-05 | wait=3/10
Electricity H=336 ep=064/100 | train=0.162528 | val=0.141255 | best=0.140739@60 | lr=4.218e-05 | wait=4/10
Electricity H=336 ep=065/100 | train=0.162404 | val=0.141568 | best=0.140739@60 | lr=4.024e-05 | wait=5/10
Electricity H=336 ep=066/100 | train=0.162243 | val=0.141151 | best=0.140739@60 | lr=3.832e-05 | wait=6/10
Electricity H=336 ep=067/100 | train=0.162149 | val=0.140920 | best=0.140739@60 | lr=3.642e-05 | wait=7/10
Electricity H=336 ep=068/100 | train=0.161983 | val=0.141388 | best=0.140739@60 | lr=3.455e-05 | wait=8/10
Electricity H=336 ep=069/100 | train=0.161897 | val=0.140645 | best=0.140645@69 | lr=3.269e-05 | wait=0/10
Electricity H=336 ep=070/100 | train=0.161773 | val=0.141012 | best=0.140645@69 | lr=3.086e-05 | wait=1/10
Electricity H=336 ep=071/100 | train=0.161662 | val=0.141170 | best=0.140645@69 | lr=2.906e-05 | wait=2/10
Electricity H=336 ep=072/100 | train=0.161493 | val=0.141107 | best=0.140645@69 | lr=2.730e-05 | wait=3/10
Electricity H=336 ep=073/100 | train=0.161433 | val=0.140815 | best=0.140645@69 | lr=2.557e-05 | wait=4/10
Electricity H=336 ep=074/100 | train=0.161383 | val=0.141236 | best=0.140645@69 | lr=2.387e-05 | wait=5/10
Electricity H=336 ep=075/100 | train=0.161274 | val=0.140742 | best=0.140645@69 | lr=2.222e-05 | wait=6/10
Electricity H=336 ep=076/100 | train=0.161165 | val=0.141234 | best=0.140645@69 | lr=2.061e-05 | wait=7/10
Electricity H=336 ep=077/100 | train=0.161082 | val=0.140894 | best=0.140645@69 | lr=1.904e-05 | wait=8/10
Electricity H=336 ep=078/100 | train=0.161013 | val=0.140919 | best=0.140645@69 | lr=1.753e-05 | wait=9/10
Electricity H=336 ep=079/100 | train=0.160902 | val=0.140739 | best=0.140645@69 | lr=1.606e-05 | wait=10/10
Early stopping: Electricity H=336 at epoch 79.

       Dataset  Horizon  BestEpoch  BestValMSE  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  FullStride1_Windows  ExcludedByOfficialDropLast
0  Electricity      336         69    0.140645           0.164611           0.258211          0.16569         0.258694                 4925                          29

============================================================================================================================================
OFFICIAL PATCHTST | Electricity | L=336 | H=720
============================================================================================================================================
Electricity H=720 ep=001/100 | train=0.470779 | val=0.240102 | best=0.240102@1 | lr=4.591e-06 | wait=0/10
Electricity H=720 ep=002/100 | train=0.314628 | val=0.208828 | best=0.208828@2 | lr=6.350e-06 | wait=0/10
Electricity H=720 ep=003/100 | train=0.278951 | val=0.194973 | best=0.194973@3 | lr=9.233e-06 | wait=0/10
Electricity H=720 ep=004/100 | train=0.261796 | val=0.188743 | best=0.188743@4 | lr=1.317e-05 | wait=0/10
Electricity H=720 ep=005/100 | train=0.252910 | val=0.185612 | best=0.185612@5 | lr=1.806e-05 | wait=0/10
Electricity H=720 ep=006/100 | train=0.247512 | val=0.183264 | best=0.183264@6 | lr=2.379e-05 | wait=0/10
Electricity H=720 ep=007/100 | train=0.243755 | val=0.181605 | best=0.181605@7 | lr=3.021e-05 | wait=0/10
Electricity H=720 ep=008/100 | train=0.241070 | val=0.181211 | best=0.181211@8 | lr=3.717e-05 | wait=0/10
Electricity H=720 ep=009/100 | train=0.238516 | val=0.180988 | best=0.180988@9 | lr=4.450e-05 | wait=0/10
Electricity H=720 ep=010/100 | train=0.236403 | val=0.179169 | best=0.179169@10 | lr=5.201e-05 | wait=0/10
Electricity H=720 ep=011/100 | train=0.234320 | val=0.180347 | best=0.179169@10 | lr=5.952e-05 | wait=1/10
Electricity H=720 ep=012/100 | train=0.232646 | val=0.178947 | best=0.178947@12 | lr=6.684e-05 | wait=0/10
Electricity H=720 ep=013/100 | train=0.230836 | val=0.180528 | best=0.178947@12 | lr=7.380e-05 | wait=1/10
Electricity H=720 ep=014/100 | train=0.229281 | val=0.178666 | best=0.178666@14 | lr=8.022e-05 | wait=0/10
Electricity H=720 ep=015/100 | train=0.227963 | val=0.179407 | best=0.178666@14 | lr=8.595e-05 | wait=1/10
Electricity H=720 ep=016/100 | train=0.226849 | val=0.176686 | best=0.176686@16 | lr=9.084e-05 | wait=0/10
Electricity H=720 ep=017/100 | train=0.225393 | val=0.178743 | best=0.176686@16 | lr=9.477e-05 | wait=1/10
Electricity H=720 ep=018/100 | train=0.224429 | val=0.180243 | best=0.176686@16 | lr=9.765e-05 | wait=2/10
Electricity H=720 ep=019/100 | train=0.223391 | val=0.175668 | best=0.175668@19 | lr=9.941e-05 | wait=0/10
Electricity H=720 ep=020/100 | train=0.222193 | val=0.180268 | best=0.175668@19 | lr=1.000e-04 | wait=1/10
Electricity H=720 ep=021/100 | train=0.221316 | val=0.176499 | best=0.175668@19 | lr=9.996e-05 | wait=2/10
Electricity H=720 ep=022/100 | train=0.220079 | val=0.178351 | best=0.175668@19 | lr=9.985e-05 | wait=3/10
Electricity H=720 ep=023/100 | train=0.219247 | val=0.176736 | best=0.175668@19 | lr=9.965e-05 | wait=4/10
Electricity H=720 ep=024/100 | train=0.218245 | val=0.178815 | best=0.175668@19 | lr=9.938e-05 | wait=5/10
Electricity H=720 ep=025/100 | train=0.217385 | val=0.178864 | best=0.175668@19 | lr=9.904e-05 | wait=6/10
Electricity H=720 ep=026/100 | train=0.216446 | val=0.176649 | best=0.175668@19 | lr=9.862e-05 | wait=7/10
Electricity H=720 ep=027/100 | train=0.215651 | val=0.175443 | best=0.175443@27 | lr=9.812e-05 | wait=0/10
Electricity H=720 ep=028/100 | train=0.214836 | val=0.176778 | best=0.175443@27 | lr=9.755e-05 | wait=1/10
Electricity H=720 ep=029/100 | train=0.214053 | val=0.173765 | best=0.173765@29 | lr=9.691e-05 | wait=0/10
Electricity H=720 ep=030/100 | train=0.213400 | val=0.175443 | best=0.173765@29 | lr=9.619e-05 | wait=1/10
Electricity H=720 ep=031/100 | train=0.212604 | val=0.176747 | best=0.173765@29 | lr=9.541e-05 | wait=2/10
Electricity H=720 ep=032/100 | train=0.211840 | val=0.176866 | best=0.173765@29 | lr=9.455e-05 | wait=3/10
Electricity H=720 ep=033/100 | train=0.211374 | val=0.176435 | best=0.173765@29 | lr=9.362e-05 | wait=4/10
Electricity H=720 ep=034/100 | train=0.210594 | val=0.173392 | best=0.173392@34 | lr=9.263e-05 | wait=0/10
Electricity H=720 ep=035/100 | train=0.209965 | val=0.173442 | best=0.173392@34 | lr=9.157e-05 | wait=1/10
Electricity H=720 ep=036/100 | train=0.209363 | val=0.177608 | best=0.173392@34 | lr=9.045e-05 | wait=2/10
Electricity H=720 ep=037/100 | train=0.208855 | val=0.174915 | best=0.173392@34 | lr=8.926e-05 | wait=3/10
Electricity H=720 ep=038/100 | train=0.208324 | val=0.176390 | best=0.173392@34 | lr=8.802e-05 | wait=4/10
Electricity H=720 ep=039/100 | train=0.207809 | val=0.173104 | best=0.173104@39 | lr=8.671e-05 | wait=0/10
Electricity H=720 ep=040/100 | train=0.207269 | val=0.175462 | best=0.173104@39 | lr=8.535e-05 | wait=1/10
Electricity H=720 ep=041/100 | train=0.206911 | val=0.176505 | best=0.173104@39 | lr=8.394e-05 | wait=2/10
Electricity H=720 ep=042/100 | train=0.206357 | val=0.174860 | best=0.173104@39 | lr=8.247e-05 | wait=3/10
Electricity H=720 ep=043/100 | train=0.205953 | val=0.174454 | best=0.173104@39 | lr=8.095e-05 | wait=4/10
Electricity H=720 ep=044/100 | train=0.205546 | val=0.174001 | best=0.173104@39 | lr=7.939e-05 | wait=5/10
Electricity H=720 ep=045/100 | train=0.205122 | val=0.174542 | best=0.173104@39 | lr=7.778e-05 | wait=6/10
Electricity H=720 ep=046/100 | train=0.204771 | val=0.173142 | best=0.173104@39 | lr=7.612e-05 | wait=7/10
Electricity H=720 ep=047/100 | train=0.204365 | val=0.176655 | best=0.173104@39 | lr=7.443e-05 | wait=8/10
Electricity H=720 ep=048/100 | train=0.204040 | val=0.174949 | best=0.173104@39 | lr=7.270e-05 | wait=9/10
Electricity H=720 ep=049/100 | train=0.203697 | val=0.174919 | best=0.173104@39 | lr=7.093e-05 | wait=10/10
Early stopping: Electricity H=720 at epoch 49.

       Dataset  Horizon  BestEpoch  BestValMSE  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  FullStride1_Windows  ExcludedByOfficialDropLast
0  Electricity      720         39    0.173104           0.202358           0.292115         0.203216         0.292492                 4541                          29

       Dataset  Horizon  SeqLen  Channels  BestEpoch  BestValMSE  OfficialStyle_MSE  OfficialStyle_MAE  OfficialStyle_BatchAverageMSE  OfficialStyle_Windows  FullStride1_MSE  FullStride1_MAE  FullStride1_Windows  ExcludedByOfficialDropLast  RuntimeMinutes                                         Checkpoint                        OfficialRepoCommit
0  Electricity       96     336       321         97    0.110311           0.129935           0.222482                       0.129935                   5152         0.129977         0.222527                 5165                          13      340.099770  /data/dataset/strong_forecaster/weather_electr...  204c21efe0b39603ad6e2ca640ef5896646ab1a9
1  Electricity      192     336       321         48    0.126097           0.148336           0.241681                       0.148336                   5056         0.149116         0.242038                 5069                          13      196.938228  /data/dataset/strong_forecaster/weather_electr...  204c21efe0b39603ad6e2ca640ef5896646ab1a9
2  Electricity      336     336       321         69    0.140645           0.164611           0.258211                       0.164611                   4896         0.165690         0.258694                 4925                          29      269.017774  /data/dataset/strong_forecaster/weather_electr...  204c21efe0b39603ad6e2ca640ef5896646ab1a9
3  Electricity      720     336       321         39    0.173104           0.202358           0.292115                       0.202358                   4512         0.203216         0.292492                 4541                          29      168.304391  /data/dataset/strong_forecaster/weather_electr...  204c21efe0b39603ad6e2ca640ef5896646ab1a9
4      Weather       96     336        21         65    0.390229           0.150419           0.198269                       0.150419                  10368         0.149690         0.197816                10444                          76       39.099661  /data/dataset/strong_forecaster/weather_electr...  204c21efe0b39603ad6e2ca640ef5896646ab1a9
5      Weather      192     336        21         45    0.456669           0.195386           0.241418                       0.195386                  10240         0.194775         0.240853                10348                         108       30.519710  /data/dataset/strong_forecaster/weather_electr...  204c21efe0b39603ad6e2ca640ef5896646ab1a9
6      Weather      336     336        21         19    0.547002           0.247370           0.282072                       0.247370                  10112         0.246900         0.281548                10204                          92       18.725101  /data/dataset/strong_forecaster/weather_electr...  204c21efe0b39603ad6e2ca640ef5896646ab1a9
7      Weather      720     336        21         23    0.653166           0.319053           0.334466                       0.319053                   9728         0.320894         0.334351                 9820                          92       21.177871  /data/dataset/strong_forecaster/weather_electr...  204c21efe0b39603ad6e2ca640ef5896646ab1a9

## 14. Compact baseline table

In [15]:

compact = summary_df[
    [
        "Dataset",
        "Horizon",
        "OfficialStyle_MSE",
        "OfficialStyle_MAE",
        "FullStride1_MSE",
        "FullStride1_MAE",
        "BestEpoch",
        "BestValMSE",
    ]
].copy()

display(compact)

compact.to_csv(
    RESULT_ROOT
    / "compact_baselines.csv",
    index=False,
)

       Dataset  Horizon  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  BestEpoch  BestValMSE
0  Electricity       96           0.129935           0.222482         0.129977         0.222527         97    0.110311
1  Electricity      192           0.148336           0.241681         0.149116         0.242038         48    0.126097
2  Electricity      336           0.164611           0.258211         0.165690         0.258694         69    0.140645
3  Electricity      720           0.202358           0.292115         0.203216         0.292492         39    0.173104
4      Weather       96           0.150419           0.198269         0.149690         0.197816         65    0.390229
5      Weather      192           0.195386           0.241418         0.194775         0.240853         45    0.456669
6      Weather      336           0.247370           0.282072         0.246900         0.281548         19    0.547002
7      Weather      720           0.319053           0.334466         0.320894         0.334351         23    0.653166

## 15. Optional comparison with the old Experiment 13 screening baseline

In [16]:

OLD_SUMMARY_CANDIDATES = [
    Path(
        "/data/dataset/strong_forecaster/"
        "multidataset_crossfit_screening/"
        "summary.csv"
    ),
    Path(
        "/data/dataset/strong_forecaster/"
        "multidataset_crossfit_screening/"
        "screening_summary.csv"
    ),
]

old_path = next(
    (
        p
        for p in OLD_SUMMARY_CANDIDATES
        if p.is_file()
    ),
    None,
)

if old_path is None:
    print(
        "Old Experiment 13 summary not found. "
        "This comparison is optional."
    )
else:
    old = pd.read_csv(old_path)

    print(
        "Old screening summary:",
        old_path,
    )

    # Handle the column names used in our previous notebooks.
    direct_col = next(
        (
            c
            for c in [
                "PatchTST_MSE",
                "Direct_MSE",
                "DirectMSE",
            ]
            if c in old.columns
        ),
        None,
    )

    horizon_col = next(
        (
            c
            for c in [
                "Horizon",
                "PredLen",
                "pred_len",
            ]
            if c in old.columns
        ),
        None,
    )

    dataset_col = next(
        (
            c
            for c in [
                "Dataset",
                "dataset",
            ]
            if c in old.columns
        ),
        None,
    )

    if (
        direct_col is None
        or horizon_col is None
        or dataset_col is None
    ):
        print(
            "Could not identify the old direct-baseline columns. "
            "Available columns:"
        )
        print(
            old.columns.tolist()
        )
    else:
        old_sub = old[
            old[
                dataset_col
            ].isin(
                DATASETS
            )
        ][
            [
                dataset_col,
                horizon_col,
                direct_col,
            ]
        ].copy()

        old_sub.columns = [
            "Dataset",
            "Horizon",
            "OldScreening_MSE",
        ]

        comparison = compact.merge(
            old_sub,
            on=[
                "Dataset",
                "Horizon",
            ],
            how="left",
        )

        comparison[
            "StrongGainVsOld_pct"
        ] = (
            100.0
            * (
                comparison[
                    "OldScreening_MSE"
                ]
                - comparison[
                    "FullStride1_MSE"
                ]
            )
            / comparison[
                "OldScreening_MSE"
            ]
        )

        display(comparison)

        comparison.to_csv(
            RESULT_ROOT
            / "comparison_vs_exp13.csv",
            index=False,
        )

Old screening summary: /data/dataset/strong_forecaster/multidataset_crossfit_screening/summary.csv

       Dataset  Horizon  OfficialStyle_MSE  OfficialStyle_MAE  FullStride1_MSE  FullStride1_MAE  BestEpoch  BestValMSE  OldScreening_MSE  StrongGainVsOld_pct
0  Electricity       96           0.129935           0.222482         0.129977         0.222527         97    0.110311          0.196270            33.776385
1  Electricity      192           0.148336           0.241681         0.149116         0.242038         48    0.126097          0.198762            24.977493
2  Electricity      336           0.164611           0.258211         0.165690         0.258694         69    0.140645          0.220282            24.782742
3  Electricity      720           0.202358           0.292115         0.203216         0.292492         39    0.173104          0.271241            25.078996
4      Weather       96           0.150419           0.198269         0.149690         0.197816         65    0.390229          0.172091            13.016606
5      Weather      192           0.195386           0.241418         0.194775         0.240853         45    0.456669          0.217632            10.502482
6      Weather      336           0.247370           0.282072         0.246900         0.281548         19    0.547002          0.273997             9.889319
7      Weather      720           0.319053           0.334466         0.320894         0.334351         23    0.653166          0.351578             8.727437


# 16. Experiment 18 decision rule

이번 실험에서는 retrieval 결과를 만들지 않습니다.

확인할 것은 다음 두 가지입니다.

### 1. Official-style baseline이 충분히 강한가?

공식 script와 동일한 architecture, split, optimizer, schedule을 사용했기 때문에
재현값이 통상적인 PatchTST 결과와 비슷한 범위인지 확인합니다.

### 2. FullStride1 baseline을 최종 direct 기준으로 고정

Experiment 19에서는 각 조건의

$$
\texttt{FullStride1\_MSE}
$$

와 정확히 동일한 test window에 retrieval augmentation을 적용합니다.

즉 Experiment 19의 비교는

$$
\boxed{
\text{Official PatchTST FullStride1}
\quad \text{vs.} \quad
\text{Official PatchTST FullStride1 + Frozen Memory}
}
$$

가 됩니다.

---

## 중요한 연구 원칙

Experiment 18 결과를 보고 retrieval architecture나 gate를 변경하지 않습니다.

Weather와 Electricity에서 strong PatchTST가 확정되면,
Experiment 19는 Experiment 16/17과 동일한 frozen augmentation을 그대로 적용합니다.

## 17. Saved artifacts

In [17]:

print("Result root:", RESULT_ROOT)

for p in sorted(
    RESULT_ROOT.rglob("*")
):
    if p.is_file():
        print(
            p.relative_to(
                RESULT_ROOT
            )
        )

Result root: /data/dataset/strong_forecaster/weather_electricity_official_patchtst_baselines
artifacts/dataset_protocol.csv
artifacts/official_repo_commit.txt
compact_baselines.csv
comparison_vs_exp13.csv
full_direct/electricity_L336_H192_official_recipe_seed2021.pt
full_direct/electricity_L336_H336_official_recipe_seed2021.pt
full_direct/electricity_L336_H720_official_recipe_seed2021.pt
full_direct/electricity_L336_H96_official_recipe_seed2021.pt
full_direct/weather_L336_H192_official_recipe_seed2021.pt
full_direct/weather_L336_H336_official_recipe_seed2021.pt
full_direct/weather_L336_H720_official_recipe_seed2021.pt
full_direct/weather_L336_H96_official_recipe_seed2021.pt
history/electricity_L336_H192_official_recipe_seed2021.csv
history/electricity_L336_H336_official_recipe_seed2021.csv
history/electricity_L336_H720_official_recipe_seed2021.csv
history/electricity_L336_H96_official_recipe_seed2021.csv
history/weather_L336_H192_official_recipe_seed2021.csv
history/weather_L336_H336_official_recipe_seed2021.csv
history/weather_L336_H720_official_recipe_seed2021.csv
history/weather_L336_H96_official_recipe_seed2021.csv
summary.csv