
# Experiment 19 — Strong PatchTST + Frozen Historical Memory on Weather and Electricity

## 핵심 질문

Experiment 18에서 Weather와 Electricity의 강한 official-level PatchTST baseline을 확정했습니다.

이제 그 checkpoint를 그대로 고정한 상태에서 기존 historical-memory module이 추가적인 예측 이득을 제공하는지 검증합니다.

$$
\boxed{
\text{Strong PatchTST}
+
\text{Frozen Historical Memory}
>
\text{Strong PatchTST}
}
$$

대상은 다음과 같습니다.

$$
H \in \{96, 192, 336, 720\}
$$

- Weather
- Electricity

---

## 이번 실험에서 변경하지 않는 요소

Retrieval 쪽은 Experiment 13에서 확정한 설정을 그대로 사용합니다.

### Predictive retriever

$$
s(q,i)
=
\gamma \cos(z_q,z_i)
$$

- EmbeddingOnly predictive retriever
- retrieval query length: \(L_R=96\)
- patch length: 16
- patch stride: 16
- embedding dimension: 64
- Top-\(K=10\)
- retrieval-memory stride: 24
- retrieved future: uniform Top-10 average

### Strong direct forecaster

Experiment 18의 official PatchTST checkpoint를 그대로 불러옵니다.

$$
L_D=336
$$

PatchTST는 이번 notebook에서 full model을 다시 학습하지 않습니다.

### Adaptive trust

Experiment 16/17과 같은 26-dimensional gate를 사용합니다.

$$
\hat{\mathbf y}
=
(1-\alpha_q)
\hat{\mathbf y}_{\mathrm{PatchTST}}
+
\alpha_q
\hat{\mathbf y}_{\mathrm{retrieval}}
$$

그리고 validation-calibrated shrinkage를 적용합니다.

$$
\alpha_{\mathrm{final}}
=
(1-\lambda)\alpha_0
+
\lambda\alpha_{\mathrm{gate}}
$$

---

## Leakage-free cross-fitting

Gate가 strong PatchTST의 error regime을 학습하도록
train split 내부에 세 개의 chronological fold를 만듭니다.

$$
0.55 \rightarrow 0.70
$$

$$
0.70 \rightarrow 0.85
$$

$$
0.85 \rightarrow 1.00
$$

각 fold에서:

1. prefix 구간만으로 normalization
2. prefix 구간만으로 official PatchTST fold model 학습
3. prefix 이전에 future까지 완전히 관측된 history만 retrieval memory로 사용
4. 바로 뒤 OOF 구간의 prediction과 retrieval을 생성
5. OOF target은 gate 학습에만 사용

Fold direct model의 epoch 수는 OOF target으로 고르지 않습니다.

Experiment 18의 full official PatchTST가 validation으로 선택한 best epoch 수를 고정하여 사용합니다.

$$
E_{\mathrm{fold}}
=
E_{\mathrm{full}}^{*}
$$

---

## Validation과 test

### Validation

- direct model: Experiment 18 train-only checkpoint
- retrieval memory: train histories only
- scalar \(\alpha_0\): validation only
- gate epoch: validation only
- shrinkage \(\lambda\): validation only

### Test

- direct model: Experiment 18 train-only checkpoint
- retrieval memory: train + validation histories only
- test history를 rolling memory에 추가하지 않음
- all valid test origins
- stride 1
- all channels

---

## 계산량 절약

Electricity는 321 channels이므로 cross-fitting이 매우 무겁습니다.

이 notebook은 다음을 모두 cache합니다.

- fold official PatchTST checkpoint
- fold OOF gate features
- validation gate features
- retrieval-memory embeddings
- gate checkpoint
- final per-anchor test losses
- condition별 summary

중간에 kernel이 종료되어도 `RESUME=True`로 이어서 실행할 수 있습니다.

완료된 dataset × horizon 조건은 자동으로 건너뜁니다.

In [1]:

from pathlib import Path
from types import SimpleNamespace
from contextlib import nullcontext

import gc
import importlib
import math
import random
import sys
import time
import warnings

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 220)
pd.set_option("display.width", 460)

DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

DATASETS = ["Weather", "Electricity"]
HORIZONS = [96, 192, 336, 720]

# Weather first: cheaper and gives an early scientific signal.
TASKS = [
    ("Weather", 96),
    ("Weather", 192),
    ("Weather", 336),
    ("Weather", 720),
    ("Electricity", 96),
    ("Electricity", 192),
    ("Electricity", 336),
    ("Electricity", 720),
]

DIRECT_SEQ_LEN = 336
RET_SEQ_LEN = 96

CROSSFIT_SEED = 1313

TOP_K = 10
MEMORY_STRIDE = 24
OOF_ANCHOR_STRIDE = 4

FOLDS = [
    (0.55, 0.70),
    (0.70, 0.85),
    (0.85, 1.00),
]

# Frozen predictive representation.
REP_PATCH_LEN = 16
REP_PATCH_STRIDE = 16
REP_D_MODEL = 64
REP_N_HEADS = 4
REP_LAYERS = 2
REP_D_FF = 128
REP_DIM = 64
REP_DROPOUT = 0.1

REP_NUM_PATCHES = (
    1
    + (
        RET_SEQ_LEN
        - REP_PATCH_LEN
    )
    // REP_PATCH_STRIDE
)

# Frozen adaptive gate.
GATE_DIM = 26
GATE_LR = 1e-3
GATE_WD = 1e-4
GATE_BATCH = 8192
GATE_MAX_EPOCHS = 50
GATE_PATIENCE = 7

ALPHA_GRID = np.round(
    np.arange(
        0.0,
        1.0001,
        0.1,
    ),
    10,
)

LAMBDA_GRID = np.array(
    [
        0.0,
        0.25,
        0.50,
        0.75,
        1.00,
    ],
    dtype=np.float32,
)

EPS = 1e-8
RETRIEVER_USE_AMP = torch.cuda.is_available()

# Keep roughly the same number of channel-query pairs per batch.
TARGET_QUERY_PAIRS = 672

EXP18_ROOT = Path(
    "/data/dataset/strong_forecaster/"
    "weather_electricity_official_patchtst_baselines"
)

FROZEN_RET_ROOT = Path(
    "/data/dataset/strong_forecaster/"
    "multidataset_crossfit_screening"
)

ROOT = Path(
    "/data/dataset/strong_forecaster/"
    "weather_electricity_official_patchtst_plus_frozen_retrieval"
)

DIRS = {
    "fold_direct": ROOT / "fold_direct",
    "oof": ROOT / "oof",
    "validation": ROOT / "validation",
    "memory_emb": ROOT / "memory_embeddings",
    "gate": ROOT / "gate",
    "history": ROOT / "history",
    "paired": ROOT / "paired_test",
    "channel": ROOT / "channel_test",
}

for p in DIRS.values():
    p.mkdir(
        parents=True,
        exist_ok=True,
    )

RESUME = True
FORCE = False

print("Device:", DEVICE)
print("Tasks:", TASKS)
print("Experiment 18:", EXP18_ROOT)
print("Frozen retrievers:", FROZEN_RET_ROOT)
print("Output:", ROOT)

Device: cuda
Tasks: [('Weather', 96), ('Weather', 192), ('Weather', 336), ('Weather', 720), ('Electricity', 96), ('Electricity', 192), ('Electricity', 336), ('Electricity', 720)]
Experiment 18: /data/dataset/strong_forecaster/weather_electricity_official_patchtst_baselines
Frozen retrievers: /data/dataset/strong_forecaster/multidataset_crossfit_screening
Output: /data/dataset/strong_forecaster/weather_electricity_official_patchtst_plus_frozen_retrieval

## 1. Load the same official PatchTST implementation used in Experiment 18

In [2]:

OFFICIAL_REPO_CANDIDATES = [
    Path(
        "/code/stock_regime_retrieval/"
        "strong_forecaster/PatchTST_official"
    ),
    Path("/code/PatchTST_official"),
    Path("/data/PatchTST_official"),
    Path("/data/PatchTST"),
]

OFFICIAL_REPO = next(
    (
        p
        for p in OFFICIAL_REPO_CANDIDATES
        if (
            p
            / "PatchTST_supervised"
            / "models"
            / "PatchTST.py"
        ).exists()
    ),
    None,
)

if OFFICIAL_REPO is None:
    raise FileNotFoundError(
        "Official PatchTST repository was not found. "
        "Experiment 18 should have used the same repository."
    )

SUPERVISED_ROOT = (
    OFFICIAL_REPO
    / "PatchTST_supervised"
)

for module_name in list(
    sys.modules.keys()
):
    if (
        module_name == "models"
        or module_name.startswith("models.")
        or module_name == "layers"
        or module_name.startswith("layers.")
    ):
        del sys.modules[module_name]

if str(SUPERVISED_ROOT) in sys.path:
    sys.path.remove(
        str(SUPERVISED_ROOT)
    )

sys.path.insert(
    0,
    str(SUPERVISED_ROOT),
)

patchtst_module = importlib.import_module(
    "models.PatchTST"
)

OfficialPatchTST = patchtst_module.Model

actual_model_file = Path(
    patchtst_module.__file__
).resolve()

expected_model_file = (
    SUPERVISED_ROOT
    / "models"
    / "PatchTST.py"
).resolve()

print("Imported:", actual_model_file)

if actual_model_file != expected_model_file:
    raise RuntimeError(
        "Wrong PatchTST implementation imported.\n"
        f"Expected: {expected_model_file}\n"
        f"Actual:   {actual_model_file}"
    )

print(
    "PASS: official PatchTST implementation is active."
)

Imported: /code/stock_regime_retrieval/strong_forecaster/PatchTST_official/PatchTST_supervised/models/PatchTST.py
PASS: official PatchTST implementation is active.

## 2. Load Experiment 18 dataset paths and reproduce its exact data ordering

In [3]:

EXP18_SUMMARY_PATH = (
    EXP18_ROOT
    / "summary.csv"
)

if not EXP18_SUMMARY_PATH.is_file():
    raise FileNotFoundError(
        f"Experiment 18 summary not found: {EXP18_SUMMARY_PATH}"
    )

EXP18_SUMMARY = pd.read_csv(
    EXP18_SUMMARY_PATH
)

display(
    EXP18_SUMMARY[
        [
            "Dataset",
            "Horizon",
            "FullStride1_MSE",
            "FullStride1_MAE",
            "BestEpoch",
        ]
    ].sort_values(
        [
            "Dataset",
            "Horizon",
        ]
    )
)


DATA_PATH_CANDIDATES = {
    "Weather": [
        Path("/data/dataset/weather.csv"),
        Path("/data/dataset/weather/weather.csv"),
        Path(
            "/data/Time-Series-Library/"
            "dataset/weather/weather.csv"
        ),
        Path(
            "/data/Time-Series-Library/"
            "dataset/weather.csv"
        ),
        Path(
            "/data/Time-Series-Library_v2/"
            "dataset/weather/weather.csv"
        ),
        Path(
            "/data/Time-Series-Library_v2/"
            "dataset/weather.csv"
        ),
    ],
    "Electricity": [
        Path("/data/dataset/electricity.csv"),
        Path(
            "/data/dataset/electricity/"
            "electricity.csv"
        ),
        Path(
            "/data/Time-Series-Library/"
            "dataset/electricity/electricity.csv"
        ),
        Path(
            "/data/Time-Series-Library/"
            "dataset/electricity.csv"
        ),
        Path(
            "/data/Time-Series-Library_v2/"
            "dataset/electricity/electricity.csv"
        ),
        Path(
            "/data/Time-Series-Library_v2/"
            "dataset/electricity.csv"
        ),
    ],
}

DATA_PATHS = {}

for name, candidates in DATA_PATH_CANDIDATES.items():
    hit = next(
        (
            p
            for p in candidates
            if p.is_file()
        ),
        None,
    )

    DATA_PATHS[name] = hit

    print(
        f"{name:11s}:",
        hit if hit is not None else "NOT FOUND",
    )

if any(
    p is None
    for p in DATA_PATHS.values()
):
    raise FileNotFoundError(
        "Weather/Electricity CSV path not found. "
        "Use the same dataset paths as Experiment 18."
    )


EXPECTED_CHANNELS = {
    "Weather": 21,
    "Electricity": 321,
}


def prepare_custom_data(
    name,
):
    path = DATA_PATHS[name]

    df_raw = pd.read_csv(
        path
    )

    if "date" not in df_raw.columns:
        raise ValueError(
            f"{name}: expected a date column."
        )

    if "OT" not in df_raw.columns:
        raise ValueError(
            f"{name}: expected OT target column."
        )

    # Exact Experiment 18 / official Dataset_Custom ordering:
    # date, all other variables, OT.
    cols = list(
        df_raw.columns
    )

    cols.remove(
        "OT"
    )

    cols.remove(
        "date"
    )

    ordered = df_raw[
        ["date"]
        + cols
        + ["OT"]
    ].copy()

    value_cols = list(
        ordered.columns[
            1:
        ]
    )

    raw = ordered[
        value_cols
    ].to_numpy(
        dtype=np.float32
    )

    n = len(
        raw
    )

    num_train = int(
        n
        * 0.7
    )

    num_test = int(
        n
        * 0.2
    )

    num_val = (
        n
        - num_train
        - num_test
    )

    train_end = num_train
    val_end = (
        num_train
        + num_val
    )

    test_end = n

    mu = raw[
        :train_end
    ].mean(
        axis=0
    ).astype(
        np.float32
    )

    sd = raw[
        :train_end
    ].std(
        axis=0
    ).astype(
        np.float32
    )

    if np.any(
        sd <= 1e-6
    ):
        raise ValueError(
            f"{name}: degenerate train channel."
        )

    z = (
        (
            raw
            - mu[
                None,
                :
            ]
        )
        / sd[
            None,
            :
        ]
    ).astype(
        np.float32
    )

    if (
        raw.shape[
            1
        ]
        != EXPECTED_CHANNELS[
            name
        ]
    ):
        raise ValueError(
            f"{name}: expected "
            f"{EXPECTED_CHANNELS[name]} channels, "
            f"found {raw.shape[1]}."
        )

    return {
        "name": name,
        "path": path,
        "columns": value_cols,
        "raw": raw,
        "z": z,
        "mean": mu,
        "std": sd,
        "n_channels": raw.shape[
            1
        ],
        "train_end": train_end,
        "val_end": val_end,
        "test_end": test_end,
        "num_train": num_train,
        "num_val": num_val,
        "num_test": num_test,
    }


DATA = {
    name:
        prepare_custom_data(
            name
        )
    for name in DATASETS
}

display(
    pd.DataFrame([
        {
            "Dataset": name,
            "Path": str(
                d[
                    "path"
                ]
            ),
            "Rows": len(
                d[
                    "raw"
                ]
            ),
            "Channels": d[
                "n_channels"
            ],
            "TrainEnd": d[
                "train_end"
            ],
            "ValEnd": d[
                "val_end"
            ],
            "TestEnd": d[
                "test_end"
            ],
        }
        for name, d
        in DATA.items()
    ])
)

       Dataset  Horizon  FullStride1_MSE  FullStride1_MAE  BestEpoch
4  Electricity       96         0.129977         0.222527         97
5  Electricity      192         0.149116         0.242038         48
6  Electricity      336         0.165690         0.258694         69
7  Electricity      720         0.203216         0.292492         39
0      Weather       96         0.149690         0.197816         65
1      Weather      192         0.194775         0.240853         45
2      Weather      336         0.246900         0.281548         19
3      Weather      720         0.320894         0.334351         23

Weather    : /data/Time-Series-Library/dataset/weather/weather.csv
Electricity: /data/Time-Series-Library/dataset/electricity/electricity.csv

       Dataset                                               Path   Rows  Channels  TrainEnd  ValEnd  TestEnd
0      Weather  /data/Time-Series-Library/dataset/weather/weat...  52696        21     36887   42157    52696
1  Electricity  /data/Time-Series-Library/dataset/electricity/...  26304       321     18412   21044    26304

## 3. Official PatchTST recipes and Experiment 18 checkpoint loader

In [4]:

RECIPES = {
    "Weather": {
        "enc_in": 21,
        "e_layers": 3,
        "n_heads": 16,
        "d_model": 128,
        "d_ff": 256,
        "dropout": 0.2,
        "fc_dropout": 0.2,
        "head_dropout": 0.0,
        "patch_len": 16,
        "stride": 8,
        "batch_size": 128,
        "train_epochs": 100,
        "learning_rate": 1e-4,
        "lradj": "type3",
        "pct_start": 0.3,
    },
    "Electricity": {
        "enc_in": 321,
        "e_layers": 3,
        "n_heads": 16,
        "d_model": 128,
        "d_ff": 256,
        "dropout": 0.2,
        "fc_dropout": 0.2,
        "head_dropout": 0.0,
        "patch_len": 16,
        "stride": 8,
        "batch_size": 32,
        "train_epochs": 100,
        "learning_rate": 1e-4,
        "lradj": "TST",
        "pct_start": 0.2,
    },
}


def official_config(
    name,
    horizon,
):
    r = RECIPES[
        name
    ]

    return SimpleNamespace(
        enc_in=
            r[
                "enc_in"
            ],
        seq_len=
            DIRECT_SEQ_LEN,
        pred_len=
            int(
                horizon
            ),
        e_layers=
            r[
                "e_layers"
            ],
        n_heads=
            r[
                "n_heads"
            ],
        d_model=
            r[
                "d_model"
            ],
        d_ff=
            r[
                "d_ff"
            ],
        dropout=
            r[
                "dropout"
            ],
        fc_dropout=
            r[
                "fc_dropout"
            ],
        head_dropout=
            r[
                "head_dropout"
            ],
        individual=0,
        patch_len=
            r[
                "patch_len"
            ],
        stride=
            r[
                "stride"
            ],
        padding_patch=
            "end",
        revin=1,
        affine=0,
        subtract_last=0,
        decomposition=0,
        kernel_size=25,
    )


def build_official_model(
    name,
    horizon,
):
    return OfficialPatchTST(
        official_config(
            name,
            horizon,
        )
    ).float().to(
        DEVICE
    )


def load_torch(
    path,
):
    try:
        return torch.load(
            path,
            map_location=DEVICE,
            weights_only=False,
        )
    except TypeError:
        return torch.load(
            path,
            map_location=DEVICE,
        )


def exp18_direct_ckpt_path(
    name,
    horizon,
):
    return (
        EXP18_ROOT
        / "full_direct"
        / (
            f"{name.lower()}_L336_H{horizon}_"
            "official_recipe_seed2021.pt"
        )
    )


def load_exp18_direct(
    name,
    horizon,
):
    path = exp18_direct_ckpt_path(
        name,
        horizon,
    )

    ckpt = load_torch(
        path
    )

    model = build_official_model(
        name,
        horizon,
    )

    model.load_state_dict(
        ckpt[
            "StateDict"
        ]
    )

    model.eval()

    return (
        model,
        ckpt,
    )


def exp18_reference(
    name,
    horizon,
):
    hit = EXP18_SUMMARY[
        (
            EXP18_SUMMARY[
                "Dataset"
            ]
            == name
        )
        & (
            EXP18_SUMMARY[
                "Horizon"
            ]
            == horizon
        )
    ]

    if len(
        hit
    ) != 1:
        raise RuntimeError(
            f"Expected exactly one Experiment 18 row "
            f"for {name} H={horizon}."
        )

    return hit.iloc[
        0
    ]

## 4. Frozen retriever and gate definitions

In [5]:

def inv_softplus(
    x,
):
    return math.log(
        math.exp(
            float(
                x
            )
        )
        - 1.0
    )


class PredictivePatchEncoder(
    nn.Module
):
    def __init__(
        self,
    ):
        super().__init__()

        self.patch_proj = nn.Linear(
            REP_PATCH_LEN,
            REP_D_MODEL,
        )

        self.pos_embed = nn.Parameter(
            torch.zeros(
                1,
                REP_NUM_PATCHES,
                REP_D_MODEL,
            )
        )

        nn.init.trunc_normal_(
            self.pos_embed,
            std=0.02,
        )

        layer = nn.TransformerEncoderLayer(
            d_model=
                REP_D_MODEL,
            nhead=
                REP_N_HEADS,
            dim_feedforward=
                REP_D_FF,
            dropout=
                REP_DROPOUT,
            activation=
                "gelu",
            batch_first=
                True,
            norm_first=
                True,
        )

        self.encoder = nn.TransformerEncoder(
            layer,
            num_layers=
                REP_LAYERS,
        )

        self.norm = nn.LayerNorm(
            REP_D_MODEL
        )

        self.proj = nn.Linear(
            REP_D_MODEL,
            REP_DIM,
        )

    def forward(
        self,
        x,
    ):
        p = x.unfold(
            1,
            REP_PATCH_LEN,
            REP_PATCH_STRIDE,
        )

        h = (
            self.patch_proj(
                p
            )
            + self.pos_embed[
                :,
                :p.shape[
                    1
                ],
            ]
        )

        h = self.encoder(
            h
        ).mean(
            dim=1
        )

        h = self.proj(
            self.norm(
                h
            )
        )

        return F.normalize(
            h,
            dim=-1,
            eps=1e-8,
        )


class EmbeddingOnlyRetriever(
    nn.Module
):
    def __init__(
        self,
    ):
        super().__init__()

        self.encoder = (
            PredictivePatchEncoder()
        )

        self.raw_gamma = nn.Parameter(
            torch.tensor(
                inv_softplus(
                    1.0
                ),
                dtype=torch.float32,
            )
        )

    @property
    def gamma(
        self,
    ):
        return F.softplus(
            self.raw_gamma
        )

    def encode(
        self,
        x,
    ):
        return self.encoder(
            x
        )


class CrossFitAdaptiveGate(
    nn.Module
):
    def __init__(
        self,
    ):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(
                GATE_DIM,
                64,
            ),
            nn.LayerNorm(
                64
            ),
            nn.GELU(),
            nn.Dropout(
                0.1
            ),
            nn.Linear(
                64,
                32,
            ),
            nn.GELU(),
            nn.Dropout(
                0.1
            ),
            nn.Linear(
                32,
                1,
            ),
        )

        nn.init.normal_(
            self.net[
                -1
            ].weight,
            mean=0.0,
            std=1e-3,
        )

        nn.init.constant_(
            self.net[
                -1
            ].bias,
            math.log(
                0.1
                / 0.9
            ),
        )

    def forward(
        self,
        x,
    ):
        return torch.sigmoid(
            self.net(
                x
            ).squeeze(
                -1
            )
        )


def ret_amp():
    if RETRIEVER_USE_AMP:
        return torch.autocast(
            device_type="cuda",
            dtype=torch.float16,
        )

    return nullcontext()


def full_retriever_ckpt_path(
    name,
    horizon,
):
    return (
        FROZEN_RET_ROOT
        / "full_retriever"
        / (
            f"{name}_H{horizon}_seed0.pt"
        )
    )


def fold_retriever_ckpt_path(
    name,
    horizon,
    fold,
):
    return (
        FROZEN_RET_ROOT
        / "fold_retriever"
        / (
            f"{name}_H{horizon}_F{fold}_seed0.pt"
        )
    )


def load_frozen_retriever(
    path,
):
    ckpt = load_torch(
        path
    )

    model = EmbeddingOnlyRetriever().to(
        DEVICE
    )

    model.load_state_dict(
        ckpt[
            "StateDict"
        ]
    )

    model.eval()

    return (
        model,
        ckpt,
    )

## 5. Preflight — stop before expensive computation if anything is missing

In [6]:

preflight_rows = []

for name, horizon in TASKS:
    preflight_rows.append({
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Kind":
            "Experiment18 direct",
        "Path":
            exp18_direct_ckpt_path(
                name,
                horizon,
            ),
    })

    preflight_rows.append({
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Kind":
            "Full frozen retriever",
        "Path":
            full_retriever_ckpt_path(
                name,
                horizon,
            ),
    })

    for fold in range(
        1,
        4,
    ):
        preflight_rows.append({
            "Dataset":
                name,
            "Horizon":
                horizon,
            "Kind":
                f"Fold retriever F{fold}",
            "Path":
                fold_retriever_ckpt_path(
                    name,
                    horizon,
                    fold,
                ),
        })

preflight = pd.DataFrame(
    preflight_rows
)

preflight[
    "Exists"
] = preflight[
    "Path"
].map(
    lambda p:
        Path(
            p
        ).is_file()
)

display(
    preflight
)

missing = preflight[
    ~preflight[
        "Exists"
    ]
]

if len(
    missing
):
    print(
        "\nMissing prerequisites:"
    )

    for p in missing[
        "Path"
    ]:
        print(
            " -",
            p,
        )

    raise FileNotFoundError(
        "Required Experiment 18 or frozen Experiment 13 checkpoint "
        "is missing. Do not silently retrain a different retriever."
    )

print(
    "PASS: every prerequisite checkpoint is present."
)

        Dataset  Horizon                   Kind                                               Path  Exists
0       Weather       96    Experiment18 direct  /data/dataset/strong_forecaster/weather_electr...    True
1       Weather       96  Full frozen retriever  /data/dataset/strong_forecaster/multidataset_c...    True
2       Weather       96      Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
3       Weather       96      Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
4       Weather       96      Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True
5       Weather      192    Experiment18 direct  /data/dataset/strong_forecaster/weather_electr...    True
6       Weather      192  Full frozen retriever  /data/dataset/strong_forecaster/multidataset_c...    True
7       Weather      192      Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
8       Weather      192      Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
9       Weather      192      Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True
10      Weather      336    Experiment18 direct  /data/dataset/strong_forecaster/weather_electr...    True
11      Weather      336  Full frozen retriever  /data/dataset/strong_forecaster/multidataset_c...    True
12      Weather      336      Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
13      Weather      336      Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
14      Weather      336      Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True
15      Weather      720    Experiment18 direct  /data/dataset/strong_forecaster/weather_electr...    True
16      Weather      720  Full frozen retriever  /data/dataset/strong_forecaster/multidataset_c...    True
17      Weather      720      Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
18      Weather      720      Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
19      Weather      720      Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True
20  Electricity       96    Experiment18 direct  /data/dataset/strong_forecaster/weather_electr...    True
21  Electricity       96  Full frozen retriever  /data/dataset/strong_forecaster/multidataset_c...    True
22  Electricity       96      Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
23  Electricity       96      Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
24  Electricity       96      Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True
25  Electricity      192    Experiment18 direct  /data/dataset/strong_forecaster/weather_electr...    True
26  Electricity      192  Full frozen retriever  /data/dataset/strong_forecaster/multidataset_c...    True
27  Electricity      192      Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
28  Electricity      192      Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
29  Electricity      192      Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True
30  Electricity      336    Experiment18 direct  /data/dataset/strong_forecaster/weather_electr...    True
31  Electricity      336  Full frozen retriever  /data/dataset/strong_forecaster/multidataset_c...    True
32  Electricity      336      Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
33  Electricity      336      Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
34  Electricity      336      Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True
35  Electricity      720    Experiment18 direct  /data/dataset/strong_forecaster/weather_electr...    True
36  Electricity      720  Full frozen retriever  /data/dataset/strong_forecaster/multidataset_c...    True
37  Electricity      720      Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
38  Electricity      720      Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
39  Electricity      720      Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True

PASS: every prerequisite checkpoint is present.

## 6. Core time-series utilities

In [7]:

def query_anchor_batch(
    name,
):
    c = DATA[
        name
    ][
        "n_channels"
    ]

    return max(
        1,
        TARGET_QUERY_PAIRS
        // c,
    )


def eval_anchors(
    start,
    end,
    horizon,
    stride=1,
):
    return np.arange(
        max(
            int(
                start
            ),
            DIRECT_SEQ_LEN,
        ),
        int(
            end
        )
        - int(
            horizon
        )
        + 1,
        int(
            stride
        ),
        dtype=np.int64,
    )


def set_seed(
    seed,
):
    random.seed(
        seed
    )

    np.random.seed(
        seed
    )

    torch.manual_seed(
        seed
    )

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(
            seed
        )

    torch.backends.cudnn.benchmark = False


def prefix_norm(
    raw,
    prefix,
):
    mu = raw[
        :prefix
    ].mean(
        axis=0
    ).astype(
        np.float32
    )

    sd = raw[
        :prefix
    ].std(
        axis=0
    ).astype(
        np.float32
    )

    if np.any(
        sd <= 1e-6
    ):
        raise ValueError(
            "Degenerate prefix channel."
        )

    return (
        (
            raw
            - mu[
                None,
                :
            ]
        )
        / sd[
            None,
            :
        ]
    ).astype(
        np.float32
    )


def batch_pattern(
    x,
):
    x = np.asarray(
        x,
        np.float32,
    )

    xc = (
        x
        - x.mean(
            axis=-1,
            keepdims=True,
        )
    )

    n = np.linalg.norm(
        xc,
        axis=-1,
        keepdims=True,
    )

    return np.where(
        n > EPS,
        xc
        / np.maximum(
            n,
            EPS,
        ),
        0.0,
    ).astype(
        np.float32
    )


def context7(
    x,
):
    x = np.asarray(
        x,
        np.float32,
    )

    short = max(
        8,
        RET_SEQ_LEN
        // 4,
    )

    m = x.mean(
        axis=-1
    )

    s = (
        x.std(
            axis=-1
        )
        + EPS
    )

    f1 = (
        x[
            ...,
            -1
        ]
        - m
    ) / s

    f2 = (
        x[
            ...,
            -short:
        ].mean(
            axis=-1
        )
        - m
    ) / s

    f3 = (
        x[
            ...,
            -1
        ]
        - x[
            ...,
            -short
        ]
    ) / s

    f4 = (
        x[
            ...,
            -1
        ]
        - x[
            ...,
            0
        ]
    ) / s

    df = np.diff(
        x,
        axis=-1,
    )

    ds = np.diff(
        x[
            ...,
            -short:
        ],
        axis=-1,
    )

    f5 = (
        ds.std(
            axis=-1
        )
        + EPS
    ) / (
        df.std(
            axis=-1
        )
        + EPS
    )

    t = np.linspace(
        -1.0,
        1.0,
        RET_SEQ_LEN,
        dtype=np.float32,
    )

    t = (
        t
        - t.mean()
    )

    f6 = (
        np.sum(
            t
            * (
                x
                - m[
                    ...,
                    None
                ]
            ),
            axis=-1,
        )
        / (
            np.sum(
                t
                * t
            )
            + EPS
        )
    ) / s

    a = x[
        ...,
        :-1
    ]

    b = x[
        ...,
        1:
    ]

    a = (
        a
        - a.mean(
            axis=-1,
            keepdims=True,
        )
    )

    b = (
        b
        - b.mean(
            axis=-1,
            keepdims=True,
        )
    )

    f7 = np.sum(
        a
        * b,
        axis=-1,
    ) / (
        np.sqrt(
            np.sum(
                a
                * a,
                axis=-1,
            )
            * np.sum(
                b
                * b,
                axis=-1,
            )
        )
        + EPS
    )

    return np.stack(
        [
            f1,
            f2,
            f3,
            f4,
            f5,
            f6,
            f7,
        ],
        axis=-1,
    ).astype(
        np.float32
    )


def extract_channel(
    z,
    c,
    anchors,
    horizon,
):
    anchors = np.asarray(
        anchors,
        np.int64,
    )

    pi = (
        anchors[
            :,
            None
        ]
        - RET_SEQ_LEN
        + np.arange(
            RET_SEQ_LEN
        )[
            None,
            :
        ]
    )

    fi = (
        anchors[
            :,
            None
        ]
        + np.arange(
            horizon
        )[
            None,
            :
        ]
    )

    past = z[
        pi,
        c,
    ].astype(
        np.float32
    )

    future = z[
        fi,
        c,
    ].astype(
        np.float32
    )

    current = z[
        anchors
        - 1,
        c,
    ].astype(
        np.float32
    )

    future_residual = (
        future
        - current[
            :,
            None
        ]
    ).astype(
        np.float32
    )

    return (
        past,
        future_residual,
    )


def build_memory(
    z,
    channels,
    boundary,
    horizon,
):
    memory_anchors = np.arange(
        RET_SEQ_LEN,
        int(
            boundary
        )
        - horizon
        + 1,
        MEMORY_STRIDE,
        dtype=np.int64,
    )

    if len(
        memory_anchors
    ) < TOP_K:
        raise ValueError(
            "Insufficient admissible retrieval memory."
        )

    past = np.empty(
        (
            channels,
            len(
                memory_anchors
            ),
            RET_SEQ_LEN,
        ),
        dtype=np.float32,
    )

    pattern = np.empty_like(
        past
    )

    future = np.empty(
        (
            channels,
            len(
                memory_anchors
            ),
            horizon,
        ),
        dtype=np.float32,
    )

    for c in range(
        channels
    ):
        p, f = extract_channel(
            z,
            c,
            memory_anchors,
            horizon,
        )

        past[
            c
        ] = p

        pattern[
            c
        ] = batch_pattern(
            p
        )

        future[
            c
        ] = f

    return {
        "anchors":
            memory_anchors,
        "past":
            past,
        "pattern":
            pattern,
        "future":
            future,
        "M":
            len(
                memory_anchors
            ),
        "boundary":
            int(
                boundary
            ),
    }


def query_pairs(
    z,
    anchors,
    channels,
    horizon,
):
    anchors = np.asarray(
        anchors,
        np.int64,
    )

    channels = np.asarray(
        channels,
        np.int64,
    )

    pi = (
        anchors[
            :,
            None
        ]
        - RET_SEQ_LEN
        + np.arange(
            RET_SEQ_LEN
        )[
            None,
            :
        ]
    )

    fi = (
        anchors[
            :,
            None
        ]
        + np.arange(
            horizon
        )[
            None,
            :
        ]
    )

    past = z[
        pi,
        channels[
            :,
            None
        ],
    ].astype(
        np.float32
    )

    future = z[
        fi,
        channels[
            :,
            None
        ],
    ].astype(
        np.float32
    )

    current = z[
        anchors
        - 1,
        channels,
    ].astype(
        np.float32
    )

    true_residual = (
        future
        - current[
            :,
            None
        ]
    ).astype(
        np.float32
    )

    return (
        past,
        batch_pattern(
            past
        ),
        context7(
            past
        ),
        true_residual,
    )

## 7. Cached retrieval-memory embeddings

In [8]:

@torch.no_grad()
def encode_np(
    model,
    x,
    chunk=512,
):
    parts = []

    for i in range(
        0,
        len(
            x
        ),
        chunk,
    ):
        t = torch.from_numpy(
            x[
                i:
                i+chunk
            ]
        ).to(
            DEVICE
        )

        with ret_amp():
            e = model.encode(
                t
            ).float()

        parts.append(
            e.cpu()
        )

        del (
            t,
            e,
        )

    return torch.cat(
        parts,
        dim=0,
    ).numpy().astype(
        np.float32
    )


def memory_embedding_cache_path(
    name,
    horizon,
    tag,
):
    return (
        DIRS[
            "memory_emb"
        ]
        / (
            f"{name}_H{horizon}_{tag}_emb.npy"
        )
    )


@torch.no_grad()
def memory_gpu_cached(
    name,
    horizon,
    tag,
    model,
    memory,
    channels,
):
    path = memory_embedding_cache_path(
        name,
        horizon,
        tag,
    )

    expected_shape = (
        channels,
        memory[
            "M"
        ],
        REP_DIM,
    )

    emb_np = None

    if (
        path.exists()
        and RESUME
        and not FORCE
    ):
        candidate = np.load(
            path
        )

        if (
            tuple(
                candidate.shape
            )
            == expected_shape
        ):
            emb_np = candidate.astype(
                np.float32,
                copy=False,
            )

            print(
                "Loaded memory embedding cache:",
                path.name,
            )

    if emb_np is None:
        print(
            "Building memory embedding cache:",
            path.name,
            expected_shape,
        )

        emb_np = np.empty(
            expected_shape,
            dtype=np.float32,
        )

        for c in range(
            channels
        ):
            emb_np[
                c
            ] = encode_np(
                model,
                memory[
                    "past"
                ][
                    c
                ],
            )

            if (
                c == 0
                or (
                    c + 1
                )
                % 50
                == 0
                or c + 1
                == channels
            ):
                print(
                    f"  encoded channel "
                    f"{c+1}/{channels}"
                )

        np.save(
            path,
            emb_np,
        )

    return {
        "emb":
            torch.from_numpy(
                emb_np
            ).to(
                DEVICE
            ),
        "pattern":
            torch.from_numpy(
                memory[
                    "pattern"
                ]
            ).to(
                DEVICE
            ),
        "future":
            torch.from_numpy(
                memory[
                    "future"
                ]
            ).to(
                DEVICE
            ),
    }

## 8. Frozen retriever inference

In [9]:

@torch.no_grad()
def retrieve(
    model,
    memory_gpu_obj,
    z,
    anchors,
    channels,
    horizon,
):
    past, pattern, ctx, true = query_pairs(
        z,
        anchors,
        channels,
        horizon,
    )

    past_t = torch.from_numpy(
        past
    ).to(
        DEVICE
    )

    pattern_t = torch.from_numpy(
        pattern
    ).to(
        DEVICE
    )

    with ret_amp():
        qemb = model.encode(
            past_t
        )

    qemb = qemb.float()

    memb = memory_gpu_obj[
        "emb"
    ][
        channels
    ]

    sim = torch.bmm(
        qemb[
            :,
            None,
            :
        ],
        memb.transpose(
            1,
            2,
        ),
    ).squeeze(
        1
    )

    score = (
        model.gamma
        * sim
    )

    idx = torch.topk(
        score,
        TOP_K,
        dim=1,
    ).indices

    row = torch.arange(
        len(
            channels
        ),
        device=DEVICE,
    )[
        :,
        None
    ]

    pfull = torch.bmm(
        pattern_t[
            :,
            None,
            :
        ],
        memory_gpu_obj[
            "pattern"
        ][
            channels
        ].transpose(
            1,
            2,
        ),
    ).squeeze(
        1
    )

    return {
        "score":
            score[
                row,
                idx
            ],
        "sim":
            sim[
                row,
                idx
            ],
        "pattern":
            pfull[
                row,
                idx
            ],
        "cand":
            memory_gpu_obj[
                "future"
            ][
                channels[
                    :,
                    None
                ],
                idx,
            ],
        "ctx":
            torch.from_numpy(
                ctx
            ).to(
                DEVICE
            ),
        "true":
            torch.from_numpy(
                true
            ).to(
                DEVICE
            ),
    }


## 9. Strong PatchTST residual prediction

Retriever는 query의 마지막 관측값을 기준으로 future residual을 예측합니다.

따라서 PatchTST도 동일한 좌표로 변환합니다.

$$
\Delta
\hat{\mathbf y}_{\mathrm{direct}}
=
\hat{\mathbf y}_{\mathrm{direct}}
-
\mathbf x_{t}
$$

같은 current value를 빼므로 residual space의 MSE는 original normalized-value space의 MSE와 동일합니다.

In [10]:

@torch.no_grad()
def direct_residual(
    model,
    z,
    anchors,
    horizon,
):
    anchors = np.asarray(
        anchors,
        np.int64,
    )

    pi = (
        anchors[
            :,
            None
        ]
        - DIRECT_SEQ_LEN
        + np.arange(
            DIRECT_SEQ_LEN
        )[
            None,
            :
        ]
    )

    x = torch.from_numpy(
        z[
            pi,
            :
        ].astype(
            np.float32
        )
    ).to(
        DEVICE
    )

    pred = model(
        x
    ).float()

    residual = (
        pred
        - x[
            :,
            -1:,
            :
        ].float()
    )

    del (
        x,
        pred,
    )

    return residual

## 10. Exact official fold-direct training

In [11]:

def adjust_type3_lr(
    optimizer,
    base_lr,
    epoch,
):
    lr = (
        base_lr
        if epoch < 3
        else base_lr
        * (
            0.9
            ** (
                epoch
                - 3
            )
        )
    )

    for group in optimizer.param_groups:
        group[
            "lr"
        ] = lr

    return lr


def fold_direct_path(
    name,
    horizon,
    fold,
):
    return (
        DIRS[
            "fold_direct"
        ]
        / (
            f"{name}_H{horizon}_F{fold}_"
            "official_direct.pt"
        )
    )


def direct_train_anchors(
    end,
    horizon,
):
    return np.arange(
        DIRECT_SEQ_LEN,
        int(
            end
        )
        - horizon
        + 1,
        dtype=np.int64,
    )


def make_direct_batch(
    z,
    anchors,
    horizon,
):
    anchors = np.asarray(
        anchors,
        np.int64,
    )

    pi = (
        anchors[
            :,
            None
        ]
        - DIRECT_SEQ_LEN
        + np.arange(
            DIRECT_SEQ_LEN
        )[
            None,
            :
        ]
    )

    fi = (
        anchors[
            :,
            None
        ]
        + np.arange(
            horizon
        )[
            None,
            :
        ]
    )

    return (
        z[
            pi,
            :
        ].astype(
            np.float32
        ),
        z[
            fi,
            :
        ].astype(
            np.float32
        ),
    )


def train_fold_official_direct(
    name,
    horizon,
    z,
    prefix,
    fixed_epochs,
    fold,
):
    path = fold_direct_path(
        name,
        horizon,
        fold,
    )

    if (
        path.exists()
        and RESUME
        and not FORCE
    ):
        ckpt = load_torch(
            path
        )

        model = build_official_model(
            name,
            horizon,
        )

        model.load_state_dict(
            ckpt[
                "StateDict"
            ]
        )

        model.eval()

        print(
            "Loaded fold direct:",
            path.name,
        )

        return (
            model,
            ckpt,
        )

    r = RECIPES[
        name
    ]

    seed = (
        CROSSFIT_SEED
        + horizon
        * 100
        + fold
        * 13
        + int(
            prefix
        )
        % 997
    )

    set_seed(
        seed
    )

    model = build_official_model(
        name,
        horizon,
    )

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=
            r[
                "learning_rate"
            ],
    )

    train_aa = direct_train_anchors(
        prefix,
        horizon,
    )

    steps_per_epoch = (
        len(
            train_aa
        )
        // r[
            "batch_size"
        ]
    )

    if steps_per_epoch < 1:
        raise ValueError(
            f"{name} H={horizon} F{fold}: "
            "insufficient training windows."
        )

    onecycle = torch.optim.lr_scheduler.OneCycleLR(
        optimizer=
            optimizer,
        steps_per_epoch=
            steps_per_epoch,
        pct_start=
            r[
                "pct_start"
            ],
        epochs=
            r[
                "train_epochs"
            ],
        max_lr=
            r[
                "learning_rate"
            ],
    )

    rng = np.random.default_rng(
        seed
        + 1
    )

    history = []

    for epoch in range(
        1,
        int(
            fixed_epochs
        )
        + 1,
    ):
        model.train()

        order = rng.permutation(
            len(
                train_aa
            )
        )

        usable = (
            len(
                order
            )
            // r[
                "batch_size"
            ]
        ) * r[
            "batch_size"
        ]

        order = order[
            :usable
        ]

        losses = []

        for left in range(
            0,
            usable,
            r[
                "batch_size"
            ],
        ):
            ids = order[
                left:
                left
                + r[
                    "batch_size"
                ]
            ]

            x_np, y_np = make_direct_batch(
                z,
                train_aa[
                    ids
                ],
                horizon,
            )

            x = torch.from_numpy(
                x_np
            ).to(
                DEVICE
            )

            y = torch.from_numpy(
                y_np
            ).to(
                DEVICE
            )

            optimizer.zero_grad(
                set_to_none=True
            )

            pred = model(
                x
            )

            loss = F.mse_loss(
                pred,
                y,
            )

            loss.backward()

            optimizer.step()

            losses.append(
                float(
                    loss.item()
                )
            )

            if r[
                "lradj"
            ] == "TST":
                current = onecycle.get_last_lr()[
                    0
                ]

                for group in optimizer.param_groups:
                    group[
                        "lr"
                    ] = current

                onecycle.step()

            del (
                x,
                y,
                pred,
                loss,
            )

        if r[
            "lradj"
        ] != "TST":
            lr = adjust_type3_lr(
                optimizer,
                r[
                    "learning_rate"
                ],
                epoch,
            )
        else:
            lr = onecycle.get_last_lr()[
                0
            ]

        train_mse = float(
            np.mean(
                losses
            )
        )

        history.append({
            "Epoch":
                epoch,
            "TrainMSE":
                train_mse,
            "LR":
                lr,
        })

        print(
            f"Fold direct {name:11s} "
            f"H={horizon:3d} F{fold} "
            f"ep={epoch:03d}/{fixed_epochs} "
            f"train={train_mse:.6f} "
            f"lr={lr:.3e}"
        )

        pd.DataFrame(
            history
        ).to_csv(
            DIRS[
                "history"
            ]
            / (
                f"{name}_H{horizon}_F{fold}_"
                "direct_history.csv"
            ),
            index=False,
        )

    model.eval()

    state = {
        k:
            v.detach()
            .cpu()
            .clone()
        for k, v
        in model.state_dict().items()
    }

    ckpt = {
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Fold":
            fold,
        "Prefix":
            int(
                prefix
            ),
        "FixedEpochs":
            int(
                fixed_epochs
            ),
        "Seed":
            seed,
        "StateDict":
            state,
    }

    torch.save(
        ckpt,
        path,
    )

    return (
        model,
        ckpt,
    )

## 11. Frozen 26-dimensional gate features

In [12]:

def score_entropy(
    s,
):
    p = torch.softmax(
        s,
        dim=1,
    )

    return (
        -(
            p
            * torch.log(
                p.clamp_min(
                    1e-8
                )
            )
        ).sum(
            dim=1
        )
        / math.log(
            TOP_K
        )
    )


def feature_cosine(
    a,
    b,
):
    return (
        (
            a
            * b
        ).sum(
            dim=1
        )
        / (
            torch.sqrt(
                (
                    a
                    * a
                ).sum(
                    dim=1
                )
                + 1e-8
            )
            * torch.sqrt(
                (
                    b
                    * b
                ).sum(
                    dim=1
                )
                + 1e-8
            )
        )
    )


def gate_features(
    r,
    retrieval,
    direct,
):
    s = r[
        "score"
    ]

    sim = r[
        "sim"
    ]

    pattern = r[
        "pattern"
    ]

    sorted_s = torch.sort(
        s,
        dim=1,
        descending=True,
    ).values

    cand_std = r[
        "cand"
    ].std(
        dim=1,
        unbiased=False,
    )

    disp_rms = torch.sqrt(
        (
            cand_std
            * cand_std
        ).mean(
            dim=1
        )
        + 1e-8
    )

    disp_mean = cand_std.mean(
        dim=1
    )

    direct_rms = torch.sqrt(
        (
            direct
            * direct
        ).mean(
            dim=1
        )
        + 1e-8
    )

    retrieval_rms = torch.sqrt(
        (
            retrieval
            * retrieval
        ).mean(
            dim=1
        )
        + 1e-8
    )

    disagreement = (
        retrieval
        - direct
    )

    disagreement_rms = torch.sqrt(
        (
            disagreement
            * disagreement
        ).mean(
            dim=1
        )
        + 1e-8
    )

    relative_disagreement = (
        disagreement_rms
        / (
            direct_rms
            + retrieval_rms
            + 1e-6
        )
    )

    scalars = torch.stack(
        [
            s.mean(
                dim=1
            ),
            s.std(
                dim=1,
                unbiased=False,
            ),
            s.max(
                dim=1
            ).values,
            sorted_s[
                :,
                0
            ]
            - sorted_s[
                :,
                1
            ],
            s.max(
                dim=1
            ).values
            - s.mean(
                dim=1
            ),
            score_entropy(
                s
            ),
            sim.mean(
                dim=1
            ),
            sim.std(
                dim=1,
                unbiased=False,
            ),
            sim.max(
                dim=1
            ).values,
            pattern.mean(
                dim=1
            ),
            pattern.std(
                dim=1,
                unbiased=False,
            ),
            pattern.max(
                dim=1
            ).values,
            disp_rms,
            disp_mean,
            direct_rms,
            retrieval_rms,
            disagreement_rms,
            relative_disagreement,
            feature_cosine(
                direct,
                retrieval,
            ),
        ],
        dim=1,
    )

    out = torch.cat(
        [
            r[
                "ctx"
            ],
            scalars,
        ],
        dim=1,
    )

    if out.shape[
        1
    ] != GATE_DIM:
        raise RuntimeError(
            f"Gate feature dimension mismatch: "
            f"{out.shape}"
        )

    return out


def abc_terms(
    direct,
    retrieval,
    true,
):
    e = (
        direct
        - true
    )

    delta = (
        retrieval
        - direct
    )

    return torch.stack(
        [
            (
                e
                * e
            ).mean(
                dim=1
            ),
            (
                e
                * delta
            ).mean(
                dim=1
            ),
            (
                delta
                * delta
            ).mean(
                dim=1
            ),
        ],
        dim=1,
    )

## 12. Cached OOF and validation feature collection

In [13]:

@torch.no_grad()
def collect_gate_data(
    data,
    horizon,
    direct_model,
    retriever,
    memory_gpu_obj,
    z,
    anchors,
):
    C = data[
        "n_channels"
    ]

    batch_anchors = query_anchor_batch(
        data[
            "name"
        ]
    )

    features = []
    abcs = []
    anchors_out = []
    channels_out = []

    for i in range(
        0,
        len(
            anchors
        ),
        batch_anchors,
    ):
        a = anchors[
            i:
            i+batch_anchors
        ]

        A = len(
            a
        )

        d3 = direct_residual(
            direct_model,
            z,
            a,
            horizon,
        )

        pair_anchor = np.repeat(
            a,
            C,
        )

        pair_channel = np.tile(
            np.arange(
                C,
                dtype=np.int64,
            ),
            A,
        )

        r = retrieve(
            retriever,
            memory_gpu_obj,
            z,
            pair_anchor,
            pair_channel,
            horizon,
        )

        retrieval = r[
            "cand"
        ].mean(
            dim=1
        )

        direct = d3.permute(
            0,
            2,
            1,
        ).reshape(
            -1,
            horizon,
        )

        true = r[
            "true"
        ]

        feat = gate_features(
            r,
            retrieval,
            direct,
        )

        abc = abc_terms(
            direct,
            retrieval,
            true,
        )

        features.append(
            feat.cpu()
            .numpy()
            .astype(
                np.float32
            )
        )

        abcs.append(
            abc.cpu()
            .numpy()
            .astype(
                np.float32
            )
        )

        anchors_out.append(
            pair_anchor
        )

        channels_out.append(
            pair_channel
        )

        del (
            d3,
            r,
            retrieval,
            direct,
            true,
            feat,
            abc,
        )

    return {
        "feature":
            np.concatenate(
                features,
                axis=0,
            ),
        "abc":
            np.concatenate(
                abcs,
                axis=0,
            ),
        "anchor":
            np.concatenate(
                anchors_out,
                axis=0,
            ),
        "channel":
            np.concatenate(
                channels_out,
                axis=0,
            ),
    }


def oof_cache_path(
    name,
    horizon,
    fold,
):
    return (
        DIRS[
            "oof"
        ]
        / (
            f"{name}_H{horizon}_F{fold}_"
            "official_direct.npz"
        )
    )


def val_cache_path(
    name,
    horizon,
):
    return (
        DIRS[
            "validation"
        ]
        / (
            f"{name}_H{horizon}_"
            "validation_features.npz"
        )
    )


def build_oof_fold(
    data,
    horizon,
    fold,
    p0,
    p1,
    direct_epochs,
):
    name = data[
        "name"
    ]

    C = data[
        "n_channels"
    ]

    out_path = oof_cache_path(
        name,
        horizon,
        fold,
    )

    if (
        out_path.exists()
        and RESUME
        and not FORCE
    ):
        obj = np.load(
            out_path
        )

        print(
            "Loaded OOF cache:",
            out_path.name,
        )

        return {
            key:
                obj[
                    key
                ]
            for key in [
                "feature",
                "abc",
                "anchor",
                "channel",
            ]
        }

    prefix = int(
        p0
        * data[
            "train_end"
        ]
    )

    oof_end = int(
        p1
        * data[
            "train_end"
        ]
    )

    z = prefix_norm(
        data[
            "raw"
        ],
        prefix,
    )

    direct_model, _ = train_fold_official_direct(
        name,
        horizon,
        z,
        prefix,
        direct_epochs,
        fold,
    )

    retriever, _ = load_frozen_retriever(
        fold_retriever_ckpt_path(
            name,
            horizon,
            fold,
        )
    )

    memory = build_memory(
        z,
        C,
        prefix,
        horizon,
    )

    tag = (
        f"F{fold}_prefix{prefix}"
    )

    memory_gpu_obj = memory_gpu_cached(
        name,
        horizon,
        tag,
        retriever,
        memory,
        C,
    )

    anchors = eval_anchors(
        prefix,
        oof_end,
        horizon,
        stride=
            OOF_ANCHOR_STRIDE,
    )

    print(
        f"OOF {name} H={horizon} F{fold}: "
        f"prefix={prefix}, "
        f"end={oof_end}, "
        f"anchors={len(anchors)}, "
        f"pairs={len(anchors)*C}, "
        f"memory/C={memory['M']}"
    )

    out = collect_gate_data(
        data,
        horizon,
        direct_model,
        retriever,
        memory_gpu_obj,
        z,
        anchors,
    )

    np.savez_compressed(
        out_path,
        **out,
    )

    del (
        direct_model,
        retriever,
        memory,
        memory_gpu_obj,
        z,
    )

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return out


def build_validation_cache(
    data,
    horizon,
    direct_model,
    retriever,
):
    name = data[
        "name"
    ]

    C = data[
        "n_channels"
    ]

    path = val_cache_path(
        name,
        horizon,
    )

    if (
        path.exists()
        and RESUME
        and not FORCE
    ):
        obj = np.load(
            path
        )

        print(
            "Loaded validation cache:",
            path.name,
        )

        return {
            key:
                obj[
                    key
                ]
            for key in [
                "feature",
                "abc",
                "anchor",
                "channel",
            ]
        }

    memory = build_memory(
        data[
            "z"
        ],
        C,
        data[
            "train_end"
        ],
        horizon,
    )

    memory_gpu_obj = memory_gpu_cached(
        name,
        horizon,
        "validation_train_memory",
        retriever,
        memory,
        C,
    )

    anchors = eval_anchors(
        data[
            "train_end"
        ],
        data[
            "val_end"
        ],
        horizon,
        stride=1,
    )

    print(
        f"Validation {name} H={horizon}: "
        f"anchors={len(anchors)}, "
        f"pairs={len(anchors)*C}, "
        f"memory/C={memory['M']}"
    )

    out = collect_gate_data(
        data,
        horizon,
        direct_model,
        retriever,
        memory_gpu_obj,
        data[
            "z"
        ],
        anchors,
    )

    np.savez_compressed(
        path,
        **out,
    )

    del (
        memory,
        memory_gpu_obj,
    )

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return out

## 13. Cross-fitted gate training and validation-only calibration

In [14]:

def fit_feature_scaler(
    x,
):
    median = np.median(
        x,
        axis=0,
    ).astype(
        np.float32
    )

    q25 = np.percentile(
        x,
        25,
        axis=0,
    )

    q75 = np.percentile(
        x,
        75,
        axis=0,
    )

    iqr = (
        q75
        - q25
    ).astype(
        np.float32
    )

    iqr = np.where(
        iqr < 1e-5,
        1.0,
        iqr,
    ).astype(
        np.float32
    )

    return (
        median,
        iqr,
    )


def scale_features(
    x,
    median,
    iqr,
):
    return np.clip(
        (
            x
            - median
        )
        / iqr,
        -8.0,
        8.0,
    ).astype(
        np.float32
    )


def gate_loss(
    alpha,
    abc,
):
    return (
        abc[
            :,
            0
        ]
        + 2.0
        * alpha
        * abc[
            :,
            1
        ]
        + alpha
        * alpha
        * abc[
            :,
            2
        ]
    ).mean()


def gate_checkpoint_path(
    name,
    horizon,
):
    return (
        DIRS[
            "gate"
        ]
        / (
            f"{name}_H{horizon}_"
            "official_direct.pt"
        )
    )


def train_gate_epoch(
    model,
    optimizer,
    x,
    abc,
    rng,
):
    model.train()

    order = rng.permutation(
        len(
            x
        )
    )

    losses = []

    for i in range(
        0,
        len(
            order
        ),
        GATE_BATCH,
    ):
        ids = order[
            i:
            i+GATE_BATCH
        ]

        xt = torch.from_numpy(
            x[
                ids
            ]
        ).to(
            DEVICE
        )

        at = torch.from_numpy(
            abc[
                ids
            ]
        ).to(
            DEVICE
        )

        optimizer.zero_grad(
            set_to_none=True
        )

        alpha = model(
            xt
        )

        loss = gate_loss(
            alpha,
            at,
        )

        loss.backward()

        optimizer.step()

        losses.append(
            float(
                loss.item()
            )
        )

        del (
            xt,
            at,
            alpha,
            loss,
        )

    return float(
        np.mean(
            losses
        )
    )


@torch.no_grad()
def evaluate_gate(
    model,
    x,
    abc,
):
    model.eval()

    total = 0.0
    n = 0
    alpha_sum = 0.0

    for i in range(
        0,
        len(
            x
        ),
        GATE_BATCH,
    ):
        xt = torch.from_numpy(
            x[
                i:
                i+GATE_BATCH
            ]
        ).to(
            DEVICE
        )

        at = torch.from_numpy(
            abc[
                i:
                i+GATE_BATCH
            ]
        ).to(
            DEVICE
        )

        alpha = model(
            xt
        )

        each = (
            at[
                :,
                0
            ]
            + 2.0
            * alpha
            * at[
                :,
                1
            ]
            + alpha
            * alpha
            * at[
                :,
                2
            ]
        )

        total += float(
            each.sum()
        )

        n += len(
            alpha
        )

        alpha_sum += float(
            alpha.sum()
        )

        del (
            xt,
            at,
            alpha,
            each,
        )

    return (
        total
        / n,
        alpha_sum
        / n,
    )


def train_crossfit_gate(
    name,
    horizon,
    oof_x,
    oof_abc,
    val_x,
    val_abc,
):
    path = gate_checkpoint_path(
        name,
        horizon,
    )

    if (
        path.exists()
        and RESUME
        and not FORCE
    ):
        ckpt = load_torch(
            path
        )

        model = CrossFitAdaptiveGate().to(
            DEVICE
        )

        model.load_state_dict(
            ckpt[
                "StateDict"
            ]
        )

        model.eval()

        print(
            "Loaded gate:",
            path.name,
        )

        return (
            model,
            ckpt,
        )

    median, iqr = fit_feature_scaler(
        oof_x
    )

    train_x = scale_features(
        oof_x,
        median,
        iqr,
    )

    valid_x = scale_features(
        val_x,
        median,
        iqr,
    )

    seed = (
        CROSSFIT_SEED
        + horizon
        * 3000
        + sum(
            map(
                ord,
                name,
            )
        )
    )

    set_seed(
        seed
    )

    model = CrossFitAdaptiveGate().to(
        DEVICE
    )

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=GATE_LR,
        weight_decay=GATE_WD,
    )

    rng = np.random.default_rng(
        seed
        + 1
    )

    best = float(
        "inf"
    )

    best_epoch = -1
    wait = 0
    history = []

    for epoch in range(
        1,
        GATE_MAX_EPOCHS
        + 1,
    ):
        train_mse = train_gate_epoch(
            model,
            optimizer,
            train_x,
            oof_abc,
            rng,
        )

        val_mse, mean_alpha = evaluate_gate(
            model,
            valid_x,
            val_abc,
        )

        history.append({
            "Epoch":
                epoch,
            "OOFTrainMSE":
                train_mse,
            "ValMSE":
                val_mse,
            "ValMeanAlpha":
                mean_alpha,
        })

        if (
            val_mse
            < best
            - 1e-10
        ):
            best = val_mse
            best_epoch = epoch
            wait = 0
        else:
            wait += 1

        print(
            f"Gate {name:11s} "
            f"H={horizon:3d} "
            f"ep={epoch:02d} "
            f"OOF={train_mse:.6f} "
            f"val={val_mse:.6f} "
            f"alpha={mean_alpha:.3f} "
            f"best={best:.6f}@{best_epoch}"
        )

        if (
            wait
            >= GATE_PATIENCE
        ):
            break

    # Reinitialize and refit only on OOF for the
    # validation-selected number of epochs.
    set_seed(
        seed
    )

    final = CrossFitAdaptiveGate().to(
        DEVICE
    )

    final_opt = torch.optim.AdamW(
        final.parameters(),
        lr=GATE_LR,
        weight_decay=GATE_WD,
    )

    final_rng = np.random.default_rng(
        seed
        + 2
    )

    for _ in range(
        best_epoch
    ):
        train_gate_epoch(
            final,
            final_opt,
            train_x,
            oof_abc,
            final_rng,
        )

    final.eval()

    ckpt = {
        "BestEpoch":
            best_epoch,
        "BestValMSE":
            best,
        "FeatureMedian":
            median,
        "FeatureIQR":
            iqr,
        "StateDict": {
            k:
                v.detach()
                .cpu()
                .clone()
            for k, v
            in final.state_dict().items()
        },
    }

    torch.save(
        ckpt,
        path,
    )

    pd.DataFrame(
        history
    ).to_csv(
        DIRS[
            "history"
        ]
        / (
            f"{name}_H{horizon}_"
            "gate_history.csv"
        ),
        index=False,
    )

    return (
        final,
        ckpt,
    )


def mse_scalar(
    abc,
    alpha,
):
    A = abc.astype(
        np.float64
    )

    x = float(
        alpha
    )

    return float(
        np.mean(
            A[
                :,
                0
            ]
            + 2.0
            * x
            * A[
                :,
                1
            ]
            + x
            * x
            * A[
                :,
                2
            ]
        )
    )


def choose_scalar(
    abc,
):
    rows = []

    best_alpha = None
    best_mse = float(
        "inf"
    )

    for alpha in ALPHA_GRID:
        mse = mse_scalar(
            abc,
            alpha,
        )

        rows.append({
            "Alpha":
                float(
                    alpha
                ),
            "MSE":
                mse,
        })

        if (
            mse
            < best_mse
            - 1e-10
        ):
            best_mse = mse
            best_alpha = float(
                alpha
            )

    return (
        best_alpha,
        pd.DataFrame(
            rows
        ),
    )


@torch.no_grad()
def gate_alpha(
    model,
    ckpt,
    x,
):
    sx = scale_features(
        x,
        ckpt[
            "FeatureMedian"
        ],
        ckpt[
            "FeatureIQR"
        ],
    )

    outputs = []

    for i in range(
        0,
        len(
            sx
        ),
        GATE_BATCH,
    ):
        t = torch.from_numpy(
            sx[
                i:
                i+GATE_BATCH
            ]
        ).to(
            DEVICE
        )

        outputs.append(
            model(
                t
            ).cpu()
            .numpy()
        )

        del t

    return np.concatenate(
        outputs
    ).astype(
        np.float32
    )


def mse_pair(
    abc,
    alpha,
):
    A = abc.astype(
        np.float64
    )

    x = np.asarray(
        alpha,
        dtype=np.float64,
    )

    return float(
        np.mean(
            A[
                :,
                0
            ]
            + 2.0
            * x
            * A[
                :,
                1
            ]
            + x
            * x
            * A[
                :,
                2
            ]
        )
    )


def choose_lambda(
    abc,
    gate_alpha_values,
    scalar_alpha,
):
    rows = []

    best_lambda = None
    best_mse = float(
        "inf"
    )

    for lmb in LAMBDA_GRID:
        alpha = (
            (
                1.0
                - float(
                    lmb
                )
            )
            * scalar_alpha
            + float(
                lmb
            )
            * gate_alpha_values
        )

        mse = mse_pair(
            abc,
            alpha,
        )

        rows.append({
            "Lambda":
                float(
                    lmb
                ),
            "MSE":
                mse,
            "MeanAlpha":
                float(
                    alpha.mean()
                ),
        })

        if (
            mse
            < best_mse
            - 1e-10
        ):
            best_mse = mse
            best_lambda = float(
                lmb
            )

    return (
        best_lambda,
        pd.DataFrame(
            rows
        ),
    )


## 14. Final test, Oracle diagnostic, and paired bootstrap

Oracle은 실사용 방법이 아니라 diagnostic입니다.

현재 retriever가 만든 동일한 retrieval forecast와 PatchTST forecast 사이에서
test future를 알고 최적 convex weight를 선택합니다.

따라서 Oracle headroom은

$$
\boxed{
\text{현재 retrieval forecast에 보완 정보가 존재하는가?}
}
$$

를 진단합니다.

실제 방법의 성능 주장은 Oracle이 아니라 ShrinkAdaptive로 판단합니다.

In [15]:

def empty_stat():
    return {
        "sse":
            0.0,
        "sae":
            0.0,
        "n":
            0,
    }


def update_stat(
    stat,
    pred,
    true,
):
    e = (
        pred
        - true
    )

    stat[
        "sse"
    ] += float(
        (
            e
            * e
        ).sum()
    )

    stat[
        "sae"
    ] += float(
        e.abs().sum()
    )

    stat[
        "n"
    ] += e.numel()


def finish_stat(
    stat,
):
    return (
        stat[
            "sse"
        ]
        / stat[
            "n"
        ],
        stat[
            "sae"
        ]
        / stat[
            "n"
        ],
    )


def oracle_alpha_and_prediction(
    direct,
    retrieval,
    true,
):
    e = (
        direct
        - true
    )

    delta = (
        retrieval
        - direct
    )

    alpha = torch.clamp(
        -(
            e
            * delta
        ).sum(
            dim=1
        )
        / (
            (
                delta
                * delta
            ).sum(
                dim=1
            )
            + 1e-8
        ),
        0.0,
        1.0,
    )

    pred = (
        direct
        + alpha[
            :,
            None
        ]
        * delta
    )

    return (
        alpha,
        pred,
    )


@torch.no_grad()
def test_evaluate(
    data,
    horizon,
    direct_model,
    retriever,
    memory_gpu_obj,
    gate,
    gate_ckpt,
    scalar_alpha,
    shrink_lambda,
):
    C = data[
        "n_channels"
    ]

    batch_anchors = query_anchor_batch(
        data[
            "name"
        ]
    )

    anchors = eval_anchors(
        data[
            "val_end"
        ],
        data[
            "test_end"
        ],
        horizon,
        stride=1,
    )

    keys = [
        "Direct",
        "Retrieval",
        "Scalar",
        "RawAdaptive",
        "ShrinkAdaptive",
        "Oracle",
    ]

    stats = {
        key:
            empty_stat()
        for key in keys
    }

    anchor_mse = {
        key:
            []
        for key in keys
    }

    channel_sse_direct = np.zeros(
        C,
        dtype=np.float64,
    )

    channel_sse_shrink = np.zeros(
        C,
        dtype=np.float64,
    )

    channel_count = np.zeros(
        C,
        dtype=np.int64,
    )

    raw_alpha_sum = 0.0
    shrink_alpha_sum = 0.0
    oracle_alpha_sum = 0.0
    oracle_positive = 0
    n_pairs = 0

    for i in range(
        0,
        len(
            anchors
        ),
        batch_anchors,
    ):
        a = anchors[
            i:
            i+batch_anchors
        ]

        A = len(
            a
        )

        d3 = direct_residual(
            direct_model,
            data[
                "z"
            ],
            a,
            horizon,
        )

        pair_anchor = np.repeat(
            a,
            C,
        )

        pair_channel = np.tile(
            np.arange(
                C,
                dtype=np.int64,
            ),
            A,
        )

        r = retrieve(
            retriever,
            memory_gpu_obj,
            data[
                "z"
            ],
            pair_anchor,
            pair_channel,
            horizon,
        )

        retrieval = r[
            "cand"
        ].mean(
            dim=1
        )

        direct = d3.permute(
            0,
            2,
            1,
        ).reshape(
            -1,
            horizon,
        )

        true = r[
            "true"
        ]

        scalar = (
            direct
            + scalar_alpha
            * (
                retrieval
                - direct
            )
        )

        features = gate_features(
            r,
            retrieval,
            direct,
        ).cpu().numpy().astype(
            np.float32
        )

        scaled = scale_features(
            features,
            gate_ckpt[
                "FeatureMedian"
            ],
            gate_ckpt[
                "FeatureIQR"
            ],
        )

        gate_alpha_values = gate(
            torch.from_numpy(
                scaled
            ).to(
                DEVICE
            )
        )

        shrink_alpha_values = (
            (
                1.0
                - shrink_lambda
            )
            * scalar_alpha
            + shrink_lambda
            * gate_alpha_values
        )

        raw_adaptive = (
            direct
            + gate_alpha_values[
                :,
                None
            ]
            * (
                retrieval
                - direct
            )
        )

        shrink_adaptive = (
            direct
            + shrink_alpha_values[
                :,
                None
            ]
            * (
                retrieval
                - direct
            )
        )

        oracle_alpha, oracle = (
            oracle_alpha_and_prediction(
                direct,
                retrieval,
                true,
            )
        )

        predictions = {
            "Direct":
                direct,
            "Retrieval":
                retrieval,
            "Scalar":
                scalar,
            "RawAdaptive":
                raw_adaptive,
            "ShrinkAdaptive":
                shrink_adaptive,
            "Oracle":
                oracle,
        }

        for key, pred in predictions.items():
            update_stat(
                stats[
                    key
                ],
                pred,
                true,
            )

            per_pair = (
                (
                    pred
                    - true
                )
                ** 2
            ).mean(
                dim=1
            ).reshape(
                A,
                C,
            ).mean(
                dim=1
            )

            anchor_mse[
                key
            ].extend(
                per_pair.cpu()
                .numpy()
                .tolist()
            )

        # Per-channel diagnostics.
        direct_e2 = (
            (
                direct
                - true
            )
            ** 2
        ).reshape(
            A,
            C,
            horizon,
        )

        shrink_e2 = (
            (
                shrink_adaptive
                - true
            )
            ** 2
        ).reshape(
            A,
            C,
            horizon,
        )

        channel_sse_direct += (
            direct_e2.sum(
                dim=(
                    0,
                    2,
                )
            ).cpu()
            .numpy()
        )

        channel_sse_shrink += (
            shrink_e2.sum(
                dim=(
                    0,
                    2,
                )
            ).cpu()
            .numpy()
        )

        channel_count += (
            A
            * horizon
        )

        raw_alpha_sum += float(
            gate_alpha_values.sum()
        )

        shrink_alpha_sum += float(
            shrink_alpha_values.sum()
        )

        oracle_alpha_sum += float(
            oracle_alpha.sum()
        )

        oracle_positive += int(
            (
                oracle_alpha
                > 0.01
            ).sum()
        )

        n_pairs += len(
            gate_alpha_values
        )

        del (
            d3,
            r,
            retrieval,
            direct,
            true,
            scalar,
            features,
            scaled,
            gate_alpha_values,
            shrink_alpha_values,
            raw_adaptive,
            shrink_adaptive,
            oracle_alpha,
            oracle,
            predictions,
            direct_e2,
            shrink_e2,
        )

        if (
            i == 0
            or (
                i
                // batch_anchors
                + 1
            )
            % 100
            == 0
            or (
                i
                + batch_anchors
                >= len(
                    anchors
                )
            )
        ):
            print(
                f"  test anchors "
                f"{min(i+batch_anchors, len(anchors))}"
                f"/{len(anchors)}"
            )

    channel_direct = (
        channel_sse_direct
        / channel_count
    )

    channel_shrink = (
        channel_sse_shrink
        / channel_count
    )

    return {
        "anchors":
            anchors,
        "metrics": {
            key:
                finish_stat(
                    value
                )
            for key, value
            in stats.items()
        },
        "anchor_mse": {
            key:
                np.asarray(
                    value,
                    dtype=np.float32,
                )
            for key, value
            in anchor_mse.items()
        },
        "channel_direct_mse":
            channel_direct,
        "channel_shrink_mse":
            channel_shrink,
        "raw_mean_alpha":
            raw_alpha_sum
            / n_pairs,
        "shrink_mean_alpha":
            shrink_alpha_sum
            / n_pairs,
        "oracle_mean_alpha":
            oracle_alpha_sum
            / n_pairs,
        "oracle_positive_fraction":
            oracle_positive
            / n_pairs,
    }


def moving_block_bootstrap(
    difference,
    n_boot=5000,
    block=24,
    seed=131313,
):
    x = np.asarray(
        difference,
        dtype=np.float64,
    )

    n = len(
        x
    )

    L = min(
        block,
        n,
    )

    rng = np.random.default_rng(
        seed
    )

    n_blocks = int(
        np.ceil(
            n
            / L
        )
    )

    max_start = max(
        1,
        n
        - L
        + 1,
    )

    boot = np.empty(
        n_boot,
        dtype=np.float64,
    )

    for b in range(
        n_boot
    ):
        starts = rng.integers(
            0,
            max_start,
            size=n_blocks,
        )

        sample = np.concatenate(
            [
                x[
                    s:
                    s+L
                ]
                for s in starts
            ]
        )[
            :n
        ]

        boot[
            b
        ] = sample.mean()

    return {
        "MeanImprovement":
            float(
                x.mean()
            ),
        "CI_Low":
            float(
                np.quantile(
                    boot,
                    0.025,
                )
            ),
        "CI_High":
            float(
                np.quantile(
                    boot,
                    0.975,
                )
            ),
    }


## 15. Main Experiment

각 조건에서 순서는 다음과 같습니다.

1. Experiment 18 strong PatchTST load
2. horizon-specific frozen retriever load
3. three OOF folds 생성 또는 cache load
4. validation feature 생성 또는 cache load
5. gate / scalar / shrinkage validation calibration
6. static train+validation retrieval memory로 all-window test
7. bootstrap 및 channel diagnostic 저장

조건 하나가 끝날 때마다 `summary.csv`를 즉시 갱신합니다.

In [ ]:

SUMMARY_PATH = (
    ROOT
    / "summary.csv"
)

BOOTSTRAP_PATH = (
    ROOT
    / "bootstrap.csv"
)

CALIBRATION_PATH = (
    ROOT
    / "calibration.csv"
)

FOLD_PATH = (
    ROOT
    / "folds.csv"
)

existing = (
    pd.read_csv(
        SUMMARY_PATH
    )
    if (
        RESUME
        and SUMMARY_PATH.exists()
    )
    else pd.DataFrame()
)

summary_rows = (
    existing.to_dict(
        "records"
    )
    if len(
        existing
    )
    else []
)

bootstrap_rows = (
    pd.read_csv(
        BOOTSTRAP_PATH
    ).to_dict(
        "records"
    )
    if (
        RESUME
        and BOOTSTRAP_PATH.exists()
    )
    else []
)

fold_rows = (
    pd.read_csv(
        FOLD_PATH
    ).to_dict(
        "records"
    )
    if (
        RESUME
        and FOLD_PATH.exists()
    )
    else []
)

calibration_frames = []


def already_done(
    name,
    horizon,
):
    if not len(
        existing
    ):
        return False

    return bool(
        (
            (
                existing[
                    "Dataset"
                ]
                == name
            )
            & (
                existing[
                    "Horizon"
                ]
                == horizon
            )
        ).any()
    )


for name, horizon in TASKS:
    if already_done(
        name,
        horizon,
    ):
        print(
            f"SKIP completed: "
            f"{name} H={horizon}"
        )
        continue

    start_time = time.time()

    data = DATA[
        name
    ]

    C = data[
        "n_channels"
    ]

    print(
        "\n"
        + "#"
        * 150
    )

    print(
        f"{name} | H={horizon} | "
        "OFFICIAL PATCHTST + FROZEN HISTORICAL MEMORY"
    )

    print(
        "#"
        * 150
    )

    # --------------------------------------------------------
    # 1. Load the exact Experiment 18 direct checkpoint.
    # --------------------------------------------------------
    direct_model, direct_ckpt = load_exp18_direct(
        name,
        horizon,
    )

    ref = exp18_reference(
        name,
        horizon,
    )

    direct_epochs = int(
        direct_ckpt[
            "BestEpoch"
        ]
    )

    print(
        f"Experiment 18 reference: "
        f"MSE={float(ref['FullStride1_MSE']):.6f}, "
        f"MAE={float(ref['FullStride1_MAE']):.6f}, "
        f"best_epoch={direct_epochs}"
    )

    # --------------------------------------------------------
    # 2. Load frozen full retriever.
    # --------------------------------------------------------
    retriever, retriever_ckpt = load_frozen_retriever(
        full_retriever_ckpt_path(
            name,
            horizon,
        )
    )

    print(
        "Frozen retriever best epoch:",
        retriever_ckpt.get(
            "BestEpoch",
            "unknown",
        ),
    )

    # --------------------------------------------------------
    # 3. Chronological OOF data.
    # --------------------------------------------------------
    oof_parts = []

    for fold, (
        p0,
        p1,
    ) in enumerate(
        FOLDS,
        start=1,
    ):
        part = build_oof_fold(
            data,
            horizon,
            fold,
            p0,
            p1,
            direct_epochs,
        )

        oof_parts.append(
            part
        )

        fold_rows = [
            r
            for r in fold_rows
            if not (
                r.get(
                    "Dataset"
                )
                == name
                and int(
                    r.get(
                        "Horizon",
                        -1,
                    )
                )
                == horizon
                and int(
                    r.get(
                        "Fold",
                        -1,
                    )
                )
                == fold
            )
        ]

        fold_rows.append({
            "Dataset":
                name,
            "Horizon":
                horizon,
            "Fold":
                fold,
            "PrefixFrac":
                p0,
            "OOFEndFrac":
                p1,
            "Pairs":
                len(
                    part[
                        "feature"
                    ]
                ),
            "Anchors":
                len(
                    np.unique(
                        part[
                            "anchor"
                        ]
                    )
                ),
            "DirectFixedEpochs":
                direct_epochs,
            "RetrieverCheckpoint":
                str(
                    fold_retriever_ckpt_path(
                        name,
                        horizon,
                        fold,
                    )
                ),
        })

        pd.DataFrame(
            fold_rows
        ).to_csv(
            FOLD_PATH,
            index=False,
        )

    oof_x = np.concatenate(
        [
            part[
                "feature"
            ]
            for part in oof_parts
        ],
        axis=0,
    )

    oof_abc = np.concatenate(
        [
            part[
                "abc"
            ]
            for part in oof_parts
        ],
        axis=0,
    )

    print(
        "Total OOF pairs:",
        len(
            oof_x
        ),
    )

    # --------------------------------------------------------
    # 4. Validation cache and calibration.
    # --------------------------------------------------------
    val_data = build_validation_cache(
        data,
        horizon,
        direct_model,
        retriever,
    )

    gate, gate_ckpt = train_crossfit_gate(
        name,
        horizon,
        oof_x,
        oof_abc,
        val_data[
            "feature"
        ],
        val_data[
            "abc"
        ],
    )

    scalar_alpha, scalar_curve = choose_scalar(
        val_data[
            "abc"
        ]
    )

    raw_val_alpha = gate_alpha(
        gate,
        gate_ckpt,
        val_data[
            "feature"
        ],
    )

    shrink_lambda, lambda_curve = choose_lambda(
        val_data[
            "abc"
        ],
        raw_val_alpha,
        scalar_alpha,
    )

    scalar_curve[
        "Dataset"
    ] = name

    scalar_curve[
        "Horizon"
    ] = horizon

    scalar_curve[
        "Kind"
    ] = "ScalarAlpha"

    lambda_curve[
        "Dataset"
    ] = name

    lambda_curve[
        "Horizon"
    ] = horizon

    lambda_curve[
        "Kind"
    ] = "ShrinkLambda"

    lambda_curve[
        "ScalarAlpha"
    ] = scalar_alpha

    calibration_frames.extend(
        [
            scalar_curve,
            lambda_curve,
        ]
    )

    if calibration_frames:
        pd.concat(
            calibration_frames,
            ignore_index=True,
        ).to_csv(
            CALIBRATION_PATH,
            index=False,
        )

    print(
        f"Validation calibration | "
        f"alpha0={scalar_alpha:.2f} | "
        f"lambda={shrink_lambda:.2f} | "
        f"gateEpoch={gate_ckpt['BestEpoch']}"
    )

    del (
        oof_x,
        oof_abc,
        oof_parts,
        raw_val_alpha,
        val_data,
    )

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # --------------------------------------------------------
    # 5. Static train+validation test retrieval memory.
    # --------------------------------------------------------
    test_memory = build_memory(
        data[
            "z"
        ],
        C,
        data[
            "val_end"
        ],
        horizon,
    )

    test_memory_gpu = memory_gpu_cached(
        name,
        horizon,
        "test_trainval_memory",
        retriever,
        test_memory,
        C,
    )

    test = test_evaluate(
        data,
        horizon,
        direct_model,
        retriever,
        test_memory_gpu,
        gate,
        gate_ckpt,
        scalar_alpha,
        shrink_lambda,
    )

    metrics = test[
        "metrics"
    ]

    direct_mse, direct_mae = metrics[
        "Direct"
    ]

    retrieval_mse, retrieval_mae = metrics[
        "Retrieval"
    ]

    scalar_mse, scalar_mae = metrics[
        "Scalar"
    ]

    raw_mse, raw_mae = metrics[
        "RawAdaptive"
    ]

    shrink_mse, shrink_mae = metrics[
        "ShrinkAdaptive"
    ]

    oracle_mse, oracle_mae = metrics[
        "Oracle"
    ]

    # --------------------------------------------------------
    # 6. Paired moving-block bootstrap.
    # --------------------------------------------------------
    bootstrap_rows = [
        r
        for r in bootstrap_rows
        if not (
            r.get(
                "Dataset"
            )
            == name
            and int(
                r.get(
                    "Horizon",
                    -1,
                )
            )
            == horizon
        )
    ]

    b_direct = moving_block_bootstrap(
        test[
            "anchor_mse"
        ][
            "Direct"
        ]
        - test[
            "anchor_mse"
        ][
            "ShrinkAdaptive"
        ],
        seed=
            131313
            + horizon
            + sum(
                map(
                    ord,
                    name,
                )
            ),
    )

    bootstrap_rows.append({
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Comparison":
            "Direct-ShrinkAdaptive",
        **b_direct,
        "SignificantPositive":
            b_direct[
                "CI_Low"
            ]
            > 0.0,
    })

    b_scalar = moving_block_bootstrap(
        test[
            "anchor_mse"
        ][
            "Scalar"
        ]
        - test[
            "anchor_mse"
        ][
            "ShrinkAdaptive"
        ],
        seed=
            232323
            + horizon
            + sum(
                map(
                    ord,
                    name,
                )
            ),
    )

    bootstrap_rows.append({
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Comparison":
            "Scalar-ShrinkAdaptive",
        **b_scalar,
        "SignificantPositive":
            b_scalar[
                "CI_Low"
            ]
            > 0.0,
    })

    pd.DataFrame(
        bootstrap_rows
    ).to_csv(
        BOOTSTRAP_PATH,
        index=False,
    )

    # --------------------------------------------------------
    # 7. Channel-level diagnostics.
    # --------------------------------------------------------
    channel_df = pd.DataFrame({
        "ChannelIndex":
            np.arange(
                C
            ),
        "ChannelName":
            data[
                "columns"
            ],
        "Direct_MSE":
            test[
                "channel_direct_mse"
            ],
        "ShrinkAdaptive_MSE":
            test[
                "channel_shrink_mse"
            ],
    })

    channel_df[
        "Improvement"
    ] = (
        channel_df[
            "Direct_MSE"
        ]
        - channel_df[
            "ShrinkAdaptive_MSE"
        ]
    )

    channel_df[
        "Improvement_pct"
    ] = (
        100.0
        * channel_df[
            "Improvement"
        ]
        / channel_df[
            "Direct_MSE"
        ]
    )

    channel_df.to_csv(
        DIRS[
            "channel"
        ]
        / (
            f"{name}_H{horizon}_"
            "channel_mse.csv"
        ),
        index=False,
    )

    improved_channel_fraction = float(
        (
            channel_df[
                "Improvement"
            ]
            > 0.0
        ).mean()
    )

    # --------------------------------------------------------
    # 8. Final summary.
    # --------------------------------------------------------
    exp18_mse = float(
        ref[
            "FullStride1_MSE"
        ]
    )

    exp18_mae = float(
        ref[
            "FullStride1_MAE"
        ]
    )

    row = {
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Channels":
            C,
        "OfficialPatchTST_MSE":
            direct_mse,
        "OfficialPatchTST_MAE":
            direct_mae,
        "Experiment18Reference_MSE":
            exp18_mse,
        "Experiment18Reference_MAE":
            exp18_mae,
        "DirectParityAbsDiff":
            abs(
                direct_mse
                - exp18_mse
            ),
        "Retrieval_MSE":
            retrieval_mse,
        "Retrieval_MAE":
            retrieval_mae,
        "ScalarAlpha":
            scalar_alpha,
        "Scalar_MSE":
            scalar_mse,
        "Scalar_MAE":
            scalar_mae,
        "RawAdaptive_MSE":
            raw_mse,
        "RawAdaptive_MAE":
            raw_mae,
        "ShrinkLambda":
            shrink_lambda,
        "ShrinkAdaptive_MSE":
            shrink_mse,
        "ShrinkAdaptive_MAE":
            shrink_mae,
        "Oracle_MSE":
            oracle_mse,
        "Oracle_MAE":
            oracle_mae,
        "RawMeanAlpha":
            test[
                "raw_mean_alpha"
            ],
        "ShrinkMeanAlpha":
            test[
                "shrink_mean_alpha"
            ],
        "OracleMeanAlpha":
            test[
                "oracle_mean_alpha"
            ],
        "OraclePositiveFraction":
            test[
                "oracle_positive_fraction"
            ],
        "ImprovedChannelFraction":
            improved_channel_fraction,
        "ScalarGainVsDirect_pct":
            (
                100.0
                * (
                    direct_mse
                    - scalar_mse
                )
                / direct_mse
            ),
        "ShrinkGainVsDirect_pct":
            (
                100.0
                * (
                    direct_mse
                    - shrink_mse
                )
                / direct_mse
            ),
        "ShrinkGainVsScalar_pct":
            (
                100.0
                * (
                    scalar_mse
                    - shrink_mse
                )
                / scalar_mse
            ),
        "OracleHeadroomFromDirect_pct":
            (
                100.0
                * (
                    direct_mse
                    - oracle_mse
                )
                / direct_mse
            ),
        "OracleHeadroomFromShrink_pct":
            (
                100.0
                * (
                    shrink_mse
                    - oracle_mse
                )
                / shrink_mse
            ),
        "OfficialDirectBestEpoch":
            direct_epochs,
        "FrozenRetrieverBestEpoch":
            retriever_ckpt.get(
                "BestEpoch",
                np.nan,
            ),
        "GateBestEpoch":
            int(
                gate_ckpt[
                    "BestEpoch"
                ]
            ),
        "TestMemoryPerChannel":
            int(
                test_memory[
                    "M"
                ]
            ),
        "TestWindows":
            len(
                test[
                    "anchors"
                ]
            ),
        "RuntimeMinutes":
            (
                time.time()
                - start_time
            )
            / 60.0,
    }

    summary_rows = [
        r
        for r in summary_rows
        if not (
            r.get(
                "Dataset"
            )
            == name
            and int(
                r.get(
                    "Horizon",
                    -1,
                )
            )
            == horizon
        )
    ]

    summary_rows.append(
        row
    )

    pd.DataFrame(
        summary_rows
    ).to_csv(
        SUMMARY_PATH,
        index=False,
    )

    np.savez_compressed(
        DIRS[
            "paired"
        ]
        / (
            f"{name}_H{horizon}_"
            "anchor_mse.npz"
        ),
        TestAnchors=
            test[
                "anchors"
            ],
        Direct=
            test[
                "anchor_mse"
            ][
                "Direct"
            ],
        Retrieval=
            test[
                "anchor_mse"
            ][
                "Retrieval"
            ],
        Scalar=
            test[
                "anchor_mse"
            ][
                "Scalar"
            ],
        RawAdaptive=
            test[
                "anchor_mse"
            ][
                "RawAdaptive"
            ],
        ShrinkAdaptive=
            test[
                "anchor_mse"
            ][
                "ShrinkAdaptive"
            ],
        Oracle=
            test[
                "anchor_mse"
            ][
                "Oracle"
            ],
    )

    print(
        "\nFINAL CONDITION RESULT"
    )

    display(
        pd.DataFrame([
            row
        ])[
            [
                "Dataset",
                "Horizon",
                "OfficialPatchTST_MSE",
                "ShrinkAdaptive_MSE",
                "ShrinkGainVsDirect_pct",
                "Retrieval_MSE",
                "Scalar_MSE",
                "RawAdaptive_MSE",
                "Oracle_MSE",
                "ScalarAlpha",
                "ShrinkLambda",
                "ShrinkMeanAlpha",
                "ImprovedChannelFraction",
                "OracleHeadroomFromDirect_pct",
            ]
        ]
    )

    display(
        pd.DataFrame(
            bootstrap_rows
        )[
            (
                pd.DataFrame(
                    bootstrap_rows
                )[
                    "Dataset"
                ]
                == name
            )
            & (
                pd.DataFrame(
                    bootstrap_rows
                )[
                    "Horizon"
                ]
                == horizon
            )
        ]
    )

    del (
        direct_model,
        direct_ckpt,
        retriever,
        retriever_ckpt,
        gate,
        gate_ckpt,
        test_memory,
        test_memory_gpu,
        test,
        channel_df,
    )

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()


summary_df = (
    pd.DataFrame(
        summary_rows
    )
    .sort_values(
        [
            "Dataset",
            "Horizon",
        ]
    )
    .reset_index(
        drop=True
    )
)

display(
    summary_df
)

######################################################################################################################################################
Weather | H=96 | OFFICIAL PATCHTST + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 18 reference: MSE=0.149690, MAE=0.197816, best_epoch=65
Frozen retriever best epoch: 8
Fold direct Weather     H= 96 F1 ep=001/65 train=0.951592 lr=1.000e-04
Fold direct Weather     H= 96 F1 ep=002/65 train=0.609418 lr=1.000e-04
Fold direct Weather     H= 96 F1 ep=003/65 train=0.529759 lr=1.000e-04
Fold direct Weather     H= 96 F1 ep=004/65 train=0.521188 lr=9.000e-05
Fold direct Weather     H= 96 F1 ep=005/65 train=0.514889 lr=8.100e-05
Fold direct Weather     H= 96 F1 ep=006/65 train=0.508319 lr=7.290e-05
Fold direct Weather     H= 96 F1 ep=007/65 train=0.501999 lr=6.561e-05
Fold direct Weather     H= 96 F1 ep=008/65 train=0.498658 lr=5.905e-05
Fold direct Weather     H= 96 F1 ep=009/65 train=0.495039 lr=5.314e-05
Fold direct Weather     H= 96 F1 ep=010/65 train=0.492194 lr=4.783e-05
Fold direct Weather     H= 96 F1 ep=011/65 train=0.490812 lr=4.305e-05
Fold direct Weather     H= 96 F1 ep=012/65 train=0.489186 lr=3.874e-05
Fold direct Weather     H= 96 F1 ep=013/65 train=0.487193 lr=3.487e-05
Fold direct Weather     H= 96 F1 ep=014/65 train=0.486065 lr=3.138e-05
Fold direct Weather     H= 96 F1 ep=015/65 train=0.485150 lr=2.824e-05
Fold direct Weather     H= 96 F1 ep=016/65 train=0.484467 lr=2.542e-05
Fold direct Weather     H= 96 F1 ep=017/65 train=0.482573 lr=2.288e-05
Fold direct Weather     H= 96 F1 ep=018/65 train=0.482055 lr=2.059e-05
Fold direct Weather     H= 96 F1 ep=019/65 train=0.481488 lr=1.853e-05
Fold direct Weather     H= 96 F1 ep=020/65 train=0.480928 lr=1.668e-05
Fold direct Weather     H= 96 F1 ep=021/65 train=0.479946 lr=1.501e-05
Fold direct Weather     H= 96 F1 ep=022/65 train=0.478954 lr=1.351e-05
Fold direct Weather     H= 96 F1 ep=023/65 train=0.478657 lr=1.216e-05
Fold direct Weather     H= 96 F1 ep=024/65 train=0.478459 lr=1.094e-05
Fold direct Weather     H= 96 F1 ep=025/65 train=0.478072 lr=9.848e-06
Fold direct Weather     H= 96 F1 ep=026/65 train=0.477050 lr=8.863e-06
Fold direct Weather     H= 96 F1 ep=027/65 train=0.476791 lr=7.977e-06
Fold direct Weather     H= 96 F1 ep=028/65 train=0.476651 lr=7.179e-06
Fold direct Weather     H= 96 F1 ep=029/65 train=0.476025 lr=6.461e-06
Fold direct Weather     H= 96 F1 ep=030/65 train=0.475944 lr=5.815e-06
Fold direct Weather     H= 96 F1 ep=031/65 train=0.474171 lr=5.233e-06
Fold direct Weather     H= 96 F1 ep=032/65 train=0.475284 lr=4.710e-06
Fold direct Weather     H= 96 F1 ep=033/65 train=0.475126 lr=4.239e-06
Fold direct Weather     H= 96 F1 ep=034/65 train=0.474763 lr=3.815e-06
Fold direct Weather     H= 96 F1 ep=035/65 train=0.474901 lr=3.434e-06
Fold direct Weather     H= 96 F1 ep=036/65 train=0.474864 lr=3.090e-06
Fold direct Weather     H= 96 F1 ep=037/65 train=0.474404 lr=2.781e-06
Fold direct Weather     H= 96 F1 ep=038/65 train=0.473036 lr=2.503e-06
Fold direct Weather     H= 96 F1 ep=039/65 train=0.474491 lr=2.253e-06
Fold direct Weather     H= 96 F1 ep=040/65 train=0.474268 lr=2.028e-06
Fold direct Weather     H= 96 F1 ep=041/65 train=0.473920 lr=1.825e-06
Fold direct Weather     H= 96 F1 ep=042/65 train=0.473769 lr=1.642e-06
Fold direct Weather     H= 96 F1 ep=043/65 train=0.473732 lr=1.478e-06
Fold direct Weather     H= 96 F1 ep=044/65 train=0.472561 lr=1.330e-06
Fold direct Weather     H= 96 F1 ep=045/65 train=0.474216 lr=1.197e-06
Fold direct Weather     H= 96 F1 ep=046/65 train=0.473437 lr=1.078e-06
Fold direct Weather     H= 96 F1 ep=047/65 train=0.473472 lr=9.698e-07
Fold direct Weather     H= 96 F1 ep=048/65 train=0.473083 lr=8.728e-07
Fold direct Weather     H= 96 F1 ep=049/65 train=0.473177 lr=7.855e-07
Fold direct Weather     H= 96 F1 ep=050/65 train=0.473720 lr=7.070e-07
Fold direct Weather     H= 96 F1 ep=051/65 train=0.473324 lr=6.363e-07
Fold direct Weather     H= 96 F1 ep=052/65 train=0.473556 lr=5.726e-07
Fold direct Weather     H= 96 F1 ep=053/65 train=0.473269 lr=5.154e-07
Fold direct Weather     H= 96 F1 ep=054/65 train=0.473343 lr=4.638e-07
Fold direct Weather     H= 96 F1 ep=055/65 train=0.473233 lr=4.175e-07
Fold direct Weather     H= 96 F1 ep=056/65 train=0.473217 lr=3.757e-07
Fold direct Weather     H= 96 F1 ep=057/65 train=0.473444 lr=3.381e-07
Fold direct Weather     H= 96 F1 ep=058/65 train=0.473477 lr=3.043e-07
Fold direct Weather     H= 96 F1 ep=059/65 train=0.473212 lr=2.739e-07
Fold direct Weather     H= 96 F1 ep=060/65 train=0.472457 lr=2.465e-07
Fold direct Weather     H= 96 F1 ep=061/65 train=0.472779 lr=2.219e-07
Fold direct Weather     H= 96 F1 ep=062/65 train=0.473104 lr=1.997e-07
Fold direct Weather     H= 96 F1 ep=063/65 train=0.473094 lr=1.797e-07
Fold direct Weather     H= 96 F1 ep=064/65 train=0.473589 lr=1.617e-07
Fold direct Weather     H= 96 F1 ep=065/65 train=0.473338 lr=1.456e-07
Building memory embedding cache: Weather_H96_F1_prefix20287_emb.npy (21, 838, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=96 F1: prefix=20287, end=25820, anchors=1360, pairs=28560, memory/C=838
Fold direct Weather     H= 96 F2 ep=001/65 train=0.787895 lr=1.000e-04
Fold direct Weather     H= 96 F2 ep=002/65 train=0.511376 lr=1.000e-04
Fold direct Weather     H= 96 F2 ep=003/65 train=0.465398 lr=1.000e-04
Fold direct Weather     H= 96 F2 ep=004/65 train=0.459125 lr=9.000e-05
Fold direct Weather     H= 96 F2 ep=005/65 train=0.452334 lr=8.100e-05
Fold direct Weather     H= 96 F2 ep=006/65 train=0.447251 lr=7.290e-05
Fold direct Weather     H= 96 F2 ep=007/65 train=0.444280 lr=6.561e-05
Fold direct Weather     H= 96 F2 ep=008/65 train=0.440591 lr=5.905e-05
Fold direct Weather     H= 96 F2 ep=009/65 train=0.438816 lr=5.314e-05
Fold direct Weather     H= 96 F2 ep=010/65 train=0.437686 lr=4.783e-05
Fold direct Weather     H= 96 F2 ep=011/65 train=0.435672 lr=4.305e-05
Fold direct Weather     H= 96 F2 ep=012/65 train=0.434257 lr=3.874e-05
Fold direct Weather     H= 96 F2 ep=013/65 train=0.432160 lr=3.487e-05
Fold direct Weather     H= 96 F2 ep=014/65 train=0.432030 lr=3.138e-05
Fold direct Weather     H= 96 F2 ep=015/65 train=0.430736 lr=2.824e-05
Fold direct Weather     H= 96 F2 ep=016/65 train=0.430522 lr=2.542e-05
Fold direct Weather     H= 96 F2 ep=017/65 train=0.428122 lr=2.288e-05
Fold direct Weather     H= 96 F2 ep=018/65 train=0.428387 lr=2.059e-05
Fold direct Weather     H= 96 F2 ep=019/65 train=0.426792 lr=1.853e-05
Fold direct Weather     H= 96 F2 ep=020/65 train=0.426888 lr=1.668e-05
Fold direct Weather     H= 96 F2 ep=021/65 train=0.426243 lr=1.501e-05
Fold direct Weather     H= 96 F2 ep=022/65 train=0.426472 lr=1.351e-05
Fold direct Weather     H= 96 F2 ep=023/65 train=0.425466 lr=1.216e-05
Fold direct Weather     H= 96 F2 ep=024/65 train=0.425082 lr=1.094e-05
Fold direct Weather     H= 96 F2 ep=025/65 train=0.424885 lr=9.848e-06
Fold direct Weather     H= 96 F2 ep=026/65 train=0.424372 lr=8.863e-06
Fold direct Weather     H= 96 F2 ep=027/65 train=0.424254 lr=7.977e-06
Fold direct Weather     H= 96 F2 ep=028/65 train=0.424089 lr=7.179e-06
Fold direct Weather     H= 96 F2 ep=029/65 train=0.423857 lr=6.461e-06
Fold direct Weather     H= 96 F2 ep=030/65 train=0.423379 lr=5.815e-06
Fold direct Weather     H= 96 F2 ep=031/65 train=0.423233 lr=5.233e-06
Fold direct Weather     H= 96 F2 ep=032/65 train=0.422615 lr=4.710e-06
Fold direct Weather     H= 96 F2 ep=033/65 train=0.422896 lr=4.239e-06
Fold direct Weather     H= 96 F2 ep=034/65 train=0.422929 lr=3.815e-06
Fold direct Weather     H= 96 F2 ep=035/65 train=0.421398 lr=3.434e-06
Fold direct Weather     H= 96 F2 ep=036/65 train=0.422462 lr=3.090e-06
Fold direct Weather     H= 96 F2 ep=037/65 train=0.422215 lr=2.781e-06
Fold direct Weather     H= 96 F2 ep=038/65 train=0.420970 lr=2.503e-06
Fold direct Weather     H= 96 F2 ep=039/65 train=0.422189 lr=2.253e-06
Fold direct Weather     H= 96 F2 ep=040/65 train=0.421733 lr=2.028e-06
Fold direct Weather     H= 96 F2 ep=041/65 train=0.420834 lr=1.825e-06
Fold direct Weather     H= 96 F2 ep=042/65 train=0.421969 lr=1.642e-06
Fold direct Weather     H= 96 F2 ep=043/65 train=0.421587 lr=1.478e-06
Fold direct Weather     H= 96 F2 ep=044/65 train=0.421045 lr=1.330e-06
Fold direct Weather     H= 96 F2 ep=045/65 train=0.421643 lr=1.197e-06
Fold direct Weather     H= 96 F2 ep=046/65 train=0.421636 lr=1.078e-06
Fold direct Weather     H= 96 F2 ep=047/65 train=0.421943 lr=9.698e-07
Fold direct Weather     H= 96 F2 ep=048/65 train=0.421853 lr=8.728e-07
Fold direct Weather     H= 96 F2 ep=049/65 train=0.421565 lr=7.855e-07
Fold direct Weather     H= 96 F2 ep=050/65 train=0.421654 lr=7.070e-07
Fold direct Weather     H= 96 F2 ep=051/65 train=0.421428 lr=6.363e-07
Fold direct Weather     H= 96 F2 ep=052/65 train=0.421815 lr=5.726e-07
Fold direct Weather     H= 96 F2 ep=053/65 train=0.421385 lr=5.154e-07
Fold direct Weather     H= 96 F2 ep=054/65 train=0.421553 lr=4.638e-07
Fold direct Weather     H= 96 F2 ep=055/65 train=0.421615 lr=4.175e-07
Fold direct Weather     H= 96 F2 ep=056/65 train=0.421988 lr=3.757e-07
Fold direct Weather     H= 96 F2 ep=057/65 train=0.421493 lr=3.381e-07
Fold direct Weather     H= 96 F2 ep=058/65 train=0.421297 lr=3.043e-07
Fold direct Weather     H= 96 F2 ep=059/65 train=0.420683 lr=2.739e-07
Fold direct Weather     H= 96 F2 ep=060/65 train=0.421546 lr=2.465e-07
Fold direct Weather     H= 96 F2 ep=061/65 train=0.421428 lr=2.219e-07
Fold direct Weather     H= 96 F2 ep=062/65 train=0.421675 lr=1.997e-07
Fold direct Weather     H= 96 F2 ep=063/65 train=0.421202 lr=1.797e-07
Fold direct Weather     H= 96 F2 ep=064/65 train=0.421562 lr=1.617e-07
Fold direct Weather     H= 96 F2 ep=065/65 train=0.420111 lr=1.456e-07
Building memory embedding cache: Weather_H96_F2_prefix25820_emb.npy (21, 1068, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=96 F2: prefix=25820, end=31353, anchors=1360, pairs=28560, memory/C=1068
Fold direct Weather     H= 96 F3 ep=001/65 train=0.770634 lr=1.000e-04
Fold direct Weather     H= 96 F3 ep=002/65 train=0.509332 lr=1.000e-04
Fold direct Weather     H= 96 F3 ep=003/65 train=0.461376 lr=1.000e-04
Fold direct Weather     H= 96 F3 ep=004/65 train=0.451807 lr=9.000e-05
Fold direct Weather     H= 96 F3 ep=005/65 train=0.446749 lr=8.100e-05
Fold direct Weather     H= 96 F3 ep=006/65 train=0.440616 lr=7.290e-05
Fold direct Weather     H= 96 F3 ep=007/65 train=0.437262 lr=6.561e-05
Fold direct Weather     H= 96 F3 ep=008/65 train=0.435880 lr=5.905e-05
Fold direct Weather     H= 96 F3 ep=009/65 train=0.433381 lr=5.314e-05
Fold direct Weather     H= 96 F3 ep=010/65 train=0.432091 lr=4.783e-05
Fold direct Weather     H= 96 F3 ep=011/65 train=0.430202 lr=4.305e-05
Fold direct Weather     H= 96 F3 ep=012/65 train=0.427904 lr=3.874e-05
Fold direct Weather     H= 96 F3 ep=013/65 train=0.426520 lr=3.487e-05
Fold direct Weather     H= 96 F3 ep=014/65 train=0.426701 lr=3.138e-05
Fold direct Weather     H= 96 F3 ep=015/65 train=0.425883 lr=2.824e-05
Fold direct Weather     H= 96 F3 ep=016/65 train=0.424920 lr=2.542e-05
Fold direct Weather     H= 96 F3 ep=017/65 train=0.423750 lr=2.288e-05
Fold direct Weather     H= 96 F3 ep=018/65 train=0.423232 lr=2.059e-05
Fold direct Weather     H= 96 F3 ep=019/65 train=0.422344 lr=1.853e-05
Fold direct Weather     H= 96 F3 ep=020/65 train=0.421619 lr=1.668e-05
Fold direct Weather     H= 96 F3 ep=021/65 train=0.421326 lr=1.501e-05
Fold direct Weather     H= 96 F3 ep=022/65 train=0.419387 lr=1.351e-05
Fold direct Weather     H= 96 F3 ep=023/65 train=0.420033 lr=1.216e-05
Fold direct Weather     H= 96 F3 ep=024/65 train=0.419667 lr=1.094e-05
Fold direct Weather     H= 96 F3 ep=025/65 train=0.419521 lr=9.848e-06
Fold direct Weather     H= 96 F3 ep=026/65 train=0.418872 lr=8.863e-06
Fold direct Weather     H= 96 F3 ep=027/65 train=0.418749 lr=7.977e-06
Fold direct Weather     H= 96 F3 ep=028/65 train=0.418330 lr=7.179e-06
Fold direct Weather     H= 96 F3 ep=029/65 train=0.417135 lr=6.461e-06
Fold direct Weather     H= 96 F3 ep=030/65 train=0.417838 lr=5.815e-06
Fold direct Weather     H= 96 F3 ep=031/65 train=0.417295 lr=5.233e-06
Fold direct Weather     H= 96 F3 ep=032/65 train=0.417684 lr=4.710e-06
Fold direct Weather     H= 96 F3 ep=033/65 train=0.417261 lr=4.239e-06
Fold direct Weather     H= 96 F3 ep=034/65 train=0.417211 lr=3.815e-06
Fold direct Weather     H= 96 F3 ep=035/65 train=0.416976 lr=3.434e-06
Fold direct Weather     H= 96 F3 ep=036/65 train=0.417153 lr=3.090e-06
Fold direct Weather     H= 96 F3 ep=037/65 train=0.416424 lr=2.781e-06
Fold direct Weather     H= 96 F3 ep=038/65 train=0.416702 lr=2.503e-06
Fold direct Weather     H= 96 F3 ep=039/65 train=0.416308 lr=2.253e-06
Fold direct Weather     H= 96 F3 ep=040/65 train=0.416373 lr=2.028e-06
Fold direct Weather     H= 96 F3 ep=041/65 train=0.416375 lr=1.825e-06
Fold direct Weather     H= 96 F3 ep=042/65 train=0.416319 lr=1.642e-06
Fold direct Weather     H= 96 F3 ep=043/65 train=0.416221 lr=1.478e-06
Fold direct Weather     H= 96 F3 ep=044/65 train=0.415380 lr=1.330e-06
Fold direct Weather     H= 96 F3 ep=045/65 train=0.415269 lr=1.197e-06
Fold direct Weather     H= 96 F3 ep=046/65 train=0.415978 lr=1.078e-06
Fold direct Weather     H= 96 F3 ep=047/65 train=0.416026 lr=9.698e-07
Fold direct Weather     H= 96 F3 ep=048/65 train=0.416406 lr=8.728e-07
Fold direct Weather     H= 96 F3 ep=049/65 train=0.415701 lr=7.855e-07
Fold direct Weather     H= 96 F3 ep=050/65 train=0.416136 lr=7.070e-07
Fold direct Weather     H= 96 F3 ep=051/65 train=0.415919 lr=6.363e-07
Fold direct Weather     H= 96 F3 ep=052/65 train=0.415833 lr=5.726e-07
Fold direct Weather     H= 96 F3 ep=053/65 train=0.416109 lr=5.154e-07
Fold direct Weather     H= 96 F3 ep=054/65 train=0.415710 lr=4.638e-07
Fold direct Weather     H= 96 F3 ep=055/65 train=0.414722 lr=4.175e-07
Fold direct Weather     H= 96 F3 ep=056/65 train=0.415888 lr=3.757e-07
Fold direct Weather     H= 96 F3 ep=057/65 train=0.415553 lr=3.381e-07
Fold direct Weather     H= 96 F3 ep=058/65 train=0.415996 lr=3.043e-07
Fold direct Weather     H= 96 F3 ep=059/65 train=0.415710 lr=2.739e-07
Fold direct Weather     H= 96 F3 ep=060/65 train=0.415565 lr=2.465e-07
Fold direct Weather     H= 96 F3 ep=061/65 train=0.415992 lr=2.219e-07
Fold direct Weather     H= 96 F3 ep=062/65 train=0.415040 lr=1.997e-07
Fold direct Weather     H= 96 F3 ep=063/65 train=0.415691 lr=1.797e-07
Fold direct Weather     H= 96 F3 ep=064/65 train=0.415820 lr=1.617e-07
Fold direct Weather     H= 96 F3 ep=065/65 train=0.415673 lr=1.456e-07
Building memory embedding cache: Weather_H96_F3_prefix31353_emb.npy (21, 1299, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=96 F3: prefix=31353, end=36887, anchors=1360, pairs=28560, memory/C=1299
Total OOF pairs: 85680
Building memory embedding cache: Weather_H96_validation_train_memory_emb.npy (21, 1529, 64)
  encoded channel 1/21
  encoded channel 21/21
Validation Weather H=96: anchors=5175, pairs=108675, memory/C=1529
Gate Weather     H= 96 ep=01 OOF=0.736491 val=0.389641 alpha=0.097 best=0.389641@1
Gate Weather     H= 96 ep=02 OOF=0.732144 val=0.389619 alpha=0.095 best=0.389619@2
Gate Weather     H= 96 ep=03 OOF=0.727741 val=0.389587 alpha=0.094 best=0.389587@3
Gate Weather     H= 96 ep=04 OOF=0.727942 val=0.389521 alpha=0.095 best=0.389521@4
Gate Weather     H= 96 ep=05 OOF=0.728470 val=0.389413 alpha=0.097 best=0.389413@5
Gate Weather     H= 96 ep=06 OOF=0.730528 val=0.389162 alpha=0.105 best=0.389162@6
Gate Weather     H= 96 ep=07 OOF=0.719702 val=0.388670 alpha=0.122 best=0.388670@7
Gate Weather     H= 96 ep=08 OOF=0.725076 val=0.387840 alpha=0.155 best=0.387840@8
Gate Weather     H= 96 ep=09 OOF=0.720954 val=0.386961 alpha=0.187 best=0.386961@9
Gate Weather     H= 96 ep=10 OOF=0.721116 val=0.386515 alpha=0.186 best=0.386515@10
Gate Weather     H= 96 ep=11 OOF=0.713436 val=0.386309 alpha=0.188 best=0.386309@11
Gate Weather     H= 96 ep=12 OOF=0.720087 val=0.386111 alpha=0.188 best=0.386111@12
Gate Weather     H= 96 ep=13 OOF=0.725712 val=0.386002 alpha=0.184 best=0.386002@13
Gate Weather     H= 96 ep=14 OOF=0.729742 val=0.386052 alpha=0.174 best=0.386002@13
Gate Weather     H= 96 ep=15 OOF=0.718403 val=0.385921 alpha=0.169 best=0.385921@15
Gate Weather     H= 96 ep=16 OOF=0.723977 val=0.385848 alpha=0.173 best=0.385848@16
Gate Weather     H= 96 ep=17 OOF=0.723461 val=0.386348 alpha=0.157 best=0.385848@16
Gate Weather     H= 96 ep=18 OOF=0.732410 val=0.385577 alpha=0.167 best=0.385577@18
Gate Weather     H= 96 ep=19 OOF=0.717898 val=0.385574 alpha=0.153 best=0.385574@19
Gate Weather     H= 96 ep=20 OOF=0.710505 val=0.385710 alpha=0.142 best=0.385574@19
Gate Weather     H= 96 ep=21 OOF=0.713717 val=0.385313 alpha=0.150 best=0.385313@21
Gate Weather     H= 96 ep=22 OOF=0.724511 val=0.385987 alpha=0.138 best=0.385313@21
Gate Weather     H= 96 ep=23 OOF=0.713367 val=0.385933 alpha=0.139 best=0.385313@21
Gate Weather     H= 96 ep=24 OOF=0.717545 val=0.385146 alpha=0.141 best=0.385146@24
Gate Weather     H= 96 ep=25 OOF=0.716855 val=0.384625 alpha=0.145 best=0.384625@25
Gate Weather     H= 96 ep=26 OOF=0.718704 val=0.384943 alpha=0.141 best=0.384625@25
Gate Weather     H= 96 ep=27 OOF=0.716558 val=0.385216 alpha=0.135 best=0.384625@25
Gate Weather     H= 96 ep=28 OOF=0.707582 val=0.385782 alpha=0.132 best=0.384625@25
Gate Weather     H= 96 ep=29 OOF=0.705999 val=0.384838 alpha=0.138 best=0.384625@25
Gate Weather     H= 96 ep=30 OOF=0.700901 val=0.384664 alpha=0.138 best=0.384625@25
Gate Weather     H= 96 ep=31 OOF=0.715682 val=0.384492 alpha=0.134 best=0.384492@31
Gate Weather     H= 96 ep=32 OOF=0.707099 val=0.384517 alpha=0.140 best=0.384492@31
Gate Weather     H= 96 ep=33 OOF=0.717627 val=0.384519 alpha=0.137 best=0.384492@31
Gate Weather     H= 96 ep=34 OOF=0.714218 val=0.384384 alpha=0.136 best=0.384384@34
Gate Weather     H= 96 ep=35 OOF=0.712029 val=0.384444 alpha=0.142 best=0.384384@34
Gate Weather     H= 96 ep=36 OOF=0.714242 val=0.384933 alpha=0.137 best=0.384384@34
Gate Weather     H= 96 ep=37 OOF=0.713713 val=0.384527 alpha=0.137 best=0.384384@34
Gate Weather     H= 96 ep=38 OOF=0.706795 val=0.384663 alpha=0.135 best=0.384384@34
Gate Weather     H= 96 ep=39 OOF=0.722011 val=0.384327 alpha=0.133 best=0.384327@39
Gate Weather     H= 96 ep=40 OOF=0.714755 val=0.384576 alpha=0.134 best=0.384327@39
Gate Weather     H= 96 ep=41 OOF=0.702946 val=0.384854 alpha=0.136 best=0.384327@39
Gate Weather     H= 96 ep=42 OOF=0.703967 val=0.384079 alpha=0.135 best=0.384079@42
Gate Weather     H= 96 ep=43 OOF=0.707045 val=0.384151 alpha=0.141 best=0.384079@42
Gate Weather     H= 96 ep=44 OOF=0.714948 val=0.384511 alpha=0.136 best=0.384079@42
Gate Weather     H= 96 ep=45 OOF=0.706824 val=0.384187 alpha=0.138 best=0.384079@42
Gate Weather     H= 96 ep=46 OOF=0.722571 val=0.383939 alpha=0.139 best=0.383939@46
Gate Weather     H= 96 ep=47 OOF=0.703667 val=0.384011 alpha=0.142 best=0.383939@46
Gate Weather     H= 96 ep=48 OOF=0.710927 val=0.384258 alpha=0.136 best=0.383939@46
Gate Weather     H= 96 ep=49 OOF=0.710623 val=0.384505 alpha=0.140 best=0.383939@46
Gate Weather     H= 96 ep=50 OOF=0.719501 val=0.383753 alpha=0.147 best=0.383753@50
Validation calibration | alpha0=0.10 | lambda=1.00 | gateEpoch=50
Building memory embedding cache: Weather_H96_test_trainval_memory_emb.npy (21, 1749, 64)
  encoded channel 1/21
  encoded channel 21/21
  test anchors 32/10444
  test anchors 3200/10444
  test anchors 6400/10444
  test anchors 9600/10444
  test anchors 10444/10444

FINAL CONDITION RESULT

   Dataset  Horizon  OfficialPatchTST_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct
0  Weather       96               0.14969             0.14744                1.503275       0.240003     0.14836          0.14744    0.123863          0.1           1.0         0.159055                 0.380952                     17.254005

   Dataset  Horizon             Comparison  MeanImprovement    CI_Low   CI_High  SignificantPositive
0  Weather       96  Direct-ShrinkAdaptive          0.00225  0.001320  0.003172                 True
1  Weather       96  Scalar-ShrinkAdaptive          0.00092  0.000163  0.001656                 True

######################################################################################################################################################
Weather | H=192 | OFFICIAL PATCHTST + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 18 reference: MSE=0.194775, MAE=0.240853, best_epoch=45
Frozen retriever best epoch: 5
Fold direct Weather     H=192 F1 ep=001/45 train=0.981854 lr=1.000e-04
Fold direct Weather     H=192 F1 ep=002/45 train=0.686572 lr=1.000e-04
Fold direct Weather     H=192 F1 ep=003/45 train=0.624206 lr=1.000e-04
Fold direct Weather     H=192 F1 ep=004/45 train=0.616110 lr=9.000e-05
Fold direct Weather     H=192 F1 ep=005/45 train=0.608612 lr=8.100e-05
Fold direct Weather     H=192 F1 ep=006/45 train=0.603664 lr=7.290e-05
Fold direct Weather     H=192 F1 ep=007/45 train=0.600255 lr=6.561e-05
Fold direct Weather     H=192 F1 ep=008/45 train=0.596005 lr=5.905e-05
Fold direct Weather     H=192 F1 ep=009/45 train=0.593018 lr=5.314e-05
Fold direct Weather     H=192 F1 ep=010/45 train=0.589923 lr=4.783e-05
Fold direct Weather     H=192 F1 ep=011/45 train=0.589054 lr=4.305e-05
Fold direct Weather     H=192 F1 ep=012/45 train=0.586208 lr=3.874e-05
Fold direct Weather     H=192 F1 ep=013/45 train=0.585095 lr=3.487e-05
Fold direct Weather     H=192 F1 ep=014/45 train=0.583395 lr=3.138e-05
Fold direct Weather     H=192 F1 ep=015/45 train=0.581934 lr=2.824e-05
Fold direct Weather     H=192 F1 ep=016/45 train=0.580825 lr=2.542e-05
Fold direct Weather     H=192 F1 ep=017/45 train=0.579467 lr=2.288e-05
Fold direct Weather     H=192 F1 ep=018/45 train=0.576796 lr=2.059e-05
Fold direct Weather     H=192 F1 ep=019/45 train=0.577229 lr=1.853e-05
Fold direct Weather     H=192 F1 ep=020/45 train=0.576088 lr=1.668e-05
Fold direct Weather     H=192 F1 ep=021/45 train=0.574676 lr=1.501e-05
Fold direct Weather     H=192 F1 ep=022/45 train=0.575034 lr=1.351e-05
Fold direct Weather     H=192 F1 ep=023/45 train=0.574037 lr=1.216e-05
Fold direct Weather     H=192 F1 ep=024/45 train=0.573523 lr=1.094e-05
Fold direct Weather     H=192 F1 ep=025/45 train=0.573063 lr=9.848e-06
Fold direct Weather     H=192 F1 ep=026/45 train=0.572181 lr=8.863e-06
Fold direct Weather     H=192 F1 ep=027/45 train=0.571411 lr=7.977e-06
Fold direct Weather     H=192 F1 ep=028/45 train=0.571805 lr=7.179e-06
Fold direct Weather     H=192 F1 ep=029/45 train=0.571576 lr=6.461e-06
Fold direct Weather     H=192 F1 ep=030/45 train=0.570509 lr=5.815e-06
Fold direct Weather     H=192 F1 ep=031/45 train=0.570340 lr=5.233e-06
Fold direct Weather     H=192 F1 ep=032/45 train=0.570104 lr=4.710e-06
Fold direct Weather     H=192 F1 ep=033/45 train=0.568800 lr=4.239e-06
Fold direct Weather     H=192 F1 ep=034/45 train=0.569817 lr=3.815e-06
Fold direct Weather     H=192 F1 ep=035/45 train=0.569193 lr=3.434e-06
Fold direct Weather     H=192 F1 ep=036/45 train=0.569378 lr=3.090e-06
Fold direct Weather     H=192 F1 ep=037/45 train=0.569400 lr=2.781e-06
Fold direct Weather     H=192 F1 ep=038/45 train=0.568990 lr=2.503e-06
Fold direct Weather     H=192 F1 ep=039/45 train=0.568133 lr=2.253e-06
Fold direct Weather     H=192 F1 ep=040/45 train=0.568773 lr=2.028e-06
Fold direct Weather     H=192 F1 ep=041/45 train=0.568508 lr=1.825e-06
Fold direct Weather     H=192 F1 ep=042/45 train=0.568644 lr=1.642e-06
Fold direct Weather     H=192 F1 ep=043/45 train=0.567670 lr=1.478e-06
Fold direct Weather     H=192 F1 ep=044/45 train=0.568166 lr=1.330e-06
Fold direct Weather     H=192 F1 ep=045/45 train=0.567580 lr=1.197e-06
Building memory embedding cache: Weather_H192_F1_prefix20287_emb.npy (21, 834, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=192 F1: prefix=20287, end=25820, anchors=1336, pairs=28056, memory/C=834
Fold direct Weather     H=192 F2 ep=001/45 train=0.845100 lr=1.000e-04
Fold direct Weather     H=192 F2 ep=002/45 train=0.581482 lr=1.000e-04
Fold direct Weather     H=192 F2 ep=003/45 train=0.530464 lr=1.000e-04
Fold direct Weather     H=192 F2 ep=004/45 train=0.522238 lr=9.000e-05
Fold direct Weather     H=192 F2 ep=005/45 train=0.516506 lr=8.100e-05
Fold direct Weather     H=192 F2 ep=006/45 train=0.511959 lr=7.290e-05
Fold direct Weather     H=192 F2 ep=007/45 train=0.509195 lr=6.561e-05
Fold direct Weather     H=192 F2 ep=008/45 train=0.506423 lr=5.905e-05
Fold direct Weather     H=192 F2 ep=009/45 train=0.504735 lr=5.314e-05
Fold direct Weather     H=192 F2 ep=010/45 train=0.502616 lr=4.783e-05
Fold direct Weather     H=192 F2 ep=011/45 train=0.502043 lr=4.305e-05
Fold direct Weather     H=192 F2 ep=012/45 train=0.500274 lr=3.874e-05
Fold direct Weather     H=192 F2 ep=013/45 train=0.498902 lr=3.487e-05
Fold direct Weather     H=192 F2 ep=014/45 train=0.498421 lr=3.138e-05
Fold direct Weather     H=192 F2 ep=015/45 train=0.497513 lr=2.824e-05
Fold direct Weather     H=192 F2 ep=016/45 train=0.496471 lr=2.542e-05
Fold direct Weather     H=192 F2 ep=017/45 train=0.495503 lr=2.288e-05
Fold direct Weather     H=192 F2 ep=018/45 train=0.495089 lr=2.059e-05
Fold direct Weather     H=192 F2 ep=019/45 train=0.493787 lr=1.853e-05
Fold direct Weather     H=192 F2 ep=020/45 train=0.492512 lr=1.668e-05
Fold direct Weather     H=192 F2 ep=021/45 train=0.492541 lr=1.501e-05
Fold direct Weather     H=192 F2 ep=022/45 train=0.492781 lr=1.351e-05
Fold direct Weather     H=192 F2 ep=023/45 train=0.492073 lr=1.216e-05
Fold direct Weather     H=192 F2 ep=024/45 train=0.491477 lr=1.094e-05
Fold direct Weather     H=192 F2 ep=025/45 train=0.491925 lr=9.848e-06
Fold direct Weather     H=192 F2 ep=026/45 train=0.491296 lr=8.863e-06
Fold direct Weather     H=192 F2 ep=027/45 train=0.490093 lr=7.977e-06
Fold direct Weather     H=192 F2 ep=028/45 train=0.490763 lr=7.179e-06
Fold direct Weather     H=192 F2 ep=029/45 train=0.490483 lr=6.461e-06
Fold direct Weather     H=192 F2 ep=030/45 train=0.490097 lr=5.815e-06
Fold direct Weather     H=192 F2 ep=031/45 train=0.490176 lr=5.233e-06
Fold direct Weather     H=192 F2 ep=032/45 train=0.488985 lr=4.710e-06
Fold direct Weather     H=192 F2 ep=033/45 train=0.489651 lr=4.239e-06
Fold direct Weather     H=192 F2 ep=034/45 train=0.489722 lr=3.815e-06
Fold direct Weather     H=192 F2 ep=035/45 train=0.488947 lr=3.434e-06
Fold direct Weather     H=192 F2 ep=036/45 train=0.489204 lr=3.090e-06
Fold direct Weather     H=192 F2 ep=037/45 train=0.488520 lr=2.781e-06
Fold direct Weather     H=192 F2 ep=038/45 train=0.488116 lr=2.503e-06
Fold direct Weather     H=192 F2 ep=039/45 train=0.488503 lr=2.253e-06
Fold direct Weather     H=192 F2 ep=040/45 train=0.487758 lr=2.028e-06
Fold direct Weather     H=192 F2 ep=041/45 train=0.488844 lr=1.825e-06
Fold direct Weather     H=192 F2 ep=042/45 train=0.488653 lr=1.642e-06
Fold direct Weather     H=192 F2 ep=043/45 train=0.488676 lr=1.478e-06
Fold direct Weather     H=192 F2 ep=044/45 train=0.488646 lr=1.330e-06
Fold direct Weather     H=192 F2 ep=045/45 train=0.488366 lr=1.197e-06
Building memory embedding cache: Weather_H192_F2_prefix25820_emb.npy (21, 1064, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=192 F2: prefix=25820, end=31353, anchors=1336, pairs=28056, memory/C=1064
Fold direct Weather     H=192 F3 ep=001/45 train=0.801188 lr=1.000e-04
Fold direct Weather     H=192 F3 ep=002/45 train=0.555029 lr=1.000e-04
Fold direct Weather     H=192 F3 ep=003/45 train=0.518064 lr=1.000e-04
Fold direct Weather     H=192 F3 ep=004/45 train=0.511598 lr=9.000e-05
Fold direct Weather     H=192 F3 ep=005/45 train=0.505338 lr=8.100e-05
Fold direct Weather     H=192 F3 ep=006/45 train=0.501391 lr=7.290e-05
Fold direct Weather     H=192 F3 ep=007/45 train=0.499516 lr=6.561e-05
Fold direct Weather     H=192 F3 ep=008/45 train=0.496994 lr=5.905e-05
Fold direct Weather     H=192 F3 ep=009/45 train=0.495415 lr=5.314e-05
Fold direct Weather     H=192 F3 ep=010/45 train=0.493361 lr=4.783e-05
Fold direct Weather     H=192 F3 ep=011/45 train=0.492512 lr=4.305e-05
Fold direct Weather     H=192 F3 ep=012/45 train=0.491967 lr=3.874e-05
Fold direct Weather     H=192 F3 ep=013/45 train=0.491039 lr=3.487e-05
Fold direct Weather     H=192 F3 ep=014/45 train=0.490062 lr=3.138e-05
Fold direct Weather     H=192 F3 ep=015/45 train=0.488584 lr=2.824e-05
Fold direct Weather     H=192 F3 ep=016/45 train=0.487185 lr=2.542e-05
Fold direct Weather     H=192 F3 ep=017/45 train=0.487264 lr=2.288e-05
Fold direct Weather     H=192 F3 ep=018/45 train=0.486690 lr=2.059e-05
Fold direct Weather     H=192 F3 ep=019/45 train=0.485647 lr=1.853e-05
Fold direct Weather     H=192 F3 ep=020/45 train=0.484755 lr=1.668e-05
Fold direct Weather     H=192 F3 ep=021/45 train=0.484224 lr=1.501e-05
Fold direct Weather     H=192 F3 ep=022/45 train=0.483902 lr=1.351e-05
Fold direct Weather     H=192 F3 ep=023/45 train=0.483509 lr=1.216e-05
Fold direct Weather     H=192 F3 ep=024/45 train=0.482891 lr=1.094e-05
Fold direct Weather     H=192 F3 ep=025/45 train=0.483049 lr=9.848e-06
Fold direct Weather     H=192 F3 ep=026/45 train=0.482778 lr=8.863e-06
Fold direct Weather     H=192 F3 ep=027/45 train=0.481527 lr=7.977e-06
Fold direct Weather     H=192 F3 ep=028/45 train=0.481889 lr=7.179e-06
Fold direct Weather     H=192 F3 ep=029/45 train=0.482050 lr=6.461e-06
Fold direct Weather     H=192 F3 ep=030/45 train=0.481345 lr=5.815e-06
Fold direct Weather     H=192 F3 ep=031/45 train=0.481520 lr=5.233e-06
Fold direct Weather     H=192 F3 ep=032/45 train=0.480910 lr=4.710e-06
Fold direct Weather     H=192 F3 ep=033/45 train=0.481251 lr=4.239e-06
Fold direct Weather     H=192 F3 ep=034/45 train=0.481228 lr=3.815e-06
Fold direct Weather     H=192 F3 ep=035/45 train=0.480658 lr=3.434e-06
Fold direct Weather     H=192 F3 ep=036/45 train=0.480883 lr=3.090e-06
Fold direct Weather     H=192 F3 ep=037/45 train=0.480737 lr=2.781e-06
Fold direct Weather     H=192 F3 ep=038/45 train=0.480615 lr=2.503e-06
Fold direct Weather     H=192 F3 ep=039/45 train=0.480427 lr=2.253e-06
Fold direct Weather     H=192 F3 ep=040/45 train=0.480727 lr=2.028e-06
Fold direct Weather     H=192 F3 ep=041/45 train=0.480074 lr=1.825e-06
Fold direct Weather     H=192 F3 ep=042/45 train=0.480294 lr=1.642e-06
Fold direct Weather     H=192 F3 ep=043/45 train=0.480363 lr=1.478e-06
Fold direct Weather     H=192 F3 ep=044/45 train=0.480085 lr=1.330e-06
Fold direct Weather     H=192 F3 ep=045/45 train=0.479843 lr=1.197e-06
Building memory embedding cache: Weather_H192_F3_prefix31353_emb.npy (21, 1295, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=192 F3: prefix=31353, end=36887, anchors=1336, pairs=28056, memory/C=1295
Total OOF pairs: 84168
Building memory embedding cache: Weather_H192_validation_train_memory_emb.npy (21, 1525, 64)
  encoded channel 1/21
  encoded channel 21/21
Validation Weather H=192: anchors=5079, pairs=106659, memory/C=1525
Gate Weather     H=192 ep=01 OOF=0.822720 val=0.454970 alpha=0.099 best=0.454970@1
Gate Weather     H=192 ep=02 OOF=0.823850 val=0.454893 alpha=0.097 best=0.454893@2
Gate Weather     H=192 ep=03 OOF=0.826091 val=0.454785 alpha=0.096 best=0.454785@3
Gate Weather     H=192 ep=04 OOF=0.814824 val=0.454637 alpha=0.097 best=0.454637@4
Gate Weather     H=192 ep=05 OOF=0.826898 val=0.454333 alpha=0.102 best=0.454333@5
Gate Weather     H=192 ep=06 OOF=0.818330 val=0.453838 alpha=0.115 best=0.453838@6
Gate Weather     H=192 ep=07 OOF=0.823941 val=0.453199 alpha=0.131 best=0.453199@7
Gate Weather     H=192 ep=08 OOF=0.823355 val=0.452709 alpha=0.138 best=0.452709@8
Gate Weather     H=192 ep=09 OOF=0.818098 val=0.452133 alpha=0.138 best=0.452133@9
Gate Weather     H=192 ep=10 OOF=0.819974 val=0.451622 alpha=0.140 best=0.451622@10
Gate Weather     H=192 ep=11 OOF=0.825721 val=0.451389 alpha=0.142 best=0.451389@11
Gate Weather     H=192 ep=12 OOF=0.830152 val=0.451214 alpha=0.140 best=0.451214@12
Gate Weather     H=192 ep=13 OOF=0.812664 val=0.450976 alpha=0.139 best=0.450976@13
Gate Weather     H=192 ep=14 OOF=0.824850 val=0.451009 alpha=0.135 best=0.450976@13
Gate Weather     H=192 ep=15 OOF=0.813078 val=0.450884 alpha=0.134 best=0.450884@15
Gate Weather     H=192 ep=16 OOF=0.803668 val=0.450801 alpha=0.128 best=0.450801@16
Gate Weather     H=192 ep=17 OOF=0.810717 val=0.450454 alpha=0.132 best=0.450454@17
Gate Weather     H=192 ep=18 OOF=0.810985 val=0.450477 alpha=0.127 best=0.450454@17
Gate Weather     H=192 ep=19 OOF=0.803390 val=0.450145 alpha=0.123 best=0.450145@19
Gate Weather     H=192 ep=20 OOF=0.810141 val=0.450390 alpha=0.124 best=0.450145@19
Gate Weather     H=192 ep=21 OOF=0.811889 val=0.450408 alpha=0.114 best=0.450145@19
Gate Weather     H=192 ep=22 OOF=0.825086 val=0.450682 alpha=0.109 best=0.450145@19
Gate Weather     H=192 ep=23 OOF=0.804277 val=0.449724 alpha=0.120 best=0.449724@23
Gate Weather     H=192 ep=24 OOF=0.808832 val=0.450082 alpha=0.112 best=0.449724@23
Gate Weather     H=192 ep=25 OOF=0.807913 val=0.450055 alpha=0.112 best=0.449724@23
Gate Weather     H=192 ep=26 OOF=0.801776 val=0.450049 alpha=0.115 best=0.449724@23
Gate Weather     H=192 ep=27 OOF=0.808332 val=0.449751 alpha=0.113 best=0.449724@23
Gate Weather     H=192 ep=28 OOF=0.809915 val=0.450545 alpha=0.108 best=0.449724@23
Gate Weather     H=192 ep=29 OOF=0.813725 val=0.449912 alpha=0.114 best=0.449724@23
Gate Weather     H=192 ep=30 OOF=0.807206 val=0.450236 alpha=0.112 best=0.449724@23
Validation calibration | alpha0=0.10 | lambda=1.00 | gateEpoch=23
Building memory embedding cache: Weather_H192_test_trainval_memory_emb.npy (21, 1745, 64)
  encoded channel 1/21
  encoded channel 21/21
  test anchors 32/10348
  test anchors 3200/10348
  test anchors 6400/10348
  test anchors 9600/10348
  test anchors 10348/10348

FINAL CONDITION RESULT

   Dataset  Horizon  OfficialPatchTST_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct
0  Weather      192              0.194775            0.190482                2.203907       0.300271    0.192337         0.190482    0.161471          0.1           1.0         0.110582                 0.666667                      17.09888

   Dataset  Horizon             Comparison  MeanImprovement    CI_Low   CI_High  SignificantPositive
2  Weather      192  Direct-ShrinkAdaptive         0.004293  0.003319  0.005325                 True
3  Weather      192  Scalar-ShrinkAdaptive         0.001855  0.001170  0.002572                 True

######################################################################################################################################################
Weather | H=336 | OFFICIAL PATCHTST + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 18 reference: MSE=0.246900, MAE=0.281548, best_epoch=19
Frozen retriever best epoch: 7
Fold direct Weather     H=336 F1 ep=001/19 train=1.070101 lr=1.000e-04
Fold direct Weather     H=336 F1 ep=002/19 train=0.793645 lr=1.000e-04
Fold direct Weather     H=336 F1 ep=003/19 train=0.736775 lr=1.000e-04
Fold direct Weather     H=336 F1 ep=004/19 train=0.729900 lr=9.000e-05
Fold direct Weather     H=336 F1 ep=005/19 train=0.724517 lr=8.100e-05
Fold direct Weather     H=336 F1 ep=006/19 train=0.718183 lr=7.290e-05
Fold direct Weather     H=336 F1 ep=007/19 train=0.713706 lr=6.561e-05
Fold direct Weather     H=336 F1 ep=008/19 train=0.709861 lr=5.905e-05
Fold direct Weather     H=336 F1 ep=009/19 train=0.707047 lr=5.314e-05
Fold direct Weather     H=336 F1 ep=010/19 train=0.704617 lr=4.783e-05
Fold direct Weather     H=336 F1 ep=011/19 train=0.702126 lr=4.305e-05
Fold direct Weather     H=336 F1 ep=012/19 train=0.700002 lr=3.874e-05
Fold direct Weather     H=336 F1 ep=013/19 train=0.697825 lr=3.487e-05
Fold direct Weather     H=336 F1 ep=014/19 train=0.696281 lr=3.138e-05
Fold direct Weather     H=336 F1 ep=015/19 train=0.694818 lr=2.824e-05
Fold direct Weather     H=336 F1 ep=016/19 train=0.693437 lr=2.542e-05
Fold direct Weather     H=336 F1 ep=017/19 train=0.691011 lr=2.288e-05
Fold direct Weather     H=336 F1 ep=018/19 train=0.689972 lr=2.059e-05
Fold direct Weather     H=336 F1 ep=019/19 train=0.688446 lr=1.853e-05
Building memory embedding cache: Weather_H336_F1_prefix20287_emb.npy (21, 828, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=336 F1: prefix=20287, end=25820, anchors=1300, pairs=27300, memory/C=828
Fold direct Weather     H=336 F2 ep=001/19 train=0.898908 lr=1.000e-04
Fold direct Weather     H=336 F2 ep=002/19 train=0.643817 lr=1.000e-04
Fold direct Weather     H=336 F2 ep=003/19 train=0.596718 lr=1.000e-04
Fold direct Weather     H=336 F2 ep=004/19 train=0.590857 lr=9.000e-05
Fold direct Weather     H=336 F2 ep=005/19 train=0.586377 lr=8.100e-05
Fold direct Weather     H=336 F2 ep=006/19 train=0.582288 lr=7.290e-05
Fold direct Weather     H=336 F2 ep=007/19 train=0.578792 lr=6.561e-05
Fold direct Weather     H=336 F2 ep=008/19 train=0.575848 lr=5.905e-05
Fold direct Weather     H=336 F2 ep=009/19 train=0.574096 lr=5.314e-05
Fold direct Weather     H=336 F2 ep=010/19 train=0.571946 lr=4.783e-05
Fold direct Weather     H=336 F2 ep=011/19 train=0.570249 lr=4.305e-05
Fold direct Weather     H=336 F2 ep=012/19 train=0.568366 lr=3.874e-05
Fold direct Weather     H=336 F2 ep=013/19 train=0.567519 lr=3.487e-05
Fold direct Weather     H=336 F2 ep=014/19 train=0.565558 lr=3.138e-05
Fold direct Weather     H=336 F2 ep=015/19 train=0.565266 lr=2.824e-05
Fold direct Weather     H=336 F2 ep=016/19 train=0.563231 lr=2.542e-05
Fold direct Weather     H=336 F2 ep=017/19 train=0.563004 lr=2.288e-05
Fold direct Weather     H=336 F2 ep=018/19 train=0.561873 lr=2.059e-05
Fold direct Weather     H=336 F2 ep=019/19 train=0.561041 lr=1.853e-05
Building memory embedding cache: Weather_H336_F2_prefix25820_emb.npy (21, 1058, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=336 F2: prefix=25820, end=31353, anchors=1300, pairs=27300, memory/C=1058
Fold direct Weather     H=336 F3 ep=001/19 train=0.829279 lr=1.000e-04
Fold direct Weather     H=336 F3 ep=002/19 train=0.605577 lr=1.000e-04
Fold direct Weather     H=336 F3 ep=003/19 train=0.576592 lr=1.000e-04
Fold direct Weather     H=336 F3 ep=004/19 train=0.570401 lr=9.000e-05
Fold direct Weather     H=336 F3 ep=005/19 train=0.566197 lr=8.100e-05
Fold direct Weather     H=336 F3 ep=006/19 train=0.562573 lr=7.290e-05
Fold direct Weather     H=336 F3 ep=007/19 train=0.559578 lr=6.561e-05
Fold direct Weather     H=336 F3 ep=008/19 train=0.557203 lr=5.905e-05
Fold direct Weather     H=336 F3 ep=009/19 train=0.555179 lr=5.314e-05
Fold direct Weather     H=336 F3 ep=010/19 train=0.552940 lr=4.783e-05
Fold direct Weather     H=336 F3 ep=011/19 train=0.552009 lr=4.305e-05
Fold direct Weather     H=336 F3 ep=012/19 train=0.550878 lr=3.874e-05
Fold direct Weather     H=336 F3 ep=013/19 train=0.550022 lr=3.487e-05
Fold direct Weather     H=336 F3 ep=014/19 train=0.548225 lr=3.138e-05
Fold direct Weather     H=336 F3 ep=015/19 train=0.547057 lr=2.824e-05
Fold direct Weather     H=336 F3 ep=016/19 train=0.546678 lr=2.542e-05
Fold direct Weather     H=336 F3 ep=017/19 train=0.545856 lr=2.288e-05
Fold direct Weather     H=336 F3 ep=018/19 train=0.543944 lr=2.059e-05
Fold direct Weather     H=336 F3 ep=019/19 train=0.544440 lr=1.853e-05
Building memory embedding cache: Weather_H336_F3_prefix31353_emb.npy (21, 1289, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=336 F3: prefix=31353, end=36887, anchors=1300, pairs=27300, memory/C=1289
Total OOF pairs: 81900
Building memory embedding cache: Weather_H336_validation_train_memory_emb.npy (21, 1519, 64)
  encoded channel 1/21
  encoded channel 21/21
Validation Weather H=336: anchors=4935, pairs=103635, memory/C=1519
Gate Weather     H=336 ep=01 OOF=0.923543 val=0.541091 alpha=0.098 best=0.541091@1
Gate Weather     H=336 ep=02 OOF=0.922505 val=0.541210 alpha=0.095 best=0.541091@1
Gate Weather     H=336 ep=03 OOF=0.921614 val=0.541382 alpha=0.092 best=0.541091@1
Gate Weather     H=336 ep=04 OOF=0.920066 val=0.541599 alpha=0.088 best=0.541091@1
Gate Weather     H=336 ep=05 OOF=0.918347 val=0.541809 alpha=0.086 best=0.541091@1
Gate Weather     H=336 ep=06 OOF=0.918078 val=0.541918 alpha=0.085 best=0.541091@1
Gate Weather     H=336 ep=07 OOF=0.917060 val=0.541575 alpha=0.089 best=0.541091@1
Gate Weather     H=336 ep=08 OOF=0.915776 val=0.540593 alpha=0.101 best=0.540593@8
Gate Weather     H=336 ep=09 OOF=0.914617 val=0.539056 alpha=0.120 best=0.539056@9
Gate Weather     H=336 ep=10 OOF=0.913870 val=0.538081 alpha=0.131 best=0.538081@10
Gate Weather     H=336 ep=11 OOF=0.912852 val=0.537817 alpha=0.132 best=0.537817@11
Gate Weather     H=336 ep=12 OOF=0.912255 val=0.537234 alpha=0.134 best=0.537234@12
Gate Weather     H=336 ep=13 OOF=0.911466 val=0.537342 alpha=0.127 best=0.537234@12
Gate Weather     H=336 ep=14 OOF=0.911187 val=0.536912 alpha=0.127 best=0.536912@14
Gate Weather     H=336 ep=15 OOF=0.910524 val=0.536957 alpha=0.122 best=0.536912@14
Gate Weather     H=336 ep=16 OOF=0.909923 val=0.536533 alpha=0.123 best=0.536533@16
Gate Weather     H=336 ep=17 OOF=0.909334 val=0.536720 alpha=0.118 best=0.536533@16
Gate Weather     H=336 ep=18 OOF=0.908840 val=0.536486 alpha=0.118 best=0.536486@18
Gate Weather     H=336 ep=19 OOF=0.908335 val=0.536646 alpha=0.116 best=0.536486@18
Gate Weather     H=336 ep=20 OOF=0.908124 val=0.536484 alpha=0.117 best=0.536484@20
Gate Weather     H=336 ep=21 OOF=0.907665 val=0.535954 alpha=0.125 best=0.535954@21
Gate Weather     H=336 ep=22 OOF=0.907428 val=0.536194 alpha=0.122 best=0.535954@21
Gate Weather     H=336 ep=23 OOF=0.906982 val=0.536208 alpha=0.120 best=0.535954@21
Gate Weather     H=336 ep=24 OOF=0.906625 val=0.536047 alpha=0.123 best=0.535954@21
Gate Weather     H=336 ep=25 OOF=0.906180 val=0.536081 alpha=0.129 best=0.535954@21
Gate Weather     H=336 ep=26 OOF=0.906149 val=0.535843 alpha=0.128 best=0.535843@26
Gate Weather     H=336 ep=27 OOF=0.905928 val=0.536192 alpha=0.126 best=0.535843@26
Gate Weather     H=336 ep=28 OOF=0.905462 val=0.535828 alpha=0.132 best=0.535828@28
Gate Weather     H=336 ep=29 OOF=0.905392 val=0.535641 alpha=0.136 best=0.535641@29
Gate Weather     H=336 ep=30 OOF=0.905028 val=0.535824 alpha=0.129 best=0.535641@29
Gate Weather     H=336 ep=31 OOF=0.904515 val=0.535892 alpha=0.129 best=0.535641@29
Gate Weather     H=336 ep=32 OOF=0.904656 val=0.536221 alpha=0.129 best=0.535641@29
Gate Weather     H=336 ep=33 OOF=0.904176 val=0.536164 alpha=0.130 best=0.535641@29
Gate Weather     H=336 ep=34 OOF=0.904131 val=0.535954 alpha=0.134 best=0.535641@29
Gate Weather     H=336 ep=35 OOF=0.903652 val=0.535743 alpha=0.134 best=0.535641@29
Gate Weather     H=336 ep=36 OOF=0.903641 val=0.535502 alpha=0.133 best=0.535502@36
Gate Weather     H=336 ep=37 OOF=0.903286 val=0.536035 alpha=0.129 best=0.535502@36
Gate Weather     H=336 ep=38 OOF=0.903095 val=0.535950 alpha=0.130 best=0.535502@36
Gate Weather     H=336 ep=39 OOF=0.902925 val=0.536073 alpha=0.131 best=0.535502@36
Gate Weather     H=336 ep=40 OOF=0.902534 val=0.535944 alpha=0.135 best=0.535502@36
Gate Weather     H=336 ep=41 OOF=0.902453 val=0.536105 alpha=0.132 best=0.535502@36
Gate Weather     H=336 ep=42 OOF=0.902087 val=0.535652 alpha=0.134 best=0.535502@36
Gate Weather     H=336 ep=43 OOF=0.901900 val=0.535777 alpha=0.142 best=0.535502@36
Validation calibration | alpha0=0.20 | lambda=0.75 | gateEpoch=36
Building memory embedding cache: Weather_H336_test_trainval_memory_emb.npy (21, 1739, 64)
  encoded channel 1/21
  encoded channel 21/21
  test anchors 32/10204
  test anchors 3200/10204
  test anchors 6400/10204
  test anchors 9600/10204
  test anchors 10204/10204

FINAL CONDITION RESULT

   Dataset  Horizon  OfficialPatchTST_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct
0  Weather      336                0.2469            0.241303                2.267156       0.357732    0.242897         0.241966     0.20412          0.2          0.75         0.146398                 0.666667                     17.327073

   Dataset  Horizon             Comparison  MeanImprovement    CI_Low   CI_High  SignificantPositive
4  Weather      336  Direct-ShrinkAdaptive         0.005598  0.004242  0.006882                 True
5  Weather      336  Scalar-ShrinkAdaptive         0.001594  0.000842  0.002324                 True

######################################################################################################################################################
Weather | H=720 | OFFICIAL PATCHTST + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 18 reference: MSE=0.320894, MAE=0.334351, best_epoch=23
Frozen retriever best epoch: 7
Fold direct Weather     H=720 F1 ep=001/23 train=1.178288 lr=1.000e-04
Fold direct Weather     H=720 F1 ep=002/23 train=0.924276 lr=1.000e-04
Fold direct Weather     H=720 F1 ep=003/23 train=0.875571 lr=1.000e-04
Fold direct Weather     H=720 F1 ep=004/23 train=0.869307 lr=9.000e-05
Fold direct Weather     H=720 F1 ep=005/23 train=0.862674 lr=8.100e-05
Fold direct Weather     H=720 F1 ep=006/23 train=0.855441 lr=7.290e-05
Fold direct Weather     H=720 F1 ep=007/23 train=0.851120 lr=6.561e-05
Fold direct Weather     H=720 F1 ep=008/23 train=0.848193 lr=5.905e-05
Fold direct Weather     H=720 F1 ep=009/23 train=0.844732 lr=5.314e-05
Fold direct Weather     H=720 F1 ep=010/23 train=0.841811 lr=4.783e-05
Fold direct Weather     H=720 F1 ep=011/23 train=0.839473 lr=4.305e-05
Fold direct Weather     H=720 F1 ep=012/23 train=0.836678 lr=3.874e-05
Fold direct Weather     H=720 F1 ep=013/23 train=0.833140 lr=3.487e-05
Fold direct Weather     H=720 F1 ep=014/23 train=0.831238 lr=3.138e-05
Fold direct Weather     H=720 F1 ep=015/23 train=0.828111 lr=2.824e-05
Fold direct Weather     H=720 F1 ep=016/23 train=0.826487 lr=2.542e-05
Fold direct Weather     H=720 F1 ep=017/23 train=0.824739 lr=2.288e-05
Fold direct Weather     H=720 F1 ep=018/23 train=0.822580 lr=2.059e-05
Fold direct Weather     H=720 F1 ep=019/23 train=0.821141 lr=1.853e-05
Fold direct Weather     H=720 F1 ep=020/23 train=0.819373 lr=1.668e-05
Fold direct Weather     H=720 F1 ep=021/23 train=0.817942 lr=1.501e-05
Fold direct Weather     H=720 F1 ep=022/23 train=0.816449 lr=1.351e-05
Fold direct Weather     H=720 F1 ep=023/23 train=0.816124 lr=1.216e-05
Building memory embedding cache: Weather_H720_F1_prefix20287_emb.npy (21, 812, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=720 F1: prefix=20287, end=25820, anchors=1204, pairs=25284, memory/C=812
Fold direct Weather     H=720 F2 ep=001/23 train=0.952696 lr=1.000e-04
Fold direct Weather     H=720 F2 ep=002/23 train=0.727508 lr=1.000e-04
Fold direct Weather     H=720 F2 ep=003/23 train=0.691707 lr=1.000e-04
Fold direct Weather     H=720 F2 ep=004/23 train=0.686445 lr=9.000e-05
Fold direct Weather     H=720 F2 ep=005/23 train=0.680030 lr=8.100e-05
Fold direct Weather     H=720 F2 ep=006/23 train=0.676672 lr=7.290e-05
Fold direct Weather     H=720 F2 ep=007/23 train=0.673199 lr=6.561e-05
Fold direct Weather     H=720 F2 ep=008/23 train=0.670686 lr=5.905e-05
Fold direct Weather     H=720 F2 ep=009/23 train=0.668848 lr=5.314e-05
Fold direct Weather     H=720 F2 ep=010/23 train=0.666801 lr=4.783e-05
Fold direct Weather     H=720 F2 ep=011/23 train=0.665014 lr=4.305e-05
Fold direct Weather     H=720 F2 ep=012/23 train=0.662989 lr=3.874e-05
Fold direct Weather     H=720 F2 ep=013/23 train=0.661889 lr=3.487e-05
Fold direct Weather     H=720 F2 ep=014/23 train=0.661029 lr=3.138e-05
Fold direct Weather     H=720 F2 ep=015/23 train=0.659771 lr=2.824e-05
Fold direct Weather     H=720 F2 ep=016/23 train=0.658846 lr=2.542e-05
Fold direct Weather     H=720 F2 ep=017/23 train=0.658347 lr=2.288e-05
Fold direct Weather     H=720 F2 ep=018/23 train=0.657327 lr=2.059e-05
Fold direct Weather     H=720 F2 ep=019/23 train=0.656438 lr=1.853e-05
Fold direct Weather     H=720 F2 ep=020/23 train=0.656188 lr=1.668e-05
Fold direct Weather     H=720 F2 ep=021/23 train=0.655368 lr=1.501e-05
Fold direct Weather     H=720 F2 ep=022/23 train=0.654903 lr=1.351e-05
Fold direct Weather     H=720 F2 ep=023/23 train=0.654341 lr=1.216e-05
Building memory embedding cache: Weather_H720_F2_prefix25820_emb.npy (21, 1042, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=720 F2: prefix=25820, end=31353, anchors=1204, pairs=25284, memory/C=1042
Fold direct Weather     H=720 F3 ep=001/23 train=0.906691 lr=1.000e-04
Fold direct Weather     H=720 F3 ep=002/23 train=0.678410 lr=1.000e-04
Fold direct Weather     H=720 F3 ep=003/23 train=0.648394 lr=1.000e-04
Fold direct Weather     H=720 F3 ep=004/23 train=0.642753 lr=9.000e-05
Fold direct Weather     H=720 F3 ep=005/23 train=0.637420 lr=8.100e-05
Fold direct Weather     H=720 F3 ep=006/23 train=0.633399 lr=7.290e-05
Fold direct Weather     H=720 F3 ep=007/23 train=0.631161 lr=6.561e-05
Fold direct Weather     H=720 F3 ep=008/23 train=0.628507 lr=5.905e-05
Fold direct Weather     H=720 F3 ep=009/23 train=0.627074 lr=5.314e-05
Fold direct Weather     H=720 F3 ep=010/23 train=0.625085 lr=4.783e-05
Fold direct Weather     H=720 F3 ep=011/23 train=0.623059 lr=4.305e-05
Fold direct Weather     H=720 F3 ep=012/23 train=0.622107 lr=3.874e-05
Fold direct Weather     H=720 F3 ep=013/23 train=0.620966 lr=3.487e-05
Fold direct Weather     H=720 F3 ep=014/23 train=0.619515 lr=3.138e-05
Fold direct Weather     H=720 F3 ep=015/23 train=0.618318 lr=2.824e-05
Fold direct Weather     H=720 F3 ep=016/23 train=0.617755 lr=2.542e-05
Fold direct Weather     H=720 F3 ep=017/23 train=0.616247 lr=2.288e-05
Fold direct Weather     H=720 F3 ep=018/23 train=0.615754 lr=2.059e-05
Fold direct Weather     H=720 F3 ep=019/23 train=0.614788 lr=1.853e-05
Fold direct Weather     H=720 F3 ep=020/23 train=0.614145 lr=1.668e-05
Fold direct Weather     H=720 F3 ep=021/23 train=0.613619 lr=1.501e-05
Fold direct Weather     H=720 F3 ep=022/23 train=0.613416 lr=1.351e-05
Fold direct Weather     H=720 F3 ep=023/23 train=0.612635 lr=1.216e-05
Building memory embedding cache: Weather_H720_F3_prefix31353_emb.npy (21, 1273, 64)
  encoded channel 1/21
  encoded channel 21/21
OOF Weather H=720 F3: prefix=31353, end=36887, anchors=1204, pairs=25284, memory/C=1273
Total OOF pairs: 75852
Building memory embedding cache: Weather_H720_validation_train_memory_emb.npy (21, 1503, 64)
  encoded channel 1/21
  encoded channel 21/21
Validation Weather H=720: anchors=4551, pairs=95571, memory/C=1503
Gate Weather     H=720 ep=01 OOF=1.020750 val=0.646445 alpha=0.099 best=0.646445@1
Gate Weather     H=720 ep=02 OOF=1.014788 val=0.646550 alpha=0.097 best=0.646445@1
Gate Weather     H=720 ep=03 OOF=1.010831 val=0.646702 alpha=0.094 best=0.646445@1
Gate Weather     H=720 ep=04 OOF=1.021105 val=0.646869 alpha=0.092 best=0.646445@1
Gate Weather     H=720 ep=05 OOF=1.009624 val=0.646953 alpha=0.092 best=0.646445@1
Gate Weather     H=720 ep=06 OOF=1.013805 val=0.646639 alpha=0.098 best=0.646445@1
Gate Weather     H=720 ep=07 OOF=1.009206 val=0.645543 alpha=0.113 best=0.645543@7
Gate Weather     H=720 ep=08 OOF=1.015428 val=0.645225 alpha=0.135 best=0.645225@8
Gate Weather     H=720 ep=09 OOF=1.007924 val=0.645128 alpha=0.154 best=0.645128@9
Gate Weather     H=720 ep=10 OOF=1.004190 val=0.644882 alpha=0.145 best=0.644882@10
Gate Weather     H=720 ep=11 OOF=1.001836 val=0.644924 alpha=0.133 best=0.644882@10
Gate Weather     H=720 ep=12 OOF=0.995864 val=0.644519 alpha=0.132 best=0.644519@12
Gate Weather     H=720 ep=13 OOF=1.005546 val=0.644642 alpha=0.129 best=0.644519@12
Gate Weather     H=720 ep=14 OOF=1.003726 val=0.644704 alpha=0.126 best=0.644519@12
Gate Weather     H=720 ep=15 OOF=1.010387 val=0.644604 alpha=0.126 best=0.644519@12
Gate Weather     H=720 ep=16 OOF=0.995988 val=0.644523 alpha=0.123 best=0.644519@12
Gate Weather     H=720 ep=17 OOF=1.004147 val=0.644445 alpha=0.123 best=0.644445@17
Gate Weather     H=720 ep=18 OOF=0.999138 val=0.644675 alpha=0.122 best=0.644445@17
Gate Weather     H=720 ep=19 OOF=0.996512 val=0.643983 alpha=0.123 best=0.643983@19
Gate Weather     H=720 ep=20 OOF=0.992396 val=0.644160 alpha=0.119 best=0.643983@19
Gate Weather     H=720 ep=21 OOF=0.992458 val=0.643991 alpha=0.119 best=0.643983@19
Gate Weather     H=720 ep=22 OOF=0.996152 val=0.643886 alpha=0.116 best=0.643886@22
Gate Weather     H=720 ep=23 OOF=0.997157 val=0.643720 alpha=0.117 best=0.643720@23
Gate Weather     H=720 ep=24 OOF=0.991792 val=0.643633 alpha=0.114 best=0.643633@24
Gate Weather     H=720 ep=25 OOF=0.991951 val=0.643444 alpha=0.115 best=0.643444@25
Gate Weather     H=720 ep=26 OOF=1.000322 val=0.643423 alpha=0.116 best=0.643423@26
Gate Weather     H=720 ep=27 OOF=0.991046 val=0.643413 alpha=0.111 best=0.643413@27
Gate Weather     H=720 ep=28 OOF=0.996231 val=0.643038 alpha=0.118 best=0.643038@28
Gate Weather     H=720 ep=29 OOF=0.991479 val=0.642759 alpha=0.117 best=0.642759@29
Gate Weather     H=720 ep=30 OOF=0.990254 val=0.642639 alpha=0.112 best=0.642639@30
Gate Weather     H=720 ep=31 OOF=0.993649 val=0.642315 alpha=0.114 best=0.642315@31
Gate Weather     H=720 ep=32 OOF=0.996572 val=0.642186 alpha=0.115 best=0.642186@32
Gate Weather     H=720 ep=33 OOF=0.992754 val=0.641766 alpha=0.114 best=0.641766@33
Gate Weather     H=720 ep=34 OOF=0.995848 val=0.641698 alpha=0.113 best=0.641698@34
Gate Weather     H=720 ep=35 OOF=0.995347 val=0.641908 alpha=0.112 best=0.641698@34
Gate Weather     H=720 ep=36 OOF=0.990382 val=0.641556 alpha=0.113 best=0.641556@36
Gate Weather     H=720 ep=37 OOF=0.984620 val=0.641225 alpha=0.113 best=0.641225@37
Gate Weather     H=720 ep=38 OOF=0.991030 val=0.640863 alpha=0.115 best=0.640863@38
Gate Weather     H=720 ep=39 OOF=0.984772 val=0.640444 alpha=0.117 best=0.640444@39
Gate Weather     H=720 ep=40 OOF=0.997319 val=0.640514 alpha=0.113 best=0.640444@39
Gate Weather     H=720 ep=41 OOF=0.991291 val=0.639980 alpha=0.120 best=0.639980@41
Gate Weather     H=720 ep=42 OOF=0.988207 val=0.640460 alpha=0.115 best=0.639980@41
Gate Weather     H=720 ep=43 OOF=0.981858 val=0.640135 alpha=0.115 best=0.639980@41
Gate Weather     H=720 ep=44 OOF=0.982344 val=0.640019 alpha=0.118 best=0.639980@41
Gate Weather     H=720 ep=45 OOF=0.988658 val=0.639708 alpha=0.116 best=0.639708@45
Gate Weather     H=720 ep=46 OOF=0.988932 val=0.639620 alpha=0.120 best=0.639620@46
Gate Weather     H=720 ep=47 OOF=0.990150 val=0.639535 alpha=0.119 best=0.639535@47
Gate Weather     H=720 ep=48 OOF=0.986067 val=0.639671 alpha=0.122 best=0.639535@47
Gate Weather     H=720 ep=49 OOF=0.983631 val=0.638908 alpha=0.123 best=0.638908@49
Gate Weather     H=720 ep=50 OOF=0.981567 val=0.639275 alpha=0.123 best=0.638908@49
Validation calibration | alpha0=0.10 | lambda=1.00 | gateEpoch=49
Building memory embedding cache: Weather_H720_test_trainval_memory_emb.npy (21, 1723, 64)
  encoded channel 1/21
  encoded channel 21/21
  test anchors 32/9820
  test anchors 3200/9820
  test anchors 6400/9820
  test anchors 9600/9820
  test anchors 9820/9820

FINAL CONDITION RESULT

   Dataset  Horizon  OfficialPatchTST_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct
0  Weather      720              0.320894            0.314066                2.128003       0.438721    0.315212         0.314066    0.265141          0.1           1.0         0.111809                 0.714286                     17.374355

   Dataset  Horizon             Comparison  MeanImprovement    CI_Low   CI_High  SignificantPositive
6  Weather      720  Direct-ShrinkAdaptive         0.006829  0.005369  0.008341                 True
7  Weather      720  Scalar-ShrinkAdaptive         0.001146  0.000210  0.002089                 True

######################################################################################################################################################
Electricity | H=96 | OFFICIAL PATCHTST + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 18 reference: MSE=0.129977, MAE=0.222527, best_epoch=97
Frozen retriever best epoch: 7
Fold direct Electricity H= 96 F1 ep=001/97 train=0.500946 lr=4.591e-06
Fold direct Electricity H= 96 F1 ep=002/97 train=0.287236 lr=6.350e-06
Fold direct Electricity H= 96 F1 ep=003/97 train=0.239492 lr=9.233e-06
Fold direct Electricity H= 96 F1 ep=004/97 train=0.207848 lr=1.317e-05
Fold direct Electricity H= 96 F1 ep=005/97 train=0.188400 lr=1.806e-05
Fold direct Electricity H= 96 F1 ep=006/97 train=0.177077 lr=2.379e-05
Fold direct Electricity H= 96 F1 ep=007/97 train=0.170641 lr=3.022e-05
Fold direct Electricity H= 96 F1 ep=008/97 train=0.165806 lr=3.718e-05
Fold direct Electricity H= 96 F1 ep=009/97 train=0.162590 lr=4.450e-05
Fold direct Electricity H= 96 F1 ep=010/97 train=0.159786 lr=5.201e-05
Fold direct Electricity H= 96 F1 ep=011/97 train=0.157792 lr=5.952e-05
Fold direct Electricity H= 96 F1 ep=012/97 train=0.155799 lr=6.685e-05
Fold direct Electricity H= 96 F1 ep=013/97 train=0.153918 lr=7.381e-05
Fold direct Electricity H= 96 F1 ep=014/97 train=0.152113 lr=8.023e-05
Fold direct Electricity H= 96 F1 ep=015/97 train=0.150568 lr=8.595e-05
Fold direct Electricity H= 96 F1 ep=016/97 train=0.149276 lr=9.084e-05
Fold direct Electricity H= 96 F1 ep=017/97 train=0.148038 lr=9.478e-05
Fold direct Electricity H= 96 F1 ep=018/97 train=0.146955 lr=9.766e-05
Fold direct Electricity H= 96 F1 ep=019/97 train=0.145803 lr=9.941e-05
Fold direct Electricity H= 96 F1 ep=020/97 train=0.145085 lr=1.000e-04
Fold direct Electricity H= 96 F1 ep=021/97 train=0.144298 lr=9.996e-05
Fold direct Electricity H= 96 F1 ep=022/97 train=0.143280 lr=9.985e-05
Fold direct Electricity H= 96 F1 ep=023/97 train=0.142802 lr=9.965e-05
Fold direct Electricity H= 96 F1 ep=024/97 train=0.141820 lr=9.938e-05
Fold direct Electricity H= 96 F1 ep=025/97 train=0.141375 lr=9.904e-05
Fold direct Electricity H= 96 F1 ep=026/97 train=0.140874 lr=9.862e-05
Fold direct Electricity H= 96 F1 ep=027/97 train=0.140268 lr=9.812e-05
Fold direct Electricity H= 96 F1 ep=028/97 train=0.139955 lr=9.755e-05
Fold direct Electricity H= 96 F1 ep=029/97 train=0.139518 lr=9.691e-05
Fold direct Electricity H= 96 F1 ep=030/97 train=0.138917 lr=9.619e-05
Fold direct Electricity H= 96 F1 ep=031/97 train=0.138543 lr=9.540e-05
Fold direct Electricity H= 96 F1 ep=032/97 train=0.137833 lr=9.455e-05
Fold direct Electricity H= 96 F1 ep=033/97 train=0.137470 lr=9.362e-05
Fold direct Electricity H= 96 F1 ep=034/97 train=0.137432 lr=9.263e-05
Fold direct Electricity H= 96 F1 ep=035/97 train=0.136841 lr=9.157e-05
Fold direct Electricity H= 96 F1 ep=036/97 train=0.136638 lr=9.045e-05
Fold direct Electricity H= 96 F1 ep=037/97 train=0.136202 lr=8.926e-05
Fold direct Electricity H= 96 F1 ep=038/97 train=0.135691 lr=8.802e-05
Fold direct Electricity H= 96 F1 ep=039/97 train=0.135319 lr=8.671e-05
Fold direct Electricity H= 96 F1 ep=040/97 train=0.135047 lr=8.535e-05
Fold direct Electricity H= 96 F1 ep=041/97 train=0.134674 lr=8.394e-05
Fold direct Electricity H= 96 F1 ep=042/97 train=0.134440 lr=8.247e-05
Fold direct Electricity H= 96 F1 ep=043/97 train=0.133995 lr=8.095e-05
Fold direct Electricity H= 96 F1 ep=044/97 train=0.133837 lr=7.938e-05
Fold direct Electricity H= 96 F1 ep=045/97 train=0.133398 lr=7.777e-05
Fold direct Electricity H= 96 F1 ep=046/97 train=0.133230 lr=7.612e-05
Fold direct Electricity H= 96 F1 ep=047/97 train=0.132957 lr=7.443e-05
Fold direct Electricity H= 96 F1 ep=048/97 train=0.132751 lr=7.269e-05
Fold direct Electricity H= 96 F1 ep=049/97 train=0.132509 lr=7.093e-05
Fold direct Electricity H= 96 F1 ep=050/97 train=0.132256 lr=6.913e-05
Fold direct Electricity H= 96 F1 ep=051/97 train=0.131994 lr=6.730e-05
Fold direct Electricity H= 96 F1 ep=052/97 train=0.131729 lr=6.544e-05
Fold direct Electricity H= 96 F1 ep=053/97 train=0.131589 lr=6.357e-05
Fold direct Electricity H= 96 F1 ep=054/97 train=0.131406 lr=6.167e-05
Fold direct Electricity H= 96 F1 ep=055/97 train=0.131300 lr=5.975e-05
Fold direct Electricity H= 96 F1 ep=056/97 train=0.131010 lr=5.782e-05
Fold direct Electricity H= 96 F1 ep=057/97 train=0.130877 lr=5.587e-05
Fold direct Electricity H= 96 F1 ep=058/97 train=0.130714 lr=5.392e-05
Fold direct Electricity H= 96 F1 ep=059/97 train=0.130420 lr=5.196e-05
Fold direct Electricity H= 96 F1 ep=060/97 train=0.130417 lr=4.999e-05
Fold direct Electricity H= 96 F1 ep=061/97 train=0.130134 lr=4.803e-05
Fold direct Electricity H= 96 F1 ep=062/97 train=0.130031 lr=4.607e-05
Fold direct Electricity H= 96 F1 ep=063/97 train=0.129988 lr=4.412e-05
Fold direct Electricity H= 96 F1 ep=064/97 train=0.129833 lr=4.217e-05
Fold direct Electricity H= 96 F1 ep=065/97 train=0.129710 lr=4.024e-05
Fold direct Electricity H= 96 F1 ep=066/97 train=0.129517 lr=3.832e-05
Fold direct Electricity H= 96 F1 ep=067/97 train=0.129487 lr=3.642e-05
Fold direct Electricity H= 96 F1 ep=068/97 train=0.129185 lr=3.454e-05
Fold direct Electricity H= 96 F1 ep=069/97 train=0.129183 lr=3.269e-05
Fold direct Electricity H= 96 F1 ep=070/97 train=0.129028 lr=3.086e-05
Fold direct Electricity H= 96 F1 ep=071/97 train=0.128893 lr=2.906e-05
Fold direct Electricity H= 96 F1 ep=072/97 train=0.128880 lr=2.729e-05
Fold direct Electricity H= 96 F1 ep=073/97 train=0.128714 lr=2.556e-05
Fold direct Electricity H= 96 F1 ep=074/97 train=0.128653 lr=2.387e-05
Fold direct Electricity H= 96 F1 ep=075/97 train=0.128464 lr=2.222e-05
Fold direct Electricity H= 96 F1 ep=076/97 train=0.128404 lr=2.061e-05
Fold direct Electricity H= 96 F1 ep=077/97 train=0.128422 lr=1.904e-05
Fold direct Electricity H= 96 F1 ep=078/97 train=0.128333 lr=1.752e-05
Fold direct Electricity H= 96 F1 ep=079/97 train=0.128210 lr=1.606e-05
Fold direct Electricity H= 96 F1 ep=080/97 train=0.128174 lr=1.464e-05
Fold direct Electricity H= 96 F1 ep=081/97 train=0.128128 lr=1.328e-05
Fold direct Electricity H= 96 F1 ep=082/97 train=0.127964 lr=1.198e-05
Fold direct Electricity H= 96 F1 ep=083/97 train=0.128004 lr=1.073e-05
Fold direct Electricity H= 96 F1 ep=084/97 train=0.127874 lr=9.546e-06
Fold direct Electricity H= 96 F1 ep=085/97 train=0.127867 lr=8.423e-06
Fold direct Electricity H= 96 F1 ep=086/97 train=0.127791 lr=7.365e-06
Fold direct Electricity H= 96 F1 ep=087/97 train=0.127697 lr=6.372e-06
Fold direct Electricity H= 96 F1 ep=088/97 train=0.127699 lr=5.447e-06
Fold direct Electricity H= 96 F1 ep=089/97 train=0.127723 lr=4.591e-06
Fold direct Electricity H= 96 F1 ep=090/97 train=0.127602 lr=3.804e-06
Fold direct Electricity H= 96 F1 ep=091/97 train=0.127632 lr=3.089e-06
Fold direct Electricity H= 96 F1 ep=092/97 train=0.127591 lr=2.446e-06
Fold direct Electricity H= 96 F1 ep=093/97 train=0.127543 lr=1.876e-06
Fold direct Electricity H= 96 F1 ep=094/97 train=0.127545 lr=1.380e-06
Fold direct Electricity H= 96 F1 ep=095/97 train=0.127551 lr=9.599e-07
Fold direct Electricity H= 96 F1 ep=096/97 train=0.127496 lr=6.150e-07
Fold direct Electricity H= 96 F1 ep=097/97 train=0.127439 lr=3.462e-07
Building memory embedding cache: Electricity_H96_F1_prefix10126_emb.npy (321, 414, 64)
  encoded channel 1/321
  encoded channel 50/321
  encoded channel 100/321
  encoded channel 150/321
  encoded channel 200/321
  encoded channel 250/321
  encoded channel 300/321
  encoded channel 321/321
OOF Electricity H=96 F1: prefix=10126, end=12888, anchors=667, pairs=214107, memory/C=414
Fold direct Electricity H= 96 F2 ep=001/97 train=0.453553 lr=4.591e-06
Fold direct Electricity H= 96 F2 ep=002/97 train=0.266739 lr=6.350e-06
Fold direct Electricity H= 96 F2 ep=003/97 train=0.220512 lr=9.233e-06
Fold direct Electricity H= 96 F2 ep=004/97 train=0.192447 lr=1.317e-05
Fold direct Electricity H= 96 F2 ep=005/97 train=0.177285 lr=1.806e-05
Fold direct Electricity H= 96 F2 ep=006/97 train=0.168810 lr=2.379e-05
Fold direct Electricity H= 96 F2 ep=007/97 train=0.163203 lr=3.021e-05
Fold direct Electricity H= 96 F2 ep=008/97 train=0.159135 lr=3.717e-05
Fold direct Electricity H= 96 F2 ep=009/97 train=0.156081 lr=4.450e-05
Fold direct Electricity H= 96 F2 ep=010/97 train=0.153576 lr=5.201e-05
Fold direct Electricity H= 96 F2 ep=011/97 train=0.151394 lr=5.952e-05
Fold direct Electricity H= 96 F2 ep=012/97 train=0.149304 lr=6.684e-05
Fold direct Electricity H= 96 F2 ep=013/97 train=0.147547 lr=7.380e-05
Fold direct Electricity H= 96 F2 ep=014/97 train=0.145951 lr=8.022e-05
Fold direct Electricity H= 96 F2 ep=015/97 train=0.144621 lr=8.595e-05
Fold direct Electricity H= 96 F2 ep=016/97 train=0.143567 lr=9.084e-05
Fold direct Electricity H= 96 F2 ep=017/97 train=0.142373 lr=9.478e-05
Fold direct Electricity H= 96 F2 ep=018/97 train=0.141633 lr=9.766e-05
Fold direct Electricity H= 96 F2 ep=019/97 train=0.140507 lr=9.941e-05
Fold direct Electricity H= 96 F2 ep=020/97 train=0.139857 lr=1.000e-04
Fold direct Electricity H= 96 F2 ep=021/97 train=0.139046 lr=9.996e-05
Fold direct Electricity H= 96 F2 ep=022/97 train=0.138346 lr=9.985e-05
Fold direct Electricity H= 96 F2 ep=023/97 train=0.137676 lr=9.965e-05
Fold direct Electricity H= 96 F2 ep=024/97 train=0.137250 lr=9.938e-05
Fold direct Electricity H= 96 F2 ep=025/97 train=0.136629 lr=9.904e-05
Fold direct Electricity H= 96 F2 ep=026/97 train=0.136237 lr=9.862e-05
Fold direct Electricity H= 96 F2 ep=027/97 train=0.135870 lr=9.812e-05
Fold direct Electricity H= 96 F2 ep=028/97 train=0.135338 lr=9.755e-05
Fold direct Electricity H= 96 F2 ep=029/97 train=0.134991 lr=9.691e-05
Fold direct Electricity H= 96 F2 ep=030/97 train=0.134461 lr=9.619e-05
Fold direct Electricity H= 96 F2 ep=031/97 train=0.134076 lr=9.541e-05
Fold direct Electricity H= 96 F2 ep=032/97 train=0.133775 lr=9.455e-05
Fold direct Electricity H= 96 F2 ep=033/97 train=0.133456 lr=9.362e-05
Fold direct Electricity H= 96 F2 ep=034/97 train=0.133015 lr=9.263e-05
Fold direct Electricity H= 96 F2 ep=035/97 train=0.132762 lr=9.157e-05
Fold direct Electricity H= 96 F2 ep=036/97 train=0.132428 lr=9.045e-05
Fold direct Electricity H= 96 F2 ep=037/97 train=0.132102 lr=8.926e-05
Fold direct Electricity H= 96 F2 ep=038/97 train=0.131706 lr=8.802e-05
Fold direct Electricity H= 96 F2 ep=039/97 train=0.131415 lr=8.671e-05
Fold direct Electricity H= 96 F2 ep=040/97 train=0.131124 lr=8.535e-05
Fold direct Electricity H= 96 F2 ep=041/97 train=0.130795 lr=8.394e-05
Fold direct Electricity H= 96 F2 ep=042/97 train=0.130651 lr=8.247e-05
Fold direct Electricity H= 96 F2 ep=043/97 train=0.130229 lr=8.095e-05
Fold direct Electricity H= 96 F2 ep=044/97 train=0.130040 lr=7.939e-05
Fold direct Electricity H= 96 F2 ep=045/97 train=0.129908 lr=7.777e-05
Fold direct Electricity H= 96 F2 ep=046/97 train=0.129491 lr=7.612e-05
Fold direct Electricity H= 96 F2 ep=047/97 train=0.129406 lr=7.443e-05
Fold direct Electricity H= 96 F2 ep=048/97 train=0.129166 lr=7.270e-05
Fold direct Electricity H= 96 F2 ep=049/97 train=0.128863 lr=7.093e-05
Fold direct Electricity H= 96 F2 ep=050/97 train=0.128771 lr=6.913e-05
Fold direct Electricity H= 96 F2 ep=051/97 train=0.128465 lr=6.730e-05
Fold direct Electricity H= 96 F2 ep=052/97 train=0.128329 lr=6.545e-05
Fold direct Electricity H= 96 F2 ep=053/97 train=0.128092 lr=6.357e-05
Fold direct Electricity H= 96 F2 ep=054/97 train=0.127903 lr=6.167e-05
Fold direct Electricity H= 96 F2 ep=055/97 train=0.127693 lr=5.975e-05
Fold direct Electricity H= 96 F2 ep=056/97 train=0.127553 lr=5.782e-05
Fold direct Electricity H= 96 F2 ep=057/97 train=0.127434 lr=5.587e-05
Fold direct Electricity H= 96 F2 ep=058/97 train=0.127232 lr=5.392e-05
Fold direct Electricity H= 96 F2 ep=059/97 train=0.127109 lr=5.196e-05
Fold direct Electricity H= 96 F2 ep=060/97 train=0.126949 lr=5.000e-05
Fold direct Electricity H= 96 F2 ep=061/97 train=0.126701 lr=4.803e-05
Fold direct Electricity H= 96 F2 ep=062/97 train=0.126574 lr=4.607e-05
Fold direct Electricity H= 96 F2 ep=063/97 train=0.126539 lr=4.412e-05
Fold direct Electricity H= 96 F2 ep=064/97 train=0.126447 lr=4.217e-05
Fold direct Electricity H= 96 F2 ep=065/97 train=0.126314 lr=4.024e-05
Fold direct Electricity H= 96 F2 ep=066/97 train=0.126112 lr=3.832e-05
Fold direct Electricity H= 96 F2 ep=067/97 train=0.125990 lr=3.642e-05
Fold direct Electricity H= 96 F2 ep=068/97 train=0.125960 lr=3.454e-05
Fold direct Electricity H= 96 F2 ep=069/97 train=0.125833 lr=3.269e-05
Fold direct Electricity H= 96 F2 ep=070/97 train=0.125740 lr=3.086e-05
Fold direct Electricity H= 96 F2 ep=071/97 train=0.125616 lr=2.906e-05
Fold direct Electricity H= 96 F2 ep=072/97 train=0.125549 lr=2.730e-05
Fold direct Electricity H= 96 F2 ep=073/97 train=0.125403 lr=2.556e-05
Fold direct Electricity H= 96 F2 ep=074/97 train=0.125355 lr=2.387e-05
Fold direct Electricity H= 96 F2 ep=075/97 train=0.125263 lr=2.222e-05
Fold direct Electricity H= 96 F2 ep=076/97 train=0.125222 lr=2.061e-05
Fold direct Electricity H= 96 F2 ep=077/97 train=0.125114 lr=1.904e-05
Fold direct Electricity H= 96 F2 ep=078/97 train=0.125048 lr=1.752e-05
Fold direct Electricity H= 96 F2 ep=079/97 train=0.124935 lr=1.606e-05
Fold direct Electricity H= 96 F2 ep=080/97 train=0.124901 lr=1.464e-05
Fold direct Electricity H= 96 F2 ep=081/97 train=0.124877 lr=1.328e-05
Fold direct Electricity H= 96 F2 ep=082/97 train=0.124788 lr=1.198e-05
Fold direct Electricity H= 96 F2 ep=083/97 train=0.124756 lr=1.073e-05
Fold direct Electricity H= 96 F2 ep=084/97 train=0.124671 lr=9.547e-06
Fold direct Electricity H= 96 F2 ep=085/97 train=0.124660 lr=8.424e-06
Fold direct Electricity H= 96 F2 ep=086/97 train=0.124590 lr=7.366e-06
Fold direct Electricity H= 96 F2 ep=087/97 train=0.124548 lr=6.373e-06
Fold direct Electricity H= 96 F2 ep=088/97 train=0.124553 lr=5.448e-06
Fold direct Electricity H= 96 F2 ep=089/97 train=0.124521 lr=4.591e-06
Fold direct Electricity H= 96 F2 ep=090/97 train=0.124475 lr=3.804e-06
Fold direct Electricity H= 96 F2 ep=091/97 train=0.124418 lr=3.089e-06
Fold direct Electricity H= 96 F2 ep=092/97 train=0.124396 lr=2.446e-06
Fold direct Electricity H= 96 F2 ep=093/97 train=0.124392 lr=1.876e-06
Fold direct Electricity H= 96 F2 ep=094/97 train=0.124412 lr=1.381e-06
Fold direct Electricity H= 96 F2 ep=095/97 train=0.124335 lr=9.601e-07
Fold direct Electricity H= 96 F2 ep=096/97 train=0.124352 lr=6.152e-07
Fold direct Electricity H= 96 F2 ep=097/97 train=0.124345 lr=3.464e-07
Building memory embedding cache: Electricity_H96_F2_prefix12888_emb.npy (321, 530, 64)
  encoded channel 1/321
  encoded channel 50/321
  encoded channel 100/321
  encoded channel 150/321
  encoded channel 200/321
  encoded channel 250/321
  encoded channel 300/321
  encoded channel 321/321
OOF Electricity H=96 F2: prefix=12888, end=15650, anchors=667, pairs=214107, memory/C=530
Fold direct Electricity H= 96 F3 ep=001/97 train=0.430834 lr=4.591e-06
Fold direct Electricity H= 96 F3 ep=002/97 train=0.250552 lr=6.350e-06
Fold direct Electricity H= 96 F3 ep=003/97 train=0.208912 lr=9.233e-06
Fold direct Electricity H= 96 F3 ep=004/97 train=0.186059 lr=1.317e-05
Fold direct Electricity H= 96 F3 ep=005/97 train=0.174104 lr=1.806e-05
Fold direct Electricity H= 96 F3 ep=006/97 train=0.167002 lr=2.379e-05
Fold direct Electricity H= 96 F3 ep=007/97 train=0.162114 lr=3.021e-05
Fold direct Electricity H= 96 F3 ep=008/97 train=0.158518 lr=3.717e-05
Fold direct Electricity H= 96 F3 ep=009/97 train=0.155526 lr=4.450e-05
Fold direct Electricity H= 96 F3 ep=010/97 train=0.153144 lr=5.201e-05
Fold direct Electricity H= 96 F3 ep=011/97 train=0.150774 lr=5.952e-05
Fold direct Electricity H= 96 F3 ep=012/97 train=0.148672 lr=6.684e-05
Fold direct Electricity H= 96 F3 ep=013/97 train=0.147236 lr=7.380e-05
Fold direct Electricity H= 96 F3 ep=014/97 train=0.145881 lr=8.022e-05
Fold direct Electricity H= 96 F3 ep=015/97 train=0.144482 lr=8.595e-05
Fold direct Electricity H= 96 F3 ep=016/97 train=0.143276 lr=9.084e-05
Fold direct Electricity H= 96 F3 ep=017/97 train=0.142347 lr=9.477e-05
Fold direct Electricity H= 96 F3 ep=018/97 train=0.141484 lr=9.766e-05
Fold direct Electricity H= 96 F3 ep=019/97 train=0.140837 lr=9.941e-05
Fold direct Electricity H= 96 F3 ep=020/97 train=0.139836 lr=1.000e-04
Fold direct Electricity H= 96 F3 ep=021/97 train=0.139341 lr=9.996e-05
Fold direct Electricity H= 96 F3 ep=022/97 train=0.138716 lr=9.985e-05
Fold direct Electricity H= 96 F3 ep=023/97 train=0.138045 lr=9.965e-05
Fold direct Electricity H= 96 F3 ep=024/97 train=0.137639 lr=9.938e-05
Fold direct Electricity H= 96 F3 ep=025/97 train=0.137223 lr=9.904e-05
Fold direct Electricity H= 96 F3 ep=026/97 train=0.136504 lr=9.862e-05
Fold direct Electricity H= 96 F3 ep=027/97 train=0.136238 lr=9.812e-05
Fold direct Electricity H= 96 F3 ep=028/97 train=0.135771 lr=9.755e-05
Fold direct Electricity H= 96 F3 ep=029/97 train=0.135376 lr=9.691e-05
Fold direct Electricity H= 96 F3 ep=030/97 train=0.135042 lr=9.619e-05
Fold direct Electricity H= 96 F3 ep=031/97 train=0.134719 lr=9.541e-05
Fold direct Electricity H= 96 F3 ep=032/97 train=0.134410 lr=9.455e-05
Fold direct Electricity H= 96 F3 ep=033/97 train=0.134111 lr=9.362e-05
Fold direct Electricity H= 96 F3 ep=034/97 train=0.133669 lr=9.263e-05
Fold direct Electricity H= 96 F3 ep=035/97 train=0.133439 lr=9.157e-05
Fold direct Electricity H= 96 F3 ep=036/97 train=0.133082 lr=9.045e-05
Fold direct Electricity H= 96 F3 ep=037/97 train=0.132806 lr=8.926e-05
Fold direct Electricity H= 96 F3 ep=038/97 train=0.132468 lr=8.802e-05
Fold direct Electricity H= 96 F3 ep=039/97 train=0.132291 lr=8.671e-05
Fold direct Electricity H= 96 F3 ep=040/97 train=0.131981 lr=8.535e-05
Fold direct Electricity H= 96 F3 ep=041/97 train=0.131694 lr=8.394e-05
Fold direct Electricity H= 96 F3 ep=042/97 train=0.131487 lr=8.247e-05
Fold direct Electricity H= 96 F3 ep=043/97 train=0.131160 lr=8.095e-05
Fold direct Electricity H= 96 F3 ep=044/97 train=0.130982 lr=7.939e-05
Fold direct Electricity H= 96 F3 ep=045/97 train=0.130781 lr=7.778e-05
Fold direct Electricity H= 96 F3 ep=046/97 train=0.130496 lr=7.612e-05
Fold direct Electricity H= 96 F3 ep=047/97 train=0.130222 lr=7.443e-05
Fold direct Electricity H= 96 F3 ep=048/97 train=0.130177 lr=7.270e-05
Fold direct Electricity H= 96 F3 ep=049/97 train=0.129951 lr=7.093e-05
Fold direct Electricity H= 96 F3 ep=050/97 train=0.129650 lr=6.913e-05
Fold direct Electricity H= 96 F3 ep=051/97 train=0.129588 lr=6.730e-05
Fold direct Electricity H= 96 F3 ep=052/97 train=0.129349 lr=6.545e-05
Fold direct Electricity H= 96 F3 ep=053/97 train=0.129084 lr=6.357e-05
Fold direct Electricity H= 96 F3 ep=054/97 train=0.128984 lr=6.167e-05
Fold direct Electricity H= 96 F3 ep=055/97 train=0.128803 lr=5.975e-05
Fold direct Electricity H= 96 F3 ep=056/97 train=0.128629 lr=5.782e-05
Fold direct Electricity H= 96 F3 ep=057/97 train=0.128604 lr=5.587e-05
Fold direct Electricity H= 96 F3 ep=058/97 train=0.128386 lr=5.392e-05
Fold direct Electricity H= 96 F3 ep=059/97 train=0.128225 lr=5.196e-05
Fold direct Electricity H= 96 F3 ep=060/97 train=0.128035 lr=5.000e-05
Fold direct Electricity H= 96 F3 ep=061/97 train=0.127939 lr=4.803e-05
Fold direct Electricity H= 96 F3 ep=062/97 train=0.127795 lr=4.607e-05
Fold direct Electricity H= 96 F3 ep=063/97 train=0.127681 lr=4.412e-05
Fold direct Electricity H= 96 F3 ep=064/97 train=0.127558 lr=4.217e-05
Fold direct Electricity H= 96 F3 ep=065/97 train=0.127405 lr=4.024e-05
Fold direct Electricity H= 96 F3 ep=066/97 train=0.127377 lr=3.832e-05
Fold direct Electricity H= 96 F3 ep=067/97 train=0.127152 lr=3.642e-05
Fold direct Electricity H= 96 F3 ep=068/97 train=0.127054 lr=3.455e-05
Fold direct Electricity H= 96 F3 ep=069/97 train=0.127026 lr=3.269e-05
Fold direct Electricity H= 96 F3 ep=070/97 train=0.126941 lr=3.086e-05

       Dataset  Horizon  OfficialPatchTST_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct
0  Electricity       96              0.129977            0.129218                0.584101       1.839673    0.129977         0.129218    0.119747          0.0           1.0         0.020581                 0.417445                      7.870349

       Dataset  Horizon             Comparison  MeanImprovement    CI_Low   CI_High  SignificantPositive
8  Electricity       96  Direct-ShrinkAdaptive         0.000759  0.000457  0.001120                 True
9  Electricity       96  Scalar-ShrinkAdaptive         0.000759  0.000463  0.001113                 True

######################################################################################################################################################
Electricity | H=192 | OFFICIAL PATCHTST + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 18 reference: MSE=0.149116, MAE=0.242038, best_epoch=48
Frozen retriever best epoch: 16
Fold direct Electricity H=192 F1 ep=001/48 train=0.533017 lr=4.591e-06
Fold direct Electricity H=192 F1 ep=002/48 train=0.298756 lr=6.350e-06
Fold direct Electricity H=192 F1 ep=003/48 train=0.251623 lr=9.233e-06
Fold direct Electricity H=192 F1 ep=004/48 train=0.220620 lr=1.317e-05
Fold direct Electricity H=192 F1 ep=005/48 train=0.201749 lr=1.806e-05
Fold direct Electricity H=192 F1 ep=006/48 train=0.191237 lr=2.379e-05
Fold direct Electricity H=192 F1 ep=007/48 train=0.184810 lr=3.022e-05
Fold direct Electricity H=192 F1 ep=008/48 train=0.180409 lr=3.718e-05
Fold direct Electricity H=192 F1 ep=009/48 train=0.177101 lr=4.450e-05
Fold direct Electricity H=192 F1 ep=010/48 train=0.174599 lr=5.201e-05
Fold direct Electricity H=192 F1 ep=011/48 train=0.172063 lr=5.952e-05
Fold direct Electricity H=192 F1 ep=012/48 train=0.170448 lr=6.685e-05
Fold direct Electricity H=192 F1 ep=013/48 train=0.168781 lr=7.381e-05
Fold direct Electricity H=192 F1 ep=014/48 train=0.167313 lr=8.023e-05
Fold direct Electricity H=192 F1 ep=015/48 train=0.165634 lr=8.595e-05
Fold direct Electricity H=192 F1 ep=016/48 train=0.164389 lr=9.084e-05
Fold direct Electricity H=192 F1 ep=017/48 train=0.163211 lr=9.478e-05
Fold direct Electricity H=192 F1 ep=018/48 train=0.162093 lr=9.766e-05
Fold direct Electricity H=192 F1 ep=019/48 train=0.161333 lr=9.941e-05
Fold direct Electricity H=192 F1 ep=020/48 train=0.160090 lr=1.000e-04
Fold direct Electricity H=192 F1 ep=021/48 train=0.159344 lr=9.996e-05
Fold direct Electricity H=192 F1 ep=022/48 train=0.158831 lr=9.985e-05
Fold direct Electricity H=192 F1 ep=023/48 train=0.157825 lr=9.965e-05
Fold direct Electricity H=192 F1 ep=024/48 train=0.157391 lr=9.938e-05
Fold direct Electricity H=192 F1 ep=025/48 train=0.156731 lr=9.904e-05
Fold direct Electricity H=192 F1 ep=026/48 train=0.156210 lr=9.862e-05
Fold direct Electricity H=192 F1 ep=027/48 train=0.155403 lr=9.812e-05
Fold direct Electricity H=192 F1 ep=028/48 train=0.155188 lr=9.755e-05
Fold direct Electricity H=192 F1 ep=029/48 train=0.154471 lr=9.691e-05
Fold direct Electricity H=192 F1 ep=030/48 train=0.154115 lr=9.619e-05
Fold direct Electricity H=192 F1 ep=031/48 train=0.153674 lr=9.540e-05
Fold direct Electricity H=192 F1 ep=032/48 train=0.153306 lr=9.455e-05
Fold direct Electricity H=192 F1 ep=033/48 train=0.152841 lr=9.362e-05
Fold direct Electricity H=192 F1 ep=034/48 train=0.152364 lr=9.263e-05
Fold direct Electricity H=192 F1 ep=035/48 train=0.151996 lr=9.157e-05
Fold direct Electricity H=192 F1 ep=036/48 train=0.151608 lr=9.045e-05
Fold direct Electricity H=192 F1 ep=037/48 train=0.151265 lr=8.926e-05
Fold direct Electricity H=192 F1 ep=038/48 train=0.151029 lr=8.802e-05
Fold direct Electricity H=192 F1 ep=039/48 train=0.150447 lr=8.671e-05
Fold direct Electricity H=192 F1 ep=040/48 train=0.150391 lr=8.535e-05
Fold direct Electricity H=192 F1 ep=041/48 train=0.149877 lr=8.394e-05
Fold direct Electricity H=192 F1 ep=042/48 train=0.149618 lr=8.247e-05
Fold direct Electricity H=192 F1 ep=043/48 train=0.149341 lr=8.095e-05
Fold direct Electricity H=192 F1 ep=044/48 train=0.149110 lr=7.938e-05
Fold direct Electricity H=192 F1 ep=045/48 train=0.148813 lr=7.777e-05
Fold direct Electricity H=192 F1 ep=046/48 train=0.148562 lr=7.612e-05
Fold direct Electricity H=192 F1 ep=047/48 train=0.148314 lr=7.443e-05
Fold direct Electricity H=192 F1 ep=048/48 train=0.147889 lr=7.269e-05
Building memory embedding cache: Electricity_H192_F1_prefix10126_emb.npy (321, 410, 64)
  encoded channel 1/321
  encoded channel 50/321
  encoded channel 100/321
  encoded channel 150/321
  encoded channel 200/321
  encoded channel 250/321
  encoded channel 300/321
  encoded channel 321/321
OOF Electricity H=192 F1: prefix=10126, end=12888, anchors=643, pairs=206403, memory/C=410
Fold direct Electricity H=192 F2 ep=001/48 train=0.460963 lr=4.591e-06
Fold direct Electricity H=192 F2 ep=002/48 train=0.274806 lr=6.350e-06
Fold direct Electricity H=192 F2 ep=003/48 train=0.229657 lr=9.233e-06
Fold direct Electricity H=192 F2 ep=004/48 train=0.203426 lr=1.317e-05
Fold direct Electricity H=192 F2 ep=005/48 train=0.189577 lr=1.806e-05
Fold direct Electricity H=192 F2 ep=006/48 train=0.181628 lr=2.379e-05
Fold direct Electricity H=192 F2 ep=007/48 train=0.176464 lr=3.021e-05
Fold direct Electricity H=192 F2 ep=008/48 train=0.172668 lr=3.717e-05
Fold direct Electricity H=192 F2 ep=009/48 train=0.169908 lr=4.450e-05
Fold direct Electricity H=192 F2 ep=010/48 train=0.167605 lr=5.201e-05
Fold direct Electricity H=192 F2 ep=011/48 train=0.165694 lr=5.952e-05
Fold direct Electricity H=192 F2 ep=012/48 train=0.163686 lr=6.684e-05
Fold direct Electricity H=192 F2 ep=013/48 train=0.161982 lr=7.380e-05
Fold direct Electricity H=192 F2 ep=014/48 train=0.160626 lr=8.022e-05
Fold direct Electricity H=192 F2 ep=015/48 train=0.159149 lr=8.595e-05
Fold direct Electricity H=192 F2 ep=016/48 train=0.157929 lr=9.084e-05
Fold direct Electricity H=192 F2 ep=017/48 train=0.156946 lr=9.478e-05
Fold direct Electricity H=192 F2 ep=018/48 train=0.155873 lr=9.766e-05
Fold direct Electricity H=192 F2 ep=019/48 train=0.155115 lr=9.941e-05
Fold direct Electricity H=192 F2 ep=020/48 train=0.154208 lr=1.000e-04
Fold direct Electricity H=192 F2 ep=021/48 train=0.153726 lr=9.996e-05
Fold direct Electricity H=192 F2 ep=022/48 train=0.152823 lr=9.985e-05
Fold direct Electricity H=192 F2 ep=023/48 train=0.152010 lr=9.965e-05
Fold direct Electricity H=192 F2 ep=024/48 train=0.151593 lr=9.938e-05
Fold direct Electricity H=192 F2 ep=025/48 train=0.151077 lr=9.904e-05
Fold direct Electricity H=192 F2 ep=026/48 train=0.150501 lr=9.862e-05
Fold direct Electricity H=192 F2 ep=027/48 train=0.150093 lr=9.812e-05
Fold direct Electricity H=192 F2 ep=028/48 train=0.149598 lr=9.755e-05
Fold direct Electricity H=192 F2 ep=029/48 train=0.149007 lr=9.691e-05
Fold direct Electricity H=192 F2 ep=030/48 train=0.148601 lr=9.619e-05
Fold direct Electricity H=192 F2 ep=031/48 train=0.148133 lr=9.541e-05
Fold direct Electricity H=192 F2 ep=032/48 train=0.147808 lr=9.455e-05
Fold direct Electricity H=192 F2 ep=033/48 train=0.147396 lr=9.362e-05
Fold direct Electricity H=192 F2 ep=034/48 train=0.147036 lr=9.263e-05
Fold direct Electricity H=192 F2 ep=035/48 train=0.146606 lr=9.157e-05
Fold direct Electricity H=192 F2 ep=036/48 train=0.146139 lr=9.045e-05
Fold direct Electricity H=192 F2 ep=037/48 train=0.145846 lr=8.926e-05
Fold direct Electricity H=192 F2 ep=038/48 train=0.145510 lr=8.802e-05
Fold direct Electricity H=192 F2 ep=039/48 train=0.145144 lr=8.671e-05
Fold direct Electricity H=192 F2 ep=040/48 train=0.144845 lr=8.535e-05
Fold direct Electricity H=192 F2 ep=041/48 train=0.144471 lr=8.394e-05
Fold direct Electricity H=192 F2 ep=042/48 train=0.144261 lr=8.247e-05
Fold direct Electricity H=192 F2 ep=043/48 train=0.143927 lr=8.095e-05
Fold direct Electricity H=192 F2 ep=044/48 train=0.143720 lr=7.939e-05
Fold direct Electricity H=192 F2 ep=045/48 train=0.143388 lr=7.777e-05


## 16. Compact decision table

가장 먼저 볼 값은 다음입니다.

$$
\text{Gain}
=
100
\cdot
\frac{
\mathrm{MSE}_{\mathrm{Direct}}
-
\mathrm{MSE}_{\mathrm{Ours}}
}{
\mathrm{MSE}_{\mathrm{Direct}}
}
$$

`ShrinkGainVsDirect_pct > 0`이면 Ours가 strong PatchTST보다 좋습니다.

통계적 안정성은 moving-block bootstrap에서 확인합니다.

$$
\mathrm{CI}_{\mathrm{low}} > 0
$$

이면 Direct 대비 improvement가 유의한 것으로 해석합니다.

In [ ]:

if not len(
    summary_df
):
    raise RuntimeError(
        "No completed Experiment 19 result."
    )

compact = summary_df[
    [
        "Dataset",
        "Horizon",
        "OfficialPatchTST_MSE",
        "ShrinkAdaptive_MSE",
        "ShrinkGainVsDirect_pct",
        "OfficialPatchTST_MAE",
        "ShrinkAdaptive_MAE",
        "ScalarAlpha",
        "ShrinkLambda",
        "ShrinkMeanAlpha",
        "ImprovedChannelFraction",
        "Oracle_MSE",
        "OracleHeadroomFromDirect_pct",
        "DirectParityAbsDiff",
    ]
].copy()

compact[
    "Winner"
] = np.where(
    compact[
        "ShrinkAdaptive_MSE"
    ]
    < compact[
        "OfficialPatchTST_MSE"
    ],
    "Ours",
    "Direct",
)

display(
    compact
)

if BOOTSTRAP_PATH.exists():
    boot_df = pd.read_csv(
        BOOTSTRAP_PATH
    )

    direct_boot = boot_df[
        boot_df[
            "Comparison"
        ]
        == "Direct-ShrinkAdaptive"
    ][
        [
            "Dataset",
            "Horizon",
            "MeanImprovement",
            "CI_Low",
            "CI_High",
            "SignificantPositive",
        ]
    ].sort_values(
        [
            "Dataset",
            "Horizon",
        ]
    )

    display(
        direct_boot
    )


# 17. 해석 기준

## 시나리오 A — Weather와 Electricity에서 여러 horizon 개선

가장 좋은 결과입니다.

특히 strong official-level PatchTST를 대상으로 반복적인 개선이 나오면

$$
\boxed{
\text{historical memory is complementary to a strong parametric forecaster}
}
$$

라는 주장을 직접 지지합니다.

1% 안팎의 개선도 strong baseline 위에서 반복되면 충분히 의미가 있습니다.

---

## 시나리오 B — Weather만 개선

Weather는 이전 screening에서 historical retrieval이 전반적으로 유용했던 데이터셋입니다.

이 경우 연구 질문은

> historical memory는 어떤 data regime에서 strong forecaster를 보완하는가?

로 좁혀질 수 있습니다.

ETT와 Electricity 결과를 함께 사용해
retrieval-friendly regime의 특성을 분석할 수 있습니다.

---

## 시나리오 C — Electricity에서 scalar는 실패하지만 adaptive gate가 개선

이 결과도 매우 흥미롭습니다.

$$
\alpha_0 = 0
$$

인데 adaptive gate가 strong PatchTST를 개선하면

> retrieval is not globally useful, but is selectively useful for identifiable queries

라는 해석이 가능합니다.

---

## 시나리오 D — 둘 다 개선하지 못함

그 경우 현재 frozen method는 strong PatchTST에 대한 일반적인 model-agnostic augmentation이라고 주장할 수 없습니다.

하지만 Oracle headroom을 함께 봅니다.

### Oracle headroom도 작음

PatchTST가 historical analog의 정보를 대부분 이미 흡수하고 있을 가능성이 큽니다.

### Oracle headroom은 큼

보완 정보는 존재하지만 현재 retriever 또는 trust estimator가 이를 충분히 활용하지 못하는 것입니다.

---

## 중요한 원칙

Experiment 19의 Weather/Electricity test 결과를 본 뒤
retriever나 gate를 해당 데이터셋에 맞춰 다시 튜닝하지 않습니다.

먼저 8개 조건 전체 결과를 고정된 방법으로 끝까지 확인한 후 다음 연구 결정을 내립니다.

## 18. Saved artifacts

In [ ]:

print(
    "Experiment root:",
    ROOT,
)

for p in sorted(
    ROOT.rglob(
        "*"
    )
):
    if p.is_file():
        print(
            p.relative_to(
                ROOT
            )
        )

In [19]:
# ============================================================
# Experiment 19 — Disk-based progress / result checker
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np
import os
from datetime import datetime

ROOT = Path(
    "/data/dataset/strong_forecaster/"
    "weather_electricity_official_patchtst_plus_frozen_retrieval"
)

EXP18_ROOT = Path(
    "/data/dataset/strong_forecaster/"
    "weather_electricity_official_patchtst_baselines"
)

TASKS = [
    ("Weather", 96),
    ("Weather", 192),
    ("Weather", 336),
    ("Weather", 720),
    ("Electricity", 96),
    ("Electricity", 192),
    ("Electricity", 336),
    ("Electricity", 720),
]

summary_path = ROOT / "summary.csv"
bootstrap_path = ROOT / "bootstrap.csv"
folds_path = ROOT / "folds.csv"

exp18_summary = pd.read_csv(EXP18_ROOT / "summary.csv")

if summary_path.exists():
    summary = pd.read_csv(summary_path)
else:
    summary = pd.DataFrame()

rows = []

for dataset, h in TASKS:

    # Experiment 18에서 정한 fold 학습 epoch
    ref = exp18_summary[
        (exp18_summary["Dataset"] == dataset)
        & (exp18_summary["Horizon"] == h)
    ]

    target_epoch = (
        int(ref.iloc[0]["BestEpoch"])
        if len(ref) == 1
        else None
    )

    # 최종 결과 존재 여부
    completed = (
        len(summary) > 0
        and (
            (summary["Dataset"] == dataset)
            & (summary["Horizon"] == h)
        ).any()
    )

    # Fold별 상태
    fold_status = []

    for fold in [1, 2, 3]:
        ckpt = (
            ROOT / "fold_direct"
            / f"{dataset}_H{h}_F{fold}_official_direct.pt"
        )

        oof = (
            ROOT / "oof"
            / f"{dataset}_H{h}_F{fold}_official_direct.npz"
        )

        hist = (
            ROOT / "history"
            / f"{dataset}_H{h}_F{fold}_direct_history.csv"
        )

        last_epoch = 0

        if hist.exists():
            try:
                hh = pd.read_csv(hist)
                if len(hh):
                    last_epoch = int(hh["Epoch"].max())
            except Exception:
                pass

        if oof.exists():
            s = "OOF done"
        elif ckpt.exists():
            s = "Direct done"
        elif last_epoch > 0:
            s = f"epoch {last_epoch}/{target_epoch}"
        else:
            s = "-"

        fold_status.append(s)

    val_cache = (
        ROOT / "validation"
        / f"{dataset}_H{h}_validation_features.npz"
    ).exists()

    gate = (
        ROOT / "gate"
        / f"{dataset}_H{h}_official_direct.pt"
    ).exists()

    paired = (
        ROOT / "paired_test"
        / f"{dataset}_H{h}_anchor_mse.npz"
    ).exists()

    channel = (
        ROOT / "channel_test"
        / f"{dataset}_H{h}_channel_mse.csv"
    ).exists()

    if completed:
        status = "✅ COMPLETE"
    elif paired:
        status = "⚠️ Test done / summary missing"
    elif gate:
        status = "🟡 Gate done"
    elif val_cache:
        status = "🟡 Validation done"
    elif any(x != "-" for x in fold_status):
        status = "🟠 Cross-fit in progress"
    else:
        status = "⚪ Not started"

    rows.append({
        "Dataset": dataset,
        "H": h,
        "Status": status,
        "TargetEpoch": target_epoch,
        "Fold1": fold_status[0],
        "Fold2": fold_status[1],
        "Fold3": fold_status[2],
        "ValCache": val_cache,
        "Gate": gate,
        "PairedTest": paired,
        "ChannelResult": channel,
    })

status_df = pd.DataFrame(rows)

print("=" * 120)
print("EXPERIMENT 19 DISK STATUS")
print("=" * 120)
display(status_df)

print("\n" + "=" * 120)
print("SAVED FINAL RESULTS")
print("=" * 120)

if len(summary):
    cols = [
        "Dataset",
        "Horizon",
        "OfficialPatchTST_MSE",
        "ShrinkAdaptive_MSE",
        "ShrinkGainVsDirect_pct",
        "ScalarAlpha",
        "ShrinkLambda",
        "Oracle_MSE",
        "OracleHeadroomFromDirect_pct",
    ]

    cols = [c for c in cols if c in summary.columns]

    display(
        summary[cols]
        .sort_values(["Dataset", "Horizon"])
        .reset_index(drop=True)
    )

    print(f"\nCompleted conditions: {len(summary)}/8")
else:
    print("summary.csv가 아직 없습니다.")

print("\n" + "=" * 120)
print("LATEST MODIFIED FILES")
print("=" * 120)

files = [
    p for p in ROOT.rglob("*")
    if p.is_file()
]

files = sorted(
    files,
    key=lambda p: p.stat().st_mtime,
    reverse=True,
)[:20]

for p in files:
    t = datetime.fromtimestamp(
        p.stat().st_mtime
    ).strftime("%Y-%m-%d %H:%M:%S")

    print(
        t,
        " | ",
        p.relative_to(ROOT)
    )

print("\n" + "=" * 120)

if len(summary) == 8:
    print("✅ Experiment 19 전체 8개 조건이 완료되었습니다.")
else:
    print(
        f"현재 최종 완료: {len(summary)}/8 조건"
    )
    print(
        "미완료 상태라면 RESUME=True 상태에서 "
        "Main Experiment 셀을 다시 실행하면 됩니다."
    )

========================================================================================================================
EXPERIMENT 19 DISK STATUS
========================================================================================================================

       Dataset    H      Status  TargetEpoch     Fold1     Fold2     Fold3  ValCache  Gate  PairedTest  ChannelResult
0      Weather   96  ✅ COMPLETE           65  OOF done  OOF done  OOF done      True  True        True           True
1      Weather  192  ✅ COMPLETE           45  OOF done  OOF done  OOF done      True  True        True           True
2      Weather  336  ✅ COMPLETE           19  OOF done  OOF done  OOF done      True  True        True           True
3      Weather  720  ✅ COMPLETE           23  OOF done  OOF done  OOF done      True  True        True           True
4  Electricity   96  ✅ COMPLETE           97  OOF done  OOF done  OOF done      True  True        True           True
5  Electricity  192  ✅ COMPLETE           48  OOF done  OOF done  OOF done      True  True        True           True
6  Electricity  336  ✅ COMPLETE           69  OOF done  OOF done  OOF done      True  True        True           True
7  Electricity  720  ✅ COMPLETE           39  OOF done  OOF done  OOF done      True  True        True           True

========================================================================================================================
SAVED FINAL RESULTS
========================================================================================================================

       Dataset  Horizon  OfficialPatchTST_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  ScalarAlpha  ShrinkLambda  Oracle_MSE  OracleHeadroomFromDirect_pct
0  Electricity       96              0.129977            0.129218                0.584101          0.0          1.00    0.119747                      7.870349
1  Electricity      192              0.149116            0.148559                0.373992          0.0          0.75    0.139304                      6.580320
2  Electricity      336              0.165690            0.164748                0.568902          0.0          1.00    0.154490                      6.760021
3  Electricity      720              0.203216            0.202541                0.332348          0.0          1.00    0.187749                      7.611145
4      Weather       96              0.149690            0.147440                1.503275          0.1          1.00    0.123863                     17.254005
5      Weather      192              0.194775            0.190482                2.203907          0.1          1.00    0.161471                     17.098880
6      Weather      336              0.246900            0.241303                2.267156          0.2          0.75    0.204120                     17.327073
7      Weather      720              0.320894            0.314066                2.128003          0.1          1.00    0.265141                     17.374355

Completed conditions: 8/8

========================================================================================================================
LATEST MODIFIED FILES
========================================================================================================================
2026-08-26 22:13:59  |  paired_test/Electricity_H720_anchor_mse.npz
2026-08-26 22:13:59  |  summary.csv
2026-08-26 22:13:59  |  bootstrap.csv
2026-08-26 22:13:59  |  channel_test/Electricity_H720_channel_mse.csv
2026-08-26 22:13:27  |  memory_embeddings/Electricity_H720_test_trainval_memory_emb.npy
2026-08-26 22:13:24  |  calibration.csv
2026-08-26 22:13:24  |  history/Electricity_H720_gate_history.csv
2026-08-26 22:13:24  |  gate/Electricity_H720_official_direct.pt
2026-08-26 22:13:04  |  validation/Electricity_H720_validation_features.npz
2026-08-26 22:12:50  |  memory_embeddings/Electricity_H720_validation_train_memory_emb.npy
2026-08-26 22:12:47  |  folds.csv
2026-08-26 22:12:47  |  oof/Electricity_H720_F3_official_direct.npz
2026-08-26 22:12:43  |  memory_embeddings/Electricity_H720_F3_prefix15650_emb.npy
2026-08-26 22:12:41  |  fold_direct/Electricity_H720_F3_official_direct.pt
2026-08-26 22:12:41  |  history/Electricity_H720_F3_direct_history.csv
2026-08-26 20:21:06  |  oof/Electricity_H720_F2_official_direct.npz
2026-08-26 20:21:02  |  memory_embeddings/Electricity_H720_F2_prefix12888_emb.npy
2026-08-26 20:21:00  |  fold_direct/Electricity_H720_F2_official_direct.pt
2026-08-26 20:21:00  |  history/Electricity_H720_F2_direct_history.csv
2026-08-26 18:14:37  |  oof/Electricity_H720_F1_official_direct.npz

========================================================================================================================
✅ Experiment 19 전체 8개 조건이 완료되었습니다.