
# Experiment 22 — iTransformer + Frozen Historical Memory

## 연구 질문

Experiment 21에서 strong official-style iTransformer baseline을 고정했습니다.

이제 PatchTST에서 사용했던 historical-memory augmentation을 **구조 변경 없이**
iTransformer에 적용합니다.

핵심 검증은 다음과 같습니다.

$$
\boxed{
F_{\mathrm{iTransformer}}
+
R_{\mathrm{historical}}
>
F_{\mathrm{iTransformer}}
}
$$

대상은

$$
\mathcal{D}
=
\{
\mathrm{ETTm1},
\mathrm{ETTh1},
\mathrm{Weather},
\mathrm{Electricity}
\}
$$

와

$$
H
\in
\{
96,192,336,720
\}
$$

입니다.

총 16개 조건을 모두 수행합니다.

---

# Frozen augmentation

PatchTST Experiment 19와 동일한 method를 사용합니다.

$$
\boxed{
\text{Predictive Retrieval}
\rightarrow
\text{Uniform Top-10 Historical Forecast}
\rightarrow
\text{Cross-Fitted Adaptive Gate}
\rightarrow
\text{Validation-Calibrated Shrinkage}
}
$$

## 1. Predictive retrieval

Experiment 13에서 이미 학습한 EmbeddingOnly retriever를 그대로 사용합니다.

$$
s(q,i)
=
\gamma
\cos(
z_q,
z_i
)
$$

- retrieval lookback: \(L_R=96\)
- patch length: 16
- patch stride: 16
- embedding dimension: 64
- Top-\(K=10\)
- memory stride: 24
- retriever architecture: frozen
- retriever checkpoint: frozen
- retriever hyperparameters: frozen

## 2. Historical forecast

Top-10 candidate의 미래 residual을 단순 평균합니다.

$$
\hat{\mathbf y}_{\mathrm{hist}}
=
\frac{1}{K}
\sum_{i\in\mathcal{N}_K(q)}
\mathbf y_i
$$

새로운 set aggregator는 사용하지 않습니다.

## 3. Adaptive trust

$$
\hat{\mathbf y}
=
(1-\alpha_q)
\hat{\mathbf y}_{\mathrm{iTransformer}}
+
\alpha_q
\hat{\mathbf y}_{\mathrm{hist}}
$$

Gate 구조는 PatchTST 실험과 동일합니다.

$$
26
\rightarrow
64
\rightarrow
32
\rightarrow
1
$$

## 4. Validation-calibrated shrinkage

$$
\alpha_{\mathrm{final}}
=
(1-\lambda)\alpha_0
+
\lambda\alpha_{\mathrm{gate}}
$$

- \(\alpha_0\): validation-only scalar weight
- \(\lambda\): validation-only shrinkage coefficient

---

# Leakage-free cross-fitting

train split 내부에서 세 개의 chronological fold를 사용합니다.

$$
0.55\rightarrow0.70
$$

$$
0.70\rightarrow0.85
$$

$$
0.85\rightarrow1.00
$$

각 fold에서:

1. prefix 구간만으로 external standardization
2. prefix 구간만으로 iTransformer 학습
3. prefix 이전에 future까지 완전히 관측된 history만 retrieval memory로 사용
4. 바로 뒤 OOF 구간에서 direct / retrieval prediction 생성
5. OOF target은 adaptive gate 학습에만 사용

Fold iTransformer의 epoch 수는 OOF target으로 선택하지 않습니다.

Experiment 21 full iTransformer에서 validation으로 선택한 best epoch를 고정하여 사용합니다.

$$
E_{\mathrm{fold}}
=
E_{\mathrm{full}}^{*}
$$

---

# Validation

- full iTransformer: Experiment 21 checkpoint
- full retriever: Experiment 13 frozen checkpoint
- retrieval memory: train only
- scalar \(\alpha_0\): validation only
- gate epoch: validation only
- shrinkage \(\lambda\): validation only

# Test

- iTransformer: train-only Experiment 21 checkpoint
- retrieval memory: train + validation only
- no rolling test-label memory
- all valid test origins
- stride 1
- all channels

---

# Computational engineering

Experiment 19에서는 Electricity에서 direct backbone을 작은 retrieval batch마다 반복 호출하는 비용이 컸습니다.

이번 notebook은 scientific protocol을 바꾸지 않고 다음을 최적화합니다.

1. iTransformer direct prediction을 큰 anchor block으로 먼저 계산
2. 동일 block 내부에서 retrieval만 작은 sub-batch로 수행
3. fold checkpoint / OOF feature / memory embedding / validation feature를 즉시 cache
4. 완료된 dataset × horizon 조건은 자동 skip
5. kernel이 종료되어도 `RESUME=True`로 재개

따라서 Experiment 19보다 상당히 빠를 것으로 기대하지만,
Electricity의 321-channel retrieval과 3-fold cross-fitting 때문에 여전히 수 시간이 걸릴 수 있습니다.

In [1]:

from pathlib import Path
from types import SimpleNamespace
from contextlib import nullcontext

import gc
import importlib
import math
import random
import subprocess
import sys
import time
import warnings

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 240)
pd.set_option("display.width", 500)

DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

DATASETS = [
    "ETTm1",
    "ETTh1",
    "Weather",
    "Electricity",
]

HORIZONS = [
    96,
    192,
    336,
    720,
]

TASKS = [
    (dataset, horizon)
    for dataset in DATASETS
    for horizon in HORIZONS
]

DIRECT_SEQ_LEN = 96
LABEL_LEN = 48
RET_SEQ_LEN = 96

DIRECT_SEED = 2023
CROSSFIT_SEED = 2222

TOP_K = 10
MEMORY_STRIDE = 24
OOF_ANCHOR_STRIDE = 4

FOLDS = [
    (0.55, 0.70),
    (0.70, 0.85),
    (0.85, 1.00),
]

# Frozen predictive representation.
REP_PATCH_LEN = 16
REP_PATCH_STRIDE = 16
REP_D_MODEL = 64
REP_N_HEADS = 4
REP_LAYERS = 2
REP_D_FF = 128
REP_DIM = 64
REP_DROPOUT = 0.1

REP_NUM_PATCHES = (
    1
    + (
        RET_SEQ_LEN
        - REP_PATCH_LEN
    )
    // REP_PATCH_STRIDE
)

# Frozen adaptive-gate design.
GATE_DIM = 26
GATE_LR = 1e-3
GATE_WD = 1e-4
GATE_BATCH = 8192
GATE_MAX_EPOCHS = 50
GATE_PATIENCE = 7

ALPHA_GRID = np.round(
    np.arange(
        0.0,
        1.0001,
        0.1,
    ),
    10,
)

LAMBDA_GRID = np.array(
    [
        0.0,
        0.25,
        0.50,
        0.75,
        1.00,
    ],
    dtype=np.float32,
)

EPS = 1e-8
RETRIEVER_USE_AMP = torch.cuda.is_available()

# Small retrieval batches prevent GPU blow-up on 321-channel Electricity.
TARGET_RETRIEVAL_PAIRS = 672

# Direct iTransformer is evaluated in much larger anchor blocks.
DIRECT_ANCHOR_BLOCK = {
    "ETTm1": 128,
    "ETTh1": 128,
    "Weather": 64,
    "Electricity": 16,
}

EXP21_ROOT = Path(
    "/data/dataset/strong_forecaster/"
    "itransformer_official_baseline_reproduction"
)

FROZEN_RET_ROOT = Path(
    "/data/dataset/strong_forecaster/"
    "multidataset_crossfit_screening"
)

ROOT = Path(
    "/data/dataset/strong_forecaster/"
    "itransformer_plus_frozen_historical_memory"
)

DIRS = {
    "fold_direct": ROOT / "fold_direct",
    "oof": ROOT / "oof",
    "validation": ROOT / "validation",
    "memory_emb": ROOT / "memory_embeddings",
    "gate": ROOT / "gate",
    "history": ROOT / "history",
    "paired": ROOT / "paired_test",
    "channel": ROOT / "channel_test",
    "calibration": ROOT / "calibration",
    "artifacts": ROOT / "artifacts",
}

for p in DIRS.values():
    p.mkdir(
        parents=True,
        exist_ok=True,
    )

RESUME = True
FORCE = False

DIRECT_PARITY_TOL = 2e-5

print("Device:", DEVICE)
print("Tasks:", len(TASKS))
print("Experiment 21:", EXP21_ROOT)
print("Frozen retrievers:", FROZEN_RET_ROOT)
print("Output:", ROOT)

Device: cuda
Tasks: 16
Experiment 21: /data/dataset/strong_forecaster/itransformer_official_baseline_reproduction
Frozen retrievers: /data/dataset/strong_forecaster/multidataset_crossfit_screening
Output: /data/dataset/strong_forecaster/itransformer_plus_frozen_historical_memory

## 1. Load the exact official iTransformer implementation used in Experiment 21

In [2]:

REPO_CANDIDATES = [
    Path(
        "/code/stock_regime_retrieval/"
        "strong_forecaster/iTransformer_official"
    ),
    Path("/code/iTransformer"),
    Path("/data/iTransformer"),
]

REPO = next(
    (
        p
        for p in REPO_CANDIDATES
        if (
            p / "model" / "iTransformer.py"
        ).is_file()
    ),
    None,
)

if REPO is None:
    raise FileNotFoundError(
        "Official iTransformer repository was not found. "
        "Experiment 21 must be available before Experiment 22."
    )

for module_name in list(
    sys.modules.keys()
):
    if (
        module_name == "model"
        or module_name.startswith("model.")
        or module_name == "layers"
        or module_name.startswith("layers.")
        or module_name == "utils"
        or module_name.startswith("utils.")
    ):
        del sys.modules[
            module_name
        ]

if str(REPO) in sys.path:
    sys.path.remove(
        str(REPO)
    )

sys.path.insert(
    0,
    str(REPO),
)

itransformer_module = importlib.import_module(
    "model.iTransformer"
)

tools_module = importlib.import_module(
    "utils.tools"
)

timefeatures_module = importlib.import_module(
    "utils.timefeatures"
)

OfficialITransformer = (
    itransformer_module.Model
)

official_adjust_lr = (
    tools_module.adjust_learning_rate
)

official_time_features = (
    timefeatures_module.time_features
)

actual_model_file = Path(
    itransformer_module.__file__
).resolve()

expected_model_file = (
    REPO
    / "model"
    / "iTransformer.py"
).resolve()

if (
    actual_model_file
    != expected_model_file
):
    raise RuntimeError(
        "Wrong iTransformer implementation imported.\n"
        f"Expected: {expected_model_file}\n"
        f"Actual:   {actual_model_file}"
    )

try:
    commit = subprocess.check_output(
        [
            "git",
            "-C",
            str(REPO),
            "rev-parse",
            "HEAD",
        ],
        text=True,
    ).strip()
except Exception:
    commit = "unknown"

print(
    "PASS: official iTransformer implementation."
)
print("Repo:", REPO)
print("Commit:", commit)

(
    DIRS["artifacts"]
    / "official_repo_commit.txt"
).write_text(
    commit + "\n"
)

PASS: official iTransformer implementation.
Repo: /code/stock_regime_retrieval/strong_forecaster/iTransformer_official
Commit: c2426e68ca13f74aaec08045c5c724d8ad328124

41

## 2. Experiment 21 frozen direct checkpoints and recipes

In [3]:

EXP21_SUMMARY_PATH = (
    EXP21_ROOT
    / "summary.csv"
)

if not EXP21_SUMMARY_PATH.is_file():
    raise FileNotFoundError(
        f"Experiment 21 summary not found: "
        f"{EXP21_SUMMARY_PATH}"
    )

EXP21_SUMMARY = pd.read_csv(
    EXP21_SUMMARY_PATH
)

display(
    EXP21_SUMMARY[
        [
            "Dataset",
            "Horizon",
            "BestEpoch",
            "Test_MSE",
            "Test_MAE",
        ]
    ].sort_values(
        [
            "Dataset",
            "Horizon",
        ]
    )
)


RECIPES = {
    "ETTm1": {
        "data": "ETTm1",
        "enc_in": 7,
        "e_layers": 2,
        "d_model": 512,
        "d_ff": 2048,
        "n_heads": 8,
        "dropout": 0.1,
        "batch_size": 32,
        "learning_rate": 1e-4,
        "train_epochs": 10,
        "patience": 3,
        "lradj": "type1",
        "factor": 1,
        "freq": "t",
    },
    "ETTh1": {
        "data": "ETTh1",
        "enc_in": 7,
        "e_layers": 2,
        "d_model": 512,
        "d_ff": 2048,
        "n_heads": 8,
        "dropout": 0.1,
        "batch_size": 32,
        "learning_rate": 1e-4,
        "train_epochs": 10,
        "patience": 3,
        "lradj": "type1",
        "factor": 1,
        "freq": "h",
    },
    "Weather": {
        "data": "custom",
        "enc_in": 21,
        "e_layers": 3,
        "d_model": 512,
        "d_ff": 512,
        "n_heads": 8,
        "dropout": 0.1,
        "batch_size": 32,
        "learning_rate": 1e-4,
        "train_epochs": 10,
        "patience": 3,
        "lradj": "type1",
        "factor": 1,
        "freq": "h",
    },
    "Electricity": {
        "data": "custom",
        "enc_in": 321,
        "e_layers": 3,
        "d_model": 512,
        "d_ff": 512,
        "n_heads": 8,
        "dropout": 0.1,
        "batch_size": 16,
        "learning_rate": 5e-4,
        "train_epochs": 10,
        "patience": 3,
        "lradj": "type1",
        "factor": 1,
        "freq": "h",
    },
}


def itransformer_config(
    name,
    horizon,
):
    r = RECIPES[
        name
    ]

    return SimpleNamespace(
        task_name=
            "long_term_forecast",
        seq_len=
            DIRECT_SEQ_LEN,
        label_len=
            LABEL_LEN,
        pred_len=
            int(
                horizon
            ),
        output_attention=
            False,
        enc_in=
            r[
                "enc_in"
            ],
        dec_in=
            r[
                "enc_in"
            ],
        c_out=
            r[
                "enc_in"
            ],
        d_model=
            r[
                "d_model"
            ],
        embed=
            "timeF",
        freq=
            r[
                "freq"
            ],
        dropout=
            r[
                "dropout"
            ],
        factor=
            r[
                "factor"
            ],
        n_heads=
            r[
                "n_heads"
            ],
        d_ff=
            r[
                "d_ff"
            ],
        activation=
            "gelu",
        e_layers=
            r[
                "e_layers"
            ],
        d_layers=
            1,
        class_strategy=
            "projection",
        use_norm=
            1,
    )


def build_itransformer(
    name,
    horizon,
):
    return OfficialITransformer(
        itransformer_config(
            name,
            horizon,
        )
    ).float().to(
        DEVICE
    )


def exp21_ckpt_path(
    name,
    horizon,
):
    return (
        EXP21_ROOT
        / "checkpoints"
        / (
            f"{name}_H{horizon}_"
            f"seed{DIRECT_SEED}.pt"
        )
    )


def exp21_reference(
    name,
    horizon,
):
    hit = EXP21_SUMMARY[
        (
            EXP21_SUMMARY[
                "Dataset"
            ]
            == name
        )
        & (
            EXP21_SUMMARY[
                "Horizon"
            ]
            == horizon
        )
    ]

    if len(
        hit
    ) != 1:
        raise RuntimeError(
            f"Expected one Experiment 21 row "
            f"for {name} H={horizon}."
        )

    return hit.iloc[
        0
    ]

        Dataset  Horizon  BestEpoch  Test_MSE  Test_MAE
4         ETTh1       96          1  0.392304  0.407334
5         ETTh1      192          1  0.442639  0.434737
6         ETTh1      336          1  0.489263  0.461457
7         ETTh1      720          1  0.506507  0.492894
0         ETTm1       96          1  0.336712  0.373422
1         ETTm1      192          3  0.394380  0.402333
2         ETTm1      336          2  0.424327  0.422129
3         ETTm1      720          3  0.496095  0.461646
12  Electricity       96          7  0.148275  0.239707
13  Electricity      192          7  0.165100  0.256106
14  Electricity      336          9  0.179687  0.272384
15  Electricity      720          3  0.217054  0.304202
8       Weather       96          6  0.173287  0.212210
9       Weather      192          5  0.224436  0.257719
10      Weather      336          3  0.282732  0.299481
11      Weather      720          4  0.357908  0.349720

## 3. Dataset paths and exact full-split normalization

In [4]:

DATA_PATH_CANDIDATES = {
    "ETTm1": [
        Path("/data/dataset/ETTm1.csv"),
        Path(
            "/data/Time-Series-Library/"
            "dataset/ETT-small/ETTm1.csv"
        ),
        Path(
            "/data/Time-Series-Library_v2/"
            "dataset/ETT-small/ETTm1.csv"
        ),
    ],
    "ETTh1": [
        Path("/data/dataset/ETTh1.csv"),
        Path(
            "/data/Time-Series-Library/"
            "dataset/ETT-small/ETTh1.csv"
        ),
        Path(
            "/data/Time-Series-Library_v2/"
            "dataset/ETT-small/ETTh1.csv"
        ),
    ],
    "Weather": [
        Path("/data/dataset/weather.csv"),
        Path("/data/dataset/weather/weather.csv"),
        Path(
            "/data/Time-Series-Library/"
            "dataset/weather/weather.csv"
        ),
        Path(
            "/data/Time-Series-Library_v2/"
            "dataset/weather/weather.csv"
        ),
    ],
    "Electricity": [
        Path("/data/dataset/electricity.csv"),
        Path(
            "/data/dataset/electricity/"
            "electricity.csv"
        ),
        Path(
            "/data/Time-Series-Library/"
            "dataset/electricity/electricity.csv"
        ),
        Path(
            "/data/Time-Series-Library_v2/"
            "dataset/electricity/electricity.csv"
        ),
    ],
}

DATA_PATHS = {}

for name, candidates in (
    DATA_PATH_CANDIDATES.items()
):
    hit = next(
        (
            p
            for p in candidates
            if p.is_file()
        ),
        None,
    )

    DATA_PATHS[
        name
    ] = hit

    print(
        f"{name:11s}:",
        hit if hit is not None else "NOT FOUND",
    )

if any(
    p is None
    for p in DATA_PATHS.values()
):
    raise FileNotFoundError(
        "At least one required dataset CSV is missing."
    )


def standard_boundaries(
    name,
    n,
):
    if name == "ETTh1":
        train_end = (
            12
            * 30
            * 24
        )

        val_end = (
            (
                12
                + 4
            )
            * 30
            * 24
        )

        test_end = (
            (
                12
                + 8
            )
            * 30
            * 24
        )

    elif name == "ETTm1":
        unit = (
            30
            * 24
            * 4
        )

        train_end = (
            12
            * unit
        )

        val_end = (
            (
                12
                + 4
            )
            * unit
        )

        test_end = (
            (
                12
                + 8
            )
            * unit
        )

    else:
        train_end = int(
            n
            * 0.7
        )

        num_test = int(
            n
            * 0.2
        )

        num_val = (
            n
            - train_end
            - num_test
        )

        val_end = (
            train_end
            + num_val
        )

        test_end = n

    if test_end > n:
        raise ValueError(
            f"{name}: dataset is shorter than "
            f"the official split. "
            f"Need {test_end}, found {n}."
        )

    return (
        train_end,
        val_end,
        test_end,
    )


def prepare_data(
    name,
):
    path = DATA_PATHS[
        name
    ]

    df = pd.read_csv(
        path
    )

    if "date" not in df.columns:
        raise ValueError(
            f"{name}: no date column."
        )

    if (
        name
        in [
            "Weather",
            "Electricity",
        ]
    ):
        if "OT" not in df.columns:
            raise ValueError(
                f"{name}: no OT column."
            )

        cols = list(
            df.columns
        )

        cols.remove(
            "OT"
        )

        cols.remove(
            "date"
        )

        df = df[
            ["date"]
            + cols
            + ["OT"]
        ].copy()

    value_cols = list(
        df.columns[
            1:
        ]
    )

    raw = df[
        value_cols
    ].to_numpy(
        dtype=np.float64
    )

    (
        train_end,
        val_end,
        test_end,
    ) = standard_boundaries(
        name,
        len(
            raw
        ),
    )

    scaler = StandardScaler()

    scaler.fit(
        raw[
            :train_end
        ]
    )

    z = scaler.transform(
        raw
    ).astype(
        np.float32
    )

    dates = pd.to_datetime(
        df[
            "date"
        ].values
    )

    marks = official_time_features(
        dates,
        freq=
            RECIPES[
                name
            ][
                "freq"
            ],
    ).transpose(
        1,
        0,
    ).astype(
        np.float32
    )

    C = raw.shape[
        1
    ]

    if (
        C
        != RECIPES[
            name
        ][
            "enc_in"
        ]
    ):
        raise ValueError(
            f"{name}: expected "
            f"{RECIPES[name]['enc_in']} channels, "
            f"found {C}."
        )

    return {
        "name":
            name,
        "path":
            path,
        "columns":
            value_cols,
        "raw":
            raw,
        "z":
            z,
        "marks":
            marks,
        "n_channels":
            C,
        "train_end":
            train_end,
        "val_end":
            val_end,
        "test_end":
            test_end,
        "full_scaler":
            scaler,
    }


DATA = {
    name:
        prepare_data(
            name
        )
    for name in DATASETS
}

display(
    pd.DataFrame([
        {
            "Dataset":
                name,
            "RowsUsed":
                d[
                    "test_end"
                ],
            "Channels":
                d[
                    "n_channels"
                ],
            "TrainEnd":
                d[
                    "train_end"
                ],
            "ValEnd":
                d[
                    "val_end"
                ],
            "TestEnd":
                d[
                    "test_end"
                ],
            "TimeFeatures":
                d[
                    "marks"
                ].shape[
                    1
                ],
        }
        for name, d
        in DATA.items()
    ])
)

ETTm1      : /data/dataset/ETTm1.csv
ETTh1      : /data/Time-Series-Library/dataset/ETT-small/ETTh1.csv
Weather    : /data/Time-Series-Library/dataset/weather/weather.csv
Electricity: /data/Time-Series-Library/dataset/electricity/electricity.csv

       Dataset  RowsUsed  Channels  TrainEnd  ValEnd  TestEnd  TimeFeatures
0        ETTm1     57600         7     34560   46080    57600             5
1        ETTh1     14400         7      8640   11520    14400             4
2      Weather     52696        21     36887   42157    52696             4
3  Electricity     26304       321     18412   21044    26304             4

## 4. Prefix-only normalization for chronological OOF folds

In [5]:

def prefix_normalize(
    raw,
    prefix,
):
    scaler = StandardScaler()

    scaler.fit(
        raw[
            :prefix
        ]
    )

    z = scaler.transform(
        raw
    ).astype(
        np.float32
    )

    return (
        z,
        scaler,
    )

## 5. iTransformer direct utilities

In [6]:

def set_seed(
    seed,
):
    random.seed(
        seed
    )

    np.random.seed(
        seed
    )

    torch.manual_seed(
        seed
    )

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(
            seed
        )

    torch.backends.cudnn.benchmark = False


def load_torch(
    path,
):
    try:
        return torch.load(
            path,
            map_location=DEVICE,
            weights_only=False,
        )
    except TypeError:
        return torch.load(
            path,
            map_location=DEVICE,
        )


def load_exp21_direct(
    name,
    horizon,
):
    path = exp21_ckpt_path(
        name,
        horizon,
    )

    ckpt = load_torch(
        path
    )

    model = build_itransformer(
        name,
        horizon,
    )

    model.load_state_dict(
        ckpt[
            "StateDict"
        ]
    )

    model.eval()

    return (
        model,
        ckpt,
    )


def eval_anchors(
    start,
    end,
    horizon,
    stride=1,
):
    return np.arange(
        max(
            int(
                start
            ),
            DIRECT_SEQ_LEN,
        ),
        int(
            end
        )
        - int(
            horizon
        )
        + 1,
        int(
            stride
        ),
        dtype=np.int64,
    )


def make_direct_batch(
    z,
    marks,
    anchors,
    horizon,
):
    anchors = np.asarray(
        anchors,
        dtype=np.int64,
    )

    x_idx = (
        anchors[
            :,
            None
        ]
        - DIRECT_SEQ_LEN
        + np.arange(
            DIRECT_SEQ_LEN
        )[
            None,
            :
        ]
    )

    y_idx = (
        anchors[
            :,
            None
        ]
        - LABEL_LEN
        + np.arange(
            LABEL_LEN
            + horizon
        )[
            None,
            :
        ]
    )

    x = z[
        x_idx,
        :
    ].astype(
        np.float32
    )

    y = z[
        y_idx,
        :
    ].astype(
        np.float32
    )

    x_mark = marks[
        x_idx,
        :
    ].astype(
        np.float32
    )

    y_mark = marks[
        y_idx,
        :
    ].astype(
        np.float32
    )

    return (
        x,
        y,
        x_mark,
        y_mark,
    )


def forward_direct(
    model,
    x,
    y,
    x_mark,
    y_mark,
    horizon,
):
    x_t = torch.from_numpy(
        x
    ).to(
        DEVICE
    )

    y_t = torch.from_numpy(
        y
    ).to(
        DEVICE
    )

    xm_t = torch.from_numpy(
        x_mark
    ).to(
        DEVICE
    )

    ym_t = torch.from_numpy(
        y_mark
    ).to(
        DEVICE
    )

    dec_inp = torch.zeros_like(
        y_t[
            :,
            -horizon:,
            :
        ]
    )

    dec_inp = torch.cat(
        [
            y_t[
                :,
                :LABEL_LEN,
                :
            ],
            dec_inp,
        ],
        dim=1,
    )

    pred = model(
        x_t,
        xm_t,
        dec_inp,
        ym_t,
    )

    pred = pred[
        :,
        -horizon:,
        :
    ].float()

    true = y_t[
        :,
        -horizon:,
        :
    ].float()

    return (
        pred,
        true,
        x_t,
        y_t,
        xm_t,
        ym_t,
        dec_inp,
    )


@torch.no_grad()
def direct_residual_block(
    model,
    z,
    marks,
    anchors,
    horizon,
):
    (
        x,
        y,
        x_mark,
        y_mark,
    ) = make_direct_batch(
        z,
        marks,
        anchors,
        horizon,
    )

    (
        pred,
        true,
        x_t,
        y_t,
        xm_t,
        ym_t,
        dec_inp,
    ) = forward_direct(
        model,
        x,
        y,
        x_mark,
        y_mark,
        horizon,
    )

    current = x_t[
        :,
        -1:,
        :
    ].float()

    pred_residual = (
        pred
        - current
    )

    true_residual = (
        true
        - current
    )

    del (
        true,
        x_t,
        y_t,
        xm_t,
        ym_t,
        dec_inp,
    )

    return (
        pred_residual,
        true_residual,
    )


@torch.no_grad()
def evaluate_direct_parity(
    name,
    horizon,
    model,
):
    d = DATA[
        name
    ]

    anchors = eval_anchors(
        d[
            "val_end"
        ],
        d[
            "test_end"
        ],
        horizon,
        stride=1,
    )

    sse = 0.0
    sae = 0.0
    n = 0

    block = DIRECT_ANCHOR_BLOCK[
        name
    ]

    for i in range(
        0,
        len(
            anchors
        ),
        block,
    ):
        a = anchors[
            i:
            i+block
        ]

        pred_r, true_r = (
            direct_residual_block(
                model,
                d[
                    "z"
                ],
                d[
                    "marks"
                ],
                a,
                horizon,
            )
        )

        e = (
            pred_r
            - true_r
        )

        sse += float(
            (
                e
                * e
            ).sum()
        )

        sae += float(
            e.abs().sum()
        )

        n += e.numel()

        del (
            pred_r,
            true_r,
            e,
        )

    return (
        sse
        / n,
        sae
        / n,
        len(
            anchors
        ),
    )


## 6. Direct parity preflight

Experiment 22에서 사용하는 manual chronological window가
Experiment 21의 official data provider와 동일한 prediction set을 만드는지 먼저 확인합니다.

각 조건에서

$$
\left|
\mathrm{MSE}_{22,\mathrm{direct}}
-
\mathrm{MSE}_{21}
\right|
<
2\times10^{-5}
$$

를 요구합니다.

이 검사를 통과하기 전에는 expensive cross-fitting을 시작하지 않습니다.

In [7]:

PARITY_PATH = (
    DIRS[
        "artifacts"
    ]
    / "direct_parity.csv"
)

parity_rows = []

for name, horizon in TASKS:
    model, ckpt = load_exp21_direct(
        name,
        horizon,
    )

    mse, mae, windows = (
        evaluate_direct_parity(
            name,
            horizon,
            model,
        )
    )

    ref = exp21_reference(
        name,
        horizon,
    )

    mse_diff = abs(
        mse
        - float(
            ref[
                "Test_MSE"
            ]
        )
    )

    mae_diff = abs(
        mae
        - float(
            ref[
                "Test_MAE"
            ]
        )
    )

    parity_rows.append({
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Exp21_MSE":
            float(
                ref[
                    "Test_MSE"
                ]
            ),
        "Manual_MSE":
            mse,
        "MSEAbsDiff":
            mse_diff,
        "Exp21_MAE":
            float(
                ref[
                    "Test_MAE"
                ]
            ),
        "Manual_MAE":
            mae,
        "MAEAbsDiff":
            mae_diff,
        "Windows":
            windows,
        "Pass":
            mse_diff
            < DIRECT_PARITY_TOL,
    })

    print(
        f"{name:11s} H={horizon:3d} | "
        f"Exp21={float(ref['Test_MSE']):.8f} | "
        f"manual={mse:.8f} | "
        f"diff={mse_diff:.2e} | "
        f"{'PASS' if mse_diff < DIRECT_PARITY_TOL else 'FAIL'}"
    )

    del (
        model,
        ckpt,
    )

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

parity_df = pd.DataFrame(
    parity_rows
)

parity_df.to_csv(
    PARITY_PATH,
    index=False,
)

display(
    parity_df
)

failed = parity_df[
    ~parity_df[
        "Pass"
    ]
]

if len(
    failed
):
    raise RuntimeError(
        "Direct parity failed. "
        "Do not start cross-fitting until this is fixed."
    )

print(
    "PASS: all 16 direct baselines match Experiment 21."
)

ETTm1       H= 96 | Exp21=0.33671204 | manual=0.33671205 | diff=7.84e-09 | PASS
ETTm1       H=192 | Exp21=0.39437993 | manual=0.39437989 | diff=4.29e-08 | PASS
ETTm1       H=336 | Exp21=0.42432655 | manual=0.42432651 | diff=3.81e-08 | PASS
ETTm1       H=720 | Exp21=0.49609469 | manual=0.49609468 | diff=1.20e-08 | PASS
ETTh1       H= 96 | Exp21=0.39230357 | manual=0.39230347 | diff=1.04e-07 | PASS
ETTh1       H=192 | Exp21=0.44263935 | manual=0.44263931 | diff=3.33e-08 | PASS
ETTh1       H=336 | Exp21=0.48926283 | manual=0.48926283 | diff=5.58e-09 | PASS
ETTh1       H=720 | Exp21=0.50650688 | manual=0.50650684 | diff=4.11e-08 | PASS
Weather     H= 96 | Exp21=0.17328721 | manual=0.17328719 | diff=2.38e-08 | PASS
Weather     H=192 | Exp21=0.22443607 | manual=0.22443608 | diff=1.06e-08 | PASS
Weather     H=336 | Exp21=0.28273247 | manual=0.28273248 | diff=8.18e-09 | PASS
Weather     H=720 | Exp21=0.35790776 | manual=0.35790778 | diff=1.75e-08 | PASS
Electricity H= 96 | Exp21=0.14827520 | manual=0.14827520 | diff=4.21e-09 | PASS
Electricity H=192 | Exp21=0.16510049 | manual=0.16510051 | diff=1.44e-08 | PASS
Electricity H=336 | Exp21=0.17968747 | manual=0.17968744 | diff=2.15e-08 | PASS
Electricity H=720 | Exp21=0.21705352 | manual=0.21705351 | diff=5.91e-09 | PASS

        Dataset  Horizon  Exp21_MSE  Manual_MSE    MSEAbsDiff  Exp21_MAE  Manual_MAE    MAEAbsDiff  Windows  Pass
0         ETTm1       96   0.336712    0.336712  7.835989e-09   0.373422    0.373422  1.574651e-08    11425  True
1         ETTm1      192   0.394380    0.394380  4.289268e-08   0.402333    0.402333  1.446892e-08    11329  True
2         ETTm1      336   0.424327    0.424327  3.805196e-08   0.422129    0.422129  1.184643e-08    11185  True
3         ETTm1      720   0.496095    0.496095  1.202157e-08   0.461646    0.461646  1.382447e-08    10801  True
4         ETTh1       96   0.392304    0.392303  1.038345e-07   0.407334    0.407334  5.240847e-08     2785  True
5         ETTh1      192   0.442639    0.442639  3.329982e-08   0.434737    0.434737  1.221880e-08     2689  True
6         ETTh1      336   0.489263    0.489263  5.577535e-09   0.461457    0.461457  5.536748e-09     2545  True
7         ETTh1      720   0.506507    0.506507  4.108821e-08   0.492894    0.492894  4.236591e-09     2161  True
8       Weather       96   0.173287    0.173287  2.378435e-08   0.212210    0.212210  4.415642e-09    10444  True
9       Weather      192   0.224436    0.224436  1.061105e-08   0.257719    0.257719  7.659541e-09    10348  True
10      Weather      336   0.282732    0.282732  8.181320e-09   0.299481    0.299481  1.073803e-08    10204  True
11      Weather      720   0.357908    0.357908  1.754615e-08   0.349720    0.349720  1.696901e-09     9820  True
12  Electricity       96   0.148275    0.148275  4.212055e-09   0.239707    0.239707  7.991553e-09     5165  True
13  Electricity      192   0.165100    0.165101  1.442278e-08   0.256106    0.256106  1.331935e-08     5069  True
14  Electricity      336   0.179687    0.179687  2.154468e-08   0.272384    0.272384  1.046808e-08     4925  True
15  Electricity      720   0.217054    0.217054  5.914185e-09   0.304202    0.304202  5.914185e-09     4541  True

PASS: all 16 direct baselines match Experiment 21.

## 7. Frozen predictive retriever

In [8]:

def inv_softplus(
    x,
):
    return math.log(
        math.exp(
            float(
                x
            )
        )
        - 1.0
    )


class PredictivePatchEncoder(
    nn.Module
):
    def __init__(
        self,
    ):
        super().__init__()

        self.patch_proj = nn.Linear(
            REP_PATCH_LEN,
            REP_D_MODEL,
        )

        self.pos_embed = nn.Parameter(
            torch.zeros(
                1,
                REP_NUM_PATCHES,
                REP_D_MODEL,
            )
        )

        nn.init.trunc_normal_(
            self.pos_embed,
            std=0.02,
        )

        layer = nn.TransformerEncoderLayer(
            d_model=
                REP_D_MODEL,
            nhead=
                REP_N_HEADS,
            dim_feedforward=
                REP_D_FF,
            dropout=
                REP_DROPOUT,
            activation=
                "gelu",
            batch_first=
                True,
            norm_first=
                True,
        )

        self.encoder = nn.TransformerEncoder(
            layer,
            num_layers=
                REP_LAYERS,
        )

        self.norm = nn.LayerNorm(
            REP_D_MODEL
        )

        self.proj = nn.Linear(
            REP_D_MODEL,
            REP_DIM,
        )

    def forward(
        self,
        x,
    ):
        p = x.unfold(
            1,
            REP_PATCH_LEN,
            REP_PATCH_STRIDE,
        )

        h = (
            self.patch_proj(
                p
            )
            + self.pos_embed[
                :,
                :p.shape[
                    1
                ],
            ]
        )

        h = self.encoder(
            h
        ).mean(
            dim=1
        )

        h = self.proj(
            self.norm(
                h
            )
        )

        return F.normalize(
            h,
            dim=-1,
            eps=1e-8,
        )


class EmbeddingOnlyRetriever(
    nn.Module
):
    def __init__(
        self,
    ):
        super().__init__()

        self.encoder = (
            PredictivePatchEncoder()
        )

        self.raw_gamma = nn.Parameter(
            torch.tensor(
                inv_softplus(
                    1.0
                ),
                dtype=torch.float32,
            )
        )

    @property
    def gamma(
        self,
    ):
        return F.softplus(
            self.raw_gamma
        )

    def encode(
        self,
        x,
    ):
        return self.encoder(
            x
        )


def ret_amp():
    if RETRIEVER_USE_AMP:
        return torch.autocast(
            device_type="cuda",
            dtype=torch.float16,
        )

    return nullcontext()


def full_retriever_ckpt_path(
    name,
    horizon,
):
    return (
        FROZEN_RET_ROOT
        / "full_retriever"
        / (
            f"{name}_H{horizon}_seed0.pt"
        )
    )


def fold_retriever_ckpt_path(
    name,
    horizon,
    fold,
):
    return (
        FROZEN_RET_ROOT
        / "fold_retriever"
        / (
            f"{name}_H{horizon}_"
            f"F{fold}_seed0.pt"
        )
    )


def load_frozen_retriever(
    path,
):
    ckpt = load_torch(
        path
    )

    model = EmbeddingOnlyRetriever().to(
        DEVICE
    )

    model.load_state_dict(
        ckpt[
            "StateDict"
        ]
    )

    model.eval()

    return (
        model,
        ckpt,
    )

## 8. Full prerequisite checkpoint audit

In [9]:

preflight_rows = []

for name, horizon in TASKS:
    preflight_rows.append({
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Kind":
            "Exp21 direct",
        "Path":
            exp21_ckpt_path(
                name,
                horizon,
            ),
    })

    preflight_rows.append({
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Kind":
            "Full retriever",
        "Path":
            full_retriever_ckpt_path(
                name,
                horizon,
            ),
    })

    for fold in range(
        1,
        4,
    ):
        preflight_rows.append({
            "Dataset":
                name,
            "Horizon":
                horizon,
            "Kind":
                f"Fold retriever F{fold}",
            "Path":
                fold_retriever_ckpt_path(
                    name,
                    horizon,
                    fold,
                ),
        })

preflight = pd.DataFrame(
    preflight_rows
)

preflight[
    "Exists"
] = preflight[
    "Path"
].map(
    lambda p:
        Path(
            p
        ).is_file()
)

display(
    preflight
)

missing = preflight[
    ~preflight[
        "Exists"
    ]
]

if len(
    missing
):
    for p in missing[
        "Path"
    ]:
        print(
            "MISSING:",
            p,
        )

    raise FileNotFoundError(
        "Required frozen checkpoint is missing."
    )

print(
    "PASS: all 80 prerequisite checkpoint references exist."
)

        Dataset  Horizon               Kind                                               Path  Exists
0         ETTm1       96       Exp21 direct  /data/dataset/strong_forecaster/itransformer_o...    True
1         ETTm1       96     Full retriever  /data/dataset/strong_forecaster/multidataset_c...    True
2         ETTm1       96  Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
3         ETTm1       96  Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
4         ETTm1       96  Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True
..          ...      ...                ...                                                ...     ...
75  Electricity      720       Exp21 direct  /data/dataset/strong_forecaster/itransformer_o...    True
76  Electricity      720     Full retriever  /data/dataset/strong_forecaster/multidataset_c...    True
77  Electricity      720  Fold retriever F1  /data/dataset/strong_forecaster/multidataset_c...    True
78  Electricity      720  Fold retriever F2  /data/dataset/strong_forecaster/multidataset_c...    True
79  Electricity      720  Fold retriever F3  /data/dataset/strong_forecaster/multidataset_c...    True

[80 rows x 5 columns]

PASS: all 80 prerequisite checkpoint references exist.

## 9. Retrieval time-series utilities

In [10]:

def retrieval_anchor_batch(
    name,
):
    C = DATA[
        name
    ][
        "n_channels"
    ]

    return max(
        1,
        TARGET_RETRIEVAL_PAIRS
        // C,
    )


def batch_pattern(
    x,
):
    x = np.asarray(
        x,
        np.float32,
    )

    xc = (
        x
        - x.mean(
            axis=-1,
            keepdims=True,
        )
    )

    n = np.linalg.norm(
        xc,
        axis=-1,
        keepdims=True,
    )

    return np.where(
        n > EPS,
        xc
        / np.maximum(
            n,
            EPS,
        ),
        0.0,
    ).astype(
        np.float32
    )


def context7(
    x,
):
    x = np.asarray(
        x,
        np.float32,
    )

    short = max(
        8,
        RET_SEQ_LEN
        // 4,
    )

    m = x.mean(
        axis=-1
    )

    s = (
        x.std(
            axis=-1
        )
        + EPS
    )

    f1 = (
        x[
            ...,
            -1
        ]
        - m
    ) / s

    f2 = (
        x[
            ...,
            -short:
        ].mean(
            axis=-1
        )
        - m
    ) / s

    f3 = (
        x[
            ...,
            -1
        ]
        - x[
            ...,
            -short
        ]
    ) / s

    f4 = (
        x[
            ...,
            -1
        ]
        - x[
            ...,
            0
        ]
    ) / s

    df = np.diff(
        x,
        axis=-1,
    )

    ds = np.diff(
        x[
            ...,
            -short:
        ],
        axis=-1,
    )

    f5 = (
        ds.std(
            axis=-1
        )
        + EPS
    ) / (
        df.std(
            axis=-1
        )
        + EPS
    )

    t = np.linspace(
        -1.0,
        1.0,
        RET_SEQ_LEN,
        dtype=np.float32,
    )

    t = (
        t
        - t.mean()
    )

    f6 = (
        np.sum(
            t
            * (
                x
                - m[
                    ...,
                    None
                ]
            ),
            axis=-1,
        )
        / (
            np.sum(
                t
                * t
            )
            + EPS
        )
    ) / s

    a = x[
        ...,
        :-1
    ]

    b = x[
        ...,
        1:
    ]

    a = (
        a
        - a.mean(
            axis=-1,
            keepdims=True,
        )
    )

    b = (
        b
        - b.mean(
            axis=-1,
            keepdims=True,
        )
    )

    f7 = np.sum(
        a
        * b,
        axis=-1,
    ) / (
        np.sqrt(
            np.sum(
                a
                * a,
                axis=-1,
            )
            * np.sum(
                b
                * b,
                axis=-1,
            )
        )
        + EPS
    )

    return np.stack(
        [
            f1,
            f2,
            f3,
            f4,
            f5,
            f6,
            f7,
        ],
        axis=-1,
    ).astype(
        np.float32
    )


def extract_channel(
    z,
    c,
    anchors,
    horizon,
):
    anchors = np.asarray(
        anchors,
        np.int64,
    )

    pi = (
        anchors[
            :,
            None
        ]
        - RET_SEQ_LEN
        + np.arange(
            RET_SEQ_LEN
        )[
            None,
            :
        ]
    )

    fi = (
        anchors[
            :,
            None
        ]
        + np.arange(
            horizon
        )[
            None,
            :
        ]
    )

    past = z[
        pi,
        c,
    ].astype(
        np.float32
    )

    future = z[
        fi,
        c,
    ].astype(
        np.float32
    )

    current = z[
        anchors
        - 1,
        c,
    ].astype(
        np.float32
    )

    future_residual = (
        future
        - current[
            :,
            None
        ]
    ).astype(
        np.float32
    )

    return (
        past,
        future_residual,
    )


def build_memory(
    z,
    channels,
    boundary,
    horizon,
):
    memory_anchors = np.arange(
        RET_SEQ_LEN,
        int(
            boundary
        )
        - horizon
        + 1,
        MEMORY_STRIDE,
        dtype=np.int64,
    )

    if len(
        memory_anchors
    ) < TOP_K:
        raise ValueError(
            "Insufficient admissible memory."
        )

    past = np.empty(
        (
            channels,
            len(
                memory_anchors
            ),
            RET_SEQ_LEN,
        ),
        dtype=np.float32,
    )

    pattern = np.empty_like(
        past
    )

    future = np.empty(
        (
            channels,
            len(
                memory_anchors
            ),
            horizon,
        ),
        dtype=np.float32,
    )

    for c in range(
        channels
    ):
        p, f = extract_channel(
            z,
            c,
            memory_anchors,
            horizon,
        )

        past[
            c
        ] = p

        pattern[
            c
        ] = batch_pattern(
            p
        )

        future[
            c
        ] = f

    return {
        "anchors":
            memory_anchors,
        "past":
            past,
        "pattern":
            pattern,
        "future":
            future,
        "M":
            len(
                memory_anchors
            ),
        "boundary":
            int(
                boundary
            ),
    }


def query_pairs(
    z,
    anchors,
    channels,
    horizon,
):
    anchors = np.asarray(
        anchors,
        np.int64,
    )

    channels = np.asarray(
        channels,
        np.int64,
    )

    pi = (
        anchors[
            :,
            None
        ]
        - RET_SEQ_LEN
        + np.arange(
            RET_SEQ_LEN
        )[
            None,
            :
        ]
    )

    fi = (
        anchors[
            :,
            None
        ]
        + np.arange(
            horizon
        )[
            None,
            :
        ]
    )

    past = z[
        pi,
        channels[
            :,
            None
        ],
    ].astype(
        np.float32
    )

    future = z[
        fi,
        channels[
            :,
            None
        ],
    ].astype(
        np.float32
    )

    current = z[
        anchors
        - 1,
        channels,
    ].astype(
        np.float32
    )

    true_residual = (
        future
        - current[
            :,
            None
        ]
    ).astype(
        np.float32
    )

    return (
        past,
        batch_pattern(
            past
        ),
        context7(
            past
        ),
        true_residual,
    )

## 10. Cached memory embeddings

In [11]:

@torch.no_grad()
def encode_np(
    model,
    x,
    chunk=512,
):
    parts = []

    for i in range(
        0,
        len(
            x
        ),
        chunk,
    ):
        t = torch.from_numpy(
            x[
                i:
                i+chunk
            ]
        ).to(
            DEVICE
        )

        with ret_amp():
            e = model.encode(
                t
            ).float()

        parts.append(
            e.cpu()
        )

        del (
            t,
            e,
        )

    return torch.cat(
        parts,
        dim=0,
    ).numpy().astype(
        np.float32
    )


def memory_embedding_path(
    name,
    horizon,
    tag,
):
    return (
        DIRS[
            "memory_emb"
        ]
        / (
            f"{name}_H{horizon}_"
            f"{tag}_emb.npy"
        )
    )


@torch.no_grad()
def memory_gpu_cached(
    name,
    horizon,
    tag,
    model,
    memory,
    channels,
):
    path = memory_embedding_path(
        name,
        horizon,
        tag,
    )

    expected = (
        channels,
        memory[
            "M"
        ],
        REP_DIM,
    )

    emb_np = None

    if (
        path.exists()
        and RESUME
        and not FORCE
    ):
        candidate = np.load(
            path,
            mmap_mode=None,
        )

        if (
            tuple(
                candidate.shape
            )
            == expected
        ):
            emb_np = candidate.astype(
                np.float32,
                copy=False,
            )

            print(
                "Loaded memory embedding:",
                path.name,
            )

    if emb_np is None:
        emb_np = np.empty(
            expected,
            dtype=np.float32,
        )

        print(
            "Building memory embedding:",
            path.name,
            expected,
        )

        for c in range(
            channels
        ):
            emb_np[
                c
            ] = encode_np(
                model,
                memory[
                    "past"
                ][
                    c
                ],
            )

            if (
                c == 0
                or (
                    c + 1
                )
                % 50
                == 0
                or (
                    c + 1
                    == channels
                )
            ):
                print(
                    f"  channel "
                    f"{c+1}/{channels}"
                )

        np.save(
            path,
            emb_np,
        )

    return {
        "emb":
            torch.from_numpy(
                emb_np
            ).to(
                DEVICE
            ),
        "pattern":
            torch.from_numpy(
                memory[
                    "pattern"
                ]
            ).to(
                DEVICE
            ),
        "future":
            torch.from_numpy(
                memory[
                    "future"
                ]
            ).to(
                DEVICE
            ),
    }

## 11. Frozen retrieval inference

In [12]:

@torch.no_grad()
def retrieve(
    model,
    memory_gpu_obj,
    z,
    anchors,
    channels,
    horizon,
):
    (
        past,
        pattern,
        ctx,
        true,
    ) = query_pairs(
        z,
        anchors,
        channels,
        horizon,
    )

    past_t = torch.from_numpy(
        past
    ).to(
        DEVICE
    )

    pattern_t = torch.from_numpy(
        pattern
    ).to(
        DEVICE
    )

    with ret_amp():
        qemb = model.encode(
            past_t
        )

    qemb = qemb.float()

    memb = memory_gpu_obj[
        "emb"
    ][
        channels
    ]

    sim = torch.bmm(
        qemb[
            :,
            None,
            :
        ],
        memb.transpose(
            1,
            2,
        ),
    ).squeeze(
        1
    )

    score = (
        model.gamma
        * sim
    )

    idx = torch.topk(
        score,
        TOP_K,
        dim=1,
    ).indices

    row = torch.arange(
        len(
            channels
        ),
        device=DEVICE,
    )[
        :,
        None
    ]

    pfull = torch.bmm(
        pattern_t[
            :,
            None,
            :
        ],
        memory_gpu_obj[
            "pattern"
        ][
            channels
        ].transpose(
            1,
            2,
        ),
    ).squeeze(
        1
    )

    return {
        "score":
            score[
                row,
                idx
            ],
        "sim":
            sim[
                row,
                idx
            ],
        "pattern":
            pfull[
                row,
                idx
            ],
        "cand":
            memory_gpu_obj[
                "future"
            ][
                channels[
                    :,
                    None
                ],
                idx,
            ],
        "ctx":
            torch.from_numpy(
                ctx
            ).to(
                DEVICE
            ),
        "true":
            torch.from_numpy(
                true
            ).to(
                DEVICE
            ),
    }

## 12. Frozen 26-dimensional adaptive gate

In [13]:

class CrossFitAdaptiveGate(
    nn.Module
):
    def __init__(
        self,
    ):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(
                GATE_DIM,
                64,
            ),
            nn.LayerNorm(
                64
            ),
            nn.GELU(),
            nn.Dropout(
                0.1
            ),
            nn.Linear(
                64,
                32,
            ),
            nn.GELU(),
            nn.Dropout(
                0.1
            ),
            nn.Linear(
                32,
                1,
            ),
        )

        nn.init.normal_(
            self.net[
                -1
            ].weight,
            mean=0.0,
            std=1e-3,
        )

        nn.init.constant_(
            self.net[
                -1
            ].bias,
            math.log(
                0.1
                / 0.9
            ),
        )

    def forward(
        self,
        x,
    ):
        return torch.sigmoid(
            self.net(
                x
            ).squeeze(
                -1
            )
        )


def score_entropy(
    s,
):
    p = torch.softmax(
        s,
        dim=1,
    )

    return (
        -(
            p
            * torch.log(
                p.clamp_min(
                    1e-8
                )
            )
        ).sum(
            dim=1
        )
        / math.log(
            TOP_K
        )
    )


def feature_cosine(
    a,
    b,
):
    return (
        (
            a
            * b
        ).sum(
            dim=1
        )
        / (
            torch.sqrt(
                (
                    a
                    * a
                ).sum(
                    dim=1
                )
                + 1e-8
            )
            * torch.sqrt(
                (
                    b
                    * b
                ).sum(
                    dim=1
                )
                + 1e-8
            )
        )
    )


def gate_features(
    r,
    retrieval,
    direct,
):
    s = r[
        "score"
    ]

    sim = r[
        "sim"
    ]

    pattern = r[
        "pattern"
    ]

    sorted_s = torch.sort(
        s,
        dim=1,
        descending=True,
    ).values

    cand_std = r[
        "cand"
    ].std(
        dim=1,
        unbiased=False,
    )

    disp_rms = torch.sqrt(
        (
            cand_std
            * cand_std
        ).mean(
            dim=1
        )
        + 1e-8
    )

    disp_mean = cand_std.mean(
        dim=1
    )

    direct_rms = torch.sqrt(
        (
            direct
            * direct
        ).mean(
            dim=1
        )
        + 1e-8
    )

    retrieval_rms = torch.sqrt(
        (
            retrieval
            * retrieval
        ).mean(
            dim=1
        )
        + 1e-8
    )

    disagreement = (
        retrieval
        - direct
    )

    disagreement_rms = torch.sqrt(
        (
            disagreement
            * disagreement
        ).mean(
            dim=1
        )
        + 1e-8
    )

    relative_disagreement = (
        disagreement_rms
        / (
            direct_rms
            + retrieval_rms
            + 1e-6
        )
    )

    scalars = torch.stack(
        [
            s.mean(
                dim=1
            ),
            s.std(
                dim=1,
                unbiased=False,
            ),
            s.max(
                dim=1
            ).values,
            sorted_s[
                :,
                0
            ]
            - sorted_s[
                :,
                1
            ],
            s.max(
                dim=1
            ).values
            - s.mean(
                dim=1
            ),
            score_entropy(
                s
            ),
            sim.mean(
                dim=1
            ),
            sim.std(
                dim=1,
                unbiased=False,
            ),
            sim.max(
                dim=1
            ).values,
            pattern.mean(
                dim=1
            ),
            pattern.std(
                dim=1,
                unbiased=False,
            ),
            pattern.max(
                dim=1
            ).values,
            disp_rms,
            disp_mean,
            direct_rms,
            retrieval_rms,
            disagreement_rms,
            relative_disagreement,
            feature_cosine(
                direct,
                retrieval,
            ),
        ],
        dim=1,
    )

    out = torch.cat(
        [
            r[
                "ctx"
            ],
            scalars,
        ],
        dim=1,
    )

    if out.shape[
        1
    ] != GATE_DIM:
        raise RuntimeError(
            f"Gate feature dimension mismatch: "
            f"{out.shape}"
        )

    return out


def abc_terms(
    direct,
    retrieval,
    true,
):
    e = (
        direct
        - true
    )

    delta = (
        retrieval
        - direct
    )

    return torch.stack(
        [
            (
                e
                * e
            ).mean(
                dim=1
            ),
            (
                e
                * delta
            ).mean(
                dim=1
            ),
            (
                delta
                * delta
            ).mean(
                dim=1
            ),
        ],
        dim=1,
    )

## 13. Fold-specific iTransformer training

In [14]:

def fold_direct_path(
    name,
    horizon,
    fold,
):
    return (
        DIRS[
            "fold_direct"
        ]
        / (
            f"{name}_H{horizon}_"
            f"F{fold}_itransformer.pt"
        )
    )


def history_path(
    name,
    horizon,
    fold,
):
    return (
        DIRS[
            "history"
        ]
        / (
            f"{name}_H{horizon}_"
            f"F{fold}_direct_history.csv"
        )
    )


def train_anchors(
    prefix,
    horizon,
):
    return np.arange(
        DIRECT_SEQ_LEN,
        int(
            prefix
        )
        - horizon
        + 1,
        dtype=np.int64,
    )


def train_fold_itransformer(
    name,
    horizon,
    z,
    marks,
    prefix,
    fixed_epochs,
    fold,
):
    path = fold_direct_path(
        name,
        horizon,
        fold,
    )

    if (
        path.exists()
        and RESUME
        and not FORCE
    ):
        ckpt = load_torch(
            path
        )

        model = build_itransformer(
            name,
            horizon,
        )

        model.load_state_dict(
            ckpt[
                "StateDict"
            ]
        )

        model.eval()

        print(
            "Loaded fold direct:",
            path.name,
        )

        return (
            model,
            ckpt,
        )

    r = RECIPES[
        name
    ]

    seed = (
        CROSSFIT_SEED
        + horizon
        * 100
        + fold
        * 17
        + int(
            prefix
        )
        % 997
    )

    set_seed(
        seed
    )

    model = build_itransformer(
        name,
        horizon,
    )

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=
            r[
                "learning_rate"
            ],
    )

    anchors = train_anchors(
        prefix,
        horizon,
    )

    rng = np.random.default_rng(
        seed
        + 1
    )

    history = []

    for epoch in range(
        1,
        int(
            fixed_epochs
        )
        + 1,
    ):
        model.train()

        order = rng.permutation(
            len(
                anchors
            )
        )

        usable = (
            len(
                order
            )
            // r[
                "batch_size"
            ]
        ) * r[
            "batch_size"
        ]

        order = order[
            :usable
        ]

        losses = []
        t0 = time.time()

        for left in range(
            0,
            usable,
            r[
                "batch_size"
            ],
        ):
            ids = order[
                left:
                left
                + r[
                    "batch_size"
                ]
            ]

            a = anchors[
                ids
            ]

            (
                x,
                y,
                x_mark,
                y_mark,
            ) = make_direct_batch(
                z,
                marks,
                a,
                horizon,
            )

            optimizer.zero_grad(
                set_to_none=True
            )

            (
                pred,
                true,
                x_t,
                y_t,
                xm_t,
                ym_t,
                dec_inp,
            ) = forward_direct(
                model,
                x,
                y,
                x_mark,
                y_mark,
                horizon,
            )

            loss = F.mse_loss(
                pred,
                true,
            )

            loss.backward()
            optimizer.step()

            losses.append(
                float(
                    loss.item()
                )
            )

            del (
                pred,
                true,
                x_t,
                y_t,
                xm_t,
                ym_t,
                dec_inp,
                loss,
            )

        train_mse = float(
            np.mean(
                losses
            )
        )

        # Same type1 schedule as Experiment 21.
        args = SimpleNamespace(
            learning_rate=
                r[
                    "learning_rate"
                ],
            lradj=
                r[
                    "lradj"
                ],
            train_epochs=
                r[
                    "train_epochs"
                ],
        )

        official_adjust_lr(
            optimizer,
            epoch,
            args,
        )

        current_lr = optimizer.param_groups[
            0
        ][
            "lr"
        ]

        history.append({
            "Epoch":
                epoch,
            "TrainMSE":
                train_mse,
            "LR":
                current_lr,
            "Seconds":
                time.time()
                - t0,
        })

        pd.DataFrame(
            history
        ).to_csv(
            history_path(
                name,
                horizon,
                fold,
            ),
            index=False,
        )

        print(
            f"Fold direct {name:11s} "
            f"H={horizon:3d} F{fold} "
            f"ep={epoch:02d}/{fixed_epochs} "
            f"train={train_mse:.6f} "
            f"lr={current_lr:.3e}"
        )

    model.eval()

    state = {
        k:
            v.detach()
            .cpu()
            .clone()
        for k, v
        in model.state_dict().items()
    }

    ckpt = {
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Fold":
            fold,
        "Prefix":
            int(
                prefix
            ),
        "FixedEpochs":
            int(
                fixed_epochs
            ),
        "Seed":
            seed,
        "StateDict":
            state,
    }

    torch.save(
        ckpt,
        path,
    )

    return (
        model,
        ckpt,
    )


## 14. Efficient gate-data collection

Direct backbone은 retrieval query batch보다 훨씬 큰 anchor block으로 한 번 계산합니다.

예를 들어 Electricity에서는:

- direct block: 16 anchors
- retrieval sub-batch: 약 2 anchors

따라서 같은 direct forward를 8번 반복하지 않습니다.

이 최적화는 prediction 값이나 training protocol을 바꾸지 않습니다.

In [15]:

@torch.no_grad()
def collect_gate_data(
    data,
    horizon,
    direct_model,
    retriever,
    memory_gpu_obj,
    z,
    anchors,
):
    name = data[
        "name"
    ]

    C = data[
        "n_channels"
    ]

    ret_block = retrieval_anchor_batch(
        name
    )

    direct_block = DIRECT_ANCHOR_BLOCK[
        name
    ]

    features = []
    abcs = []
    anchors_out = []
    channels_out = []

    for outer in range(
        0,
        len(
            anchors
        ),
        direct_block,
    ):
        a_big = anchors[
            outer:
            outer+direct_block
        ]

        direct_big, true_big = (
            direct_residual_block(
                direct_model,
                z,
                data[
                    "marks"
                ],
                a_big,
                horizon,
            )
        )

        # [A, H, C] -> [A, C, H]
        direct_big = direct_big.permute(
            0,
            2,
            1,
        ).contiguous()

        true_big = true_big.permute(
            0,
            2,
            1,
        ).contiguous()

        for inner in range(
            0,
            len(
                a_big
            ),
            ret_block,
        ):
            a = a_big[
                inner:
                inner+ret_block
            ]

            A = len(
                a
            )

            pair_anchor = np.repeat(
                a,
                C,
            )

            pair_channel = np.tile(
                np.arange(
                    C,
                    dtype=np.int64,
                ),
                A,
            )

            r = retrieve(
                retriever,
                memory_gpu_obj,
                z,
                pair_anchor,
                pair_channel,
                horizon,
            )

            retrieval = r[
                "cand"
            ].mean(
                dim=1
            )

            d = direct_big[
                inner:
                inner+A
            ].reshape(
                -1,
                horizon,
            )

            t = true_big[
                inner:
                inner+A
            ].reshape(
                -1,
                horizon,
            )

            # Strong consistency check:
            # direct true residual must match retrieval true residual.
            max_true_diff = float(
                (
                    t
                    - r[
                        "true"
                    ]
                ).abs().max()
            )

            if (
                max_true_diff
                > 2e-5
            ):
                raise RuntimeError(
                    f"True residual mismatch: "
                    f"{max_true_diff}"
                )

            feat = gate_features(
                r,
                retrieval,
                d,
            )

            abc = abc_terms(
                d,
                retrieval,
                t,
            )

            features.append(
                feat.cpu()
                .numpy()
                .astype(
                    np.float32
                )
            )

            abcs.append(
                abc.cpu()
                .numpy()
                .astype(
                    np.float32
                )
            )

            anchors_out.append(
                pair_anchor
            )

            channels_out.append(
                pair_channel
            )

            del (
                r,
                retrieval,
                d,
                t,
                feat,
                abc,
            )

        del (
            direct_big,
            true_big,
        )

    return {
        "feature":
            np.concatenate(
                features,
                axis=0,
            ),
        "abc":
            np.concatenate(
                abcs,
                axis=0,
            ),
        "anchor":
            np.concatenate(
                anchors_out,
                axis=0,
            ),
        "channel":
            np.concatenate(
                channels_out,
                axis=0,
            ),
    }

## 15. OOF and validation feature cache

In [16]:

def oof_cache_path(
    name,
    horizon,
    fold,
):
    return (
        DIRS[
            "oof"
        ]
        / (
            f"{name}_H{horizon}_"
            f"F{fold}_oof.npz"
        )
    )


def val_cache_path(
    name,
    horizon,
):
    return (
        DIRS[
            "validation"
        ]
        / (
            f"{name}_H{horizon}_"
            "validation.npz"
        )
    )


def build_oof_fold(
    data,
    horizon,
    fold,
    p0,
    p1,
    fixed_epochs,
):
    name = data[
        "name"
    ]

    C = data[
        "n_channels"
    ]

    out_path = oof_cache_path(
        name,
        horizon,
        fold,
    )

    if (
        out_path.exists()
        and RESUME
        and not FORCE
    ):
        obj = np.load(
            out_path
        )

        print(
            "Loaded OOF cache:",
            out_path.name,
        )

        return {
            key:
                obj[
                    key
                ]
            for key in [
                "feature",
                "abc",
                "anchor",
                "channel",
            ]
        }

    prefix = int(
        p0
        * data[
            "train_end"
        ]
    )

    oof_end = int(
        p1
        * data[
            "train_end"
        ]
    )

    z, prefix_scaler = prefix_normalize(
        data[
            "raw"
        ],
        prefix,
    )

    direct_model, _ = (
        train_fold_itransformer(
            name,
            horizon,
            z,
            data[
                "marks"
            ],
            prefix,
            fixed_epochs,
            fold,
        )
    )

    retriever, _ = load_frozen_retriever(
        fold_retriever_ckpt_path(
            name,
            horizon,
            fold,
        )
    )

    memory = build_memory(
        z,
        C,
        prefix,
        horizon,
    )

    memory_gpu_obj = memory_gpu_cached(
        name,
        horizon,
        (
            f"F{fold}_"
            f"prefix{prefix}"
        ),
        retriever,
        memory,
        C,
    )

    anchors = eval_anchors(
        prefix,
        oof_end,
        horizon,
        stride=
            OOF_ANCHOR_STRIDE,
    )

    print(
        f"OOF {name} H={horizon} F{fold}: "
        f"prefix={prefix}, "
        f"end={oof_end}, "
        f"anchors={len(anchors)}, "
        f"pairs={len(anchors)*C}, "
        f"memory/C={memory['M']}"
    )

    out = collect_gate_data(
        data,
        horizon,
        direct_model,
        retriever,
        memory_gpu_obj,
        z,
        anchors,
    )

    np.savez_compressed(
        out_path,
        **out,
    )

    del (
        direct_model,
        retriever,
        memory,
        memory_gpu_obj,
        prefix_scaler,
        z,
    )

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return out


def build_validation_cache(
    data,
    horizon,
    direct_model,
    retriever,
):
    name = data[
        "name"
    ]

    C = data[
        "n_channels"
    ]

    path = val_cache_path(
        name,
        horizon,
    )

    if (
        path.exists()
        and RESUME
        and not FORCE
    ):
        obj = np.load(
            path
        )

        print(
            "Loaded validation cache:",
            path.name,
        )

        return {
            key:
                obj[
                    key
                ]
            for key in [
                "feature",
                "abc",
                "anchor",
                "channel",
            ]
        }

    memory = build_memory(
        data[
            "z"
        ],
        C,
        data[
            "train_end"
        ],
        horizon,
    )

    memory_gpu_obj = memory_gpu_cached(
        name,
        horizon,
        "validation_train_memory",
        retriever,
        memory,
        C,
    )

    anchors = eval_anchors(
        data[
            "train_end"
        ],
        data[
            "val_end"
        ],
        horizon,
        stride=1,
    )

    print(
        f"Validation {name} H={horizon}: "
        f"anchors={len(anchors)}, "
        f"pairs={len(anchors)*C}, "
        f"memory/C={memory['M']}"
    )

    out = collect_gate_data(
        data,
        horizon,
        direct_model,
        retriever,
        memory_gpu_obj,
        data[
            "z"
        ],
        anchors,
    )

    np.savez_compressed(
        path,
        **out,
    )

    del (
        memory,
        memory_gpu_obj,
    )

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return out

## 16. Cross-fitted gate and validation-only calibration

In [17]:

def fit_feature_scaler(
    x,
):
    median = np.median(
        x,
        axis=0,
    ).astype(
        np.float32
    )

    q25 = np.percentile(
        x,
        25,
        axis=0,
    )

    q75 = np.percentile(
        x,
        75,
        axis=0,
    )

    iqr = (
        q75
        - q25
    ).astype(
        np.float32
    )

    iqr = np.where(
        iqr < 1e-5,
        1.0,
        iqr,
    ).astype(
        np.float32
    )

    return (
        median,
        iqr,
    )


def scale_features(
    x,
    median,
    iqr,
):
    return np.clip(
        (
            x
            - median
        )
        / iqr,
        -8.0,
        8.0,
    ).astype(
        np.float32
    )


def gate_loss(
    alpha,
    abc,
):
    return (
        abc[
            :,
            0
        ]
        + 2.0
        * alpha
        * abc[
            :,
            1
        ]
        + alpha
        * alpha
        * abc[
            :,
            2
        ]
    ).mean()


def gate_checkpoint_path(
    name,
    horizon,
):
    return (
        DIRS[
            "gate"
        ]
        / (
            f"{name}_H{horizon}_"
            "gate.pt"
        )
    )


def train_gate_epoch(
    model,
    optimizer,
    x,
    abc,
    rng,
):
    model.train()

    order = rng.permutation(
        len(
            x
        )
    )

    losses = []

    for i in range(
        0,
        len(
            order
        ),
        GATE_BATCH,
    ):
        ids = order[
            i:
            i+GATE_BATCH
        ]

        xt = torch.from_numpy(
            x[
                ids
            ]
        ).to(
            DEVICE
        )

        at = torch.from_numpy(
            abc[
                ids
            ]
        ).to(
            DEVICE
        )

        optimizer.zero_grad(
            set_to_none=True
        )

        alpha = model(
            xt
        )

        loss = gate_loss(
            alpha,
            at,
        )

        loss.backward()
        optimizer.step()

        losses.append(
            float(
                loss.item()
            )
        )

        del (
            xt,
            at,
            alpha,
            loss,
        )

    return float(
        np.mean(
            losses
        )
    )


@torch.no_grad()
def evaluate_gate(
    model,
    x,
    abc,
):
    model.eval()

    total = 0.0
    n = 0
    alpha_sum = 0.0

    for i in range(
        0,
        len(
            x
        ),
        GATE_BATCH,
    ):
        xt = torch.from_numpy(
            x[
                i:
                i+GATE_BATCH
            ]
        ).to(
            DEVICE
        )

        at = torch.from_numpy(
            abc[
                i:
                i+GATE_BATCH
            ]
        ).to(
            DEVICE
        )

        alpha = model(
            xt
        )

        each = (
            at[
                :,
                0
            ]
            + 2.0
            * alpha
            * at[
                :,
                1
            ]
            + alpha
            * alpha
            * at[
                :,
                2
            ]
        )

        total += float(
            each.sum()
        )

        n += len(
            alpha
        )

        alpha_sum += float(
            alpha.sum()
        )

        del (
            xt,
            at,
            alpha,
            each,
        )

    return (
        total
        / n,
        alpha_sum
        / n,
    )


def train_crossfit_gate(
    name,
    horizon,
    oof_x,
    oof_abc,
    val_x,
    val_abc,
):
    path = gate_checkpoint_path(
        name,
        horizon,
    )

    if (
        path.exists()
        and RESUME
        and not FORCE
    ):
        ckpt = load_torch(
            path
        )

        model = CrossFitAdaptiveGate().to(
            DEVICE
        )

        model.load_state_dict(
            ckpt[
                "StateDict"
            ]
        )

        model.eval()

        print(
            "Loaded gate:",
            path.name,
        )

        return (
            model,
            ckpt,
        )

    median, iqr = fit_feature_scaler(
        oof_x
    )

    train_x = scale_features(
        oof_x,
        median,
        iqr,
    )

    valid_x = scale_features(
        val_x,
        median,
        iqr,
    )

    seed = (
        CROSSFIT_SEED
        + horizon
        * 3000
        + sum(
            map(
                ord,
                name,
            )
        )
    )

    set_seed(
        seed
    )

    model = CrossFitAdaptiveGate().to(
        DEVICE
    )

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=GATE_LR,
        weight_decay=GATE_WD,
    )

    rng = np.random.default_rng(
        seed
        + 1
    )

    best = float(
        "inf"
    )

    best_epoch = -1
    wait = 0
    history = []

    for epoch in range(
        1,
        GATE_MAX_EPOCHS
        + 1,
    ):
        train_mse = train_gate_epoch(
            model,
            optimizer,
            train_x,
            oof_abc,
            rng,
        )

        val_mse, mean_alpha = evaluate_gate(
            model,
            valid_x,
            val_abc,
        )

        history.append({
            "Epoch":
                epoch,
            "OOFTrainMSE":
                train_mse,
            "ValMSE":
                val_mse,
            "ValMeanAlpha":
                mean_alpha,
        })

        if (
            val_mse
            < best
            - 1e-10
        ):
            best = val_mse
            best_epoch = epoch
            wait = 0
        else:
            wait += 1

        print(
            f"Gate {name:11s} H={horizon:3d} "
            f"ep={epoch:02d} "
            f"OOF={train_mse:.6f} "
            f"val={val_mse:.6f} "
            f"alpha={mean_alpha:.3f} "
            f"best={best:.6f}@{best_epoch}"
        )

        if (
            wait
            >= GATE_PATIENCE
        ):
            break

    # Reinitialize and fit only on OOF for the
    # validation-selected number of epochs.
    set_seed(
        seed
    )

    final = CrossFitAdaptiveGate().to(
        DEVICE
    )

    final_opt = torch.optim.AdamW(
        final.parameters(),
        lr=GATE_LR,
        weight_decay=GATE_WD,
    )

    final_rng = np.random.default_rng(
        seed
        + 2
    )

    for _ in range(
        best_epoch
    ):
        train_gate_epoch(
            final,
            final_opt,
            train_x,
            oof_abc,
            final_rng,
        )

    final.eval()

    ckpt = {
        "BestEpoch":
            best_epoch,
        "BestValMSE":
            best,
        "FeatureMedian":
            median,
        "FeatureIQR":
            iqr,
        "StateDict": {
            k:
                v.detach()
                .cpu()
                .clone()
            for k, v
            in final.state_dict().items()
        },
    }

    torch.save(
        ckpt,
        path,
    )

    pd.DataFrame(
        history
    ).to_csv(
        DIRS[
            "history"
        ]
        / (
            f"{name}_H{horizon}_"
            "gate_history.csv"
        ),
        index=False,
    )

    return (
        final,
        ckpt,
    )


def mse_scalar(
    abc,
    alpha,
):
    A = abc.astype(
        np.float64
    )

    x = float(
        alpha
    )

    return float(
        np.mean(
            A[
                :,
                0
            ]
            + 2.0
            * x
            * A[
                :,
                1
            ]
            + x
            * x
            * A[
                :,
                2
            ]
        )
    )


def choose_scalar(
    abc,
):
    rows = []

    best_alpha = None
    best_mse = float(
        "inf"
    )

    for alpha in ALPHA_GRID:
        mse = mse_scalar(
            abc,
            alpha,
        )

        rows.append({
            "Alpha":
                float(
                    alpha
                ),
            "MSE":
                mse,
        })

        if (
            mse
            < best_mse
            - 1e-10
        ):
            best_mse = mse
            best_alpha = float(
                alpha
            )

    return (
        best_alpha,
        pd.DataFrame(
            rows
        ),
    )


@torch.no_grad()
def gate_alpha(
    model,
    ckpt,
    x,
):
    sx = scale_features(
        x,
        ckpt[
            "FeatureMedian"
        ],
        ckpt[
            "FeatureIQR"
        ],
    )

    outputs = []

    for i in range(
        0,
        len(
            sx
        ),
        GATE_BATCH,
    ):
        t = torch.from_numpy(
            sx[
                i:
                i+GATE_BATCH
            ]
        ).to(
            DEVICE
        )

        outputs.append(
            model(
                t
            ).cpu()
            .numpy()
        )

        del t

    return np.concatenate(
        outputs
    ).astype(
        np.float32
    )


def mse_pair(
    abc,
    alpha,
):
    A = abc.astype(
        np.float64
    )

    x = np.asarray(
        alpha,
        dtype=np.float64,
    )

    return float(
        np.mean(
            A[
                :,
                0
            ]
            + 2.0
            * x
            * A[
                :,
                1
            ]
            + x
            * x
            * A[
                :,
                2
            ]
        )
    )


def choose_lambda(
    abc,
    gate_alpha_values,
    scalar_alpha,
):
    rows = []

    best_lambda = None
    best_mse = float(
        "inf"
    )

    for lmb in LAMBDA_GRID:
        alpha = (
            (
                1.0
                - float(
                    lmb
                )
            )
            * scalar_alpha
            + float(
                lmb
            )
            * gate_alpha_values
        )

        mse = mse_pair(
            abc,
            alpha,
        )

        rows.append({
            "Lambda":
                float(
                    lmb
                ),
            "MSE":
                mse,
            "MeanAlpha":
                float(
                    alpha.mean()
                ),
        })

        if (
            mse
            < best_mse
            - 1e-10
        ):
            best_mse = mse
            best_lambda = float(
                lmb
            )

    return (
        best_lambda,
        pd.DataFrame(
            rows
        ),
    )

## 17. Final test and Oracle diagnostic

In [18]:

def empty_stat():
    return {
        "sse":
            0.0,
        "sae":
            0.0,
        "n":
            0,
    }


def update_stat(
    stat,
    pred,
    true,
):
    e = (
        pred
        - true
    )

    stat[
        "sse"
    ] += float(
        (
            e
            * e
        ).sum()
    )

    stat[
        "sae"
    ] += float(
        e.abs().sum()
    )

    stat[
        "n"
    ] += e.numel()


def finish_stat(
    stat,
):
    return (
        stat[
            "sse"
        ]
        / stat[
            "n"
        ],
        stat[
            "sae"
        ]
        / stat[
            "n"
        ],
    )


def oracle_alpha_and_prediction(
    direct,
    retrieval,
    true,
):
    e = (
        direct
        - true
    )

    delta = (
        retrieval
        - direct
    )

    alpha = torch.clamp(
        -(
            e
            * delta
        ).sum(
            dim=1
        )
        / (
            (
                delta
                * delta
            ).sum(
                dim=1
            )
            + 1e-8
        ),
        0.0,
        1.0,
    )

    pred = (
        direct
        + alpha[
            :,
            None
        ]
        * delta
    )

    return (
        alpha,
        pred,
    )


@torch.no_grad()
def test_evaluate(
    data,
    horizon,
    direct_model,
    retriever,
    memory_gpu_obj,
    gate,
    gate_ckpt,
    scalar_alpha,
    shrink_lambda,
):
    name = data[
        "name"
    ]

    C = data[
        "n_channels"
    ]

    direct_block = DIRECT_ANCHOR_BLOCK[
        name
    ]

    ret_block = retrieval_anchor_batch(
        name
    )

    anchors = eval_anchors(
        data[
            "val_end"
        ],
        data[
            "test_end"
        ],
        horizon,
        stride=1,
    )

    keys = [
        "Direct",
        "Retrieval",
        "Scalar",
        "RawAdaptive",
        "ShrinkAdaptive",
        "Oracle",
    ]

    stats = {
        key:
            empty_stat()
        for key in keys
    }

    anchor_mse = {
        key:
            []
        for key in keys
    }

    channel_sse_direct = np.zeros(
        C,
        dtype=np.float64,
    )

    channel_sse_shrink = np.zeros(
        C,
        dtype=np.float64,
    )

    channel_count = np.zeros(
        C,
        dtype=np.int64,
    )

    raw_alpha_sum = 0.0
    shrink_alpha_sum = 0.0
    oracle_alpha_sum = 0.0
    oracle_positive = 0
    n_pairs = 0

    processed = 0

    for outer in range(
        0,
        len(
            anchors
        ),
        direct_block,
    ):
        a_big = anchors[
            outer:
            outer+direct_block
        ]

        direct_big, true_big = (
            direct_residual_block(
                direct_model,
                data[
                    "z"
                ],
                data[
                    "marks"
                ],
                a_big,
                horizon,
            )
        )

        direct_big = direct_big.permute(
            0,
            2,
            1,
        ).contiguous()

        true_big = true_big.permute(
            0,
            2,
            1,
        ).contiguous()

        # anchor-level MSE accumulators within this direct block
        block_anchor_sums = {
            key:
                torch.zeros(
                    len(
                        a_big
                    ),
                    device=DEVICE,
                    dtype=torch.float64,
                )
            for key in keys
        }

        for inner in range(
            0,
            len(
                a_big
            ),
            ret_block,
        ):
            a = a_big[
                inner:
                inner+ret_block
            ]

            A = len(
                a
            )

            pair_anchor = np.repeat(
                a,
                C,
            )

            pair_channel = np.tile(
                np.arange(
                    C,
                    dtype=np.int64,
                ),
                A,
            )

            r = retrieve(
                retriever,
                memory_gpu_obj,
                data[
                    "z"
                ],
                pair_anchor,
                pair_channel,
                horizon,
            )

            retrieval = r[
                "cand"
            ].mean(
                dim=1
            )

            direct = direct_big[
                inner:
                inner+A
            ].reshape(
                -1,
                horizon,
            )

            true = true_big[
                inner:
                inner+A
            ].reshape(
                -1,
                horizon,
            )

            scalar = (
                direct
                + scalar_alpha
                * (
                    retrieval
                    - direct
                )
            )

            features = gate_features(
                r,
                retrieval,
                direct,
            ).cpu().numpy().astype(
                np.float32
            )

            scaled = scale_features(
                features,
                gate_ckpt[
                    "FeatureMedian"
                ],
                gate_ckpt[
                    "FeatureIQR"
                ],
            )

            gate_alpha_values = gate(
                torch.from_numpy(
                    scaled
                ).to(
                    DEVICE
                )
            )

            shrink_alpha_values = (
                (
                    1.0
                    - shrink_lambda
                )
                * scalar_alpha
                + shrink_lambda
                * gate_alpha_values
            )

            raw_adaptive = (
                direct
                + gate_alpha_values[
                    :,
                    None
                ]
                * (
                    retrieval
                    - direct
                )
            )

            shrink_adaptive = (
                direct
                + shrink_alpha_values[
                    :,
                    None
                ]
                * (
                    retrieval
                    - direct
                )
            )

            (
                oracle_alpha,
                oracle,
            ) = oracle_alpha_and_prediction(
                direct,
                retrieval,
                true,
            )

            predictions = {
                "Direct":
                    direct,
                "Retrieval":
                    retrieval,
                "Scalar":
                    scalar,
                "RawAdaptive":
                    raw_adaptive,
                "ShrinkAdaptive":
                    shrink_adaptive,
                "Oracle":
                    oracle,
            }

            for key, pred in predictions.items():
                update_stat(
                    stats[
                        key
                    ],
                    pred,
                    true,
                )

                per_anchor = (
                    (
                        (
                            pred
                            - true
                        )
                        ** 2
                    )
                    .reshape(
                        A,
                        C,
                        horizon,
                    )
                    .mean(
                        dim=(
                            1,
                            2,
                        )
                    )
                    .double()
                )

                block_anchor_sums[
                    key
                ][
                    inner:
                    inner+A
                ] = per_anchor

            direct_e2 = (
                (
                    direct
                    - true
                )
                ** 2
            ).reshape(
                A,
                C,
                horizon,
            )

            shrink_e2 = (
                (
                    shrink_adaptive
                    - true
                )
                ** 2
            ).reshape(
                A,
                C,
                horizon,
            )

            channel_sse_direct += (
                direct_e2.sum(
                    dim=(
                        0,
                        2,
                    )
                ).cpu()
                .numpy()
            )

            channel_sse_shrink += (
                shrink_e2.sum(
                    dim=(
                        0,
                        2,
                    )
                ).cpu()
                .numpy()
            )

            channel_count += (
                A
                * horizon
            )

            raw_alpha_sum += float(
                gate_alpha_values.sum()
            )

            shrink_alpha_sum += float(
                shrink_alpha_values.sum()
            )

            oracle_alpha_sum += float(
                oracle_alpha.sum()
            )

            oracle_positive += int(
                (
                    oracle_alpha
                    > 0.01
                ).sum()
            )

            n_pairs += len(
                gate_alpha_values
            )

            del (
                r,
                retrieval,
                direct,
                true,
                scalar,
                features,
                scaled,
                gate_alpha_values,
                shrink_alpha_values,
                raw_adaptive,
                shrink_adaptive,
                oracle_alpha,
                oracle,
                predictions,
                direct_e2,
                shrink_e2,
            )

        for key in keys:
            anchor_mse[
                key
            ].extend(
                block_anchor_sums[
                    key
                ].cpu()
                .numpy()
                .astype(
                    np.float32
                )
                .tolist()
            )

        processed += len(
            a_big
        )

        if (
            processed
            == len(
                a_big
            )
            or processed
            % 500
            < len(
                a_big
            )
            or processed
            == len(
                anchors
            )
        ):
            print(
                f"  test anchors "
                f"{processed}/{len(anchors)}"
            )

        del (
            direct_big,
            true_big,
            block_anchor_sums,
        )

    return {
        "anchors":
            anchors,
        "metrics": {
            key:
                finish_stat(
                    value
                )
            for key, value
            in stats.items()
        },
        "anchor_mse": {
            key:
                np.asarray(
                    value,
                    dtype=np.float32,
                )
            for key, value
            in anchor_mse.items()
        },
        "channel_direct_mse":
            channel_sse_direct
            / channel_count,
        "channel_shrink_mse":
            channel_sse_shrink
            / channel_count,
        "raw_mean_alpha":
            raw_alpha_sum
            / n_pairs,
        "shrink_mean_alpha":
            shrink_alpha_sum
            / n_pairs,
        "oracle_mean_alpha":
            oracle_alpha_sum
            / n_pairs,
        "oracle_positive_fraction":
            oracle_positive
            / n_pairs,
    }

## 18. Paired moving-block bootstrap

In [19]:

def moving_block_bootstrap(
    difference,
    n_boot=5000,
    block=24,
    seed=222222,
):
    x = np.asarray(
        difference,
        dtype=np.float64,
    )

    n = len(
        x
    )

    L = min(
        block,
        n,
    )

    rng = np.random.default_rng(
        seed
    )

    n_blocks = int(
        np.ceil(
            n
            / L
        )
    )

    max_start = max(
        1,
        n
        - L
        + 1,
    )

    boot = np.empty(
        n_boot,
        dtype=np.float64,
    )

    for b in range(
        n_boot
    ):
        starts = rng.integers(
            0,
            max_start,
            size=n_blocks,
        )

        sample = np.concatenate(
            [
                x[
                    s:
                    s+L
                ]
                for s in starts
            ]
        )[
            :n
        ]

        boot[
            b
        ] = sample.mean()

    return {
        "MeanImprovement":
            float(
                x.mean()
            ),
        "CI_Low":
            float(
                np.quantile(
                    boot,
                    0.025,
                )
            ),
        "CI_High":
            float(
                np.quantile(
                    boot,
                    0.975,
                )
            ),
    }


# 19. Main Experiment

각 dataset × horizon에서 다음을 수행합니다.

1. Experiment 21 full iTransformer load
2. Experiment 13 frozen full retriever load
3. three chronological OOF folds
4. cross-fitted gate
5. validation scalar / shrinkage calibration
6. static train+validation retrieval memory
7. all-window test
8. Oracle diagnostic
9. moving-block bootstrap
10. per-channel diagnostic
11. condition별 즉시 저장

중간 결과를 본 뒤 method를 변경하지 않습니다.

In [20]:

SUMMARY_PATH = (
    ROOT
    / "summary.csv"
)

BOOTSTRAP_PATH = (
    ROOT
    / "bootstrap.csv"
)

FOLD_PATH = (
    ROOT
    / "folds.csv"
)

existing = (
    pd.read_csv(
        SUMMARY_PATH
    )
    if (
        RESUME
        and SUMMARY_PATH.exists()
    )
    else pd.DataFrame()
)

summary_rows = (
    existing.to_dict(
        "records"
    )
    if len(
        existing
    )
    else []
)

bootstrap_rows = (
    pd.read_csv(
        BOOTSTRAP_PATH
    ).to_dict(
        "records"
    )
    if (
        RESUME
        and BOOTSTRAP_PATH.exists()
    )
    else []
)

fold_rows = (
    pd.read_csv(
        FOLD_PATH
    ).to_dict(
        "records"
    )
    if (
        RESUME
        and FOLD_PATH.exists()
    )
    else []
)


def already_done(
    name,
    horizon,
):
    if not len(
        existing
    ):
        return False

    return bool(
        (
            (
                existing[
                    "Dataset"
                ]
                == name
            )
            & (
                existing[
                    "Horizon"
                ]
                == horizon
            )
        ).any()
    )


for name, horizon in TASKS:
    if already_done(
        name,
        horizon,
    ):
        print(
            f"SKIP completed: "
            f"{name} H={horizon}"
        )
        continue

    start_time = time.time()

    data = DATA[
        name
    ]

    C = data[
        "n_channels"
    ]

    print(
        "\n"
        + "#"
        * 150
    )

    print(
        f"{name} | H={horizon} | "
        "iTransformer + FROZEN HISTORICAL MEMORY"
    )

    print(
        "#"
        * 150
    )

    # --------------------------------------------------------
    # 1. Frozen strong full direct.
    # --------------------------------------------------------
    direct_model, direct_ckpt = load_exp21_direct(
        name,
        horizon,
    )

    ref = exp21_reference(
        name,
        horizon,
    )

    direct_epochs = int(
        direct_ckpt[
            "BestEpoch"
        ]
    )

    print(
        f"Experiment 21 direct: "
        f"MSE={float(ref['Test_MSE']):.6f}, "
        f"MAE={float(ref['Test_MAE']):.6f}, "
        f"best_epoch={direct_epochs}"
    )

    # --------------------------------------------------------
    # 2. Frozen full retriever.
    # --------------------------------------------------------
    retriever, retriever_ckpt = load_frozen_retriever(
        full_retriever_ckpt_path(
            name,
            horizon,
        )
    )

    # --------------------------------------------------------
    # 3. OOF cross-fitting.
    # --------------------------------------------------------
    oof_parts = []

    for fold, (
        p0,
        p1,
    ) in enumerate(
        FOLDS,
        start=1,
    ):
        part = build_oof_fold(
            data,
            horizon,
            fold,
            p0,
            p1,
            direct_epochs,
        )

        oof_parts.append(
            part
        )

        fold_rows = [
            r
            for r in fold_rows
            if not (
                r.get(
                    "Dataset"
                )
                == name
                and int(
                    r.get(
                        "Horizon",
                        -1,
                    )
                )
                == horizon
                and int(
                    r.get(
                        "Fold",
                        -1,
                    )
                )
                == fold
            )
        ]

        fold_rows.append({
            "Dataset":
                name,
            "Horizon":
                horizon,
            "Fold":
                fold,
            "PrefixFrac":
                p0,
            "OOFEndFrac":
                p1,
            "Pairs":
                len(
                    part[
                        "feature"
                    ]
                ),
            "Anchors":
                len(
                    np.unique(
                        part[
                            "anchor"
                        ]
                    )
                ),
            "DirectFixedEpochs":
                direct_epochs,
            "RetrieverCheckpoint":
                str(
                    fold_retriever_ckpt_path(
                        name,
                        horizon,
                        fold,
                    )
                ),
        })

        pd.DataFrame(
            fold_rows
        ).to_csv(
            FOLD_PATH,
            index=False,
        )

    oof_x = np.concatenate(
        [
            p[
                "feature"
            ]
            for p in oof_parts
        ],
        axis=0,
    )

    oof_abc = np.concatenate(
        [
            p[
                "abc"
            ]
            for p in oof_parts
        ],
        axis=0,
    )

    print(
        "Total OOF pairs:",
        len(
            oof_x
        ),
    )

    # --------------------------------------------------------
    # 4. Validation.
    # --------------------------------------------------------
    val_data = build_validation_cache(
        data,
        horizon,
        direct_model,
        retriever,
    )

    gate, gate_ckpt = train_crossfit_gate(
        name,
        horizon,
        oof_x,
        oof_abc,
        val_data[
            "feature"
        ],
        val_data[
            "abc"
        ],
    )

    scalar_alpha, scalar_curve = choose_scalar(
        val_data[
            "abc"
        ]
    )

    raw_val_alpha = gate_alpha(
        gate,
        gate_ckpt,
        val_data[
            "feature"
        ],
    )

    shrink_lambda, lambda_curve = choose_lambda(
        val_data[
            "abc"
        ],
        raw_val_alpha,
        scalar_alpha,
    )

    scalar_curve.to_csv(
        DIRS[
            "calibration"
        ]
        / (
            f"{name}_H{horizon}_"
            "scalar_alpha.csv"
        ),
        index=False,
    )

    lambda_curve.to_csv(
        DIRS[
            "calibration"
        ]
        / (
            f"{name}_H{horizon}_"
            "shrink_lambda.csv"
        ),
        index=False,
    )

    print(
        f"Validation calibration | "
        f"alpha0={scalar_alpha:.2f} | "
        f"lambda={shrink_lambda:.2f} | "
        f"gateEpoch={gate_ckpt['BestEpoch']}"
    )

    del (
        oof_x,
        oof_abc,
        oof_parts,
        raw_val_alpha,
        val_data,
    )

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # --------------------------------------------------------
    # 5. Static test retrieval memory: train + validation only.
    # --------------------------------------------------------
    test_memory = build_memory(
        data[
            "z"
        ],
        C,
        data[
            "val_end"
        ],
        horizon,
    )

    test_memory_gpu = memory_gpu_cached(
        name,
        horizon,
        "test_trainval_memory",
        retriever,
        test_memory,
        C,
    )

    test = test_evaluate(
        data,
        horizon,
        direct_model,
        retriever,
        test_memory_gpu,
        gate,
        gate_ckpt,
        scalar_alpha,
        shrink_lambda,
    )

    metrics = test[
        "metrics"
    ]

    (
        direct_mse,
        direct_mae,
    ) = metrics[
        "Direct"
    ]

    (
        retrieval_mse,
        retrieval_mae,
    ) = metrics[
        "Retrieval"
    ]

    (
        scalar_mse,
        scalar_mae,
    ) = metrics[
        "Scalar"
    ]

    (
        raw_mse,
        raw_mae,
    ) = metrics[
        "RawAdaptive"
    ]

    (
        shrink_mse,
        shrink_mae,
    ) = metrics[
        "ShrinkAdaptive"
    ]

    (
        oracle_mse,
        oracle_mae,
    ) = metrics[
        "Oracle"
    ]

    exp21_mse = float(
        ref[
            "Test_MSE"
        ]
    )

    exp21_mae = float(
        ref[
            "Test_MAE"
        ]
    )

    parity_diff = abs(
        direct_mse
        - exp21_mse
    )

    if (
        parity_diff
        >= DIRECT_PARITY_TOL
    ):
        raise RuntimeError(
            f"Final direct parity failed for "
            f"{name} H={horizon}: "
            f"{parity_diff}"
        )

    # --------------------------------------------------------
    # 6. Paired bootstrap.
    # --------------------------------------------------------
    bootstrap_rows = [
        r
        for r in bootstrap_rows
        if not (
            r.get(
                "Dataset"
            )
            == name
            and int(
                r.get(
                    "Horizon",
                    -1,
                )
            )
            == horizon
        )
    ]

    b_direct = moving_block_bootstrap(
        test[
            "anchor_mse"
        ][
            "Direct"
        ]
        - test[
            "anchor_mse"
        ][
            "ShrinkAdaptive"
        ],
        seed=
            222222
            + horizon
            + sum(
                map(
                    ord,
                    name,
                )
            ),
    )

    bootstrap_rows.append({
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Comparison":
            "Direct-ShrinkAdaptive",
        **b_direct,
        "SignificantPositive":
            b_direct[
                "CI_Low"
            ]
            > 0.0,
    })

    b_scalar = moving_block_bootstrap(
        test[
            "anchor_mse"
        ][
            "Scalar"
        ]
        - test[
            "anchor_mse"
        ][
            "ShrinkAdaptive"
        ],
        seed=
            333333
            + horizon
            + sum(
                map(
                    ord,
                    name,
                )
            ),
    )

    bootstrap_rows.append({
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Comparison":
            "Scalar-ShrinkAdaptive",
        **b_scalar,
        "SignificantPositive":
            b_scalar[
                "CI_Low"
            ]
            > 0.0,
    })

    pd.DataFrame(
        bootstrap_rows
    ).to_csv(
        BOOTSTRAP_PATH,
        index=False,
    )

    # --------------------------------------------------------
    # 7. Per-channel diagnostic.
    # --------------------------------------------------------
    channel_df = pd.DataFrame({
        "ChannelIndex":
            np.arange(
                C
            ),
        "ChannelName":
            data[
                "columns"
            ],
        "Direct_MSE":
            test[
                "channel_direct_mse"
            ],
        "ShrinkAdaptive_MSE":
            test[
                "channel_shrink_mse"
            ],
    })

    channel_df[
        "Improvement"
    ] = (
        channel_df[
            "Direct_MSE"
        ]
        - channel_df[
            "ShrinkAdaptive_MSE"
        ]
    )

    channel_df[
        "Improvement_pct"
    ] = (
        100.0
        * channel_df[
            "Improvement"
        ]
        / channel_df[
            "Direct_MSE"
        ]
    )

    channel_df.to_csv(
        DIRS[
            "channel"
        ]
        / (
            f"{name}_H{horizon}_"
            "channel_mse.csv"
        ),
        index=False,
    )

    improved_channel_fraction = float(
        (
            channel_df[
                "Improvement"
            ]
            > 0.0
        ).mean()
    )

    # --------------------------------------------------------
    # 8. Save anchor-level paired losses.
    # --------------------------------------------------------
    np.savez_compressed(
        DIRS[
            "paired"
        ]
        / (
            f"{name}_H{horizon}_"
            "anchor_mse.npz"
        ),
        TestAnchors=
            test[
                "anchors"
            ],
        Direct=
            test[
                "anchor_mse"
            ][
                "Direct"
            ],
        Retrieval=
            test[
                "anchor_mse"
            ][
                "Retrieval"
            ],
        Scalar=
            test[
                "anchor_mse"
            ][
                "Scalar"
            ],
        RawAdaptive=
            test[
                "anchor_mse"
            ][
                "RawAdaptive"
            ],
        ShrinkAdaptive=
            test[
                "anchor_mse"
            ][
                "ShrinkAdaptive"
            ],
        Oracle=
            test[
                "anchor_mse"
            ][
                "Oracle"
            ],
    )

    # --------------------------------------------------------
    # 9. Final summary.
    # --------------------------------------------------------
    row = {
        "Dataset":
            name,
        "Horizon":
            horizon,
        "Channels":
            C,
        "iTransformer_MSE":
            direct_mse,
        "iTransformer_MAE":
            direct_mae,
        "Experiment21Reference_MSE":
            exp21_mse,
        "Experiment21Reference_MAE":
            exp21_mae,
        "DirectParityAbsDiff":
            parity_diff,
        "Retrieval_MSE":
            retrieval_mse,
        "Retrieval_MAE":
            retrieval_mae,
        "ScalarAlpha":
            scalar_alpha,
        "Scalar_MSE":
            scalar_mse,
        "Scalar_MAE":
            scalar_mae,
        "RawAdaptive_MSE":
            raw_mse,
        "RawAdaptive_MAE":
            raw_mae,
        "ShrinkLambda":
            shrink_lambda,
        "ShrinkAdaptive_MSE":
            shrink_mse,
        "ShrinkAdaptive_MAE":
            shrink_mae,
        "Oracle_MSE":
            oracle_mse,
        "Oracle_MAE":
            oracle_mae,
        "RawMeanAlpha":
            test[
                "raw_mean_alpha"
            ],
        "ShrinkMeanAlpha":
            test[
                "shrink_mean_alpha"
            ],
        "OracleMeanAlpha":
            test[
                "oracle_mean_alpha"
            ],
        "OraclePositiveFraction":
            test[
                "oracle_positive_fraction"
            ],
        "ImprovedChannelFraction":
            improved_channel_fraction,
        "ScalarGainVsDirect_pct":
            (
                100.0
                * (
                    direct_mse
                    - scalar_mse
                )
                / direct_mse
            ),
        "ShrinkGainVsDirect_pct":
            (
                100.0
                * (
                    direct_mse
                    - shrink_mse
                )
                / direct_mse
            ),
        "ShrinkGainVsScalar_pct":
            (
                100.0
                * (
                    scalar_mse
                    - shrink_mse
                )
                / scalar_mse
            ),
        "OracleHeadroomFromDirect_pct":
            (
                100.0
                * (
                    direct_mse
                    - oracle_mse
                )
                / direct_mse
            ),
        "OracleHeadroomFromShrink_pct":
            (
                100.0
                * (
                    shrink_mse
                    - oracle_mse
                )
                / shrink_mse
            ),
        "DirectBestEpoch":
            direct_epochs,
        "FrozenRetrieverBestEpoch":
            retriever_ckpt.get(
                "BestEpoch",
                np.nan,
            ),
        "GateBestEpoch":
            int(
                gate_ckpt[
                    "BestEpoch"
                ]
            ),
        "TestMemoryPerChannel":
            int(
                test_memory[
                    "M"
                ]
            ),
        "TestWindows":
            len(
                test[
                    "anchors"
                ]
            ),
        "RuntimeMinutes":
            (
                time.time()
                - start_time
            )
            / 60.0,
    }

    summary_rows = [
        r
        for r in summary_rows
        if not (
            r.get(
                "Dataset"
            )
            == name
            and int(
                r.get(
                    "Horizon",
                    -1,
                )
            )
            == horizon
        )
    ]

    summary_rows.append(
        row
    )

    pd.DataFrame(
        summary_rows
    ).to_csv(
        SUMMARY_PATH,
        index=False,
    )

    print(
        "\nFINAL CONDITION RESULT"
    )

    display(
        pd.DataFrame([
            row
        ])[
            [
                "Dataset",
                "Horizon",
                "iTransformer_MSE",
                "ShrinkAdaptive_MSE",
                "ShrinkGainVsDirect_pct",
                "iTransformer_MAE",
                "ShrinkAdaptive_MAE",
                "Retrieval_MSE",
                "Scalar_MSE",
                "RawAdaptive_MSE",
                "Oracle_MSE",
                "ScalarAlpha",
                "ShrinkLambda",
                "ShrinkMeanAlpha",
                "ImprovedChannelFraction",
                "OracleHeadroomFromDirect_pct",
                "RuntimeMinutes",
            ]
        ]
    )

    del (
        direct_model,
        direct_ckpt,
        retriever,
        retriever_ckpt,
        gate,
        gate_ckpt,
        test_memory,
        test_memory_gpu,
        test,
        channel_df,
    )

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()


summary_df = (
    pd.DataFrame(
        summary_rows
    )
    .sort_values(
        [
            "Dataset",
            "Horizon",
        ]
    )
    .reset_index(
        drop=True
    )
)

display(
    summary_df
)

######################################################################################################################################################
ETTm1 | H=96 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.336712, MAE=0.373422, best_epoch=1
Updating learning rate to 0.0001
Fold direct ETTm1       H= 96 F1 ep=01/1 train=0.340237 lr=1.000e-04
Building memory embedding: ETTm1_H96_F1_prefix19008_emb.npy (7, 785, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=96 F1: prefix=19008, end=24192, anchors=1273, pairs=8911, memory/C=785
Updating learning rate to 0.0001
Fold direct ETTm1       H= 96 F2 ep=01/1 train=0.304745 lr=1.000e-04
Building memory embedding: ETTm1_H96_F2_prefix24192_emb.npy (7, 1001, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=96 F2: prefix=24192, end=29376, anchors=1273, pairs=8911, memory/C=1001
Updating learning rate to 0.0001
Fold direct ETTm1       H= 96 F3 ep=01/1 train=0.302197 lr=1.000e-04
Building memory embedding: ETTm1_H96_F3_prefix29376_emb.npy (7, 1217, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=96 F3: prefix=29376, end=34560, anchors=1273, pairs=8911, memory/C=1217
Total OOF pairs: 26733
Building memory embedding: ETTm1_H96_validation_train_memory_emb.npy (7, 1433, 64)
  channel 1/7
  channel 7/7
Validation ETTm1 H=96: anchors=11425, pairs=79975, memory/C=1433
Gate ETTm1       H= 96 ep=01 OOF=0.620792 val=0.402003 alpha=0.099 best=0.402003@1
Gate ETTm1       H= 96 ep=02 OOF=0.629087 val=0.401533 alpha=0.097 best=0.401533@2
Gate ETTm1       H= 96 ep=03 OOF=0.624783 val=0.400939 alpha=0.095 best=0.400939@3
Gate ETTm1       H= 96 ep=04 OOF=0.623582 val=0.400246 alpha=0.093 best=0.400246@4
Gate ETTm1       H= 96 ep=05 OOF=0.627614 val=0.399481 alpha=0.090 best=0.399481@5
Gate ETTm1       H= 96 ep=06 OOF=0.618354 val=0.398681 alpha=0.087 best=0.398681@6
Gate ETTm1       H= 96 ep=07 OOF=0.617824 val=0.397908 alpha=0.084 best=0.397908@7
Gate ETTm1       H= 96 ep=08 OOF=0.611668 val=0.397222 alpha=0.080 best=0.397222@8
Gate ETTm1       H= 96 ep=09 OOF=0.615801 val=0.396660 alpha=0.077 best=0.396660@9
Gate ETTm1       H= 96 ep=10 OOF=0.615157 val=0.396241 alpha=0.075 best=0.396241@10
Gate ETTm1       H= 96 ep=11 OOF=0.611567 val=0.395944 alpha=0.074 best=0.395944@11
Gate ETTm1       H= 96 ep=12 OOF=0.612594 val=0.395745 alpha=0.074 best=0.395745@12
Gate ETTm1       H= 96 ep=13 OOF=0.608159 val=0.395613 alpha=0.076 best=0.395613@13
Gate ETTm1       H= 96 ep=14 OOF=0.611948 val=0.395535 alpha=0.079 best=0.395535@14
Gate ETTm1       H= 96 ep=15 OOF=0.606716 val=0.395497 alpha=0.083 best=0.395497@15
Gate ETTm1       H= 96 ep=16 OOF=0.611117 val=0.395491 alpha=0.086 best=0.395491@16
Gate ETTm1       H= 96 ep=17 OOF=0.607902 val=0.395509 alpha=0.088 best=0.395491@16
Gate ETTm1       H= 96 ep=18 OOF=0.611968 val=0.395522 alpha=0.089 best=0.395491@16
Gate ETTm1       H= 96 ep=19 OOF=0.603504 val=0.395576 alpha=0.092 best=0.395491@16
Gate ETTm1       H= 96 ep=20 OOF=0.604967 val=0.395635 alpha=0.093 best=0.395491@16
Gate ETTm1       H= 96 ep=21 OOF=0.602274 val=0.395696 alpha=0.093 best=0.395491@16
Gate ETTm1       H= 96 ep=22 OOF=0.605380 val=0.395807 alpha=0.094 best=0.395491@16
Gate ETTm1       H= 96 ep=23 OOF=0.606705 val=0.395957 alpha=0.095 best=0.395491@16
Validation calibration | alpha0=0.00 | lambda=0.75 | gateEpoch=16
Building memory embedding: ETTm1_H96_test_trainval_memory_emb.npy (7, 1913, 64)
  channel 1/7
  channel 7/7
  test anchors 128/11425
  test anchors 512/11425
  test anchors 1024/11425
  test anchors 1536/11425
  test anchors 2048/11425
  test anchors 2560/11425
  test anchors 3072/11425
  test anchors 3584/11425
  test anchors 4096/11425
  test anchors 4608/11425
  test anchors 5120/11425
  test anchors 5504/11425
  test anchors 6016/11425
  test anchors 6528/11425
  test anchors 7040/11425
  test anchors 7552/11425
  test anchors 8064/11425
  test anchors 8576/11425
  test anchors 9088/11425
  test anchors 9600/11425
  test anchors 10112/11425
  test anchors 10624/11425
  test anchors 11008/11425
  test anchors 11425/11425

FINAL CONDITION RESULT

  Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0   ETTm1       96          0.336712            0.337092               -0.112813          0.373422            0.373635       1.273082    0.336712         0.337788    0.280151          0.0          0.75         0.071921                 0.428571                     16.797973        0.390909

######################################################################################################################################################
ETTm1 | H=192 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.394380, MAE=0.402333, best_epoch=3
Updating learning rate to 0.0001
Fold direct ETTm1       H=192 F1 ep=01/3 train=0.401970 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct ETTm1       H=192 F1 ep=02/3 train=0.354952 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct ETTm1       H=192 F1 ep=03/3 train=0.325659 lr=2.500e-05
Building memory embedding: ETTm1_H192_F1_prefix19008_emb.npy (7, 781, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=192 F1: prefix=19008, end=24192, anchors=1249, pairs=8743, memory/C=781
Updating learning rate to 0.0001
Fold direct ETTm1       H=192 F2 ep=01/3 train=0.352908 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct ETTm1       H=192 F2 ep=02/3 train=0.313909 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct ETTm1       H=192 F2 ep=03/3 train=0.289232 lr=2.500e-05
Building memory embedding: ETTm1_H192_F2_prefix24192_emb.npy (7, 997, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=192 F2: prefix=24192, end=29376, anchors=1249, pairs=8743, memory/C=997
Updating learning rate to 0.0001
Fold direct ETTm1       H=192 F3 ep=01/3 train=0.352580 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct ETTm1       H=192 F3 ep=02/3 train=0.316518 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct ETTm1       H=192 F3 ep=03/3 train=0.291790 lr=2.500e-05
Building memory embedding: ETTm1_H192_F3_prefix29376_emb.npy (7, 1213, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=192 F3: prefix=29376, end=34560, anchors=1249, pairs=8743, memory/C=1213
Total OOF pairs: 26229
Building memory embedding: ETTm1_H192_validation_train_memory_emb.npy (7, 1429, 64)
  channel 1/7
  channel 7/7
Validation ETTm1 H=192: anchors=11329, pairs=79303, memory/C=1429
Gate ETTm1       H=192 ep=01 OOF=0.678663 val=0.513786 alpha=0.099 best=0.513786@1
Gate ETTm1       H=192 ep=02 OOF=0.675579 val=0.513542 alpha=0.098 best=0.513542@2
Gate ETTm1       H=192 ep=03 OOF=0.675975 val=0.513227 alpha=0.096 best=0.513227@3
Gate ETTm1       H=192 ep=04 OOF=0.674759 val=0.512866 alpha=0.094 best=0.512866@4
Gate ETTm1       H=192 ep=05 OOF=0.667064 val=0.512490 alpha=0.091 best=0.512490@5
Gate ETTm1       H=192 ep=06 OOF=0.673251 val=0.512142 alpha=0.088 best=0.512142@6
Gate ETTm1       H=192 ep=07 OOF=0.677727 val=0.511862 alpha=0.085 best=0.511862@7
Gate ETTm1       H=192 ep=08 OOF=0.670864 val=0.511672 alpha=0.083 best=0.511672@8
Gate ETTm1       H=192 ep=09 OOF=0.671602 val=0.511597 alpha=0.081 best=0.511597@9
Gate ETTm1       H=192 ep=10 OOF=0.668310 val=0.511606 alpha=0.081 best=0.511597@9
Gate ETTm1       H=192 ep=11 OOF=0.665426 val=0.511657 alpha=0.083 best=0.511597@9
Gate ETTm1       H=192 ep=12 OOF=0.661384 val=0.511695 alpha=0.087 best=0.511597@9
Gate ETTm1       H=192 ep=13 OOF=0.662227 val=0.511698 alpha=0.093 best=0.511597@9
Gate ETTm1       H=192 ep=14 OOF=0.667585 val=0.511698 alpha=0.101 best=0.511597@9
Gate ETTm1       H=192 ep=15 OOF=0.670604 val=0.511737 alpha=0.110 best=0.511597@9
Gate ETTm1       H=192 ep=16 OOF=0.673772 val=0.511879 alpha=0.119 best=0.511597@9
Validation calibration | alpha0=0.10 | lambda=1.00 | gateEpoch=9
Building memory embedding: ETTm1_H192_test_trainval_memory_emb.npy (7, 1909, 64)
  channel 1/7
  channel 7/7
  test anchors 128/11329
  test anchors 512/11329
  test anchors 1024/11329
  test anchors 1536/11329
  test anchors 2048/11329
  test anchors 2560/11329
  test anchors 3072/11329
  test anchors 3584/11329
  test anchors 4096/11329
  test anchors 4608/11329
  test anchors 5120/11329
  test anchors 5504/11329
  test anchors 6016/11329
  test anchors 6528/11329
  test anchors 7040/11329
  test anchors 7552/11329
  test anchors 8064/11329
  test anchors 8576/11329
  test anchors 9088/11329
  test anchors 9600/11329
  test anchors 10112/11329
  test anchors 10624/11329
  test anchors 11008/11329
  test anchors 11329/11329

FINAL CONDITION RESULT

  Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0   ETTm1      192           0.39438             0.39062                0.953379          0.402333            0.400364        1.32552    0.392679          0.39062    0.328181          0.1           1.0         0.084481                      1.0                     16.785594        0.897363

######################################################################################################################################################
ETTm1 | H=336 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.424327, MAE=0.422129, best_epoch=2
Updating learning rate to 0.0001
Fold direct ETTm1       H=336 F1 ep=01/2 train=0.485104 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct ETTm1       H=336 F1 ep=02/2 train=0.433559 lr=5.000e-05
Building memory embedding: ETTm1_H336_F1_prefix19008_emb.npy (7, 775, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=336 F1: prefix=19008, end=24192, anchors=1213, pairs=8491, memory/C=775
Updating learning rate to 0.0001
Fold direct ETTm1       H=336 F2 ep=01/2 train=0.413914 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct ETTm1       H=336 F2 ep=02/2 train=0.373735 lr=5.000e-05
Building memory embedding: ETTm1_H336_F2_prefix24192_emb.npy (7, 991, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=336 F2: prefix=24192, end=29376, anchors=1213, pairs=8491, memory/C=991
Updating learning rate to 0.0001
Fold direct ETTm1       H=336 F3 ep=01/2 train=0.408353 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct ETTm1       H=336 F3 ep=02/2 train=0.371506 lr=5.000e-05
Building memory embedding: ETTm1_H336_F3_prefix29376_emb.npy (7, 1207, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=336 F3: prefix=29376, end=34560, anchors=1213, pairs=8491, memory/C=1207
Total OOF pairs: 25473
Building memory embedding: ETTm1_H336_validation_train_memory_emb.npy (7, 1423, 64)
  channel 1/7
  channel 7/7
Validation ETTm1 H=336: anchors=11185, pairs=78295, memory/C=1423
Gate ETTm1       H=336 ep=01 OOF=0.755327 val=0.651380 alpha=0.099 best=0.651380@1
Gate ETTm1       H=336 ep=02 OOF=0.763233 val=0.651042 alpha=0.097 best=0.651042@2
Gate ETTm1       H=336 ep=03 OOF=0.755337 val=0.650594 alpha=0.095 best=0.650594@3
Gate ETTm1       H=336 ep=04 OOF=0.743813 val=0.650080 alpha=0.092 best=0.650080@4
Gate ETTm1       H=336 ep=05 OOF=0.753891 val=0.649560 alpha=0.088 best=0.649560@5
Gate ETTm1       H=336 ep=06 OOF=0.745696 val=0.649106 alpha=0.084 best=0.649106@6
Gate ETTm1       H=336 ep=07 OOF=0.750727 val=0.648792 alpha=0.080 best=0.648792@7
Gate ETTm1       H=336 ep=08 OOF=0.742664 val=0.648632 alpha=0.077 best=0.648632@8
Gate ETTm1       H=336 ep=09 OOF=0.755668 val=0.648595 alpha=0.074 best=0.648595@9
Gate ETTm1       H=336 ep=10 OOF=0.734230 val=0.648629 alpha=0.073 best=0.648595@9
Gate ETTm1       H=336 ep=11 OOF=0.748174 val=0.648664 alpha=0.073 best=0.648595@9
Gate ETTm1       H=336 ep=12 OOF=0.743598 val=0.648684 alpha=0.075 best=0.648595@9
Gate ETTm1       H=336 ep=13 OOF=0.726729 val=0.648666 alpha=0.078 best=0.648595@9
Gate ETTm1       H=336 ep=14 OOF=0.747385 val=0.648621 alpha=0.083 best=0.648595@9
Gate ETTm1       H=336 ep=15 OOF=0.752345 val=0.648583 alpha=0.089 best=0.648583@15
Gate ETTm1       H=336 ep=16 OOF=0.746930 val=0.648567 alpha=0.096 best=0.648567@16
Gate ETTm1       H=336 ep=17 OOF=0.742607 val=0.648572 alpha=0.101 best=0.648567@16
Gate ETTm1       H=336 ep=18 OOF=0.736297 val=0.648607 alpha=0.106 best=0.648567@16
Gate ETTm1       H=336 ep=19 OOF=0.734088 val=0.648631 alpha=0.110 best=0.648567@16
Gate ETTm1       H=336 ep=20 OOF=0.757845 val=0.648647 alpha=0.111 best=0.648567@16
Gate ETTm1       H=336 ep=21 OOF=0.732946 val=0.648595 alpha=0.111 best=0.648567@16
Gate ETTm1       H=336 ep=22 OOF=0.754145 val=0.648461 alpha=0.110 best=0.648461@22
Gate ETTm1       H=336 ep=23 OOF=0.746342 val=0.648251 alpha=0.110 best=0.648251@23
Gate ETTm1       H=336 ep=24 OOF=0.732979 val=0.648147 alpha=0.112 best=0.648147@24
Gate ETTm1       H=336 ep=25 OOF=0.747147 val=0.648178 alpha=0.113 best=0.648147@24
Gate ETTm1       H=336 ep=26 OOF=0.740014 val=0.648196 alpha=0.114 best=0.648147@24
Gate ETTm1       H=336 ep=27 OOF=0.729653 val=0.648022 alpha=0.113 best=0.648022@27
Gate ETTm1       H=336 ep=28 OOF=0.734715 val=0.648017 alpha=0.111 best=0.648017@28
Gate ETTm1       H=336 ep=29 OOF=0.736280 val=0.647955 alpha=0.110 best=0.647955@29
Gate ETTm1       H=336 ep=30 OOF=0.737376 val=0.648022 alpha=0.112 best=0.647955@29
Gate ETTm1       H=336 ep=31 OOF=0.743039 val=0.647761 alpha=0.111 best=0.647761@31
Gate ETTm1       H=336 ep=32 OOF=0.737561 val=0.647287 alpha=0.106 best=0.647287@32
Gate ETTm1       H=336 ep=33 OOF=0.735189 val=0.646907 alpha=0.103 best=0.646907@33
Gate ETTm1       H=336 ep=34 OOF=0.734403 val=0.646612 alpha=0.104 best=0.646612@34
Gate ETTm1       H=336 ep=35 OOF=0.736433 val=0.646528 alpha=0.104 best=0.646528@35
Gate ETTm1       H=336 ep=36 OOF=0.729270 val=0.646420 alpha=0.105 best=0.646420@36
Gate ETTm1       H=336 ep=37 OOF=0.729419 val=0.646420 alpha=0.105 best=0.646420@37
Gate ETTm1       H=336 ep=38 OOF=0.742633 val=0.646204 alpha=0.106 best=0.646204@38
Gate ETTm1       H=336 ep=39 OOF=0.720609 val=0.645957 alpha=0.107 best=0.645957@39
Gate ETTm1       H=336 ep=40 OOF=0.737973 val=0.646090 alpha=0.103 best=0.645957@39
Gate ETTm1       H=336 ep=41 OOF=0.735457 val=0.646152 alpha=0.108 best=0.645957@39
Gate ETTm1       H=336 ep=42 OOF=0.725958 val=0.646739 alpha=0.111 best=0.645957@39
Gate ETTm1       H=336 ep=43 OOF=0.744710 val=0.646901 alpha=0.114 best=0.645957@39
Gate ETTm1       H=336 ep=44 OOF=0.737579 val=0.646047 alpha=0.110 best=0.645957@39
Gate ETTm1       H=336 ep=45 OOF=0.726664 val=0.645649 alpha=0.106 best=0.645649@45
Gate ETTm1       H=336 ep=46 OOF=0.725612 val=0.645385 alpha=0.110 best=0.645385@46
Gate ETTm1       H=336 ep=47 OOF=0.734601 val=0.645729 alpha=0.111 best=0.645385@46
Gate ETTm1       H=336 ep=48 OOF=0.726837 val=0.645795 alpha=0.111 best=0.645385@46
Gate ETTm1       H=336 ep=49 OOF=0.721991 val=0.646163 alpha=0.110 best=0.645385@46
Gate ETTm1       H=336 ep=50 OOF=0.728098 val=0.646082 alpha=0.112 best=0.645385@46
Validation calibration | alpha0=0.10 | lambda=0.75 | gateEpoch=46
Building memory embedding: ETTm1_H336_test_trainval_memory_emb.npy (7, 1903, 64)
  channel 1/7
  channel 7/7
  test anchors 128/11185
  test anchors 512/11185
  test anchors 1024/11185
  test anchors 1536/11185
  test anchors 2048/11185
  test anchors 2560/11185
  test anchors 3072/11185
  test anchors 3584/11185
  test anchors 4096/11185
  test anchors 4608/11185
  test anchors 5120/11185
  test anchors 5504/11185
  test anchors 6016/11185
  test anchors 6528/11185
  test anchors 7040/11185
  test anchors 7552/11185
  test anchors 8064/11185
  test anchors 8576/11185
  test anchors 9088/11185
  test anchors 9600/11185
  test anchors 10112/11185
  test anchors 10624/11185
  test anchors 11008/11185
  test anchors 11185/11185

FINAL CONDITION RESULT

  Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0   ETTm1      336          0.424327            0.423381                0.222913          0.422129            0.421551       1.364253     0.42466         0.425539    0.368539          0.1          0.75         0.110815                 0.714286                     13.147345        0.676535

######################################################################################################################################################
ETTm1 | H=720 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.496095, MAE=0.461646, best_epoch=3
Updating learning rate to 0.0001
Fold direct ETTm1       H=720 F1 ep=01/3 train=0.603846 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct ETTm1       H=720 F1 ep=02/3 train=0.551149 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct ETTm1       H=720 F1 ep=03/3 train=0.515657 lr=2.500e-05
Building memory embedding: ETTm1_H720_F1_prefix19008_emb.npy (7, 759, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=720 F1: prefix=19008, end=24192, anchors=1117, pairs=7819, memory/C=759
Updating learning rate to 0.0001
Fold direct ETTm1       H=720 F2 ep=01/3 train=0.511617 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct ETTm1       H=720 F2 ep=02/3 train=0.469892 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct ETTm1       H=720 F2 ep=03/3 train=0.439846 lr=2.500e-05
Building memory embedding: ETTm1_H720_F2_prefix24192_emb.npy (7, 975, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=720 F2: prefix=24192, end=29376, anchors=1117, pairs=7819, memory/C=975
Updating learning rate to 0.0001
Fold direct ETTm1       H=720 F3 ep=01/3 train=0.482799 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct ETTm1       H=720 F3 ep=02/3 train=0.445783 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct ETTm1       H=720 F3 ep=03/3 train=0.419536 lr=2.500e-05
Building memory embedding: ETTm1_H720_F3_prefix29376_emb.npy (7, 1191, 64)
  channel 1/7
  channel 7/7
OOF ETTm1 H=720 F3: prefix=29376, end=34560, anchors=1117, pairs=7819, memory/C=1191
Total OOF pairs: 23457
Building memory embedding: ETTm1_H720_validation_train_memory_emb.npy (7, 1407, 64)
  channel 1/7
  channel 7/7
Validation ETTm1 H=720: anchors=10801, pairs=75607, memory/C=1407
Gate ETTm1       H=720 ep=01 OOF=0.807302 val=0.953587 alpha=0.099 best=0.953587@1
Gate ETTm1       H=720 ep=02 OOF=0.807656 val=0.953556 alpha=0.098 best=0.953556@2
Gate ETTm1       H=720 ep=03 OOF=0.806705 val=0.953519 alpha=0.097 best=0.953519@3
Gate ETTm1       H=720 ep=04 OOF=0.806658 val=0.953485 alpha=0.095 best=0.953485@4
Gate ETTm1       H=720 ep=05 OOF=0.807938 val=0.953465 alpha=0.094 best=0.953465@5
Gate ETTm1       H=720 ep=06 OOF=0.805863 val=0.953471 alpha=0.092 best=0.953465@5
Gate ETTm1       H=720 ep=07 OOF=0.805238 val=0.953505 alpha=0.090 best=0.953465@5
Gate ETTm1       H=720 ep=08 OOF=0.804876 val=0.953572 alpha=0.089 best=0.953465@5
Gate ETTm1       H=720 ep=09 OOF=0.805779 val=0.953658 alpha=0.088 best=0.953465@5
Gate ETTm1       H=720 ep=10 OOF=0.803964 val=0.953728 alpha=0.088 best=0.953465@5
Gate ETTm1       H=720 ep=11 OOF=0.803769 val=0.953761 alpha=0.089 best=0.953465@5
Gate ETTm1       H=720 ep=12 OOF=0.803889 val=0.953702 alpha=0.092 best=0.953465@5
Validation calibration | alpha0=0.10 | lambda=0.75 | gateEpoch=5
Building memory embedding: ETTm1_H720_test_trainval_memory_emb.npy (7, 1887, 64)
  channel 1/7
  channel 7/7
  test anchors 128/10801
  test anchors 512/10801
  test anchors 1024/10801
  test anchors 1536/10801
  test anchors 2048/10801
  test anchors 2560/10801
  test anchors 3072/10801
  test anchors 3584/10801
  test anchors 4096/10801
  test anchors 4608/10801
  test anchors 5120/10801
  test anchors 5504/10801
  test anchors 6016/10801
  test anchors 6528/10801
  test anchors 7040/10801
  test anchors 7552/10801
  test anchors 8064/10801
  test anchors 8576/10801
  test anchors 9088/10801
  test anchors 9600/10801
  test anchors 10112/10801
  test anchors 10624/10801
  test anchors 10801/10801

FINAL CONDITION RESULT

  Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0   ETTm1      720          0.496095            0.488999                1.430322          0.461646            0.460045       1.424698    0.489097         0.489012    0.427392          0.1          0.75         0.095913                      1.0                     13.848778        0.994463

######################################################################################################################################################
ETTh1 | H=96 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.392304, MAE=0.407334, best_epoch=1
Updating learning rate to 0.0001
Fold direct ETTh1       H= 96 F1 ep=01/1 train=0.482506 lr=1.000e-04
Building memory embedding: ETTh1_H96_F1_prefix4752_emb.npy (7, 191, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=96 F1: prefix=4752, end=6048, anchors=301, pairs=2107, memory/C=191
Updating learning rate to 0.0001
Fold direct ETTh1       H= 96 F2 ep=01/1 train=0.406694 lr=1.000e-04
Building memory embedding: ETTh1_H96_F2_prefix6048_emb.npy (7, 245, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=96 F2: prefix=6048, end=7344, anchors=301, pairs=2107, memory/C=245
Updating learning rate to 0.0001
Fold direct ETTh1       H= 96 F3 ep=01/1 train=0.393632 lr=1.000e-04
Building memory embedding: ETTh1_H96_F3_prefix7344_emb.npy (7, 299, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=96 F3: prefix=7344, end=8640, anchors=301, pairs=2107, memory/C=299
Total OOF pairs: 6321
Building memory embedding: ETTh1_H96_validation_train_memory_emb.npy (7, 353, 64)
  channel 1/7
  channel 7/7
Validation ETTh1 H=96: anchors=2785, pairs=19495, memory/C=353
Gate ETTh1       H= 96 ep=01 OOF=0.559428 val=0.680142 alpha=0.100 best=0.680142@1
Gate ETTh1       H= 96 ep=02 OOF=0.559261 val=0.680078 alpha=0.099 best=0.680078@2
Gate ETTh1       H= 96 ep=03 OOF=0.559067 val=0.680003 alpha=0.099 best=0.680003@3
Gate ETTh1       H= 96 ep=04 OOF=0.558841 val=0.679916 alpha=0.099 best=0.679916@4
Gate ETTh1       H= 96 ep=05 OOF=0.558581 val=0.679817 alpha=0.098 best=0.679817@5
Gate ETTh1       H= 96 ep=06 OOF=0.558293 val=0.679706 alpha=0.098 best=0.679706@6
Gate ETTh1       H= 96 ep=07 OOF=0.557983 val=0.679583 alpha=0.098 best=0.679583@7
Gate ETTh1       H= 96 ep=08 OOF=0.557587 val=0.679447 alpha=0.097 best=0.679447@8
Gate ETTh1       H= 96 ep=09 OOF=0.557196 val=0.679299 alpha=0.097 best=0.679299@9
Gate ETTh1       H= 96 ep=10 OOF=0.556762 val=0.679141 alpha=0.096 best=0.679141@10
Gate ETTh1       H= 96 ep=11 OOF=0.556295 val=0.678973 alpha=0.095 best=0.678973@11
Gate ETTh1       H= 96 ep=12 OOF=0.555774 val=0.678796 alpha=0.095 best=0.678796@12
Gate ETTh1       H= 96 ep=13 OOF=0.555207 val=0.678612 alpha=0.094 best=0.678612@13
Gate ETTh1       H= 96 ep=14 OOF=0.554601 val=0.678421 alpha=0.093 best=0.678421@14
Gate ETTh1       H= 96 ep=15 OOF=0.554007 val=0.678227 alpha=0.092 best=0.678227@15
Gate ETTh1       H= 96 ep=16 OOF=0.553294 val=0.678030 alpha=0.092 best=0.678030@16
Gate ETTh1       H= 96 ep=17 OOF=0.552672 val=0.677833 alpha=0.091 best=0.677833@17
Gate ETTh1       H= 96 ep=18 OOF=0.551987 val=0.677638 alpha=0.090 best=0.677638@18
Gate ETTh1       H= 96 ep=19 OOF=0.551283 val=0.677449 alpha=0.089 best=0.677449@19
Gate ETTh1       H= 96 ep=20 OOF=0.550600 val=0.677267 alpha=0.088 best=0.677267@20
Gate ETTh1       H= 96 ep=21 OOF=0.549852 val=0.677095 alpha=0.087 best=0.677095@21
Gate ETTh1       H= 96 ep=22 OOF=0.549134 val=0.676936 alpha=0.086 best=0.676936@22
Gate ETTh1       H= 96 ep=23 OOF=0.548348 val=0.676792 alpha=0.085 best=0.676792@23
Gate ETTh1       H= 96 ep=24 OOF=0.547651 val=0.676665 alpha=0.083 best=0.676665@24
Gate ETTh1       H= 96 ep=25 OOF=0.546949 val=0.676556 alpha=0.082 best=0.676556@25
Gate ETTh1       H= 96 ep=26 OOF=0.546225 val=0.676469 alpha=0.081 best=0.676469@26
Gate ETTh1       H= 96 ep=27 OOF=0.545485 val=0.676403 alpha=0.080 best=0.676403@27
Gate ETTh1       H= 96 ep=28 OOF=0.544828 val=0.676358 alpha=0.079 best=0.676358@28
Gate ETTh1       H= 96 ep=29 OOF=0.544313 val=0.676336 alpha=0.078 best=0.676336@29
Gate ETTh1       H= 96 ep=30 OOF=0.543553 val=0.676335 alpha=0.077 best=0.676335@30
Gate ETTh1       H= 96 ep=31 OOF=0.543110 val=0.676354 alpha=0.075 best=0.676335@30
Gate ETTh1       H= 96 ep=32 OOF=0.542454 val=0.676392 alpha=0.074 best=0.676335@30
Gate ETTh1       H= 96 ep=33 OOF=0.541928 val=0.676447 alpha=0.073 best=0.676335@30
Gate ETTh1       H= 96 ep=34 OOF=0.541378 val=0.676516 alpha=0.072 best=0.676335@30
Gate ETTh1       H= 96 ep=35 OOF=0.541109 val=0.676598 alpha=0.071 best=0.676335@30
Gate ETTh1       H= 96 ep=36 OOF=0.540670 val=0.676690 alpha=0.070 best=0.676335@30
Gate ETTh1       H= 96 ep=37 OOF=0.540162 val=0.676789 alpha=0.070 best=0.676335@30
Validation calibration | alpha0=0.10 | lambda=1.00 | gateEpoch=30
Building memory embedding: ETTh1_H96_test_trainval_memory_emb.npy (7, 473, 64)
  channel 1/7
  channel 7/7
  test anchors 128/2785
  test anchors 512/2785
  test anchors 1024/2785
  test anchors 1536/2785
  test anchors 2048/2785
  test anchors 2560/2785
  test anchors 2785/2785

FINAL CONDITION RESULT

  Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0   ETTh1       96          0.392303            0.394281               -0.504197          0.407334            0.410792       1.799798    0.403233         0.394281    0.362519          0.1           1.0         0.079177                 0.571429                      7.592273        0.113245

######################################################################################################################################################
ETTh1 | H=192 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.442639, MAE=0.434737, best_epoch=1
Updating learning rate to 0.0001
Fold direct ETTh1       H=192 F1 ep=01/1 train=0.585267 lr=1.000e-04
Building memory embedding: ETTh1_H192_F1_prefix4752_emb.npy (7, 187, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=192 F1: prefix=4752, end=6048, anchors=277, pairs=1939, memory/C=187
Updating learning rate to 0.0001
Fold direct ETTh1       H=192 F2 ep=01/1 train=0.493909 lr=1.000e-04
Building memory embedding: ETTh1_H192_F2_prefix6048_emb.npy (7, 241, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=192 F2: prefix=6048, end=7344, anchors=277, pairs=1939, memory/C=241
Updating learning rate to 0.0001
Fold direct ETTh1       H=192 F3 ep=01/1 train=0.462719 lr=1.000e-04
Building memory embedding: ETTh1_H192_F3_prefix7344_emb.npy (7, 295, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=192 F3: prefix=7344, end=8640, anchors=277, pairs=1939, memory/C=295
Total OOF pairs: 5817
Building memory embedding: ETTh1_H192_validation_train_memory_emb.npy (7, 349, 64)
  channel 1/7
  channel 7/7
Validation ETTh1 H=192: anchors=2689, pairs=18823, memory/C=349
Gate ETTh1       H=192 ep=01 OOF=0.640374 val=0.977679 alpha=0.100 best=0.977679@1
Gate ETTh1       H=192 ep=02 OOF=0.640245 val=0.977626 alpha=0.099 best=0.977626@2
Gate ETTh1       H=192 ep=03 OOF=0.640102 val=0.977569 alpha=0.099 best=0.977569@3
Gate ETTh1       H=192 ep=04 OOF=0.639941 val=0.977511 alpha=0.099 best=0.977511@4
Gate ETTh1       H=192 ep=05 OOF=0.639744 val=0.977451 alpha=0.098 best=0.977451@5
Gate ETTh1       H=192 ep=06 OOF=0.639532 val=0.977389 alpha=0.098 best=0.977389@6
Gate ETTh1       H=192 ep=07 OOF=0.639296 val=0.977326 alpha=0.098 best=0.977326@7
Gate ETTh1       H=192 ep=08 OOF=0.639012 val=0.977263 alpha=0.097 best=0.977263@8
Gate ETTh1       H=192 ep=09 OOF=0.638699 val=0.977199 alpha=0.097 best=0.977199@9
Gate ETTh1       H=192 ep=10 OOF=0.638353 val=0.977136 alpha=0.096 best=0.977136@10
Gate ETTh1       H=192 ep=11 OOF=0.637984 val=0.977074 alpha=0.096 best=0.977074@11
Gate ETTh1       H=192 ep=12 OOF=0.637618 val=0.977015 alpha=0.095 best=0.977015@12
Gate ETTh1       H=192 ep=13 OOF=0.637140 val=0.976960 alpha=0.094 best=0.976960@13
Gate ETTh1       H=192 ep=14 OOF=0.636670 val=0.976910 alpha=0.094 best=0.976910@14
Gate ETTh1       H=192 ep=15 OOF=0.636221 val=0.976867 alpha=0.093 best=0.976867@15
Gate ETTh1       H=192 ep=16 OOF=0.635677 val=0.976831 alpha=0.092 best=0.976831@16
Gate ETTh1       H=192 ep=17 OOF=0.635138 val=0.976806 alpha=0.091 best=0.976806@17
Gate ETTh1       H=192 ep=18 OOF=0.634578 val=0.976792 alpha=0.090 best=0.976792@18
Gate ETTh1       H=192 ep=19 OOF=0.633913 val=0.976790 alpha=0.089 best=0.976790@19
Gate ETTh1       H=192 ep=20 OOF=0.633353 val=0.976803 alpha=0.089 best=0.976790@19
Gate ETTh1       H=192 ep=21 OOF=0.632659 val=0.976831 alpha=0.088 best=0.976790@19
Gate ETTh1       H=192 ep=22 OOF=0.632012 val=0.976875 alpha=0.087 best=0.976790@19
Gate ETTh1       H=192 ep=23 OOF=0.631311 val=0.976937 alpha=0.085 best=0.976790@19
Gate ETTh1       H=192 ep=24 OOF=0.630626 val=0.977017 alpha=0.084 best=0.976790@19
Gate ETTh1       H=192 ep=25 OOF=0.630054 val=0.977115 alpha=0.083 best=0.976790@19
Gate ETTh1       H=192 ep=26 OOF=0.629353 val=0.977232 alpha=0.082 best=0.976790@19
Validation calibration | alpha0=0.10 | lambda=1.00 | gateEpoch=19
Building memory embedding: ETTh1_H192_test_trainval_memory_emb.npy (7, 469, 64)
  channel 1/7
  channel 7/7
  test anchors 128/2689
  test anchors 512/2689
  test anchors 1024/2689
  test anchors 1536/2689
  test anchors 2048/2689
  test anchors 2560/2689
  test anchors 2689/2689

FINAL CONDITION RESULT

  Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0   ETTh1      192          0.442639            0.449096               -1.458748          0.434737            0.442669       1.791403    0.453672         0.449096    0.413171          0.1           1.0         0.089948                 0.428571                      6.657512        0.109456

######################################################################################################################################################
ETTh1 | H=336 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.489263, MAE=0.461457, best_epoch=1
Updating learning rate to 0.0001
Fold direct ETTh1       H=336 F1 ep=01/1 train=0.679152 lr=1.000e-04
Building memory embedding: ETTh1_H336_F1_prefix4752_emb.npy (7, 181, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=336 F1: prefix=4752, end=6048, anchors=241, pairs=1687, memory/C=181
Updating learning rate to 0.0001
Fold direct ETTh1       H=336 F2 ep=01/1 train=0.565065 lr=1.000e-04
Building memory embedding: ETTh1_H336_F2_prefix6048_emb.npy (7, 235, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=336 F2: prefix=6048, end=7344, anchors=241, pairs=1687, memory/C=235
Updating learning rate to 0.0001
Fold direct ETTh1       H=336 F3 ep=01/1 train=0.525664 lr=1.000e-04
Building memory embedding: ETTh1_H336_F3_prefix7344_emb.npy (7, 289, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=336 F3: prefix=7344, end=8640, anchors=241, pairs=1687, memory/C=289
Total OOF pairs: 5061
Building memory embedding: ETTh1_H336_validation_train_memory_emb.npy (7, 343, 64)
  channel 1/7
  channel 7/7
Validation ETTh1 H=336: anchors=2545, pairs=17815, memory/C=343
Gate ETTh1       H=336 ep=01 OOF=0.725524 val=1.260752 alpha=0.100 best=1.260752@1
Gate ETTh1       H=336 ep=02 OOF=0.725377 val=1.260753 alpha=0.099 best=1.260752@1
Gate ETTh1       H=336 ep=03 OOF=0.725223 val=1.260751 alpha=0.099 best=1.260751@3
Gate ETTh1       H=336 ep=04 OOF=0.725050 val=1.260748 alpha=0.099 best=1.260748@4
Gate ETTh1       H=336 ep=05 OOF=0.724853 val=1.260746 alpha=0.099 best=1.260746@5
Gate ETTh1       H=336 ep=06 OOF=0.724610 val=1.260746 alpha=0.098 best=1.260746@6
Gate ETTh1       H=336 ep=07 OOF=0.724361 val=1.260749 alpha=0.098 best=1.260746@6
Gate ETTh1       H=336 ep=08 OOF=0.724071 val=1.260755 alpha=0.098 best=1.260746@6
Gate ETTh1       H=336 ep=09 OOF=0.723748 val=1.260766 alpha=0.097 best=1.260746@6
Gate ETTh1       H=336 ep=10 OOF=0.723366 val=1.260781 alpha=0.097 best=1.260746@6
Gate ETTh1       H=336 ep=11 OOF=0.722922 val=1.260801 alpha=0.096 best=1.260746@6
Gate ETTh1       H=336 ep=12 OOF=0.722513 val=1.260826 alpha=0.096 best=1.260746@6
Gate ETTh1       H=336 ep=13 OOF=0.722070 val=1.260856 alpha=0.095 best=1.260746@6
Validation calibration | alpha0=0.10 | lambda=1.00 | gateEpoch=6
Building memory embedding: ETTh1_H336_test_trainval_memory_emb.npy (7, 463, 64)
  channel 1/7
  channel 7/7
  test anchors 128/2545
  test anchors 512/2545
  test anchors 1024/2545
  test anchors 1536/2545
  test anchors 2048/2545
  test anchors 2545/2545

FINAL CONDITION RESULT

  Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0   ETTh1      336          0.489263               0.498               -1.785874          0.461457            0.473326       1.850616    0.498583            0.498    0.454354          0.1           1.0         0.098503                 0.571429                      7.135021        0.109588

######################################################################################################################################################
ETTh1 | H=720 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.506507, MAE=0.492894, best_epoch=1
Updating learning rate to 0.0001
Fold direct ETTh1       H=720 F1 ep=01/1 train=0.901983 lr=1.000e-04
Building memory embedding: ETTh1_H720_F1_prefix4752_emb.npy (7, 165, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=720 F1: prefix=4752, end=6048, anchors=145, pairs=1015, memory/C=165
Updating learning rate to 0.0001
Fold direct ETTh1       H=720 F2 ep=01/1 train=0.722247 lr=1.000e-04
Building memory embedding: ETTh1_H720_F2_prefix6048_emb.npy (7, 219, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=720 F2: prefix=6048, end=7344, anchors=145, pairs=1015, memory/C=219
Updating learning rate to 0.0001
Fold direct ETTh1       H=720 F3 ep=01/1 train=0.660038 lr=1.000e-04
Building memory embedding: ETTh1_H720_F3_prefix7344_emb.npy (7, 273, 64)
  channel 1/7
  channel 7/7
OOF ETTh1 H=720 F3: prefix=7344, end=8640, anchors=145, pairs=1015, memory/C=273
Total OOF pairs: 3045
Building memory embedding: ETTh1_H720_validation_train_memory_emb.npy (7, 327, 64)
  channel 1/7
  channel 7/7
Validation ETTh1 H=720: anchors=2161, pairs=15127, memory/C=327
Gate ETTh1       H=720 ep=01 OOF=0.857383 val=1.514817 alpha=0.100 best=1.514817@1
Gate ETTh1       H=720 ep=02 OOF=0.857217 val=1.514824 alpha=0.100 best=1.514817@1
Gate ETTh1       H=720 ep=03 OOF=0.857046 val=1.514833 alpha=0.099 best=1.514817@1
Gate ETTh1       H=720 ep=04 OOF=0.856852 val=1.514846 alpha=0.099 best=1.514817@1
Gate ETTh1       H=720 ep=05 OOF=0.856656 val=1.514866 alpha=0.099 best=1.514817@1
Gate ETTh1       H=720 ep=06 OOF=0.856406 val=1.514893 alpha=0.099 best=1.514817@1
Gate ETTh1       H=720 ep=07 OOF=0.856106 val=1.514929 alpha=0.099 best=1.514817@1
Gate ETTh1       H=720 ep=08 OOF=0.855814 val=1.514975 alpha=0.098 best=1.514817@1
Validation calibration | alpha0=0.20 | lambda=0.50 | gateEpoch=1
Building memory embedding: ETTh1_H720_test_trainval_memory_emb.npy (7, 447, 64)
  channel 1/7
  channel 7/7
  test anchors 128/2161
  test anchors 512/2161
  test anchors 1024/2161
  test anchors 1536/2161
  test anchors 2048/2161
  test anchors 2161/2161

FINAL CONDITION RESULT

  Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0   ETTh1      720          0.506507            0.536269               -5.876001          0.492894            0.515912       1.920954    0.560588         0.519138    0.471712          0.2           0.5         0.149958                 0.571429                      6.869664        0.109269

######################################################################################################################################################
Weather | H=96 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.173287, MAE=0.212210, best_epoch=6
Updating learning rate to 0.0001
Fold direct Weather     H= 96 F1 ep=01/6 train=0.582657 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H= 96 F1 ep=02/6 train=0.510992 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H= 96 F1 ep=03/6 train=0.476715 lr=2.500e-05
Updating learning rate to 1.25e-05
Fold direct Weather     H= 96 F1 ep=04/6 train=0.457687 lr=1.250e-05
Updating learning rate to 6.25e-06
Fold direct Weather     H= 96 F1 ep=05/6 train=0.447144 lr=6.250e-06
Updating learning rate to 3.125e-06
Fold direct Weather     H= 96 F1 ep=06/6 train=0.441862 lr=3.125e-06
Building memory embedding: Weather_H96_F1_prefix20287_emb.npy (21, 838, 64)
  channel 1/21
  channel 21/21
OOF Weather H=96 F1: prefix=20287, end=25820, anchors=1360, pairs=28560, memory/C=838
Updating learning rate to 0.0001
Fold direct Weather     H= 96 F2 ep=01/6 train=0.524208 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H= 96 F2 ep=02/6 train=0.469640 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H= 96 F2 ep=03/6 train=0.447346 lr=2.500e-05
Updating learning rate to 1.25e-05
Fold direct Weather     H= 96 F2 ep=04/6 train=0.433261 lr=1.250e-05
Updating learning rate to 6.25e-06
Fold direct Weather     H= 96 F2 ep=05/6 train=0.425737 lr=6.250e-06
Updating learning rate to 3.125e-06
Fold direct Weather     H= 96 F2 ep=06/6 train=0.421241 lr=3.125e-06
Building memory embedding: Weather_H96_F2_prefix25820_emb.npy (21, 1068, 64)
  channel 1/21
  channel 21/21
OOF Weather H=96 F2: prefix=25820, end=31353, anchors=1360, pairs=28560, memory/C=1068
Updating learning rate to 0.0001
Fold direct Weather     H= 96 F3 ep=01/6 train=0.516609 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H= 96 F3 ep=02/6 train=0.464303 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H= 96 F3 ep=03/6 train=0.441037 lr=2.500e-05
Updating learning rate to 1.25e-05
Fold direct Weather     H= 96 F3 ep=04/6 train=0.428623 lr=1.250e-05
Updating learning rate to 6.25e-06
Fold direct Weather     H= 96 F3 ep=05/6 train=0.420926 lr=6.250e-06
Updating learning rate to 3.125e-06
Fold direct Weather     H= 96 F3 ep=06/6 train=0.417526 lr=3.125e-06
Building memory embedding: Weather_H96_F3_prefix31353_emb.npy (21, 1299, 64)
  channel 1/21
  channel 21/21
OOF Weather H=96 F3: prefix=31353, end=36887, anchors=1360, pairs=28560, memory/C=1299
Total OOF pairs: 85680
Building memory embedding: Weather_H96_validation_train_memory_emb.npy (21, 1529, 64)
  channel 1/21
  channel 21/21
Validation Weather H=96: anchors=5175, pairs=108675, memory/C=1529
Gate Weather     H= 96 ep=01 OOF=0.831786 val=0.418066 alpha=0.103 best=0.418066@1
Gate Weather     H= 96 ep=02 OOF=0.822160 val=0.417869 alpha=0.105 best=0.417869@2
Gate Weather     H= 96 ep=03 OOF=0.830279 val=0.417586 alpha=0.108 best=0.417586@3
Gate Weather     H= 96 ep=04 OOF=0.839257 val=0.417064 alpha=0.114 best=0.417064@4
Gate Weather     H= 96 ep=05 OOF=0.816532 val=0.415974 alpha=0.124 best=0.415974@5
Gate Weather     H= 96 ep=06 OOF=0.830757 val=0.413990 alpha=0.144 best=0.413990@6
Gate Weather     H= 96 ep=07 OOF=0.817138 val=0.410835 alpha=0.186 best=0.410835@7
Gate Weather     H= 96 ep=08 OOF=0.804217 val=0.409297 alpha=0.214 best=0.409297@8
Gate Weather     H= 96 ep=09 OOF=0.801698 val=0.408622 alpha=0.226 best=0.408622@9
Gate Weather     H= 96 ep=10 OOF=0.804831 val=0.408107 alpha=0.222 best=0.408107@10
Gate Weather     H= 96 ep=11 OOF=0.796183 val=0.407139 alpha=0.227 best=0.407139@11
Gate Weather     H= 96 ep=12 OOF=0.794600 val=0.406808 alpha=0.232 best=0.406808@12
Gate Weather     H= 96 ep=13 OOF=0.799064 val=0.406693 alpha=0.238 best=0.406693@13
Gate Weather     H= 96 ep=14 OOF=0.782280 val=0.406295 alpha=0.243 best=0.406295@14
Gate Weather     H= 96 ep=15 OOF=0.785642 val=0.406771 alpha=0.231 best=0.406295@14
Gate Weather     H= 96 ep=16 OOF=0.786594 val=0.407163 alpha=0.223 best=0.406295@14
Gate Weather     H= 96 ep=17 OOF=0.775736 val=0.406175 alpha=0.228 best=0.406175@17
Gate Weather     H= 96 ep=18 OOF=0.783280 val=0.406462 alpha=0.219 best=0.406175@17
Gate Weather     H= 96 ep=19 OOF=0.781552 val=0.406653 alpha=0.218 best=0.406175@17
Gate Weather     H= 96 ep=20 OOF=0.788141 val=0.405610 alpha=0.228 best=0.405610@20
Gate Weather     H= 96 ep=21 OOF=0.783184 val=0.405695 alpha=0.222 best=0.405610@20
Gate Weather     H= 96 ep=22 OOF=0.779598 val=0.405389 alpha=0.223 best=0.405389@22
Gate Weather     H= 96 ep=23 OOF=0.777295 val=0.405446 alpha=0.214 best=0.405389@22
Gate Weather     H= 96 ep=24 OOF=0.777867 val=0.404598 alpha=0.235 best=0.404598@24
Gate Weather     H= 96 ep=25 OOF=0.781253 val=0.404651 alpha=0.222 best=0.404598@24
Gate Weather     H= 96 ep=26 OOF=0.782901 val=0.404333 alpha=0.222 best=0.404333@26
Gate Weather     H= 96 ep=27 OOF=0.779727 val=0.404138 alpha=0.228 best=0.404138@27
Gate Weather     H= 96 ep=28 OOF=0.782272 val=0.403886 alpha=0.218 best=0.403886@28
Gate Weather     H= 96 ep=29 OOF=0.778094 val=0.403648 alpha=0.227 best=0.403648@29
Gate Weather     H= 96 ep=30 OOF=0.771904 val=0.404525 alpha=0.214 best=0.403648@29
Gate Weather     H= 96 ep=31 OOF=0.781328 val=0.404100 alpha=0.222 best=0.403648@29
Gate Weather     H= 96 ep=32 OOF=0.776407 val=0.403561 alpha=0.228 best=0.403561@32
Gate Weather     H= 96 ep=33 OOF=0.774658 val=0.403683 alpha=0.214 best=0.403561@32
Gate Weather     H= 96 ep=34 OOF=0.778163 val=0.403312 alpha=0.222 best=0.403312@34
Gate Weather     H= 96 ep=35 OOF=0.782017 val=0.402912 alpha=0.222 best=0.402912@35
Gate Weather     H= 96 ep=36 OOF=0.775975 val=0.403855 alpha=0.221 best=0.402912@35
Gate Weather     H= 96 ep=37 OOF=0.779982 val=0.403325 alpha=0.209 best=0.402912@35
Gate Weather     H= 96 ep=38 OOF=0.773468 val=0.402888 alpha=0.227 best=0.402888@38
Gate Weather     H= 96 ep=39 OOF=0.771638 val=0.402774 alpha=0.221 best=0.402774@39
Gate Weather     H= 96 ep=40 OOF=0.778683 val=0.403356 alpha=0.209 best=0.402774@39
Gate Weather     H= 96 ep=41 OOF=0.772448 val=0.402985 alpha=0.210 best=0.402774@39
Gate Weather     H= 96 ep=42 OOF=0.775136 val=0.402637 alpha=0.217 best=0.402637@42
Gate Weather     H= 96 ep=43 OOF=0.771329 val=0.402792 alpha=0.212 best=0.402637@42
Gate Weather     H= 96 ep=44 OOF=0.780214 val=0.402452 alpha=0.216 best=0.402452@44
Gate Weather     H= 96 ep=45 OOF=0.788660 val=0.402881 alpha=0.215 best=0.402452@44
Gate Weather     H= 96 ep=46 OOF=0.768435 val=0.402783 alpha=0.209 best=0.402452@44
Gate Weather     H= 96 ep=47 OOF=0.772523 val=0.402247 alpha=0.215 best=0.402247@47
Gate Weather     H= 96 ep=48 OOF=0.783617 val=0.402287 alpha=0.214 best=0.402247@47
Gate Weather     H= 96 ep=49 OOF=0.772399 val=0.402356 alpha=0.216 best=0.402247@47
Gate Weather     H= 96 ep=50 OOF=0.773111 val=0.402150 alpha=0.215 best=0.402150@50
Validation calibration | alpha0=0.20 | lambda=1.00 | gateEpoch=50
Building memory embedding: Weather_H96_test_trainval_memory_emb.npy (21, 1749, 64)
  channel 1/21
  channel 21/21
  test anchors 64/10444
  test anchors 512/10444
  test anchors 1024/10444
  test anchors 1536/10444
  test anchors 2048/10444
  test anchors 2560/10444
  test anchors 3008/10444
  test anchors 3520/10444
  test anchors 4032/10444
  test anchors 4544/10444
  test anchors 5056/10444
  test anchors 5504/10444
  test anchors 6016/10444
  test anchors 6528/10444
  test anchors 7040/10444
  test anchors 7552/10444
  test anchors 8000/10444
  test anchors 8512/10444
  test anchors 9024/10444
  test anchors 9536/10444
  test anchors 10048/10444
  test anchors 10444/10444

FINAL CONDITION RESULT

   Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0  Weather       96          0.173287            0.166006                4.201641           0.21221             0.20935       0.239999    0.167517         0.166006    0.134499          0.2           1.0          0.21357                 0.619048                     22.383703        2.378653

######################################################################################################################################################
Weather | H=192 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.224436, MAE=0.257719, best_epoch=5
Updating learning rate to 0.0001
Fold direct Weather     H=192 F1 ep=01/5 train=0.703291 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H=192 F1 ep=02/5 train=0.631740 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H=192 F1 ep=03/5 train=0.598037 lr=2.500e-05
Updating learning rate to 1.25e-05
Fold direct Weather     H=192 F1 ep=04/5 train=0.578038 lr=1.250e-05
Updating learning rate to 6.25e-06
Fold direct Weather     H=192 F1 ep=05/5 train=0.567426 lr=6.250e-06
Building memory embedding: Weather_H192_F1_prefix20287_emb.npy (21, 834, 64)
  channel 1/21
  channel 21/21
OOF Weather H=192 F1: prefix=20287, end=25820, anchors=1336, pairs=28056, memory/C=834
Updating learning rate to 0.0001
Fold direct Weather     H=192 F2 ep=01/5 train=0.595544 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H=192 F2 ep=02/5 train=0.549315 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H=192 F2 ep=03/5 train=0.528790 lr=2.500e-05
Updating learning rate to 1.25e-05
Fold direct Weather     H=192 F2 ep=04/5 train=0.516788 lr=1.250e-05
Updating learning rate to 6.25e-06
Fold direct Weather     H=192 F2 ep=05/5 train=0.509605 lr=6.250e-06
Building memory embedding: Weather_H192_F2_prefix25820_emb.npy (21, 1064, 64)
  channel 1/21
  channel 21/21
OOF Weather H=192 F2: prefix=25820, end=31353, anchors=1336, pairs=28056, memory/C=1064
Updating learning rate to 0.0001
Fold direct Weather     H=192 F3 ep=01/5 train=0.582007 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H=192 F3 ep=02/5 train=0.536838 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H=192 F3 ep=03/5 train=0.517202 lr=2.500e-05
Updating learning rate to 1.25e-05
Fold direct Weather     H=192 F3 ep=04/5 train=0.505146 lr=1.250e-05
Updating learning rate to 6.25e-06
Fold direct Weather     H=192 F3 ep=05/5 train=0.497992 lr=6.250e-06
Building memory embedding: Weather_H192_F3_prefix31353_emb.npy (21, 1295, 64)
  channel 1/21
  channel 21/21
OOF Weather H=192 F3: prefix=31353, end=36887, anchors=1336, pairs=28056, memory/C=1295
Total OOF pairs: 84168
Building memory embedding: Weather_H192_validation_train_memory_emb.npy (21, 1525, 64)
  channel 1/21
  channel 21/21
Validation Weather H=192: anchors=5079, pairs=106659, memory/C=1525
Gate Weather     H=192 ep=01 OOF=0.980555 val=0.490809 alpha=0.103 best=0.490809@1
Gate Weather     H=192 ep=02 OOF=0.972326 val=0.490817 alpha=0.103 best=0.490809@1
Gate Weather     H=192 ep=03 OOF=0.962097 val=0.490753 alpha=0.104 best=0.490753@3
Gate Weather     H=192 ep=04 OOF=0.945595 val=0.490573 alpha=0.107 best=0.490573@4
Gate Weather     H=192 ep=05 OOF=0.941788 val=0.490158 alpha=0.114 best=0.490158@5
Gate Weather     H=192 ep=06 OOF=0.942856 val=0.489250 alpha=0.129 best=0.489250@6
Gate Weather     H=192 ep=07 OOF=0.942576 val=0.487978 alpha=0.156 best=0.487978@7
Gate Weather     H=192 ep=08 OOF=0.927853 val=0.486917 alpha=0.202 best=0.486917@8
Gate Weather     H=192 ep=09 OOF=0.935546 val=0.487052 alpha=0.230 best=0.486917@8
Gate Weather     H=192 ep=10 OOF=0.927934 val=0.487519 alpha=0.247 best=0.486917@8
Gate Weather     H=192 ep=11 OOF=0.915122 val=0.487469 alpha=0.241 best=0.486917@8
Gate Weather     H=192 ep=12 OOF=0.910691 val=0.487433 alpha=0.238 best=0.486917@8
Gate Weather     H=192 ep=13 OOF=0.908728 val=0.486696 alpha=0.220 best=0.486696@13
Gate Weather     H=192 ep=14 OOF=0.906600 val=0.486342 alpha=0.218 best=0.486342@14
Gate Weather     H=192 ep=15 OOF=0.916971 val=0.485885 alpha=0.203 best=0.485885@15
Gate Weather     H=192 ep=16 OOF=0.915169 val=0.485581 alpha=0.195 best=0.485581@16
Gate Weather     H=192 ep=17 OOF=0.901544 val=0.485155 alpha=0.192 best=0.485155@17
Gate Weather     H=192 ep=18 OOF=0.903690 val=0.485095 alpha=0.180 best=0.485095@18
Gate Weather     H=192 ep=19 OOF=0.897956 val=0.484888 alpha=0.186 best=0.484888@19
Gate Weather     H=192 ep=20 OOF=0.895424 val=0.484597 alpha=0.180 best=0.484597@20
Gate Weather     H=192 ep=21 OOF=0.897150 val=0.484247 alpha=0.184 best=0.484247@21
Gate Weather     H=192 ep=22 OOF=0.909054 val=0.484052 alpha=0.180 best=0.484052@22
Gate Weather     H=192 ep=23 OOF=0.901006 val=0.484419 alpha=0.176 best=0.484052@22
Gate Weather     H=192 ep=24 OOF=0.906913 val=0.483843 alpha=0.189 best=0.483843@24
Gate Weather     H=192 ep=25 OOF=0.911856 val=0.483664 alpha=0.184 best=0.483664@25
Gate Weather     H=192 ep=26 OOF=0.895885 val=0.483672 alpha=0.186 best=0.483664@25
Gate Weather     H=192 ep=27 OOF=0.891481 val=0.483323 alpha=0.183 best=0.483323@27
Gate Weather     H=192 ep=28 OOF=0.894842 val=0.483347 alpha=0.189 best=0.483323@27
Gate Weather     H=192 ep=29 OOF=0.895139 val=0.483313 alpha=0.190 best=0.483313@29
Gate Weather     H=192 ep=30 OOF=0.908757 val=0.483274 alpha=0.192 best=0.483274@30
Gate Weather     H=192 ep=31 OOF=0.894927 val=0.483132 alpha=0.194 best=0.483132@31
Gate Weather     H=192 ep=32 OOF=0.899704 val=0.482748 alpha=0.195 best=0.482748@32
Gate Weather     H=192 ep=33 OOF=0.899869 val=0.483330 alpha=0.211 best=0.482748@32
Gate Weather     H=192 ep=34 OOF=0.896491 val=0.483075 alpha=0.191 best=0.482748@32
Gate Weather     H=192 ep=35 OOF=0.898008 val=0.482614 alpha=0.195 best=0.482614@35
Gate Weather     H=192 ep=36 OOF=0.890917 val=0.482693 alpha=0.203 best=0.482614@35
Gate Weather     H=192 ep=37 OOF=0.903518 val=0.482645 alpha=0.197 best=0.482614@35
Gate Weather     H=192 ep=38 OOF=0.896602 val=0.482245 alpha=0.204 best=0.482245@38
Gate Weather     H=192 ep=39 OOF=0.885642 val=0.482165 alpha=0.202 best=0.482165@39
Gate Weather     H=192 ep=40 OOF=0.893877 val=0.482545 alpha=0.208 best=0.482165@39
Gate Weather     H=192 ep=41 OOF=0.892644 val=0.482388 alpha=0.203 best=0.482165@39
Gate Weather     H=192 ep=42 OOF=0.888025 val=0.481989 alpha=0.208 best=0.481989@42
Gate Weather     H=192 ep=43 OOF=0.890379 val=0.482321 alpha=0.209 best=0.481989@42
Gate Weather     H=192 ep=44 OOF=0.882848 val=0.482443 alpha=0.202 best=0.481989@42
Gate Weather     H=192 ep=45 OOF=0.892347 val=0.482082 alpha=0.208 best=0.481989@42
Gate Weather     H=192 ep=46 OOF=0.880675 val=0.481668 alpha=0.209 best=0.481668@46
Gate Weather     H=192 ep=47 OOF=0.925094 val=0.481998 alpha=0.204 best=0.481668@46
Gate Weather     H=192 ep=48 OOF=0.892917 val=0.481702 alpha=0.210 best=0.481668@46
Gate Weather     H=192 ep=49 OOF=0.890097 val=0.481861 alpha=0.206 best=0.481668@46
Gate Weather     H=192 ep=50 OOF=0.892784 val=0.481486 alpha=0.212 best=0.481486@50
Validation calibration | alpha0=0.20 | lambda=1.00 | gateEpoch=50
Building memory embedding: Weather_H192_test_trainval_memory_emb.npy (21, 1745, 64)
  channel 1/21
  channel 21/21
  test anchors 64/10348
  test anchors 512/10348
  test anchors 1024/10348
  test anchors 1536/10348
  test anchors 2048/10348
  test anchors 2560/10348
  test anchors 3008/10348
  test anchors 3520/10348
  test anchors 4032/10348
  test anchors 4544/10348
  test anchors 5056/10348
  test anchors 5504/10348
  test anchors 6016/10348
  test anchors 6528/10348
  test anchors 7040/10348
  test anchors 7552/10348
  test anchors 8000/10348
  test anchors 8512/10348
  test anchors 9024/10348
  test anchors 9536/10348
  test anchors 10048/10348
  test anchors 10348/10348

FINAL CONDITION RESULT

   Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0  Weather      192          0.224436              0.2144                4.471502          0.257719            0.253501        0.30028    0.216241           0.2144    0.175964          0.2           1.0         0.207794                 0.904762                     21.597297        2.070459

######################################################################################################################################################
Weather | H=336 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.282732, MAE=0.299481, best_epoch=3
Updating learning rate to 0.0001
Fold direct Weather     H=336 F1 ep=01/3 train=0.838181 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H=336 F1 ep=02/3 train=0.769272 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H=336 F1 ep=03/3 train=0.730610 lr=2.500e-05
Building memory embedding: Weather_H336_F1_prefix20287_emb.npy (21, 828, 64)
  channel 1/21
  channel 21/21
OOF Weather H=336 F1: prefix=20287, end=25820, anchors=1300, pairs=27300, memory/C=828
Updating learning rate to 0.0001
Fold direct Weather     H=336 F2 ep=01/3 train=0.682502 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H=336 F2 ep=02/3 train=0.633141 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H=336 F2 ep=03/3 train=0.611930 lr=2.500e-05
Building memory embedding: Weather_H336_F2_prefix25820_emb.npy (21, 1058, 64)
  channel 1/21
  channel 21/21
OOF Weather H=336 F2: prefix=25820, end=31353, anchors=1300, pairs=27300, memory/C=1058
Updating learning rate to 0.0001
Fold direct Weather     H=336 F3 ep=01/3 train=0.663575 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H=336 F3 ep=02/3 train=0.618967 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H=336 F3 ep=03/3 train=0.599418 lr=2.500e-05
Building memory embedding: Weather_H336_F3_prefix31353_emb.npy (21, 1289, 64)
  channel 1/21
  channel 21/21
OOF Weather H=336 F3: prefix=31353, end=36887, anchors=1300, pairs=27300, memory/C=1289
Total OOF pairs: 81900
Building memory embedding: Weather_H336_validation_train_memory_emb.npy (21, 1519, 64)
  channel 1/21
  channel 21/21
Validation Weather H=336: anchors=4935, pairs=103635, memory/C=1519
Gate Weather     H=336 ep=01 OOF=1.064701 val=0.579281 alpha=0.103 best=0.579281@1
Gate Weather     H=336 ep=02 OOF=1.064378 val=0.579188 alpha=0.104 best=0.579188@2
Gate Weather     H=336 ep=03 OOF=1.063884 val=0.578873 alpha=0.109 best=0.578873@3
Gate Weather     H=336 ep=04 OOF=1.063015 val=0.578212 alpha=0.118 best=0.578212@4
Gate Weather     H=336 ep=05 OOF=1.061040 val=0.577064 alpha=0.135 best=0.577064@5
Gate Weather     H=336 ep=06 OOF=1.057763 val=0.575361 alpha=0.163 best=0.575361@6
Gate Weather     H=336 ep=07 OOF=1.053264 val=0.574403 alpha=0.193 best=0.574403@7
Gate Weather     H=336 ep=08 OOF=1.048526 val=0.574499 alpha=0.216 best=0.574403@7
Gate Weather     H=336 ep=09 OOF=1.044623 val=0.574803 alpha=0.227 best=0.574403@7
Gate Weather     H=336 ep=10 OOF=1.041709 val=0.574798 alpha=0.229 best=0.574403@7
Gate Weather     H=336 ep=11 OOF=1.040265 val=0.574376 alpha=0.226 best=0.574376@11
Gate Weather     H=336 ep=12 OOF=1.035866 val=0.573526 alpha=0.227 best=0.573526@12
Gate Weather     H=336 ep=13 OOF=1.034549 val=0.572965 alpha=0.220 best=0.572965@13
Gate Weather     H=336 ep=14 OOF=1.033642 val=0.572350 alpha=0.214 best=0.572350@14
Gate Weather     H=336 ep=15 OOF=1.031585 val=0.571580 alpha=0.213 best=0.571580@15
Gate Weather     H=336 ep=16 OOF=1.030203 val=0.571495 alpha=0.201 best=0.571495@16
Gate Weather     H=336 ep=17 OOF=1.028448 val=0.570907 alpha=0.192 best=0.570907@17
Gate Weather     H=336 ep=18 OOF=1.027450 val=0.570669 alpha=0.185 best=0.570669@18
Gate Weather     H=336 ep=19 OOF=1.026681 val=0.571224 alpha=0.177 best=0.570669@18
Gate Weather     H=336 ep=20 OOF=1.025957 val=0.570136 alpha=0.183 best=0.570136@20
Gate Weather     H=336 ep=21 OOF=1.025323 val=0.569883 alpha=0.184 best=0.569883@21
Gate Weather     H=336 ep=22 OOF=1.024479 val=0.570234 alpha=0.179 best=0.569883@21
Gate Weather     H=336 ep=23 OOF=1.023425 val=0.570196 alpha=0.178 best=0.569883@21
Gate Weather     H=336 ep=24 OOF=1.022267 val=0.569285 alpha=0.187 best=0.569285@24
Gate Weather     H=336 ep=25 OOF=1.022130 val=0.570014 alpha=0.181 best=0.569285@24
Gate Weather     H=336 ep=26 OOF=1.021223 val=0.569519 alpha=0.186 best=0.569285@24
Gate Weather     H=336 ep=27 OOF=1.020027 val=0.569275 alpha=0.194 best=0.569275@27
Gate Weather     H=336 ep=28 OOF=1.020205 val=0.568719 alpha=0.198 best=0.568719@28
Gate Weather     H=336 ep=29 OOF=1.020059 val=0.568508 alpha=0.202 best=0.568508@29
Gate Weather     H=336 ep=30 OOF=1.018381 val=0.568489 alpha=0.208 best=0.568489@30
Gate Weather     H=336 ep=31 OOF=1.017617 val=0.568834 alpha=0.210 best=0.568489@30
Gate Weather     H=336 ep=32 OOF=1.017452 val=0.568161 alpha=0.217 best=0.568161@32
Gate Weather     H=336 ep=33 OOF=1.016992 val=0.568183 alpha=0.217 best=0.568161@32
Gate Weather     H=336 ep=34 OOF=1.016418 val=0.567057 alpha=0.232 best=0.567057@34
Gate Weather     H=336 ep=35 OOF=1.016337 val=0.568139 alpha=0.223 best=0.567057@34
Gate Weather     H=336 ep=36 OOF=1.015289 val=0.567876 alpha=0.225 best=0.567057@34
Gate Weather     H=336 ep=37 OOF=1.015159 val=0.567857 alpha=0.227 best=0.567057@34
Gate Weather     H=336 ep=38 OOF=1.014369 val=0.567651 alpha=0.228 best=0.567057@34
Gate Weather     H=336 ep=39 OOF=1.014067 val=0.567615 alpha=0.235 best=0.567057@34
Gate Weather     H=336 ep=40 OOF=1.013503 val=0.566652 alpha=0.239 best=0.566652@40
Gate Weather     H=336 ep=41 OOF=1.013526 val=0.566693 alpha=0.234 best=0.566652@40
Gate Weather     H=336 ep=42 OOF=1.012921 val=0.566619 alpha=0.243 best=0.566619@42
Gate Weather     H=336 ep=43 OOF=1.012409 val=0.566822 alpha=0.237 best=0.566619@42
Gate Weather     H=336 ep=44 OOF=1.012084 val=0.566409 alpha=0.239 best=0.566409@44
Gate Weather     H=336 ep=45 OOF=1.011579 val=0.566481 alpha=0.233 best=0.566409@44
Gate Weather     H=336 ep=46 OOF=1.010836 val=0.565886 alpha=0.243 best=0.565886@46
Gate Weather     H=336 ep=47 OOF=1.010497 val=0.566285 alpha=0.240 best=0.565886@46
Gate Weather     H=336 ep=48 OOF=1.010565 val=0.566491 alpha=0.232 best=0.565886@46
Gate Weather     H=336 ep=49 OOF=1.010285 val=0.565979 alpha=0.235 best=0.565886@46
Gate Weather     H=336 ep=50 OOF=1.009915 val=0.566404 alpha=0.231 best=0.565886@46
Validation calibration | alpha0=0.20 | lambda=1.00 | gateEpoch=46
Building memory embedding: Weather_H336_test_trainval_memory_emb.npy (21, 1739, 64)
  channel 1/21
  channel 21/21
  test anchors 64/10204
  test anchors 512/10204
  test anchors 1024/10204
  test anchors 1536/10204
  test anchors 2048/10204
  test anchors 2560/10204
  test anchors 3008/10204
  test anchors 3520/10204
  test anchors 4032/10204
  test anchors 4544/10204
  test anchors 5056/10204
  test anchors 5504/10204
  test anchors 6016/10204
  test anchors 6528/10204
  test anchors 7040/10204
  test anchors 7552/10204
  test anchors 8000/10204
  test anchors 8512/10204
  test anchors 9024/10204
  test anchors 9536/10204
  test anchors 10048/10204
  test anchors 10204/10204

FINAL CONDITION RESULT

   Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0  Weather      336          0.282732            0.270471                4.336659          0.299481            0.296607       0.357731    0.270843         0.270471    0.222023          0.2           1.0         0.265729                 0.714286                     21.472557         1.38288

######################################################################################################################################################
Weather | H=720 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.357908, MAE=0.349720, best_epoch=4
Updating learning rate to 0.0001
Fold direct Weather     H=720 F1 ep=01/4 train=1.019857 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H=720 F1 ep=02/4 train=0.959190 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H=720 F1 ep=03/4 train=0.920812 lr=2.500e-05
Updating learning rate to 1.25e-05
Fold direct Weather     H=720 F1 ep=04/4 train=0.893955 lr=1.250e-05
Building memory embedding: Weather_H720_F1_prefix20287_emb.npy (21, 812, 64)
  channel 1/21
  channel 21/21
OOF Weather H=720 F1: prefix=20287, end=25820, anchors=1204, pairs=25284, memory/C=812
Updating learning rate to 0.0001
Fold direct Weather     H=720 F2 ep=01/4 train=0.791286 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H=720 F2 ep=02/4 train=0.746336 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H=720 F2 ep=03/4 train=0.725420 lr=2.500e-05
Updating learning rate to 1.25e-05
Fold direct Weather     H=720 F2 ep=04/4 train=0.712468 lr=1.250e-05
Building memory embedding: Weather_H720_F2_prefix25820_emb.npy (21, 1042, 64)
  channel 1/21
  channel 21/21
OOF Weather H=720 F2: prefix=25820, end=31353, anchors=1204, pairs=25284, memory/C=1042
Updating learning rate to 0.0001
Fold direct Weather     H=720 F3 ep=01/4 train=0.750970 lr=1.000e-04
Updating learning rate to 5e-05
Fold direct Weather     H=720 F3 ep=02/4 train=0.706127 lr=5.000e-05
Updating learning rate to 2.5e-05
Fold direct Weather     H=720 F3 ep=03/4 train=0.688220 lr=2.500e-05
Updating learning rate to 1.25e-05
Fold direct Weather     H=720 F3 ep=04/4 train=0.677296 lr=1.250e-05
Building memory embedding: Weather_H720_F3_prefix31353_emb.npy (21, 1273, 64)
  channel 1/21
  channel 21/21
OOF Weather H=720 F3: prefix=31353, end=36887, anchors=1204, pairs=25284, memory/C=1273
Total OOF pairs: 75852
Building memory embedding: Weather_H720_validation_train_memory_emb.npy (21, 1503, 64)
  channel 1/21
  channel 21/21
Validation Weather H=720: anchors=4551, pairs=95571, memory/C=1503
Gate Weather     H=720 ep=01 OOF=1.171960 val=0.706360 alpha=0.100 best=0.706360@1
Gate Weather     H=720 ep=02 OOF=1.167285 val=0.706298 alpha=0.102 best=0.706298@2
Gate Weather     H=720 ep=03 OOF=1.168845 val=0.706119 alpha=0.104 best=0.706119@3
Gate Weather     H=720 ep=04 OOF=1.171975 val=0.705545 alpha=0.111 best=0.705545@4
Gate Weather     H=720 ep=05 OOF=1.160973 val=0.704205 alpha=0.128 best=0.704205@5
Gate Weather     H=720 ep=06 OOF=1.162777 val=0.702070 alpha=0.166 best=0.702070@6
Gate Weather     H=720 ep=07 OOF=1.148724 val=0.701297 alpha=0.218 best=0.701297@7
Gate Weather     H=720 ep=08 OOF=1.158386 val=0.702671 alpha=0.238 best=0.701297@7
Gate Weather     H=720 ep=09 OOF=1.144764 val=0.703003 alpha=0.248 best=0.701297@7
Gate Weather     H=720 ep=10 OOF=1.146670 val=0.702824 alpha=0.262 best=0.701297@7
Gate Weather     H=720 ep=11 OOF=1.144037 val=0.702928 alpha=0.264 best=0.701297@7
Gate Weather     H=720 ep=12 OOF=1.126277 val=0.703013 alpha=0.264 best=0.701297@7
Gate Weather     H=720 ep=13 OOF=1.133644 val=0.702740 alpha=0.252 best=0.701297@7
Gate Weather     H=720 ep=14 OOF=1.129728 val=0.702390 alpha=0.259 best=0.701297@7
Validation calibration | alpha0=0.20 | lambda=0.75 | gateEpoch=7
Building memory embedding: Weather_H720_test_trainval_memory_emb.npy (21, 1723, 64)
  channel 1/21
  channel 21/21
  test anchors 64/9820
  test anchors 512/9820
  test anchors 1024/9820
  test anchors 1536/9820
  test anchors 2048/9820
  test anchors 2560/9820
  test anchors 3008/9820
  test anchors 3520/9820
  test anchors 4032/9820
  test anchors 4544/9820
  test anchors 5056/9820
  test anchors 5504/9820
  test anchors 6016/9820
  test anchors 6528/9820
  test anchors 7040/9820
  test anchors 7552/9820
  test anchors 8000/9820
  test anchors 8512/9820
  test anchors 9024/9820
  test anchors 9536/9820
  test anchors 9820/9820

FINAL CONDITION RESULT

   Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0  Weather      720          0.357908            0.344274                3.809215           0.34972            0.344686       0.438722    0.341699         0.345558    0.283096          0.2          0.75         0.191808                 0.857143                     20.902616        1.889911

######################################################################################################################################################
Electricity | H=96 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.148275, MAE=0.239707, best_epoch=7
Updating learning rate to 0.0005
Fold direct Electricity H= 96 F1 ep=01/7 train=0.209518 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H= 96 F1 ep=02/7 train=0.176026 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H= 96 F1 ep=03/7 train=0.161989 lr=1.250e-04
Updating learning rate to 6.25e-05
Fold direct Electricity H= 96 F1 ep=04/7 train=0.155424 lr=6.250e-05
Updating learning rate to 3.125e-05
Fold direct Electricity H= 96 F1 ep=05/7 train=0.151490 lr=3.125e-05
Updating learning rate to 1.5625e-05
Fold direct Electricity H= 96 F1 ep=06/7 train=0.149135 lr=1.563e-05
Updating learning rate to 7.8125e-06
Fold direct Electricity H= 96 F1 ep=07/7 train=0.147600 lr=7.813e-06
Building memory embedding: Electricity_H96_F1_prefix10126_emb.npy (321, 414, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=96 F1: prefix=10126, end=12888, anchors=667, pairs=214107, memory/C=414
Updating learning rate to 0.0005
Fold direct Electricity H= 96 F2 ep=01/7 train=0.202191 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H= 96 F2 ep=02/7 train=0.170320 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H= 96 F2 ep=03/7 train=0.157089 lr=1.250e-04
Updating learning rate to 6.25e-05
Fold direct Electricity H= 96 F2 ep=04/7 train=0.150951 lr=6.250e-05
Updating learning rate to 3.125e-05
Fold direct Electricity H= 96 F2 ep=05/7 train=0.147145 lr=3.125e-05
Updating learning rate to 1.5625e-05
Fold direct Electricity H= 96 F2 ep=06/7 train=0.144744 lr=1.563e-05
Updating learning rate to 7.8125e-06
Fold direct Electricity H= 96 F2 ep=07/7 train=0.143396 lr=7.813e-06
Building memory embedding: Electricity_H96_F2_prefix12888_emb.npy (321, 530, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=96 F2: prefix=12888, end=15650, anchors=667, pairs=214107, memory/C=530
Updating learning rate to 0.0005
Fold direct Electricity H= 96 F3 ep=01/7 train=0.196701 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H= 96 F3 ep=02/7 train=0.167187 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H= 96 F3 ep=03/7 train=0.155174 lr=1.250e-04
Updating learning rate to 6.25e-05
Fold direct Electricity H= 96 F3 ep=04/7 train=0.149239 lr=6.250e-05
Updating learning rate to 3.125e-05
Fold direct Electricity H= 96 F3 ep=05/7 train=0.145411 lr=3.125e-05
Updating learning rate to 1.5625e-05
Fold direct Electricity H= 96 F3 ep=06/7 train=0.143012 lr=1.563e-05
Updating learning rate to 7.8125e-06
Fold direct Electricity H= 96 F3 ep=07/7 train=0.141608 lr=7.813e-06
Building memory embedding: Electricity_H96_F3_prefix15650_emb.npy (321, 645, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=96 F3: prefix=15650, end=18412, anchors=667, pairs=214107, memory/C=645
Total OOF pairs: 642321
Building memory embedding: Electricity_H96_validation_train_memory_emb.npy (321, 760, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
Validation Electricity H=96: anchors=2537, pairs=814377, memory/C=760
Gate Electricity H= 96 ep=01 OOF=0.165296 val=0.127486 alpha=0.021 best=0.127486@1
Gate Electricity H= 96 ep=02 OOF=0.160383 val=0.127335 alpha=0.019 best=0.127335@2
Gate Electricity H= 96 ep=03 OOF=0.160086 val=0.127134 alpha=0.016 best=0.127134@3
Gate Electricity H= 96 ep=04 OOF=0.159776 val=0.126924 alpha=0.021 best=0.126924@4
Gate Electricity H= 96 ep=05 OOF=0.159650 val=0.126790 alpha=0.020 best=0.126790@5
Gate Electricity H= 96 ep=06 OOF=0.159468 val=0.126621 alpha=0.023 best=0.126621@6
Gate Electricity H= 96 ep=07 OOF=0.159519 val=0.126683 alpha=0.022 best=0.126621@6
Gate Electricity H= 96 ep=08 OOF=0.159314 val=0.126767 alpha=0.026 best=0.126621@6
Gate Electricity H= 96 ep=09 OOF=0.159225 val=0.126608 alpha=0.022 best=0.126608@9
Gate Electricity H= 96 ep=10 OOF=0.159150 val=0.126409 alpha=0.025 best=0.126409@10
Gate Electricity H= 96 ep=11 OOF=0.159157 val=0.126533 alpha=0.027 best=0.126409@10
Gate Electricity H= 96 ep=12 OOF=0.159148 val=0.126422 alpha=0.025 best=0.126409@10
Gate Electricity H= 96 ep=13 OOF=0.159146 val=0.126413 alpha=0.026 best=0.126409@10
Gate Electricity H= 96 ep=14 OOF=0.159111 val=0.126432 alpha=0.029 best=0.126409@10
Gate Electricity H= 96 ep=15 OOF=0.158969 val=0.126461 alpha=0.025 best=0.126409@10
Gate Electricity H= 96 ep=16 OOF=0.159016 val=0.126312 alpha=0.027 best=0.126312@16
Gate Electricity H= 96 ep=17 OOF=0.159065 val=0.126398 alpha=0.027 best=0.126312@16
Gate Electricity H= 96 ep=18 OOF=0.158967 val=0.126353 alpha=0.025 best=0.126312@16
Gate Electricity H= 96 ep=19 OOF=0.158997 val=0.126296 alpha=0.027 best=0.126296@19
Gate Electricity H= 96 ep=20 OOF=0.159031 val=0.126370 alpha=0.028 best=0.126296@19
Gate Electricity H= 96 ep=21 OOF=0.158896 val=0.126261 alpha=0.029 best=0.126261@21
Gate Electricity H= 96 ep=22 OOF=0.158823 val=0.126381 alpha=0.027 best=0.126261@21
Gate Electricity H= 96 ep=23 OOF=0.158824 val=0.126323 alpha=0.026 best=0.126261@21
Gate Electricity H= 96 ep=24 OOF=0.158833 val=0.126451 alpha=0.028 best=0.126261@21
Gate Electricity H= 96 ep=25 OOF=0.158731 val=0.126305 alpha=0.028 best=0.126261@21
Gate Electricity H= 96 ep=26 OOF=0.158739 val=0.126257 alpha=0.028 best=0.126257@26
Gate Electricity H= 96 ep=27 OOF=0.158755 val=0.126368 alpha=0.028 best=0.126257@26
Gate Electricity H= 96 ep=28 OOF=0.158715 val=0.126235 alpha=0.028 best=0.126235@28
Gate Electricity H= 96 ep=29 OOF=0.158756 val=0.126345 alpha=0.026 best=0.126235@28
Gate Electricity H= 96 ep=30 OOF=0.158644 val=0.126195 alpha=0.026 best=0.126195@30
Gate Electricity H= 96 ep=31 OOF=0.158630 val=0.126156 alpha=0.026 best=0.126156@31
Gate Electricity H= 96 ep=32 OOF=0.158655 val=0.126274 alpha=0.028 best=0.126156@31
Gate Electricity H= 96 ep=33 OOF=0.158601 val=0.126132 alpha=0.033 best=0.126132@33
Gate Electricity H= 96 ep=34 OOF=0.158723 val=0.126093 alpha=0.029 best=0.126093@34
Gate Electricity H= 96 ep=35 OOF=0.158653 val=0.126241 alpha=0.027 best=0.126093@34
Gate Electricity H= 96 ep=36 OOF=0.158678 val=0.126240 alpha=0.024 best=0.126093@34
Gate Electricity H= 96 ep=37 OOF=0.158676 val=0.126134 alpha=0.026 best=0.126093@34
Gate Electricity H= 96 ep=38 OOF=0.158501 val=0.126092 alpha=0.026 best=0.126092@38
Gate Electricity H= 96 ep=39 OOF=0.158454 val=0.126224 alpha=0.025 best=0.126092@38
Gate Electricity H= 96 ep=40 OOF=0.158526 val=0.126035 alpha=0.031 best=0.126035@40
Gate Electricity H= 96 ep=41 OOF=0.158410 val=0.126046 alpha=0.025 best=0.126035@40
Gate Electricity H= 96 ep=42 OOF=0.158453 val=0.125993 alpha=0.030 best=0.125993@42
Gate Electricity H= 96 ep=43 OOF=0.158427 val=0.126098 alpha=0.027 best=0.125993@42
Gate Electricity H= 96 ep=44 OOF=0.158478 val=0.126021 alpha=0.026 best=0.125993@42
Gate Electricity H= 96 ep=45 OOF=0.158407 val=0.126016 alpha=0.027 best=0.125993@42
Gate Electricity H= 96 ep=46 OOF=0.158442 val=0.125974 alpha=0.029 best=0.125974@46
Gate Electricity H= 96 ep=47 OOF=0.158359 val=0.126016 alpha=0.026 best=0.125974@46
Gate Electricity H= 96 ep=48 OOF=0.158338 val=0.126093 alpha=0.026 best=0.125974@46
Gate Electricity H= 96 ep=49 OOF=0.158346 val=0.125995 alpha=0.029 best=0.125974@46
Gate Electricity H= 96 ep=50 OOF=0.158249 val=0.126169 alpha=0.029 best=0.125974@46
Validation calibration | alpha0=0.00 | lambda=1.00 | gateEpoch=46
Building memory embedding: Electricity_H96_test_trainval_memory_emb.npy (321, 869, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
  test anchors 16/5165
  test anchors 512/5165
  test anchors 1008/5165
  test anchors 1504/5165
  test anchors 2000/5165
  test anchors 2512/5165
  test anchors 3008/5165
  test anchors 3504/5165
  test anchors 4000/5165
  test anchors 4512/5165
  test anchors 5008/5165
  test anchors 5165/5165

FINAL CONDITION RESULT

       Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0  Electricity       96          0.148275             0.14631                1.325576          0.239707              0.2395       1.839673    0.148275          0.14631    0.134724          0.0           1.0         0.031767                 0.813084                      9.139225        7.553352

######################################################################################################################################################
Electricity | H=192 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.165100, MAE=0.256106, best_epoch=7
Updating learning rate to 0.0005
Fold direct Electricity H=192 F1 ep=01/7 train=0.217142 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H=192 F1 ep=02/7 train=0.185918 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H=192 F1 ep=03/7 train=0.174591 lr=1.250e-04
Updating learning rate to 6.25e-05
Fold direct Electricity H=192 F1 ep=04/7 train=0.169459 lr=6.250e-05
Updating learning rate to 3.125e-05
Fold direct Electricity H=192 F1 ep=05/7 train=0.166311 lr=3.125e-05
Updating learning rate to 1.5625e-05
Fold direct Electricity H=192 F1 ep=06/7 train=0.164306 lr=1.563e-05
Updating learning rate to 7.8125e-06
Fold direct Electricity H=192 F1 ep=07/7 train=0.163185 lr=7.813e-06
Building memory embedding: Electricity_H192_F1_prefix10126_emb.npy (321, 410, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=192 F1: prefix=10126, end=12888, anchors=643, pairs=206403, memory/C=410
Updating learning rate to 0.0005
Fold direct Electricity H=192 F2 ep=01/7 train=0.208503 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H=192 F2 ep=02/7 train=0.179762 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H=192 F2 ep=03/7 train=0.169428 lr=1.250e-04
Updating learning rate to 6.25e-05
Fold direct Electricity H=192 F2 ep=04/7 train=0.164282 lr=6.250e-05
Updating learning rate to 3.125e-05
Fold direct Electricity H=192 F2 ep=05/7 train=0.161155 lr=3.125e-05
Updating learning rate to 1.5625e-05
Fold direct Electricity H=192 F2 ep=06/7 train=0.159122 lr=1.563e-05
Updating learning rate to 7.8125e-06
Fold direct Electricity H=192 F2 ep=07/7 train=0.157887 lr=7.813e-06
Building memory embedding: Electricity_H192_F2_prefix12888_emb.npy (321, 526, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=192 F2: prefix=12888, end=15650, anchors=643, pairs=206403, memory/C=526
Updating learning rate to 0.0005
Fold direct Electricity H=192 F3 ep=01/7 train=0.206492 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H=192 F3 ep=02/7 train=0.179598 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H=192 F3 ep=03/7 train=0.170154 lr=1.250e-04
Updating learning rate to 6.25e-05
Fold direct Electricity H=192 F3 ep=04/7 train=0.165366 lr=6.250e-05
Updating learning rate to 3.125e-05
Fold direct Electricity H=192 F3 ep=05/7 train=0.162003 lr=3.125e-05
Updating learning rate to 1.5625e-05
Fold direct Electricity H=192 F3 ep=06/7 train=0.159694 lr=1.563e-05
Updating learning rate to 7.8125e-06
Fold direct Electricity H=192 F3 ep=07/7 train=0.158302 lr=7.813e-06
Building memory embedding: Electricity_H192_F3_prefix15650_emb.npy (321, 641, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=192 F3: prefix=15650, end=18412, anchors=643, pairs=206403, memory/C=641
Total OOF pairs: 619209
Building memory embedding: Electricity_H192_validation_train_memory_emb.npy (321, 756, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
Validation Electricity H=192: anchors=2441, pairs=783561, memory/C=756
Gate Electricity H=192 ep=01 OOF=0.187137 val=0.138528 alpha=0.023 best=0.138528@1
Gate Electricity H=192 ep=02 OOF=0.181609 val=0.138329 alpha=0.019 best=0.138329@2
Gate Electricity H=192 ep=03 OOF=0.181268 val=0.138069 alpha=0.017 best=0.138069@3
Gate Electricity H=192 ep=04 OOF=0.181134 val=0.137937 alpha=0.019 best=0.137937@4
Gate Electricity H=192 ep=05 OOF=0.180862 val=0.137798 alpha=0.023 best=0.137798@5
Gate Electricity H=192 ep=06 OOF=0.180697 val=0.137677 alpha=0.022 best=0.137677@6
Gate Electricity H=192 ep=07 OOF=0.180532 val=0.137736 alpha=0.029 best=0.137677@6
Gate Electricity H=192 ep=08 OOF=0.180508 val=0.137633 alpha=0.033 best=0.137633@8
Gate Electricity H=192 ep=09 OOF=0.180345 val=0.137574 alpha=0.034 best=0.137574@9
Gate Electricity H=192 ep=10 OOF=0.180249 val=0.137605 alpha=0.036 best=0.137574@9
Gate Electricity H=192 ep=11 OOF=0.180214 val=0.137547 alpha=0.032 best=0.137547@11
Gate Electricity H=192 ep=12 OOF=0.180183 val=0.137594 alpha=0.039 best=0.137547@11
Gate Electricity H=192 ep=13 OOF=0.180204 val=0.137640 alpha=0.038 best=0.137547@11
Gate Electricity H=192 ep=14 OOF=0.180119 val=0.137512 alpha=0.037 best=0.137512@14
Gate Electricity H=192 ep=15 OOF=0.180112 val=0.137465 alpha=0.031 best=0.137465@15
Gate Electricity H=192 ep=16 OOF=0.180072 val=0.137402 alpha=0.037 best=0.137402@16
Gate Electricity H=192 ep=17 OOF=0.180106 val=0.137597 alpha=0.037 best=0.137402@16
Gate Electricity H=192 ep=18 OOF=0.179970 val=0.137418 alpha=0.036 best=0.137402@16
Gate Electricity H=192 ep=19 OOF=0.180042 val=0.137386 alpha=0.038 best=0.137386@19
Gate Electricity H=192 ep=20 OOF=0.179994 val=0.137538 alpha=0.044 best=0.137386@19
Gate Electricity H=192 ep=21 OOF=0.179966 val=0.137278 alpha=0.034 best=0.137278@21
Gate Electricity H=192 ep=22 OOF=0.179935 val=0.137586 alpha=0.041 best=0.137278@21
Gate Electricity H=192 ep=23 OOF=0.179901 val=0.137358 alpha=0.033 best=0.137278@21
Gate Electricity H=192 ep=24 OOF=0.179934 val=0.137321 alpha=0.034 best=0.137278@21
Gate Electricity H=192 ep=25 OOF=0.179863 val=0.137319 alpha=0.037 best=0.137278@21
Gate Electricity H=192 ep=26 OOF=0.179860 val=0.137383 alpha=0.036 best=0.137278@21
Gate Electricity H=192 ep=27 OOF=0.179837 val=0.137468 alpha=0.036 best=0.137278@21
Gate Electricity H=192 ep=28 OOF=0.179865 val=0.137434 alpha=0.035 best=0.137278@21
Validation calibration | alpha0=0.00 | lambda=1.00 | gateEpoch=21
Building memory embedding: Electricity_H192_test_trainval_memory_emb.npy (321, 865, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
  test anchors 16/5069
  test anchors 512/5069
  test anchors 1008/5069
  test anchors 1504/5069
  test anchors 2000/5069
  test anchors 2512/5069
  test anchors 3008/5069
  test anchors 3504/5069
  test anchors 4000/5069
  test anchors 4512/5069
  test anchors 5008/5069
  test anchors 5069/5069

FINAL CONDITION RESULT

       Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0  Electricity      192          0.165101            0.164833                0.161767          0.256106            0.257408       1.996508    0.165101         0.164833    0.153132          0.0           1.0         0.043048                 0.666667                      7.249021        7.628455

######################################################################################################################################################
Electricity | H=336 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.179687, MAE=0.272384, best_epoch=9
Updating learning rate to 0.0005
Fold direct Electricity H=336 F1 ep=01/9 train=0.241576 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H=336 F1 ep=02/9 train=0.209079 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H=336 F1 ep=03/9 train=0.197080 lr=1.250e-04
Updating learning rate to 6.25e-05
Fold direct Electricity H=336 F1 ep=04/9 train=0.191694 lr=6.250e-05
Updating learning rate to 3.125e-05
Fold direct Electricity H=336 F1 ep=05/9 train=0.188226 lr=3.125e-05
Updating learning rate to 1.5625e-05
Fold direct Electricity H=336 F1 ep=06/9 train=0.185709 lr=1.563e-05
Updating learning rate to 7.8125e-06
Fold direct Electricity H=336 F1 ep=07/9 train=0.184021 lr=7.813e-06
Updating learning rate to 3.90625e-06
Fold direct Electricity H=336 F1 ep=08/9 train=0.182924 lr=3.906e-06
Updating learning rate to 1.953125e-06
Fold direct Electricity H=336 F1 ep=09/9 train=0.182471 lr=1.953e-06
Building memory embedding: Electricity_H336_F1_prefix10126_emb.npy (321, 404, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=336 F1: prefix=10126, end=12888, anchors=607, pairs=194847, memory/C=404
Updating learning rate to 0.0005
Fold direct Electricity H=336 F2 ep=01/9 train=0.230554 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H=336 F2 ep=02/9 train=0.199905 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H=336 F2 ep=03/9 train=0.189098 lr=1.250e-04
Updating learning rate to 6.25e-05
Fold direct Electricity H=336 F2 ep=04/9 train=0.183989 lr=6.250e-05
Updating learning rate to 3.125e-05
Fold direct Electricity H=336 F2 ep=05/9 train=0.180414 lr=3.125e-05
Updating learning rate to 1.5625e-05
Fold direct Electricity H=336 F2 ep=06/9 train=0.177869 lr=1.563e-05
Updating learning rate to 7.8125e-06
Fold direct Electricity H=336 F2 ep=07/9 train=0.176265 lr=7.813e-06
Updating learning rate to 3.90625e-06
Fold direct Electricity H=336 F2 ep=08/9 train=0.175364 lr=3.906e-06
Updating learning rate to 1.953125e-06
Fold direct Electricity H=336 F2 ep=09/9 train=0.174976 lr=1.953e-06
Building memory embedding: Electricity_H336_F2_prefix12888_emb.npy (321, 520, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=336 F2: prefix=12888, end=15650, anchors=607, pairs=194847, memory/C=520
Updating learning rate to 0.0005
Fold direct Electricity H=336 F3 ep=01/9 train=0.231342 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H=336 F3 ep=02/9 train=0.203036 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H=336 F3 ep=03/9 train=0.191907 lr=1.250e-04
Updating learning rate to 6.25e-05
Fold direct Electricity H=336 F3 ep=04/9 train=0.185982 lr=6.250e-05
Updating learning rate to 3.125e-05
Fold direct Electricity H=336 F3 ep=05/9 train=0.181408 lr=3.125e-05
Updating learning rate to 1.5625e-05
Fold direct Electricity H=336 F3 ep=06/9 train=0.178410 lr=1.563e-05
Updating learning rate to 7.8125e-06
Fold direct Electricity H=336 F3 ep=07/9 train=0.176615 lr=7.813e-06
Updating learning rate to 3.90625e-06
Fold direct Electricity H=336 F3 ep=08/9 train=0.175661 lr=3.906e-06
Updating learning rate to 1.953125e-06
Fold direct Electricity H=336 F3 ep=09/9 train=0.175256 lr=1.953e-06
Building memory embedding: Electricity_H336_F3_prefix15650_emb.npy (321, 635, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=336 F3: prefix=15650, end=18412, anchors=607, pairs=194847, memory/C=635
Total OOF pairs: 584541
Building memory embedding: Electricity_H336_validation_train_memory_emb.npy (321, 750, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
Validation Electricity H=336: anchors=2297, pairs=737337, memory/C=750
Gate Electricity H=336 ep=01 OOF=0.219537 val=0.156117 alpha=0.027 best=0.156117@1
Gate Electricity H=336 ep=02 OOF=0.213348 val=0.156156 alpha=0.020 best=0.156117@1
Gate Electricity H=336 ep=03 OOF=0.212906 val=0.155855 alpha=0.019 best=0.155855@3
Gate Electricity H=336 ep=04 OOF=0.212600 val=0.155699 alpha=0.018 best=0.155699@4
Gate Electricity H=336 ep=05 OOF=0.212433 val=0.155578 alpha=0.019 best=0.155578@5
Gate Electricity H=336 ep=06 OOF=0.212237 val=0.155320 alpha=0.020 best=0.155320@6
Gate Electricity H=336 ep=07 OOF=0.211809 val=0.155233 alpha=0.019 best=0.155233@7
Gate Electricity H=336 ep=08 OOF=0.211649 val=0.155192 alpha=0.023 best=0.155192@8
Gate Electricity H=336 ep=09 OOF=0.211422 val=0.155153 alpha=0.019 best=0.155153@9
Gate Electricity H=336 ep=10 OOF=0.211296 val=0.155074 alpha=0.021 best=0.155074@10
Gate Electricity H=336 ep=11 OOF=0.211306 val=0.155227 alpha=0.019 best=0.155074@10
Gate Electricity H=336 ep=12 OOF=0.211236 val=0.154950 alpha=0.023 best=0.154950@12
Gate Electricity H=336 ep=13 OOF=0.211107 val=0.155045 alpha=0.022 best=0.154950@12
Gate Electricity H=336 ep=14 OOF=0.211021 val=0.154889 alpha=0.026 best=0.154889@14
Gate Electricity H=336 ep=15 OOF=0.211032 val=0.155021 alpha=0.024 best=0.154889@14
Gate Electricity H=336 ep=16 OOF=0.211040 val=0.154964 alpha=0.022 best=0.154889@14
Gate Electricity H=336 ep=17 OOF=0.210847 val=0.154941 alpha=0.024 best=0.154889@14
Gate Electricity H=336 ep=18 OOF=0.210917 val=0.154642 alpha=0.029 best=0.154642@18
Gate Electricity H=336 ep=19 OOF=0.210795 val=0.154823 alpha=0.025 best=0.154642@18
Gate Electricity H=336 ep=20 OOF=0.210821 val=0.154731 alpha=0.026 best=0.154642@18
Gate Electricity H=336 ep=21 OOF=0.210874 val=0.154631 alpha=0.028 best=0.154631@21
Gate Electricity H=336 ep=22 OOF=0.210815 val=0.154797 alpha=0.025 best=0.154631@21
Gate Electricity H=336 ep=23 OOF=0.210721 val=0.154535 alpha=0.031 best=0.154535@23
Gate Electricity H=336 ep=24 OOF=0.210701 val=0.154597 alpha=0.026 best=0.154535@23
Gate Electricity H=336 ep=25 OOF=0.210637 val=0.154582 alpha=0.029 best=0.154535@23
Gate Electricity H=336 ep=26 OOF=0.210623 val=0.154600 alpha=0.029 best=0.154535@23
Gate Electricity H=336 ep=27 OOF=0.210477 val=0.154567 alpha=0.029 best=0.154535@23
Gate Electricity H=336 ep=28 OOF=0.210551 val=0.154542 alpha=0.026 best=0.154535@23
Gate Electricity H=336 ep=29 OOF=0.210558 val=0.154513 alpha=0.024 best=0.154513@29
Gate Electricity H=336 ep=30 OOF=0.210500 val=0.154487 alpha=0.026 best=0.154487@30
Gate Electricity H=336 ep=31 OOF=0.210361 val=0.154444 alpha=0.028 best=0.154444@31
Gate Electricity H=336 ep=32 OOF=0.210380 val=0.154508 alpha=0.025 best=0.154444@31
Gate Electricity H=336 ep=33 OOF=0.210446 val=0.154448 alpha=0.028 best=0.154444@31
Gate Electricity H=336 ep=34 OOF=0.210345 val=0.154463 alpha=0.029 best=0.154444@31
Gate Electricity H=336 ep=35 OOF=0.210459 val=0.154512 alpha=0.029 best=0.154444@31
Gate Electricity H=336 ep=36 OOF=0.210359 val=0.154266 alpha=0.031 best=0.154266@36
Gate Electricity H=336 ep=37 OOF=0.210449 val=0.154363 alpha=0.029 best=0.154266@36
Gate Electricity H=336 ep=38 OOF=0.210236 val=0.154414 alpha=0.028 best=0.154266@36
Gate Electricity H=336 ep=39 OOF=0.210233 val=0.154242 alpha=0.031 best=0.154242@39
Gate Electricity H=336 ep=40 OOF=0.210313 val=0.154248 alpha=0.027 best=0.154242@39
Gate Electricity H=336 ep=41 OOF=0.210416 val=0.154294 alpha=0.032 best=0.154242@39
Gate Electricity H=336 ep=42 OOF=0.210237 val=0.154370 alpha=0.027 best=0.154242@39
Gate Electricity H=336 ep=43 OOF=0.210349 val=0.154273 alpha=0.027 best=0.154242@39
Gate Electricity H=336 ep=44 OOF=0.210191 val=0.154293 alpha=0.029 best=0.154242@39
Gate Electricity H=336 ep=45 OOF=0.210377 val=0.154167 alpha=0.034 best=0.154167@45
Gate Electricity H=336 ep=46 OOF=0.210212 val=0.154349 alpha=0.031 best=0.154167@45
Gate Electricity H=336 ep=47 OOF=0.210247 val=0.154268 alpha=0.030 best=0.154167@45
Gate Electricity H=336 ep=48 OOF=0.210157 val=0.154056 alpha=0.033 best=0.154056@48
Gate Electricity H=336 ep=49 OOF=0.210231 val=0.154277 alpha=0.028 best=0.154056@48
Gate Electricity H=336 ep=50 OOF=0.210045 val=0.154204 alpha=0.030 best=0.154056@48
Validation calibration | alpha0=0.00 | lambda=1.00 | gateEpoch=48
Building memory embedding: Electricity_H336_test_trainval_memory_emb.npy (321, 859, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
  test anchors 16/4925
  test anchors 512/4925
  test anchors 1008/4925
  test anchors 1504/4925
  test anchors 2000/4925
  test anchors 2512/4925
  test anchors 3008/4925
  test anchors 3504/4925
  test anchors 4000/4925
  test anchors 4512/4925
  test anchors 4925/4925

FINAL CONDITION RESULT

       Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0  Electricity      336          0.179687            0.178503                0.659223          0.272384            0.273237       1.936648    0.179687         0.178503    0.166097          0.0           1.0         0.036784                 0.809969                      7.563408       10.112683

######################################################################################################################################################
Electricity | H=720 | iTransformer + FROZEN HISTORICAL MEMORY
######################################################################################################################################################
Experiment 21 direct: MSE=0.217054, MAE=0.304202, best_epoch=3
Updating learning rate to 0.0005
Fold direct Electricity H=720 F1 ep=01/3 train=0.292047 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H=720 F1 ep=02/3 train=0.256062 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H=720 F1 ep=03/3 train=0.239109 lr=1.250e-04
Building memory embedding: Electricity_H720_F1_prefix10126_emb.npy (321, 388, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=720 F1: prefix=10126, end=12888, anchors=511, pairs=164031, memory/C=388
Updating learning rate to 0.0005
Fold direct Electricity H=720 F2 ep=01/3 train=0.275832 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H=720 F2 ep=02/3 train=0.242471 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H=720 F2 ep=03/3 train=0.227342 lr=1.250e-04
Building memory embedding: Electricity_H720_F2_prefix12888_emb.npy (321, 504, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=720 F2: prefix=12888, end=15650, anchors=511, pairs=164031, memory/C=504
Updating learning rate to 0.0005
Fold direct Electricity H=720 F3 ep=01/3 train=0.281898 lr=5.000e-04
Updating learning rate to 0.00025
Fold direct Electricity H=720 F3 ep=02/3 train=0.249306 lr=2.500e-04
Updating learning rate to 0.000125
Fold direct Electricity H=720 F3 ep=03/3 train=0.233779 lr=1.250e-04
Building memory embedding: Electricity_H720_F3_prefix15650_emb.npy (321, 619, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
OOF Electricity H=720 F3: prefix=15650, end=18412, anchors=511, pairs=164031, memory/C=619
Total OOF pairs: 492093
Building memory embedding: Electricity_H720_validation_train_memory_emb.npy (321, 734, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
Validation Electricity H=720: anchors=1913, pairs=614073, memory/C=734
Gate Electricity H=720 ep=01 OOF=0.285719 val=0.202032 alpha=0.034 best=0.202032@1
Gate Electricity H=720 ep=02 OOF=0.276077 val=0.202415 alpha=0.028 best=0.202032@1
Gate Electricity H=720 ep=03 OOF=0.274805 val=0.202168 alpha=0.032 best=0.202032@1
Gate Electricity H=720 ep=04 OOF=0.274049 val=0.202138 alpha=0.030 best=0.202032@1
Gate Electricity H=720 ep=05 OOF=0.272715 val=0.201957 alpha=0.040 best=0.201957@5
Gate Electricity H=720 ep=06 OOF=0.272623 val=0.201768 alpha=0.037 best=0.201768@6
Gate Electricity H=720 ep=07 OOF=0.272360 val=0.201443 alpha=0.040 best=0.201443@7
Gate Electricity H=720 ep=08 OOF=0.271996 val=0.201468 alpha=0.040 best=0.201443@7
Gate Electricity H=720 ep=09 OOF=0.271540 val=0.201037 alpha=0.045 best=0.201037@9
Gate Electricity H=720 ep=10 OOF=0.271592 val=0.200821 alpha=0.044 best=0.200821@10
Gate Electricity H=720 ep=11 OOF=0.271340 val=0.200547 alpha=0.046 best=0.200547@11
Gate Electricity H=720 ep=12 OOF=0.271443 val=0.200633 alpha=0.045 best=0.200547@11
Gate Electricity H=720 ep=13 OOF=0.271580 val=0.200082 alpha=0.050 best=0.200082@13
Gate Electricity H=720 ep=14 OOF=0.270954 val=0.200286 alpha=0.041 best=0.200082@13
Gate Electricity H=720 ep=15 OOF=0.270838 val=0.200148 alpha=0.045 best=0.200082@13
Gate Electricity H=720 ep=16 OOF=0.270883 val=0.199979 alpha=0.045 best=0.199979@16
Gate Electricity H=720 ep=17 OOF=0.271524 val=0.199766 alpha=0.042 best=0.199766@17
Gate Electricity H=720 ep=18 OOF=0.270582 val=0.199792 alpha=0.046 best=0.199766@17
Gate Electricity H=720 ep=19 OOF=0.269945 val=0.199579 alpha=0.042 best=0.199579@19
Gate Electricity H=720 ep=20 OOF=0.271255 val=0.199654 alpha=0.050 best=0.199579@19
Gate Electricity H=720 ep=21 OOF=0.270590 val=0.199697 alpha=0.043 best=0.199579@19
Gate Electricity H=720 ep=22 OOF=0.270100 val=0.199326 alpha=0.049 best=0.199326@22
Gate Electricity H=720 ep=23 OOF=0.269746 val=0.199579 alpha=0.042 best=0.199326@22
Gate Electricity H=720 ep=24 OOF=0.270163 val=0.199382 alpha=0.045 best=0.199326@22
Gate Electricity H=720 ep=25 OOF=0.270186 val=0.199677 alpha=0.041 best=0.199326@22
Gate Electricity H=720 ep=26 OOF=0.270344 val=0.199495 alpha=0.043 best=0.199326@22
Gate Electricity H=720 ep=27 OOF=0.269814 val=0.199356 alpha=0.043 best=0.199326@22
Gate Electricity H=720 ep=28 OOF=0.269750 val=0.199461 alpha=0.046 best=0.199326@22
Gate Electricity H=720 ep=29 OOF=0.270003 val=0.199332 alpha=0.045 best=0.199326@22
Validation calibration | alpha0=0.00 | lambda=1.00 | gateEpoch=22
Building memory embedding: Electricity_H720_test_trainval_memory_emb.npy (321, 843, 64)
  channel 1/321
  channel 50/321
  channel 100/321
  channel 150/321
  channel 200/321
  channel 250/321
  channel 300/321
  channel 321/321
  test anchors 16/4541
  test anchors 512/4541
  test anchors 1008/4541
  test anchors 1504/4541
  test anchors 2000/4541
  test anchors 2512/4541
  test anchors 3008/4541
  test anchors 3504/4541
  test anchors 4000/4541
  test anchors 4512/4541
  test anchors 4541/4541

FINAL CONDITION RESULT

       Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  Retrieval_MSE  Scalar_MSE  RawAdaptive_MSE  Oracle_MSE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  OracleHeadroomFromDirect_pct  RuntimeMinutes
0  Electricity      720          0.217054            0.215217                0.845958          0.304202            0.305317       1.898134    0.217054         0.215217     0.19811          0.0           1.0         0.045871                 0.741433                      8.727727        4.591641

,Dataset,Horizon,Channels,iTransformer_MSE,iTransformer_MAE,Experiment21Reference_MSE,Experiment21Reference_MAE,DirectParityAbsDiff,Retrieval_MSE,Retrieval_MAE,ScalarAlpha,Scalar_MSE,Scalar_MAE,RawAdaptive_MSE,RawAdaptive_MAE,ShrinkLambda,ShrinkAdaptive_MSE,ShrinkAdaptive_MAE,Oracle_MSE,Oracle_MAE,RawMeanAlpha,ShrinkMeanAlpha,OracleMeanAlpha,OraclePositiveFraction,ImprovedChannelFraction,ScalarGainVsDirect_pct,ShrinkGainVsDirect_pct,ShrinkGainVsScalar_pct,OracleHeadroomFromDirect_pct,OracleHeadroomFromShrink_pct,DirectBestEpoch,FrozenRetrieverBestEpoch,GateBestEpoch,TestMemoryPerChannel,TestWindows,RuntimeMinutes
0,ETTh1,96,7,0.392303,0.407334,0.392304,0.407334,1.073240e-07,1.799798,0.845403,0.1,0.403233,0.418905,0.394281,0.410792,1.00,0.394281,0.410792,0.362519,0.392469,0.079177,0.079177,0.161444,0.558348,0.571429,-2.786079,-0.504197,2.220029,7.592273,8.055853,1,2,30,473,2785,0.113245
1,ETTh1,192,7,0.442639,0.434737,0.442639,0.434737,3.424557e-08,1.791403,0.866270,0.1,0.453672,0.446403,0.449096,0.442669,1.00,0.449096,0.442669,0.413171,0.420761,0.089948,0.089948,0.154008,0.539659,0.428571,-2.492544,-1.458748,1.008655,6.657512,7.999566,1,5,19,469,2689,0.109456
2,ETTh1,336,7,0.489263,0.461457,0.489263,0.461457,3.946080e-09,1.850616,0.889907,0.1,0.498583,0.473796,0.498000,0.473326,1.00,0.498000,0.473326,0.454354,0.448419,0.098503,0.098503,0.152534,0.534718,0.571429,-1.904970,-1.785874,0.116870,7.135021,8.764374,1,3,6,463,2545,0.109588
3,ETTh1,720,7,0.506507,0.492894,0.506507,0.492894,1.634114e-08,1.920954,0.922036,0.2,0.560588,0.528789,0.519138,0.505294,0.50,0.536269,0.515912,0.471712,0.476156,0.099917,0.149958,0.143740,0.558009,0.571429,-10.677292,-5.876001,4.338099,6.869664,12.038295,1,3,1,447,2161,0.109269
4,ETTm1,96,7,0.336712,0.373422,0.336712,0.373422,9.791633e-09,1.273082,0.700499,0.0,0.336712,0.373422,0.337788,0.374302,0.75,0.337092,0.373635,0.280151,0.339608,0.095895,0.071921,0.211982,0.510772,0.428571,0.000000,-0.112813,-0.112813,16.797973,16.891730,1,2,16,1913,11425,0.390909
5,ETTm1,192,7,0.394380,0.402333,0.394380,0.402333,4.346991e-08,1.325520,0.731763,0.1,0.392679,0.402721,0.390620,0.400364,1.00,0.390620,0.400364,0.328181,0.368165,0.084481,0.084481,0.209284,0.565199,1.000000,0.431246,0.953379,0.524394,16.785594,15.984609,3,1,9,1909,11329,0.897363
6,ETTm1,336,7,0.424327,0.422129,0.424327,0.422129,3.578755e-08,1.364253,0.761082,0.1,0.424660,0.424178,0.425539,0.422317,0.75,0.423381,0.421551,0.368539,0.393009,0.114420,0.110815,0.180624,0.544505,0.714286,-0.078535,0.222913,0.301212,13.147345,12.953306,2,5,46,1903,11185,0.676535
7,ETTm1,720,7,0.496095,0.461646,0.496095,0.461646,1.632701e-08,1.424698,0.797972,0.1,0.489097,0.460496,0.489012,0.459917,0.75,0.488999,0.460045,0.427392,0.428242,0.094551,0.095913,0.185172,0.553031,1.000000,1.410598,1.430322,0.020006,13.848778,12.598657,3,5,5,1887,10801,0.994463
8,Electricity,96,321,0.148275,0.239707,0.148275,0.239707,4.570984e-09,1.839673,1.024234,0.0,0.148275,0.239707,0.146310,0.239500,1.00,0.146310,0.239500,0.134724,0.232317,0.031767,0.031767,0.065458,0.481328,0.813084,0.000000,1.325576,1.325576,9.139225,7.918617,7,7,46,869,5165,7.553352
9,Electricity,192,321,0.165101,0.256106,0.165100,0.256106,1.342250e-08,1.996508,1.058647,0.0,0.165101,0.256106,0.164833,0.257408,1.00,0.164833,0.257408,0.153132,0.249967,0.043048,0.043048,0.063306,0.466086,0.666667,0.000000,0.161767,0.161767,7.249021,7.098738,7,16,21,865,5069,7.628455
10,Electricity,336,321,0.179687,0.272384,0.179687,0.272384,2.129098e-08,1.936648,1.049990,0.0,0.179687,0.272384,0.178503,0.273237,1.00,0.178503,0.273237,0.166097,0.265394,0.036784,0.036784,0.066769,0.473814,0.809969,0.000000,0.659223,0.659223,7.563408,6.950000,9,7,48,859,4925,10.112683
11,Electricity,720,321,0.217054,0.304202,0.217054,0.304202,5.903019e-09,1.898134,1.047431,0.0,0.217054,0.304202,0.215217,0.305317,1.00,0.215217,0.305317,0.198110,0.295487,0.045871,0.045871,0.075287,0.482540,0.741433,0.000000,0.845958,0.845958,8.727727,7.949014,3,10,22,843,4541,4.591641
12,Weather,96,21,0.173287,0.212210,0.173287,0.212210,2.282774e-08,0.239999,0.259326,0.2,0.167517,0.210169,0.166006,0.209350,1.00,0.166006,0.209350,0.134499,0.176366,0.213570,0.213570,0.410113,0.606951,0.619048,3.329838,4.201641,0.901832,22.383703,18.979513,6,8,50,1749,10444,2.378653
13,Weather,192,21,0.224436,0.257719,0.224436,0.257719,8.586447e-09,0.300280,0.309905,0.2,0.216241,0.254748,0.214400,0.253501,1.00,0.214400,0.253501,0.175964,0.219176,0.207794,0.207794,0.357143,0.591023,0.904762,3.651385,4.471502,0.851198,21.597297,17.927420,5,5,50,1745,10348,2.070459
14,Weather,336,21,0.282732,0.299481,0.282732,0.299481,7.570963e-09,0.357731,0.356853,0.2,0.270843,0.295811,0.270471,0.296607,1.00,0.270471,0.296607,0.222023,0.257863,0.265729,0.265729,0.350568,0.609588,0.714286,4.205050,4.336659,0.137387,21.472557,17.912711,3,7,46,1739,10204,1.382880
15,Weather,720,21,0.357908,0.349720,0.357908,0.349720,1.415235e-08,0.438722,0.411107,0.2,0.341699,0.343678,0.345558,0.345255,0.75,0.344274,0.344686,0.283096,0.303774,0.189078,0.191808,0.350790,0.633081,0.857143,4.528630,3.809215,-0.753539,20.902616,17.770310,4,7,7,1723,9820,1.889911

## 20. Compact evidence table

In [21]:

if not len(
    summary_df
):
    raise RuntimeError(
        "No completed Experiment 22 result."
    )

compact = summary_df[
    [
        "Dataset",
        "Horizon",
        "iTransformer_MSE",
        "ShrinkAdaptive_MSE",
        "ShrinkGainVsDirect_pct",
        "iTransformer_MAE",
        "ShrinkAdaptive_MAE",
        "ScalarAlpha",
        "ShrinkLambda",
        "ShrinkMeanAlpha",
        "ImprovedChannelFraction",
        "Oracle_MSE",
        "OracleHeadroomFromDirect_pct",
        "DirectParityAbsDiff",
    ]
].copy()

compact[
    "Winner"
] = np.where(
    compact[
        "ShrinkAdaptive_MSE"
    ]
    < compact[
        "iTransformer_MSE"
    ],
    "Ours",
    "Direct",
)

display(
    compact
)

compact.to_csv(
    ROOT
    / "compact_results.csv",
    index=False,
)

if BOOTSTRAP_PATH.exists():
    boot_df = pd.read_csv(
        BOOTSTRAP_PATH
    )

    direct_boot = boot_df[
        boot_df[
            "Comparison"
        ]
        == "Direct-ShrinkAdaptive"
    ].copy()

    direct_boot[
        "Significance"
    ] = np.select(
        [
            direct_boot[
                "CI_Low"
            ]
            > 0.0,
            direct_boot[
                "CI_High"
            ]
            < 0.0,
        ],
        [
            "Ours significantly better",
            "Direct significantly better",
        ],
        default=
            "Not significant",
    )

    display(
        direct_boot.sort_values(
            [
                "Dataset",
                "Horizon",
            ]
        )
    )

        Dataset  Horizon  iTransformer_MSE  ShrinkAdaptive_MSE  ShrinkGainVsDirect_pct  iTransformer_MAE  ShrinkAdaptive_MAE  ScalarAlpha  ShrinkLambda  ShrinkMeanAlpha  ImprovedChannelFraction  Oracle_MSE  OracleHeadroomFromDirect_pct  DirectParityAbsDiff  Winner
0         ETTh1       96          0.392303            0.394281               -0.504197          0.407334            0.410792          0.1          1.00         0.079177                 0.571429    0.362519                      7.592273         1.073240e-07  Direct
1         ETTh1      192          0.442639            0.449096               -1.458748          0.434737            0.442669          0.1          1.00         0.089948                 0.428571    0.413171                      6.657512         3.424557e-08  Direct
2         ETTh1      336          0.489263            0.498000               -1.785874          0.461457            0.473326          0.1          1.00         0.098503                 0.571429    0.454354                      7.135021         3.946080e-09  Direct
3         ETTh1      720          0.506507            0.536269               -5.876001          0.492894            0.515912          0.2          0.50         0.149958                 0.571429    0.471712                      6.869664         1.634114e-08  Direct
4         ETTm1       96          0.336712            0.337092               -0.112813          0.373422            0.373635          0.0          0.75         0.071921                 0.428571    0.280151                     16.797973         9.791633e-09  Direct
5         ETTm1      192          0.394380            0.390620                0.953379          0.402333            0.400364          0.1          1.00         0.084481                 1.000000    0.328181                     16.785594         4.346991e-08    Ours
6         ETTm1      336          0.424327            0.423381                0.222913          0.422129            0.421551          0.1          0.75         0.110815                 0.714286    0.368539                     13.147345         3.578755e-08    Ours
7         ETTm1      720          0.496095            0.488999                1.430322          0.461646            0.460045          0.1          0.75         0.095913                 1.000000    0.427392                     13.848778         1.632701e-08    Ours
8   Electricity       96          0.148275            0.146310                1.325576          0.239707            0.239500          0.0          1.00         0.031767                 0.813084    0.134724                      9.139225         4.570984e-09    Ours
9   Electricity      192          0.165101            0.164833                0.161767          0.256106            0.257408          0.0          1.00         0.043048                 0.666667    0.153132                      7.249021         1.342250e-08    Ours
10  Electricity      336          0.179687            0.178503                0.659223          0.272384            0.273237          0.0          1.00         0.036784                 0.809969    0.166097                      7.563408         2.129098e-08    Ours
11  Electricity      720          0.217054            0.215217                0.845958          0.304202            0.305317          0.0          1.00         0.045871                 0.741433    0.198110                      8.727727         5.903019e-09    Ours
12      Weather       96          0.173287            0.166006                4.201641          0.212210            0.209350          0.2          1.00         0.213570                 0.619048    0.134499                     22.383703         2.282774e-08    Ours
13      Weather      192          0.224436            0.214400                4.471502          0.257719            0.253501          0.2          1.00         0.207794                 0.904762    0.175964                     21.597297         8.586447e-09    Ours
14      Weather      336          0.282732            0.270471                4.336659          0.299481            0.296607          0.2          1.00         0.265729                 0.714286    0.222023                     21.472557         7.570963e-09    Ours
15      Weather      720          0.357908            0.344274                3.809215          0.349720            0.344686          0.2          0.75         0.191808                 0.857143    0.283096                     20.902616         1.415235e-08    Ours

        Dataset  Horizon             Comparison  MeanImprovement    CI_Low   CI_High  SignificantPositive                 Significance
8         ETTh1       96  Direct-ShrinkAdaptive        -0.001978 -0.004286  0.000448                False              Not significant
10        ETTh1      192  Direct-ShrinkAdaptive        -0.006457 -0.009515 -0.002894                False  Direct significantly better
12        ETTh1      336  Direct-ShrinkAdaptive        -0.008738 -0.012672 -0.004596                False  Direct significantly better
14        ETTh1      720  Direct-ShrinkAdaptive        -0.029762 -0.035795 -0.023611                False  Direct significantly better
0         ETTm1       96  Direct-ShrinkAdaptive        -0.000380 -0.001116  0.000391                False              Not significant
2         ETTm1      192  Direct-ShrinkAdaptive         0.003760  0.001944  0.005723                 True    Ours significantly better
4         ETTm1      336  Direct-ShrinkAdaptive         0.000946 -0.000936  0.002938                False              Not significant
6         ETTm1      720  Direct-ShrinkAdaptive         0.007096  0.003982  0.010414                 True    Ours significantly better
24  Electricity       96  Direct-ShrinkAdaptive         0.001966  0.001538  0.002453                 True    Ours significantly better
26  Electricity      192  Direct-ShrinkAdaptive         0.000267 -0.000084  0.000646                False              Not significant
28  Electricity      336  Direct-ShrinkAdaptive         0.001185  0.000672  0.001719                 True    Ours significantly better
30  Electricity      720  Direct-ShrinkAdaptive         0.001836  0.000820  0.002869                 True    Ours significantly better
16      Weather       96  Direct-ShrinkAdaptive         0.007281  0.005587  0.009051                 True    Ours significantly better
18      Weather      192  Direct-ShrinkAdaptive         0.010036  0.008367  0.012079                 True    Ours significantly better
20      Weather      336  Direct-ShrinkAdaptive         0.012261  0.010366  0.014490                 True    Ours significantly better
22      Weather      720  Direct-ShrinkAdaptive         0.013633  0.011818  0.015599                 True    Ours significantly better


# 21. Decision criteria

## 가장 강한 성공 시나리오

PatchTST에서 positive였던 Weather/Electricity뿐 아니라
iTransformer에서도 같은 regime이 반복됩니다.

예를 들어

$$
\mathrm{Weather/Electricity}
:
8/8\ \mathrm{wins}
$$

에 가까운 결과가 나오면

> historical memory complements strong forecasters across different backbone architectures

라는 주장이 매우 강해집니다.

---

## 부분 성공

Weather에서는 반복되지만 Electricity 또는 ETT에서는 혼합된 결과가 나올 수 있습니다.

이 경우에도 동일한 frozen memory module이
서로 다른 backbone에서 Weather를 반복적으로 개선한다면
PatchTST-specific artifact라는 설명은 약해집니다.

---

## 실패

iTransformer에서는 전반적으로 개선되지 않는다면
현재 method를 `model-agnostic augmentation`이라고 부르기 어렵습니다.

이 경우:

- PatchTST-specific interaction
- backbone calibration difference
- direct-error geometry difference
- opportunity identification failure

를 분석합니다.

그러나 Experiment 22 test 결과를 본 뒤
iTransformer용 gate/retriever를 별도로 test-tuning하지 않습니다.

---

## Oracle의 역할

Oracle headroom이 작으면
retrieval forecast 자체에 complementary signal이 거의 없는 것입니다.

Oracle headroom이 크지만 Ours가 개선하지 못하면

$$
\boxed{
\text{signal exists, but trust/opportunity identification fails}
}
$$

로 해석합니다.

---

# 이후 단계

Experiment 22가 성공하면 다음 우선순위는:

1. PatchTST + iTransformer 통합 backbone table
2. multi-seed confirmation
3. 필요 시 한 개의 newer strong backbone 추가

입니다.

## 22. Runtime summary

In [22]:

if len(
    summary_df
):
    runtime = (
        summary_df
        .groupby(
            "Dataset",
            as_index=False,
        )
        .agg(
            Conditions=(
                "Horizon",
                "size",
            ),
            TotalRuntimeMinutes=(
                "RuntimeMinutes",
                "sum",
            ),
            MeanRuntimeMinutes=(
                "RuntimeMinutes",
                "mean",
            ),
        )
    )

    runtime[
        "TotalRuntimeHours"
    ] = (
        runtime[
            "TotalRuntimeMinutes"
        ]
        / 60.0
    )

    display(
        runtime
    )

    print(
        "Recorded total runtime (hours):",
        summary_df[
            "RuntimeMinutes"
        ].sum()
        / 60.0,
    )

       Dataset  Conditions  TotalRuntimeMinutes  MeanRuntimeMinutes  TotalRuntimeHours
0        ETTh1           4             0.441558            0.110389           0.007359
1        ETTm1           4             2.959270            0.739818           0.049321
2  Electricity           4            29.886133            7.471533           0.498102
3      Weather           4             7.721903            1.930476           0.128698

Recorded total runtime (hours): 0.6834810678164164

## 23. Saved artifacts

In [23]:

print(
    "Experiment root:",
    ROOT,
)

for p in sorted(
    ROOT.rglob(
        "*"
    )
):
    if p.is_file():
        print(
            p.relative_to(
                ROOT
            )
        )

Experiment root: /data/dataset/strong_forecaster/itransformer_plus_frozen_historical_memory
artifacts/direct_parity.csv
artifacts/official_repo_commit.txt
bootstrap.csv
calibration/ETTh1_H192_scalar_alpha.csv
calibration/ETTh1_H192_shrink_lambda.csv
calibration/ETTh1_H336_scalar_alpha.csv
calibration/ETTh1_H336_shrink_lambda.csv
calibration/ETTh1_H720_scalar_alpha.csv
calibration/ETTh1_H720_shrink_lambda.csv
calibration/ETTh1_H96_scalar_alpha.csv
calibration/ETTh1_H96_shrink_lambda.csv
calibration/ETTm1_H192_scalar_alpha.csv
calibration/ETTm1_H192_shrink_lambda.csv
calibration/ETTm1_H336_scalar_alpha.csv
calibration/ETTm1_H336_shrink_lambda.csv
calibration/ETTm1_H720_scalar_alpha.csv
calibration/ETTm1_H720_shrink_lambda.csv
calibration/ETTm1_H96_scalar_alpha.csv
calibration/ETTm1_H96_shrink_lambda.csv
calibration/Electricity_H192_scalar_alpha.csv
calibration/Electricity_H192_shrink_lambda.csv
calibration/Electricity_H336_scalar_alpha.csv
calibration/Electricity_H336_shrink_lambda.csv
calibration/Electricity_H720_scalar_alpha.csv
calibration/Electricity_H720_shrink_lambda.csv
calibration/Electricity_H96_scalar_alpha.csv
calibration/Electricity_H96_shrink_lambda.csv
calibration/Weather_H192_scalar_alpha.csv
calibration/Weather_H192_shrink_lambda.csv
calibration/Weather_H336_scalar_alpha.csv
calibration/Weather_H336_shrink_lambda.csv
calibration/Weather_H720_scalar_alpha.csv
calibration/Weather_H720_shrink_lambda.csv
calibration/Weather_H96_scalar_alpha.csv
calibration/Weather_H96_shrink_lambda.csv
channel_test/ETTh1_H192_channel_mse.csv
channel_test/ETTh1_H336_channel_mse.csv
channel_test/ETTh1_H720_channel_mse.csv
channel_test/ETTh1_H96_channel_mse.csv
channel_test/ETTm1_H192_channel_mse.csv
channel_test/ETTm1_H336_channel_mse.csv
channel_test/ETTm1_H720_channel_mse.csv
channel_test/ETTm1_H96_channel_mse.csv
channel_test/Electricity_H192_channel_mse.csv
channel_test/Electricity_H336_channel_mse.csv
channel_test/Electricity_H720_channel_mse.csv
channel_test/Electricity_H96_channel_mse.csv
channel_test/Weather_H192_channel_mse.csv
channel_test/Weather_H336_channel_mse.csv
channel_test/Weather_H720_channel_mse.csv
channel_test/Weather_H96_channel_mse.csv
compact_results.csv
fold_direct/ETTh1_H192_F1_itransformer.pt
fold_direct/ETTh1_H192_F2_itransformer.pt
fold_direct/ETTh1_H192_F3_itransformer.pt
fold_direct/ETTh1_H336_F1_itransformer.pt
fold_direct/ETTh1_H336_F2_itransformer.pt
fold_direct/ETTh1_H336_F3_itransformer.pt
fold_direct/ETTh1_H720_F1_itransformer.pt
fold_direct/ETTh1_H720_F2_itransformer.pt
fold_direct/ETTh1_H720_F3_itransformer.pt
fold_direct/ETTh1_H96_F1_itransformer.pt
fold_direct/ETTh1_H96_F2_itransformer.pt
fold_direct/ETTh1_H96_F3_itransformer.pt
fold_direct/ETTm1_H192_F1_itransformer.pt
fold_direct/ETTm1_H192_F2_itransformer.pt
fold_direct/ETTm1_H192_F3_itransformer.pt
fold_direct/ETTm1_H336_F1_itransformer.pt
fold_direct/ETTm1_H336_F2_itransformer.pt
fold_direct/ETTm1_H336_F3_itransformer.pt
fold_direct/ETTm1_H720_F1_itransformer.pt
fold_direct/ETTm1_H720_F2_itransformer.pt
fold_direct/ETTm1_H720_F3_itransformer.pt
fold_direct/ETTm1_H96_F1_itransformer.pt
fold_direct/ETTm1_H96_F2_itransformer.pt
fold_direct/ETTm1_H96_F3_itransformer.pt
fold_direct/Electricity_H192_F1_itransformer.pt
fold_direct/Electricity_H192_F2_itransformer.pt
fold_direct/Electricity_H192_F3_itransformer.pt
fold_direct/Electricity_H336_F1_itransformer.pt
fold_direct/Electricity_H336_F2_itransformer.pt
fold_direct/Electricity_H336_F3_itransformer.pt
fold_direct/Electricity_H720_F1_itransformer.pt
fold_direct/Electricity_H720_F2_itransformer.pt
fold_direct/Electricity_H720_F3_itransformer.pt
fold_direct/Electricity_H96_F1_itransformer.pt
fold_direct/Electricity_H96_F2_itransformer.pt
fold_direct/Electricity_H96_F3_itransformer.pt
fold_direct/Weather_H192_F1_itransformer.pt
fold_direct/Weather_H192_F2_itransformer.pt
fold_direct/Weather_H192_F3_itransformer.pt
fold_direct/Weather_H336_F1_itransformer.pt
fold_direct/Weather_H336_F2_itransformer.pt
fold_direct/Weather_H336_F3_itransformer.pt
fold_direct/Weather_H720_F1_itransformer.pt
fold_direct/Weather_H720_F2_itransformer.pt
fold_direct/Weather_H720_F3_itransformer.pt
fold_direct/Weather_H96_F1_itransformer.pt
fold_direct/Weather_H96_F2_itransformer.pt
fold_direct/Weather_H96_F3_itransformer.pt
folds.csv
gate/ETTh1_H192_gate.pt
gate/ETTh1_H336_gate.pt
gate/ETTh1_H720_gate.pt
gate/ETTh1_H96_gate.pt
gate/ETTm1_H192_gate.pt
gate/ETTm1_H336_gate.pt
gate/ETTm1_H720_gate.pt
gate/ETTm1_H96_gate.pt
gate/Electricity_H192_gate.pt
gate/Electricity_H336_gate.pt
gate/Electricity_H720_gate.pt
gate/Electricity_H96_gate.pt
gate/Weather_H192_gate.pt
gate/Weather_H336_gate.pt
gate/Weather_H720_gate.pt
gate/Weather_H96_gate.pt
history/ETTh1_H192_F1_direct_history.csv
history/ETTh1_H192_F2_direct_history.csv
history/ETTh1_H192_F3_direct_history.csv
history/ETTh1_H192_gate_history.csv
history/ETTh1_H336_F1_direct_history.csv
history/ETTh1_H336_F2_direct_history.csv
history/ETTh1_H336_F3_direct_history.csv
history/ETTh1_H336_gate_history.csv
history/ETTh1_H720_F1_direct_history.csv
history/ETTh1_H720_F2_direct_history.csv
history/ETTh1_H720_F3_direct_history.csv
history/ETTh1_H720_gate_history.csv
history/ETTh1_H96_F1_direct_history.csv
history/ETTh1_H96_F2_direct_history.csv
history/ETTh1_H96_F3_direct_history.csv
history/ETTh1_H96_gate_history.csv
history/ETTm1_H192_F1_direct_history.csv
history/ETTm1_H192_F2_direct_history.csv
history/ETTm1_H192_F3_direct_history.csv
history/ETTm1_H192_gate_history.csv
history/ETTm1_H336_F1_direct_history.csv
history/ETTm1_H336_F2_direct_history.csv
history/ETTm1_H336_F3_direct_history.csv
history/ETTm1_H336_gate_history.csv
history/ETTm1_H720_F1_direct_history.csv
history/ETTm1_H720_F2_direct_history.csv
history/ETTm1_H720_F3_direct_history.csv
history/ETTm1_H720_gate_history.csv
history/ETTm1_H96_F1_direct_history.csv
history/ETTm1_H96_F2_direct_history.csv
history/ETTm1_H96_F3_direct_history.csv
history/ETTm1_H96_gate_history.csv
history/Electricity_H192_F1_direct_history.csv
history/Electricity_H192_F2_direct_history.csv
history/Electricity_H192_F3_direct_history.csv
history/Electricity_H192_gate_history.csv
history/Electricity_H336_F1_direct_history.csv
history/Electricity_H336_F2_direct_history.csv
history/Electricity_H336_F3_direct_history.csv
history/Electricity_H336_gate_history.csv
history/Electricity_H720_F1_direct_history.csv
history/Electricity_H720_F2_direct_history.csv
history/Electricity_H720_F3_direct_history.csv
history/Electricity_H720_gate_history.csv
history/Electricity_H96_F1_direct_history.csv
history/Electricity_H96_F2_direct_history.csv
history/Electricity_H96_F3_direct_history.csv
history/Electricity_H96_gate_history.csv
history/Weather_H192_F1_direct_history.csv
history/Weather_H192_F2_direct_history.csv
history/Weather_H192_F3_direct_history.csv
history/Weather_H192_gate_history.csv
history/Weather_H336_F1_direct_history.csv
history/Weather_H336_F2_direct_history.csv
history/Weather_H336_F3_direct_history.csv
history/Weather_H336_gate_history.csv
history/Weather_H720_F1_direct_history.csv
history/Weather_H720_F2_direct_history.csv
history/Weather_H720_F3_direct_history.csv
history/Weather_H720_gate_history.csv
history/Weather_H96_F1_direct_history.csv
history/Weather_H96_F2_direct_history.csv
history/Weather_H96_F3_direct_history.csv
history/Weather_H96_gate_history.csv
memory_embeddings/ETTh1_H192_F1_prefix4752_emb.npy
memory_embeddings/ETTh1_H192_F2_prefix6048_emb.npy
memory_embeddings/ETTh1_H192_F3_prefix7344_emb.npy
memory_embeddings/ETTh1_H192_test_trainval_memory_emb.npy
memory_embeddings/ETTh1_H192_validation_train_memory_emb.npy
memory_embeddings/ETTh1_H336_F1_prefix4752_emb.npy
memory_embeddings/ETTh1_H336_F2_prefix6048_emb.npy
memory_embeddings/ETTh1_H336_F3_prefix7344_emb.npy
memory_embeddings/ETTh1_H336_test_trainval_memory_emb.npy
memory_embeddings/ETTh1_H336_validation_train_memory_emb.npy
memory_embeddings/ETTh1_H720_F1_prefix4752_emb.npy
memory_embeddings/ETTh1_H720_F2_prefix6048_emb.npy
memory_embeddings/ETTh1_H720_F3_prefix7344_emb.npy
memory_embeddings/ETTh1_H720_test_trainval_memory_emb.npy
memory_embeddings/ETTh1_H720_validation_train_memory_emb.npy
memory_embeddings/ETTh1_H96_F1_prefix4752_emb.npy
memory_embeddings/ETTh1_H96_F2_prefix6048_emb.npy
memory_embeddings/ETTh1_H96_F3_prefix7344_emb.npy
memory_embeddings/ETTh1_H96_test_trainval_memory_emb.npy
memory_embeddings/ETTh1_H96_validation_train_memory_emb.npy
memory_embeddings/ETTm1_H192_F1_prefix19008_emb.npy
memory_embeddings/ETTm1_H192_F2_prefix24192_emb.npy
memory_embeddings/ETTm1_H192_F3_prefix29376_emb.npy
memory_embeddings/ETTm1_H192_test_trainval_memory_emb.npy
memory_embeddings/ETTm1_H192_validation_train_memory_emb.npy
memory_embeddings/ETTm1_H336_F1_prefix19008_emb.npy
memory_embeddings/ETTm1_H336_F2_prefix24192_emb.npy
memory_embeddings/ETTm1_H336_F3_prefix29376_emb.npy
memory_embeddings/ETTm1_H336_test_trainval_memory_emb.npy
memory_embeddings/ETTm1_H336_validation_train_memory_emb.npy
memory_embeddings/ETTm1_H720_F1_prefix19008_emb.npy
memory_embeddings/ETTm1_H720_F2_prefix24192_emb.npy
memory_embeddings/ETTm1_H720_F3_prefix29376_emb.npy
memory_embeddings/ETTm1_H720_test_trainval_memory_emb.npy
memory_embeddings/ETTm1_H720_validation_train_memory_emb.npy
memory_embeddings/ETTm1_H96_F1_prefix19008_emb.npy
memory_embeddings/ETTm1_H96_F2_prefix24192_emb.npy
memory_embeddings/ETTm1_H96_F3_prefix29376_emb.npy
memory_embeddings/ETTm1_H96_test_trainval_memory_emb.npy
memory_embeddings/ETTm1_H96_validation_train_memory_emb.npy
memory_embeddings/Electricity_H192_F1_prefix10126_emb.npy
memory_embeddings/Electricity_H192_F2_prefix12888_emb.npy
memory_embeddings/Electricity_H192_F3_prefix15650_emb.npy
memory_embeddings/Electricity_H192_test_trainval_memory_emb.npy
memory_embeddings/Electricity_H192_validation_train_memory_emb.npy
memory_embeddings/Electricity_H336_F1_prefix10126_emb.npy
memory_embeddings/Electricity_H336_F2_prefix12888_emb.npy
memory_embeddings/Electricity_H336_F3_prefix15650_emb.npy
memory_embeddings/Electricity_H336_test_trainval_memory_emb.npy
memory_embeddings/Electricity_H336_validation_train_memory_emb.npy
memory_embeddings/Electricity_H720_F1_prefix10126_emb.npy
memory_embeddings/Electricity_H720_F2_prefix12888_emb.npy
memory_embeddings/Electricity_H720_F3_prefix15650_emb.npy
memory_embeddings/Electricity_H720_test_trainval_memory_emb.npy
memory_embeddings/Electricity_H720_validation_train_memory_emb.npy
memory_embeddings/Electricity_H96_F1_prefix10126_emb.npy
memory_embeddings/Electricity_H96_F2_prefix12888_emb.npy
memory_embeddings/Electricity_H96_F3_prefix15650_emb.npy
memory_embeddings/Electricity_H96_test_trainval_memory_emb.npy
memory_embeddings/Electricity_H96_validation_train_memory_emb.npy
memory_embeddings/Weather_H192_F1_prefix20287_emb.npy
memory_embeddings/Weather_H192_F2_prefix25820_emb.npy
memory_embeddings/Weather_H192_F3_prefix31353_emb.npy
memory_embeddings/Weather_H192_test_trainval_memory_emb.npy
memory_embeddings/Weather_H192_validation_train_memory_emb.npy
memory_embeddings/Weather_H336_F1_prefix20287_emb.npy
memory_embeddings/Weather_H336_F2_prefix25820_emb.npy
memory_embeddings/Weather_H336_F3_prefix31353_emb.npy
memory_embeddings/Weather_H336_test_trainval_memory_emb.npy
memory_embeddings/Weather_H336_validation_train_memory_emb.npy
memory_embeddings/Weather_H720_F1_prefix20287_emb.npy
memory_embeddings/Weather_H720_F2_prefix25820_emb.npy
memory_embeddings/Weather_H720_F3_prefix31353_emb.npy
memory_embeddings/Weather_H720_test_trainval_memory_emb.npy
memory_embeddings/Weather_H720_validation_train_memory_emb.npy
memory_embeddings/Weather_H96_F1_prefix20287_emb.npy
memory_embeddings/Weather_H96_F2_prefix25820_emb.npy
memory_embeddings/Weather_H96_F3_prefix31353_emb.npy
memory_embeddings/Weather_H96_test_trainval_memory_emb.npy
memory_embeddings/Weather_H96_validation_train_memory_emb.npy
oof/ETTh1_H192_F1_oof.npz
oof/ETTh1_H192_F2_oof.npz
oof/ETTh1_H192_F3_oof.npz
oof/ETTh1_H336_F1_oof.npz
oof/ETTh1_H336_F2_oof.npz
oof/ETTh1_H336_F3_oof.npz
oof/ETTh1_H720_F1_oof.npz
oof/ETTh1_H720_F2_oof.npz
oof/ETTh1_H720_F3_oof.npz
oof/ETTh1_H96_F1_oof.npz
oof/ETTh1_H96_F2_oof.npz
oof/ETTh1_H96_F3_oof.npz
oof/ETTm1_H192_F1_oof.npz
oof/ETTm1_H192_F2_oof.npz
oof/ETTm1_H192_F3_oof.npz
oof/ETTm1_H336_F1_oof.npz
oof/ETTm1_H336_F2_oof.npz
oof/ETTm1_H336_F3_oof.npz
oof/ETTm1_H720_F1_oof.npz
oof/ETTm1_H720_F2_oof.npz
oof/ETTm1_H720_F3_oof.npz
oof/ETTm1_H96_F1_oof.npz
oof/ETTm1_H96_F2_oof.npz
oof/ETTm1_H96_F3_oof.npz
oof/Electricity_H192_F1_oof.npz
oof/Electricity_H192_F2_oof.npz
oof/Electricity_H192_F3_oof.npz
oof/Electricity_H336_F1_oof.npz
oof/Electricity_H336_F2_oof.npz
oof/Electricity_H336_F3_oof.npz
oof/Electricity_H720_F1_oof.npz
oof/Electricity_H720_F2_oof.npz
oof/Electricity_H720_F3_oof.npz
oof/Electricity_H96_F1_oof.npz
oof/Electricity_H96_F2_oof.npz
oof/Electricity_H96_F3_oof.npz
oof/Weather_H192_F1_oof.npz
oof/Weather_H192_F2_oof.npz
oof/Weather_H192_F3_oof.npz
oof/Weather_H336_F1_oof.npz
oof/Weather_H336_F2_oof.npz
oof/Weather_H336_F3_oof.npz
oof/Weather_H720_F1_oof.npz
oof/Weather_H720_F2_oof.npz
oof/Weather_H720_F3_oof.npz
oof/Weather_H96_F1_oof.npz
oof/Weather_H96_F2_oof.npz
oof/Weather_H96_F3_oof.npz
paired_test/ETTh1_H192_anchor_mse.npz
paired_test/ETTh1_H336_anchor_mse.npz
paired_test/ETTh1_H720_anchor_mse.npz
paired_test/ETTh1_H96_anchor_mse.npz
paired_test/ETTm1_H192_anchor_mse.npz
paired_test/ETTm1_H336_anchor_mse.npz
paired_test/ETTm1_H720_anchor_mse.npz
paired_test/ETTm1_H96_anchor_mse.npz
paired_test/Electricity_H192_anchor_mse.npz
paired_test/Electricity_H336_anchor_mse.npz
paired_test/Electricity_H720_anchor_mse.npz
paired_test/Electricity_H96_anchor_mse.npz
paired_test/Weather_H192_anchor_mse.npz
paired_test/Weather_H336_anchor_mse.npz
paired_test/Weather_H720_anchor_mse.npz
paired_test/Weather_H96_anchor_mse.npz
summary.csv
validation/ETTh1_H192_validation.npz
validation/ETTh1_H336_validation.npz
validation/ETTh1_H720_validation.npz
validation/ETTh1_H96_validation.npz
validation/ETTm1_H192_validation.npz
validation/ETTm1_H336_validation.npz
validation/ETTm1_H720_validation.npz
validation/ETTm1_H96_validation.npz
validation/Electricity_H192_validation.npz
validation/Electricity_H336_validation.npz
validation/Electricity_H720_validation.npz
validation/Electricity_H96_validation.npz
validation/Weather_H192_validation.npz
validation/Weather_H336_validation.npz
validation/Weather_H720_validation.npz
validation/Weather_H96_validation.npz