# Experiment 41 v3 — Clean Audit of Downstream Significance Metadata

The v2 run revealed that significance information is in fact widely available, but the final
coverage report was wrong because `condition_level_selected.csv` already contained columns named
`CI_Low`, `CI_High`, etc. Merging a second significance table created `CI_Low_x` / `CI_Low_y`,
while the reporting cell looked for the unsuffixed `CI_Low`.

A second issue is that a recursive scan can rediscover files written by the recovery notebook itself,
creating circular provenance.

This v3 notebook fixes both issues.

## Rules

1. The Experiment 37 selected 96-condition table is the authoritative condition list.
2. Significance already stored in that table is retained first.
3. Historical bootstrap/CI files are scanned only outside the recovery/meta-analysis output folders.
4. Missing values are filled from the best matching historical source; existing selected values are
   never overwritten.
5. No significance label is inferred merely from the sign of MSE gain.
6. Every recovered interval must have a direction consistent with the frozen MSE gain.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 280)
pd.set_option("display.max_rows", 200)

DATASETS = [
    "Solar",
    "Weather",
    "Electricity",
    "Traffic",
    "Exchange",
    "ETTh1",
]

BACKBONES = [
    "PatchTST",
    "iTransformer",
    "TimeMixer",
    "SegMoE",
]

HORIZONS = [96, 192, 336, 720]

ROOT_CANDIDATES = [
    Path("/data/dataset/strong_forecaster"),
    Path("/data/strong_forecaster"),
]

ROOT = next((p for p in ROOT_CANDIDATES if p.exists()), None)

if ROOT is None:
    raise FileNotFoundError("strong_forecaster root not found")

OUT_DIR = ROOT / "significance_metadata_recovery_v3_clean"
OUT_DIR.mkdir(parents=True, exist_ok=True)

print("ROOT:", ROOT)
print("OUT_DIR:", OUT_DIR)

ROOT: /data/dataset/strong_forecaster
OUT_DIR: /data/dataset/strong_forecaster/significance_metadata_recovery_v3_clean

## 1. Load the frozen Experiment 37 condition table

In [2]:
preferred = (
    ROOT
    / "four_backbone_dataset_meta_analysis"
    / "condition_level_selected.csv"
)

if not preferred.is_file():
    hits = sorted(ROOT.rglob("condition_level_selected.csv"))
    hits = [
        p for p in hits
        if "significance_metadata_recovery" not in str(p)
    ]

    if not hits:
        raise FileNotFoundError("condition_level_selected.csv not found")

    preferred = hits[0]

conditions = pd.read_csv(preferred)

required = {
    "Dataset",
    "Backbone",
    "Horizon",
    "MSEGain_pct",
}

missing = required - set(conditions.columns)

if missing:
    raise ValueError(f"Missing columns: {sorted(missing)}")

conditions = conditions[
    conditions["Dataset"].isin(DATASETS)
    & conditions["Backbone"].isin(BACKBONES)
    & conditions["Horizon"].astype(int).isin(HORIZONS)
].copy()

conditions["Horizon"] = conditions["Horizon"].astype(int)

KEY = ["Dataset", "Backbone", "Horizon"]

if len(conditions) != 96:
    raise RuntimeError(f"Expected 96 conditions; got {len(conditions)}")

if conditions.duplicated(KEY).any():
    raise RuntimeError("Duplicate selected conditions found")

print("Condition table:", preferred)
print("Conditions:", len(conditions))
print("Columns:", list(conditions.columns))

Condition table: /data/dataset/strong_forecaster/four_backbone_dataset_meta_analysis/condition_level_selected.csv
Conditions: 96
Columns: ['Dataset', 'Backbone', 'Horizon', 'ProtocolFamily', 'ExperimentFamily', 'Direct_MSE', 'Final_MSE', 'MSEGain_pct', 'Direct_MAE', 'Final_MAE', 'MAEGain_pct', 'FinalMeanAlpha', 'OracleHeadroom_pct', 'ValidationGain_pct', 'CI_Low', 'CI_High', 'SignificantPositive', 'SignificantNegative', 'SourcePath', 'SourceScore', 'RecoveredFamilyBonus', 'FinalSourceScore']

## 2. Audit significance already present in the selected table

This step is important because Experiment 37 already propagated significance metadata for many
conditions. We preserve those exact values before searching historical artifacts.

In [3]:
SIG_COLS = [
    "CI_Low",
    "CI_High",
    "SignificantPositive",
    "SignificantNegative",
]

for c in SIG_COLS:
    if c not in conditions.columns:
        conditions[c] = np.nan

base = conditions.copy()

base["SelectedHasCI"] = (
    pd.to_numeric(base["CI_Low"], errors="coerce").notna()
    & pd.to_numeric(base["CI_High"], errors="coerce").notna()
)

print(
    "Significance already present in selected table:",
    int(base["SelectedHasCI"].sum()),
    "/96",
)

display(
    base.groupby("Dataset")
    .agg(
        Conditions=("Horizon", "size"),
        SelectedWithCI=("SelectedHasCI", "sum"),
    )
    .reset_index()
)

Significance already present in selected table: 68 /96

       Dataset  Conditions  SelectedWithCI
0        ETTh1          16              16
1  Electricity          16              12
2     Exchange          16               4
3        Solar          16               4
4      Traffic          16              16
5      Weather          16              16

## 3. Canonicalization and clean source filtering

In [4]:
def canon_dataset(x):
    s = str(x).strip().lower().replace("-", "").replace("_", "")
    return {
        "solar": "Solar",
        "solarenergy": "Solar",
        "weather": "Weather",
        "electricity": "Electricity",
        "ecl": "Electricity",
        "traffic": "Traffic",
        "exchange": "Exchange",
        "exchangerate": "Exchange",
        "etth1": "ETTh1",
    }.get(s, str(x).strip())


def canon_backbone(x):
    s = str(x).strip().lower().replace("-", "").replace("_", "")
    return {
        "patchtst": "PatchTST",
        "itransformer": "iTransformer",
        "timemixer": "TimeMixer",
        "segmoe": "SegMoE",
        "segmoeforecast": "SegMoE",
    }.get(s, str(x).strip())


def find_col(df, names):
    lower = {str(c).lower(): c for c in df.columns}
    for n in names:
        if n.lower() in lower:
            return lower[n.lower()]
    return None


def as_bool(v):
    if pd.isna(v):
        return np.nan
    if isinstance(v, (bool, np.bool_)):
        return bool(v)
    if isinstance(v, (int, np.integer)):
        return bool(v)
    s = str(v).strip().lower()
    if s in {"true", "1", "yes", "y"}:
        return True
    if s in {"false", "0", "no", "n"}:
        return False
    return np.nan


def is_excluded_path(p):
    s = str(p)

    # Never read outputs from this recovery workflow back into itself.
    banned = [
        "significance_metadata_recovery/",
        "significance_metadata_recovery_v3_clean/",
    ]

    return any(token in s for token in banned)


def source_priority(p):
    name = p.name.lower()
    s = str(p).lower()

    if name == "bootstrap.csv":
        return 0

    if "with_bootstrap" in name or "bootstrap" in name:
        return 1

    # Derived evidence tables are useful only after true bootstrap files.
    if (
        "cross_backbone_integrated_evidence" in s
        or "three_backbone_integrated_evidence" in s
    ):
        return 3

    return 2

## 4. Scan historical significance files, excluding recovery outputs

In [5]:
candidate_files = []

for p in ROOT.rglob("*.csv"):
    if is_excluded_path(p):
        continue

    # The Experiment 37 selected table is handled separately above.
    if p.resolve() == preferred.resolve():
        continue

    try:
        size_mb = p.stat().st_size / (1024**2)
    except Exception:
        continue

    if size_mb > 500:
        continue

    try:
        df = pd.read_csv(p)
    except Exception:
        continue

    c_dataset = find_col(df, ["Dataset", "Data"])
    c_backbone = find_col(df, ["Backbone", "Model"])
    c_horizon = find_col(df, ["Horizon", "PredLen", "pred_len", "H"])
    c_lo = find_col(df, ["CI_Low", "CILow", "Lower", "Lower95", "CI95_Low"])
    c_hi = find_col(df, ["CI_High", "CIHigh", "Upper", "Upper95", "CI95_High"])

    if None in {c_dataset, c_backbone, c_horizon, c_lo, c_hi}:
        continue

    candidate_files.append({
        "Path": str(p),
        "Rows": len(df),
        "Priority": source_priority(p),
        "SizeMB": size_mb,
    })

inventory = pd.DataFrame(
    candidate_files,
    columns=["Path", "Rows", "Priority", "SizeMB"],
)

if len(inventory):
    inventory = (
        inventory
        .drop_duplicates("Path")
        .sort_values(["Priority", "Path"])
        .reset_index(drop=True)
    )

display(inventory)

inventory.to_csv(
    OUT_DIR / "clean_candidate_significance_files.csv",
    index=False,
)

print("Clean candidate files:", len(inventory))

                                                 Path  Rows  Priority    SizeMB
0   /data/dataset/strong_forecaster/electricity_fu...    12         0  0.001682
1   /data/dataset/strong_forecaster/electricity_fu...    12         0  0.001809
2   /data/dataset/strong_forecaster/electricity_fu...    12         0  0.001769
3   /data/dataset/strong_forecaster/electricity_fu...     3         0  0.000540
4   /data/dataset/strong_forecaster/electricity_fu...     4         0  0.000662
5   /data/dataset/strong_forecaster/electricity_fu...     1         0  0.000257
6   /data/dataset/strong_forecaster/electricity_fu...     4         0  0.000668
7   /data/dataset/strong_forecaster/electricity_fu...     8         0  0.001174
8   /data/dataset/strong_forecaster/electricity_fu...    12         0  0.001710
9   /data/dataset/strong_forecaster/electricity_fu...     4         0  0.000654
10  /data/dataset/strong_forecaster/electricity_th...    12         0  0.001648
11  /data/dataset/strong_forecaster/etth1_full7_se...     4         0  0.000620
12  /data/dataset/strong_forecaster/ettm1_full7_se...     4         0  0.000633
13  /data/dataset/strong_forecaster/exchange_full8...     4         0  0.000433
14  /data/dataset/strong_forecaster/exchange_three...    12         0  0.001056
15  /data/dataset/strong_forecaster/solar_full137_...     4         0  0.000605
16  /data/dataset/strong_forecaster/solar_three_ba...    12         0  0.001546
17  /data/dataset/strong_forecaster/traffic_full86...     3         0  0.000528
18  /data/dataset/strong_forecaster/traffic_full86...     2         0  0.000384
19  /data/dataset/strong_forecaster/traffic_full86...     2         0  0.000389
20  /data/dataset/strong_forecaster/traffic_full86...     1         0  0.000255
21  /data/dataset/strong_forecaster/traffic_full86...     2         0  0.000390
22  /data/dataset/strong_forecaster/traffic_full86...     2         0  0.000386
23  /data/dataset/strong_forecaster/traffic_full86...     4         0  0.000643
24  /data/dataset/strong_forecaster/traffic_three_...    12         0  0.001559
25  /data/dataset/strong_forecaster/weather_full21...     4         0  0.000627
26  /data/dataset/strong_forecaster/electricity_fu...    12         1  0.006087
27  /data/dataset/strong_forecaster/electricity_fu...    12         1  0.006165
28  /data/dataset/strong_forecaster/electricity_fu...     4         1  0.000644
29  /data/dataset/strong_forecaster/electricity_fu...     4         1  0.002238
30  /data/dataset/strong_forecaster/electricity_fu...     4         1  0.002227
31  /data/dataset/strong_forecaster/electricity_fu...    12         1  0.005129
32  /data/dataset/strong_forecaster/electricity_fu...     4         1  0.002705
33  /data/dataset/strong_forecaster/etth1_full7_se...     4         1  0.002510
34  /data/dataset/strong_forecaster/ettm1_full7_se...     4         1  0.002517
35  /data/dataset/strong_forecaster/exchange_full8...     4         1  0.002131
36  /data/dataset/strong_forecaster/solar_full137_...     4         1  0.002485
37  /data/dataset/strong_forecaster/traffic_full86...     4         1  0.002257
38  /data/dataset/strong_forecaster/traffic_full86...     3         1  0.001799
39  /data/dataset/strong_forecaster/traffic_full86...     4         1  0.002138
40  /data/dataset/strong_forecaster/traffic_full86...     2         1  0.001263
41  /data/dataset/strong_forecaster/traffic_full86...     4         1  0.002125
42  /data/dataset/strong_forecaster/traffic_full86...     2         1  0.001259
43  /data/dataset/strong_forecaster/traffic_full86...     2         1  0.001254
44  /data/dataset/strong_forecaster/traffic_full86...     4         1  0.002553
45  /data/dataset/strong_forecaster/weather_full21...     4         1  0.002532
46  /data/dataset/strong_forecaster/relevance_to_f...    48         2  0.010670
47  /data/dataset/strong_forecaster/traffic_full86...    12         2  0.005832
48  /data/dataset/strong_forecaster/traffic_full86...     2         2  0.001263
49  /data/dataset/strong_forecaster/cross_backbone...    32         3  0.013288
50  /data/dataset/strong_forecaster/cross_backbone...    32         3  0.007735
51  /data/dataset/strong_forecaster/three_backbone...    20         3  0.008257
52  /data/dataset/strong_forecaster/three_backbone...    48         3  0.019000
53  /data/dataset/strong_forecaster/three_backbone...    48         3  0.011532

Clean candidate files: 54

## 5. Parse candidate rows

In [6]:
parsed_rows = []

for _, meta in inventory.iterrows():
    p = Path(meta["Path"])

    try:
        df = pd.read_csv(p)
    except Exception:
        continue

    c_dataset = find_col(df, ["Dataset", "Data"])
    c_backbone = find_col(df, ["Backbone", "Model"])
    c_horizon = find_col(df, ["Horizon", "PredLen", "pred_len", "H"])

    c_comp = find_col(df, ["Comparison", "Compare", "MethodComparison"])
    c_mean = find_col(df, [
        "MeanImprovement",
        "MeanDiff",
        "MSEImprovement",
        "DeltaMSE",
        "MeanDifference",
    ])

    c_lo = find_col(df, ["CI_Low", "CILow", "Lower", "Lower95", "CI95_Low"])
    c_hi = find_col(df, ["CI_High", "CIHigh", "Upper", "Upper95", "CI95_High"])

    c_pos = find_col(df, [
        "SignificantPositive",
        "SigPositive",
        "PositiveSignificant",
    ])

    c_neg = find_col(df, [
        "SignificantNegative",
        "SigNegative",
        "NegativeSignificant",
    ])

    c_block = find_col(df, ["BlockLen", "BlockLength", "BootstrapBlockLen"])
    c_rep = find_col(df, ["Replicates", "NBoot", "BootstrapReplicates"])

    for idx, r in df.iterrows():
        dataset = canon_dataset(r[c_dataset])
        backbone = canon_backbone(r[c_backbone])

        try:
            horizon = int(r[c_horizon])
        except Exception:
            continue

        if dataset not in DATASETS:
            continue
        if backbone not in BACKBONES:
            continue
        if horizon not in HORIZONS:
            continue

        lo = pd.to_numeric(
            pd.Series([r[c_lo]]),
            errors="coerce",
        ).iloc[0]

        hi = pd.to_numeric(
            pd.Series([r[c_hi]]),
            errors="coerce",
        ).iloc[0]

        if pd.isna(lo) or pd.isna(hi):
            continue

        mean = (
            pd.to_numeric(
                pd.Series([r[c_mean]]),
                errors="coerce",
            ).iloc[0]
            if c_mean is not None
            else np.nan
        )

        comparison = (
            str(r[c_comp]).strip()
            if c_comp is not None and not pd.isna(r[c_comp])
            else ""
        )

        parsed_rows.append({
            "Dataset": dataset,
            "Backbone": backbone,
            "Horizon": horizon,
            "Comparison": comparison,
            "MeanImprovement": mean,
            "CI_Low_recovered": lo,
            "CI_High_recovered": hi,
            "SigPositive_recovered": (
                as_bool(r[c_pos])
                if c_pos is not None
                else bool(lo > 0)
            ),
            "SigNegative_recovered": (
                as_bool(r[c_neg])
                if c_neg is not None
                else bool(hi < 0)
            ),
            "BlockLen_recovered": (
                r[c_block] if c_block is not None else np.nan
            ),
            "Replicates_recovered": (
                r[c_rep] if c_rep is not None else np.nan
            ),
            "RecoveredSourcePath": str(p),
            "RecoveredSourcePriority": int(meta["Priority"]),
            "RecoveredSourceRow": int(idx),
        })

parsed = pd.DataFrame(parsed_rows)

print("Parsed clean CI rows:", len(parsed))

parsed.to_csv(
    OUT_DIR / "all_clean_recovered_ci_rows.csv",
    index=False,
)

Parsed clean CI rows: 229

## 6. Resolve one clean historical source per condition

Explicit `Direct-ShrinkAdaptive` comparisons and true `bootstrap.csv` files receive highest priority.
Only sign-consistent rows are eligible.

In [7]:
def comparison_score(s):
    s = str(s).lower().strip()

    if not s:
        return 2

    direct = "direct" in s
    finalish = any(
        token in s
        for token in [
            "shrinkadaptive",
            "shrink",
            "adaptive",
            "final",
            "ours",
        ]
    )

    if direct and finalish:
        return 0
    if direct:
        return 1
    return 2


def sign_of(v, tol=1e-12):
    if pd.isna(v):
        return 0
    if v > tol:
        return 1
    if v < -tol:
        return -1
    return 0


gain_lookup = base.set_index(KEY)["MSEGain_pct"].to_dict()

resolved_rows = []

if len(parsed):
    parsed["ComparisonScore"] = parsed["Comparison"].map(comparison_score)

    for key, g in parsed.groupby(KEY):
        frozen_gain = gain_lookup.get(key, np.nan)
        frozen_sign = sign_of(frozen_gain)

        g = g.copy()

        g["IntervalSign"] = np.select(
            [
                g["CI_Low_recovered"] > 0,
                g["CI_High_recovered"] < 0,
            ],
            [
                1,
                -1,
            ],
            default=0,
        )

        # Nonsignificant intervals can coexist with either observed direction.
        g["SignConsistent"] = (
            (g["IntervalSign"] == 0)
            | (frozen_sign == 0)
            | (g["IntervalSign"] == frozen_sign)
        )

        g = g[g["SignConsistent"]].copy()

        if not len(g):
            continue

        g["RepNumeric"] = pd.to_numeric(
            g["Replicates_recovered"],
            errors="coerce",
        ).fillna(-1)

        g = g.sort_values(
            [
                "ComparisonScore",
                "RecoveredSourcePriority",
                "RepNumeric",
                "RecoveredSourcePath",
            ],
            ascending=[True, True, False, True],
        )

        resolved_rows.append(g.iloc[0].to_dict())

resolved = pd.DataFrame(resolved_rows)

print("Clean resolved historical conditions:", len(resolved))

if len(resolved):
    display(
        resolved.sort_values(KEY)
    )

resolved.to_csv(
    OUT_DIR / "resolved_clean_historical_significance.csv",
    index=False,
)

Clean resolved historical conditions: 71

,Dataset,Backbone,Horizon,Comparison,MeanImprovement,CI_Low_recovered,CI_High_recovered,SigPositive_recovered,SigNegative_recovered,BlockLen_recovered,Replicates_recovered,RecoveredSourcePath,RecoveredSourcePriority,RecoveredSourceRow,ComparisonScore,IntervalSign,SignConsistent,RepNumeric
0,ETTh1,PatchTST,96,,NaN,-0.006288,-0.002074,NaN,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,8,2,-1,True,-1.0
1,ETTh1,PatchTST,192,,NaN,-0.009349,-0.004259,NaN,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,10,2,-1,True,-1.0
2,ETTh1,PatchTST,336,,NaN,-0.008331,-0.004493,NaN,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,12,2,-1,True,-1.0
3,ETTh1,PatchTST,720,,NaN,-0.022114,-0.014229,NaN,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,14,2,-1,True,-1.0
4,ETTh1,TimeMixer,96,,NaN,-0.003480,-0.000890,False,True,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3,7,2,-1,True,-1.0
5,ETTh1,TimeMixer,192,,NaN,-0.006327,0.001269,False,False,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3,17,2,0,True,-1.0
6,ETTh1,TimeMixer,336,,NaN,-0.011725,-0.004047,False,True,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3,20,2,-1,True,-1.0
7,ETTh1,TimeMixer,720,,NaN,-0.039244,-0.025174,False,True,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3,23,2,-1,True,-1.0
8,ETTh1,iTransformer,96,,-0.001978,-0.004286,0.000448,False,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,9,2,0,True,-1.0
9,ETTh1,iTransformer,192,,-0.006457,-0.009515,-0.002894,False,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,11,2,-1,True,-1.0
10,ETTh1,iTransformer,336,,-0.008738,-0.012672,-0.004596,False,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,13,2,-1,True,-1.0
11,ETTh1,iTransformer,720,,-0.029762,-0.035795,-0.023611,False,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,15,2,-1,True,-1.0
12,Electricity,PatchTST,96,Direct-ShrinkAdaptive,0.001403,0.000676,0.002276,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,0,0,1,True,5000.0
13,Electricity,PatchTST,192,Direct-ShrinkAdaptive,0.000309,0.000196,0.000423,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,1,0,1,True,5000.0
14,Electricity,PatchTST,336,Direct-ShrinkAdaptive,0.000057,-0.000091,0.000211,False,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,2,0,0,True,5000.0
15,Electricity,PatchTST,720,Direct-ShrinkAdaptive,-0.000349,-0.000683,0.000003,False,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,3,0,0,True,5000.0
16,Electricity,TimeMixer,96,Direct-ShrinkAdaptive,0.002050,0.001651,0.002472,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,4,0,1,True,5000.0
17,Electricity,TimeMixer,192,Direct-ShrinkAdaptive,0.000708,0.000518,0.000911,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,5,0,1,True,5000.0
18,Electricity,TimeMixer,336,Direct-ShrinkAdaptive,0.002526,0.001692,0.003485,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,6,0,1,True,5000.0
19,Electricity,TimeMixer,720,Direct-ShrinkAdaptive,0.002096,0.001534,0.002740,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,7,0,1,True,5000.0
20,Electricity,iTransformer,96,Direct-ShrinkAdaptive,0.003874,0.003057,0.004786,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,8,0,1,True,5000.0
21,Electricity,iTransformer,192,Direct-ShrinkAdaptive,0.002620,0.001830,0.003459,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,9,0,1,True,5000.0
22,Electricity,iTransformer,336,Direct-ShrinkAdaptive,0.003936,0.002998,0.004982,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,10,0,1,True,5000.0
23,Electricity,iTransformer,720,Direct-ShrinkAdaptive,0.007222,0.005771,0.008848,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0,11,0,1,True,5000.0
24,Exchange,PatchTST,96,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,0,0,0,True,5000.0
25,Exchange,PatchTST,192,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,1,0,0,True,5000.0
26,Exchange,PatchTST,336,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,2,0,0,True,5000.0
27,Exchange,PatchTST,720,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,3,0,0,True,5000.0
28,Exchange,TimeMixer,96,Direct-ShrinkAdaptive,0.001636,0.000952,0.002372,True,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,4,0,1,True,5000.0
29,Exchange,TimeMixer,192,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,5,0,0,True,5000.0
30,Exchange,TimeMixer,336,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,6,0,0,True,5000.0
31,Exchange,TimeMixer,720,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,7,0,0,True,5000.0
32,Exchange,iTransformer,96,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,8,0,0,True,5000.0
33,Exchange,iTransformer,192,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,9,0,0,True,5000.0
34,Exchange,iTransformer,336,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,10,0,0,True,5000.0
35,Exchange,iTransformer,720,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0,11,0,0,True,5000.0
36,Solar,PatchTST,96,Direct-ShrinkAdaptive,0.002979,-0.001281,0.007369,False,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,0,0,0,True,5000.0
37,Solar,PatchTST,192,Direct-ShrinkAdaptive,0.001052,-0.001870,0.003871,False,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,1,0,0,True,5000.0
38,Solar,PatchTST,336,Direct-ShrinkAdaptive,0.003772,0.002087,0.005385,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,2,0,1,True,5000.0
39,Solar,PatchTST,720,Direct-ShrinkAdaptive,0.004528,0.002738,0.006251,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,3,0,1,True,5000.0
40,Solar,TimeMixer,96,Direct-ShrinkAdaptive,0.005060,0.000905,0.009791,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,4,0,1,True,5000.0
41,Solar,TimeMixer,192,Direct-ShrinkAdaptive,0.009487,0.002735,0.016665,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,5,0,1,True,5000.0
42,Solar,TimeMixer,336,Direct-ShrinkAdaptive,0.022614,0.016781,0.028967,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,6,0,1,True,5000.0
43,Solar,TimeMixer,720,Direct-ShrinkAdaptive,0.013156,0.006902,0.019541,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,7,0,1,True,5000.0
44,Solar,iTransformer,96,Direct-ShrinkAdaptive,0.021362,0.012270,0.030900,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,8,0,1,True,5000.0
45,Solar,iTransformer,192,Direct-ShrinkAdaptive,0.031502,0.021953,0.041997,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,9,0,1,True,5000.0
46,Solar,iTransformer,336,Direct-ShrinkAdaptive,0.035267,0.027903,0.043691,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,10,0,1,True,5000.0
47,Solar,iTransformer,720,Direct-ShrinkAdaptive,0.027438,0.020249,0.035178,True,False,24.0,5000.0,/data/dataset/strong_forecaster/solar_three_ba...,0,11,0,1,True,5000.0
48,Traffic,PatchTST,96,Direct-ShrinkAdaptive,0.000625,-0.000734,0.002019,False,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,0,0,0,True,5000.0
49,Traffic,PatchTST,192,Direct-ShrinkAdaptive,0.000977,-0.000442,0.002440,False,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,1,0,0,True,5000.0
50,Traffic,PatchTST,336,Direct-ShrinkAdaptive,0.000575,0.000443,0.000695,True,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,2,0,1,True,5000.0
51,Traffic,PatchTST,720,Direct-ShrinkAdaptive,0.000000,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,3,0,0,True,5000.0
52,Traffic,TimeMixer,96,Direct-ShrinkAdaptive,0.000280,-0.000023,0.000598,False,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,4,0,0,True,5000.0
53,Traffic,TimeMixer,192,Direct-ShrinkAdaptive,0.000468,0.000228,0.000751,True,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,5,0,1,True,5000.0
54,Traffic,TimeMixer,336,Direct-ShrinkAdaptive,0.000148,-0.000033,0.000331,False,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,6,0,0,True,5000.0
55,Traffic,TimeMixer,720,Direct-ShrinkAdaptive,-0.000146,-0.000337,0.000053,False,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,7,0,0,True,5000.0
56,Traffic,iTransformer,96,Direct-ShrinkAdaptive,0.002709,0.000011,0.005390,True,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,8,0,1,True,5000.0
57,Traffic,iTransformer,192,Direct-ShrinkAdaptive,0.002014,-0.000548,0.004663,False,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,9,0,0,True,5000.0
58,Traffic,iTransformer,720,Direct-ShrinkAdaptive,0.001111,0.000463,0.001754,True,False,24.0,5000.0,/data/dataset/strong_forecaster/traffic_three_...,0,11,0,1,True,5000.0
59,Weather,PatchTST,96,,NaN,0.001320,0.003172,NaN,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,16,2,1,True,-1.0
60,Weather,PatchTST,192,,NaN,0.003319,0.005325,NaN,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,18,2,1,True,-1.0
61,Weather,PatchTST,336,,NaN,0.004242,0.006882,NaN,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,20,2,1,True,-1.0
62,Weather,PatchTST,720,,NaN,0.005369,0.008341,NaN,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,22,2,1,True,-1.0
63,Weather,TimeMixer,96,,NaN,0.001241,0.002063,True,False,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3,26,2,1,True,-1.0
64,Weather,TimeMixer,192,,NaN,0.002642,0.003721,True,False,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3,29,2,1,True,-1.0
65,Weather,TimeMixer,336,,NaN,0.003935,0.005290,True,False,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3,32,2,1,True,-1.0
66,Weather,TimeMixer,720,,NaN,0.008969,0.011685,True,False,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3,35,2,1,True,-1.0
67,Weather,iTransformer,96,,0.007281,0.005587,0.009051,True,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,17,2,1,True,-1.0
68,Weather,iTransformer,192,,0.010036,0.008367,0.012079,True,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,19,2,1,True,-1.0
69,Weather,iTransformer,336,,0.012261,0.010366,0.014490,True,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,21,2,1,True,-1.0
70,Weather,iTransformer,720,,0.013633,0.011818,0.015599,True,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3,23,2,1,True,-1.0

## 7. Coalesce selected-table metadata with clean historical recovery

Selected Experiment 37 significance metadata are used first.
Recovered historical metadata fill only selected-table missing values.

In [8]:
if len(resolved):
    recovery_keep = [
        "Dataset",
        "Backbone",
        "Horizon",
        "CI_Low_recovered",
        "CI_High_recovered",
        "SigPositive_recovered",
        "SigNegative_recovered",
        "BlockLen_recovered",
        "Replicates_recovered",
        "RecoveredSourcePath",
        "RecoveredSourcePriority",
    ]

    rec = resolved[recovery_keep].copy()
else:
    rec = pd.DataFrame(
        columns=[
            "Dataset",
            "Backbone",
            "Horizon",
            "CI_Low_recovered",
            "CI_High_recovered",
            "SigPositive_recovered",
            "SigNegative_recovered",
            "BlockLen_recovered",
            "Replicates_recovered",
            "RecoveredSourcePath",
            "RecoveredSourcePriority",
        ]
    )

full = base.merge(
    rec,
    on=KEY,
    how="left",
    validate="one_to_one",
)

for c in ["CI_Low", "CI_High"]:
    full[c] = pd.to_numeric(full[c], errors="coerce")

full["Final_CI_Low"] = full["CI_Low"].combine_first(
    full["CI_Low_recovered"]
)

full["Final_CI_High"] = full["CI_High"].combine_first(
    full["CI_High_recovered"]
)

full["Final_SignificantPositive"] = (
    full["SignificantPositive"]
    .where(
        full["SignificantPositive"].notna(),
        full["SigPositive_recovered"],
    )
)

full["Final_SignificantNegative"] = (
    full["SignificantNegative"]
    .where(
        full["SignificantNegative"].notna(),
        full["SigNegative_recovered"],
    )
)

full["SignificanceSource"] = np.where(
    full["SelectedHasCI"],
    "Experiment37Selected",
    np.where(
        full["Final_CI_Low"].notna()
        & full["Final_CI_High"].notna(),
        "HistoricalRecovery",
        "Missing",
    ),
)

full["HasFinalCI"] = (
    full["Final_CI_Low"].notna()
    & full["Final_CI_High"].notna()
)

full["SignClass"] = np.select(
    [
        full["Final_CI_Low"] > 0,
        full["Final_CI_High"] < 0,
        full["HasFinalCI"],
    ],
    [
        "positive",
        "negative",
        "nonsignificant",
    ],
    default="missing",
)

full["ObservedDirection"] = np.select(
    [
        full["MSEGain_pct"] > 1e-12,
        full["MSEGain_pct"] < -1e-12,
    ],
    [
        "win",
        "loss",
    ],
    default="tie",
)

# Strict final sign audit.
bad = full[
    ((full["SignClass"] == "positive") & (full["MSEGain_pct"] <= 0))
    | ((full["SignClass"] == "negative") & (full["MSEGain_pct"] >= 0))
]

if len(bad):
    print("WARNING: sign-inconsistent final intervals:")
    display(bad[KEY + ["MSEGain_pct", "Final_CI_Low", "Final_CI_High", "SignificanceSource"]])
    raise RuntimeError("Final significance sign audit failed")

display(
    full.sort_values(KEY)
)

full.to_csv(
    OUT_DIR / "condition_level_96_with_clean_significance.csv",
    index=False,
)

,Dataset,Backbone,Horizon,ProtocolFamily,ExperimentFamily,Direct_MSE,Final_MSE,MSEGain_pct,Direct_MAE,Final_MAE,MAEGain_pct,FinalMeanAlpha,OracleHeadroom_pct,ValidationGain_pct,CI_Low,CI_High,SignificantPositive,SignificantNegative,SourcePath,SourceScore,RecoveredFamilyBonus,FinalSourceScore,SelectedHasCI,CI_Low_recovered,CI_High_recovered,SigPositive_recovered,SigNegative_recovered,BlockLen_recovered,Replicates_recovered,RecoveredSourcePath,RecoveredSourcePriority,Final_CI_Low,Final_CI_High,Final_SignificantPositive,Final_SignificantNegative,SignificanceSource,HasFinalCI,SignClass,ObservedDirection
0,ETTh1,PatchTST,96,other,cross_backbone_integrated_evidence,0.378632,NaN,-1.090730,0.400303,NaN,-1.181425,NaN,6.578487,NaN,-0.006288,-0.002074,False,True,/data/dataset/strong_forecaster/cross_backbone...,0,10000,10000,True,-0.006288,-0.002074,NaN,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3.0,-0.006288,-0.002074,False,True,Experiment37Selected,True,negative,loss
1,ETTh1,PatchTST,192,other,cross_backbone_integrated_evidence,0.413694,NaN,-1.676780,0.420978,NaN,-1.948489,NaN,6.327950,NaN,-0.009349,-0.004259,False,True,/data/dataset/strong_forecaster/cross_backbone...,0,10000,10000,True,-0.009349,-0.004259,NaN,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3.0,-0.009349,-0.004259,False,True,Experiment37Selected,True,negative,loss
2,ETTh1,PatchTST,336,other,cross_backbone_integrated_evidence,0.441984,NaN,-1.466894,0.441434,NaN,-1.700162,NaN,4.747864,NaN,-0.008331,-0.004493,False,True,/data/dataset/strong_forecaster/cross_backbone...,0,10000,10000,True,-0.008331,-0.004493,NaN,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3.0,-0.008331,-0.004493,False,True,Experiment37Selected,True,negative,loss
3,ETTh1,PatchTST,720,other,cross_backbone_integrated_evidence,0.461510,NaN,-3.931421,0.473867,NaN,-3.320312,NaN,4.868058,NaN,-0.022114,-0.014229,False,True,/data/dataset/strong_forecaster/cross_backbone...,0,10000,10000,True,-0.022114,-0.014229,NaN,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3.0,-0.022114,-0.014229,False,True,Experiment37Selected,True,negative,loss
4,ETTh1,SegMoE,96,segmoe_dataset_specific,etth1_full7_segmoe_oof_reranker,0.429677,0.434201,-1.052852,0.437933,0.441780,-0.878598,0.079709,9.609814,NaN,-0.006634,-0.002260,False,True,/data/dataset/strong_forecaster/etth1_full7_se...,1600,0,1600,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.006634,-0.002260,False,True,Experiment37Selected,True,negative,loss
5,ETTh1,SegMoE,192,segmoe_dataset_specific,etth1_full7_segmoe_oof_reranker,0.481695,0.492603,-2.264470,0.473062,0.480069,-1.481033,0.094744,7.912543,NaN,-0.013680,-0.008055,False,True,/data/dataset/strong_forecaster/etth1_full7_se...,1600,0,1600,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.013680,-0.008055,False,True,Experiment37Selected,True,negative,loss
6,ETTh1,SegMoE,336,segmoe_dataset_specific,etth1_full7_segmoe_oof_reranker,0.535394,0.547647,-2.288568,0.505612,0.512787,-1.418999,0.100000,7.730242,NaN,-0.014982,-0.009320,False,True,/data/dataset/strong_forecaster/etth1_full7_se...,1600,0,1600,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.014982,-0.009320,False,True,Experiment37Selected,True,negative,loss
7,ETTh1,SegMoE,720,segmoe_dataset_specific,etth1_full7_segmoe_oof_reranker,0.657350,0.702025,-6.796243,0.571758,0.593895,-3.871679,0.200000,8.328258,NaN,-0.051040,-0.038125,False,True,/data/dataset/strong_forecaster/etth1_full7_se...,1600,0,1600,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.051040,-0.038125,False,True,Experiment37Selected,True,negative,loss
8,ETTh1,TimeMixer,96,other,three_backbone_integrated_evidence,0.388839,NaN,-0.567222,0.402163,NaN,-0.660399,NaN,6.073419,NaN,-0.003480,-0.000890,False,True,/data/dataset/strong_forecaster/three_backbone...,80,10000,10080,True,-0.003480,-0.000890,False,True,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3.0,-0.003480,-0.000890,False,True,Experiment37Selected,True,negative,loss
9,ETTh1,TimeMixer,192,other,three_backbone_integrated_evidence,0.442255,NaN,-0.640128,0.429601,NaN,-1.443491,NaN,7.359547,NaN,-0.006327,0.001269,False,False,/data/dataset/strong_forecaster/three_backbone...,80,10000,10080,True,-0.006327,0.001269,False,False,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3.0,-0.006327,0.001269,False,False,Experiment37Selected,True,nonsignificant,loss
10,ETTh1,TimeMixer,336,other,three_backbone_integrated_evidence,0.517918,NaN,-1.529878,0.474665,NaN,-1.976771,NaN,7.404970,NaN,-0.011725,-0.004047,False,True,/data/dataset/strong_forecaster/three_backbone...,80,10000,10080,True,-0.011725,-0.004047,False,True,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3.0,-0.011725,-0.004047,False,True,Experiment37Selected,True,negative,loss
11,ETTh1,TimeMixer,720,other,three_backbone_integrated_evidence,0.512187,NaN,-6.298939,0.484744,NaN,-5.943258,NaN,7.503382,NaN,-0.039244,-0.025174,False,True,/data/dataset/strong_forecaster/three_backbone...,80,10000,10080,True,-0.039244,-0.025174,False,True,NaN,NaN,/data/dataset/strong_forecaster/three_backbone...,3.0,-0.039244,-0.025174,False,True,Experiment37Selected,True,negative,loss
12,ETTh1,iTransformer,96,other,cross_backbone_integrated_evidence,0.392303,NaN,-0.504197,0.407334,NaN,-0.848825,NaN,7.592273,NaN,-0.004286,0.000448,False,False,/data/dataset/strong_forecaster/cross_backbone...,0,10000,10000,True,-0.004286,0.000448,False,False,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3.0,-0.004286,0.000448,False,False,Experiment37Selected,True,nonsignificant,loss
13,ETTh1,iTransformer,192,other,cross_backbone_integrated_evidence,0.442639,NaN,-1.458748,0.434737,NaN,-1.824475,NaN,6.657512,NaN,-0.009515,-0.002894,False,True,/data/dataset/strong_forecaster/cross_backbone...,0,10000,10000,True,-0.009515,-0.002894,False,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3.0,-0.009515,-0.002894,False,True,Experiment37Selected,True,negative,loss
14,ETTh1,iTransformer,336,other,cross_backbone_integrated_evidence,0.489263,NaN,-1.785874,0.461457,NaN,-2.572073,NaN,7.135021,NaN,-0.012672,-0.004596,False,True,/data/dataset/strong_forecaster/cross_backbone...,0,10000,10000,True,-0.012672,-0.004596,False,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3.0,-0.012672,-0.004596,False,True,Experiment37Selected,True,negative,loss
15,ETTh1,iTransformer,720,other,cross_backbone_integrated_evidence,0.506507,NaN,-5.876001,0.492894,NaN,-4.669960,NaN,6.869664,NaN,-0.035795,-0.023611,False,True,/data/dataset/strong_forecaster/cross_backbone...,0,10000,10000,True,-0.035795,-0.023611,False,True,NaN,NaN,/data/dataset/strong_forecaster/cross_backbone...,3.0,-0.035795,-0.023611,False,True,Experiment37Selected,True,negative,loss
16,Electricity,PatchTST,96,full321_oof,electricity_full321_oof_patchtst_h96_192_336_720,0.129638,0.128549,0.839606,0.222790,0.222718,0.032344,0.019726,7.586264,NaN,0.000628,0.001644,True,False,/data/dataset/strong_forecaster/electricity_fu...,1600,0,1600,True,0.000676,0.002276,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.000628,0.001644,True,False,Experiment37Selected,True,positive,win
17,Electricity,PatchTST,192,full321_oof,electricity_full321_oof_patchtst_h96_192_336_720,0.148802,0.148138,0.445810,0.242637,0.242954,-0.130660,0.021513,5.617052,NaN,0.000320,0.001074,True,False,/data/dataset/strong_forecaster/electricity_fu...,1600,0,1600,True,0.000196,0.000423,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.000320,0.001074,True,False,Experiment37Selected,True,positive,win
18,Electricity,PatchTST,336,full321_oof,electricity_full321_oof_patchtst_h96_192_336_720,0.165312,0.163955,0.820887,0.259284,0.259330,-0.017816,0.022520,6.237337,NaN,0.001008,0.001784,True,False,/data/dataset/strong_forecaster/electricity_fu...,1600,0,1600,True,-0.000091,0.000211,False,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.001008,0.001784,True,False,Experiment37Selected,True,positive,win
19,Electricity,PatchTST,720,full321_oof,electricity_full321_oof_patchtst_h96_192_336_720,0.202859,0.204223,-0.672307,0.291769,0.293104,-0.457611,0.034530,7.844977,NaN,-0.003120,0.000454,False,False,/data/dataset/strong_forecaster/electricity_fu...,1600,0,1600,True,-0.000683,0.000003,False,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,-0.003120,0.000454,False,False,Experiment37Selected,True,nonsignificant,loss
20,Electricity,SegMoE,96,full321_oof,electricity_full321_segmoe_oof_reranker,0.131053,0.130373,0.519435,0.225169,0.225389,-0.097946,0.007066,7.375525,NaN,0.000453,0.000946,True,False,/data/dataset/strong_forecaster/electricity_fu...,2800,0,2800,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000453,0.000946,True,False,Experiment37Selected,True,positive,win
21,Electricity,SegMoE,192,full321_oof,electricity_full321_segmoe_oof_reranker,0.148784,0.148369,0.278683,0.242053,0.242182,-0.053048,0.005644,5.755194,NaN,0.000296,0.000555,True,False,/data/dataset/strong_forecaster/electricity_fu...,2800,0,2800,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000296,0.000555,True,False,Experiment37Selected,True,positive,win
22,Electricity,SegMoE,336,full321_oof,electricity_full321_segmoe_oof_reranker,0.166729,0.166240,0.293029,0.261269,0.261459,-0.072820,0.007520,5.661949,NaN,0.000348,0.000638,True,False,/data/dataset/strong_forecaster/electricity_fu...,2800,0,2800,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000348,0.000638,True,False,Experiment37Selected,True,positive,win
23,Electricity,SegMoE,720,full321_oof,electricity_full321_segmoe_oof_reranker,0.210921,0.210188,0.347162,0.301344,0.302073,-0.241862,0.015052,6.842926,NaN,0.000160,0.001312,True,False,/data/dataset/strong_forecaster/electricity_fu...,2800,0,2800,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000160,0.001312,True,False,Experiment37Selected,True,positive,win
24,Electricity,TimeMixer,96,full321_oof,electricity_full321_oof_timemixer_h96_192_336_720,0.156833,0.156269,0.359394,0.247900,0.247884,0.006271,0.022258,6.724589,NaN,0.000388,0.000724,True,False,/data/dataset/strong_forecaster/electricity_fu...,1600,0,1600,True,0.001651,0.002472,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.000388,0.000724,True,False,Experiment37Selected,True,positive,win
25,Electricity,TimeMixer,192,full321_oof,electricity_full321_oof_timemixer_h96_192_336_720,0.170396,0.169608,0.462375,0.260518,0.260731,-0.081703,0.025651,5.535213,NaN,0.000610,0.000976,True,False,/data/dataset/strong_forecaster/electricity_fu...,1600,0,1600,True,0.000518,0.000911,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.000610,0.000976,True,False,Experiment37Selected,True,positive,win
26,Electricity,TimeMixer,336,full321_oof,electricity_full321_oof_timemixer_h96_192_336_720,0.186231,0.184639,0.854897,0.276494,0.276796,-0.109363,0.025365,5.927617,NaN,0.001205,0.002058,True,False,/data/dataset/strong_forecaster/electricity_fu...,1600,0,1600,True,0.001692,0.003485,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.001205,0.002058,True,False,Experiment37Selected,True,positive,win
27,Electricity,TimeMixer,720,full321_oof,electricity_full321_oof_timemixer_h96_192_336_720,0.226784,0.226125,0.290450,0.310885,0.311662,-0.249936,0.026359,7.164771,NaN,-0.000399,0.001674,False,False,/data/dataset/strong_forecaster/electricity_fu...,1600,0,1600,True,0.001534,0.002740,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,-0.000399,0.001674,False,False,Experiment37Selected,True,nonsignificant,win
28,Electricity,iTransformer,96,full321_oof,electricity_full321_oof_pilot_itransformer_h96,0.150067,0.147866,1.466603,0.241682,0.241352,0.136547,0.026113,9.006127,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/electricity_fu...,1420,0,1420,False,0.003057,0.004786,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.003057,0.004786,True,False,HistoricalRecovery,True,positive,win
29,Electricity,iTransformer,192,full321_oof,electricity_full321_oof_itransformer_h192_336_720,0.163223,0.161652,0.962485,0.253838,0.253938,-0.039164,0.031302,6.993821,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/electricity_fu...,1420,0,1420,False,0.001830,0.003459,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.001830,0.003459,True,False,HistoricalRecovery,True,positive,win
30,Electricity,iTransformer,336,full321_oof,electricity_full321_oof_itransformer_h192_336_720,0.177195,0.175403,1.010948,0.269127,0.269705,-0.214987,0.032550,7.008661,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/electricity_fu...,1420,0,1420,False,0.002998,0.004982,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.002998,0.004982,True,False,HistoricalRecovery,True,positive,win
31,Electricity,iTransformer,720,full321_oof,electricity_full321_oof_itransformer_h192_336_720,0.216770,0.216575,0.089924,0.303519,0.304858,-0.441287,0.037694,7.885399,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/electricity_fu...,1420,0,1420,False,0.005771,0.008848,True,False,24.0,5000.0,/data/dataset/strong_forecaster/electricity_th...,0.0,0.005771,0.008848,True,False,HistoricalRecovery,True,positive,win
32,Exchange,PatchTST,96,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.088792,0.088792,0.000000,0.208818,0.208818,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
33,Exchange,PatchTST,192,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.194937,0.194937,0.000000,0.316183,0.316183,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
34,Exchange,PatchTST,336,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.346291,0.346291,0.000000,0.428873,0.428873,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
35,Exchange,PatchTST,720,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.858390,0.858390,0.000000,0.692987,0.692987,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
36,Exchange,SegMoE,96,segmoe_dataset_specific,exchange_full8_segmoe_oof_reranker,0.087003,0.087003,0.000000,0.207546,0.207546,0.000000,0.000000,23.726278,NaN,0.000000,0.000000,False,False,/data/dataset/strong_forecaster/exchange_full8...,1600,0,1600,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,False,False,Experiment37Selected,True,nonsignificant,tie
37,Exchange,SegMoE,192,segmoe_dataset_specific,exchange_full8_segmoe_oof_reranker,0.183186,0.183186,0.000000,0.307153,0.307153,0.000000,0.000000,26.363985,NaN,0.000000,0.000000,False,False,/data/dataset/strong_forecaster/exchange_full8...,1600,0,1600,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,False,False,Experiment37Selected,True,nonsignificant,tie
38,Exchange,SegMoE,336,segmoe_dataset_specific,exchange_full8_segmoe_oof_reranker,0.331033,0.331033,0.000000,0.420178,0.420178,0.000000,0.000000,25.928511,NaN,0.000000,0.000000,False,False,/data/dataset/strong_forecaster/exchange_full8...,1600,0,1600,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,False,False,Experiment37Selected,True,nonsignificant,tie
39,Exchange,SegMoE,720,segmoe_dataset_specific,exchange_full8_segmoe_oof_reranker,0.808399,0.808399,0.000000,0.680196,0.680196,0.000000,0.000000,24.565117,NaN,0.000000,0.000000,False,False,/data/dataset/strong_forecaster/exchange_full8...,1600,0,1600,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,False,False,Experiment37Selected,True,nonsignificant,tie
40,Exchange,TimeMixer,96,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.092543,0.090907,1.767956,0.210600,0.208730,0.888026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000952,0.002372,True,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000952,0.002372,True,False,HistoricalRecovery,True,positive,win
41,Exchange,TimeMixer,192,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.177509,0.177509,0.000000,0.299693,0.299693,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
42,Exchange,TimeMixer,336,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.329322,0.329322,0.000000,0.417432,0.417432,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
43,Exchange,TimeMixer,720,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,1.149432,1.149432,0.000000,0.800125,0.800125,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
44,Exchange,iTransformer,96,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.098471,0.098471,0.000000,0.223430,0.223430,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
45,Exchange,iTransformer,192,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.182288,0.182288,0.000000,0.305967,0.305967,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
46,Exchange,iTransformer,336,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.346023,0.346023,0.000000,0.426120,0.426120,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie
47,Exchange,iTransformer,720,exchange_three_backbone_frozen_historical_memory,exchange_three_backbone_frozen_historical_memory,0.832304,0.832304,0.000000,0.690283,0.690283,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,/data/dataset/strong_forecaster/exchange_three...,1415,0,1415,False,0.000000,0.000000,False,False,24.0,5000.0,/data/dataset/strong_forecaster/exchange_three...,0.0,0.000000,0.000000,False,False,HistoricalRecovery,True,nonsignificant,tie

## 8. Final clean coverage summary

In [9]:
summary_ds = (
    full.groupby("Dataset")
    .agg(
        Conditions=("Horizon", "size"),
        WithCI=("HasFinalCI", "sum"),
        SignificantWins=("SignClass", lambda s: int((s == "positive").sum())),
        SignificantLosses=("SignClass", lambda s: int((s == "negative").sum())),
        NonSignificant=("SignClass", lambda s: int((s == "nonsignificant").sum())),
        Missing=("SignClass", lambda s: int((s == "missing").sum())),
    )
    .reset_index()
)

summary_bb = (
    full.groupby("Backbone")
    .agg(
        Conditions=("Horizon", "size"),
        WithCI=("HasFinalCI", "sum"),
        SignificantWins=("SignClass", lambda s: int((s == "positive").sum())),
        SignificantLosses=("SignClass", lambda s: int((s == "negative").sum())),
        NonSignificant=("SignClass", lambda s: int((s == "nonsignificant").sum())),
        Missing=("SignClass", lambda s: int((s == "missing").sum())),
    )
    .reset_index()
)

display(summary_ds)
display(summary_bb)

summary_ds.to_csv(
    OUT_DIR / "clean_significance_coverage_by_dataset.csv",
    index=False,
)

summary_bb.to_csv(
    OUT_DIR / "clean_significance_coverage_by_backbone.csv",
    index=False,
)

missing = full[~full["HasFinalCI"]].copy()

print("=" * 118)
print("EXPERIMENT 41 v3 — CLEAN SIGNIFICANCE AUDIT")
print("=" * 118)
print(f"Final CI coverage: {int(full['HasFinalCI'].sum())}/96")
print(f"Missing: {len(missing)}/96")
print(f"Significant wins: {int((full['SignClass'] == 'positive').sum())}")
print(f"Significant losses: {int((full['SignClass'] == 'negative').sum())}")
print(f"Non-significant: {int((full['SignClass'] == 'nonsignificant').sum())}")

print("\nSource breakdown:")
print(full["SignificanceSource"].value_counts(dropna=False).to_string())

print("\nDataset summary:")
print(summary_ds.to_string(index=False))

if len(missing):
    print("\nStill missing:")
    print(
        missing[
            KEY + ["MSEGain_pct", "ObservedDirection"]
        ].sort_values(KEY).to_string(index=False)
    )

       Dataset  Conditions  WithCI  SignificantWins  SignificantLosses  NonSignificant  Missing
0        ETTh1          16      16                0                 14               2        0
1  Electricity          16      16               14                  0               2        0
2     Exchange          16      16                1                  0              15        0
3        Solar          16      16               14                  0               2        0
4      Traffic          16      16               13                  1               2        0
5      Weather          16      16               16                  0               0        0

       Backbone  Conditions  WithCI  SignificantWins  SignificantLosses  NonSignificant  Missing
0      PatchTST          24      24               12                  4               8        0
1        SegMoE          24      24               16                  4               4        0
2     TimeMixer          24      24               15                  3               6        0
3  iTransformer          24      24               15                  4               5        0

======================================================================================================================
EXPERIMENT 41 v3 — CLEAN SIGNIFICANCE AUDIT
======================================================================================================================
Final CI coverage: 96/96
Missing: 0/96
Significant wins: 58
Significant losses: 15
Non-significant: 23

Source breakdown:
Experiment37Selected    68
HistoricalRecovery      28

Dataset summary:
    Dataset  Conditions  WithCI  SignificantWins  SignificantLosses  NonSignificant  Missing
      ETTh1          16      16                0                 14               2        0
Electricity          16      16               14                  0               2        0
   Exchange          16      16                1                  0              15        0
      Solar          16      16               14                  0               2        0
    Traffic          16      16               13                  1               2        0
    Weather          16      16               16                  0               0        0

## 9. Paper-ready significance table

This compact table is intended for the appendix. It reports only the 96 frozen downstream conditions
and the clean final confidence intervals. No post-hoc statistical label is synthesized from the gain
alone.

In [10]:
paper = full[
    [
        "Dataset",
        "Backbone",
        "Horizon",
        "MSEGain_pct",
        "Final_CI_Low",
        "Final_CI_High",
        "SignClass",
        "SignificanceSource",
    ]
].copy()

paper = paper.sort_values(
    ["Dataset", "Backbone", "Horizon"]
)

display(paper)

paper.to_csv(
    OUT_DIR / "paper_downstream_significance_96_conditions.csv",
    index=False,
)

latex = paper.copy()

for c in [
    "MSEGain_pct",
    "Final_CI_Low",
    "Final_CI_High",
]:
    latex[c] = latex[c].map(
        lambda v: "" if pd.isna(v) else f"{v:.6f}"
    )

(OUT_DIR / "paper_downstream_significance_96_conditions.tex").write_text(
    latex.to_latex(
        index=False,
        escape=False,
    ),
    encoding="utf-8",
)

print("Saved paper-ready CSV and LaTeX table.")

        Dataset      Backbone  Horizon  MSEGain_pct  Final_CI_Low  Final_CI_High       SignClass    SignificanceSource
0         ETTh1      PatchTST       96    -1.090730     -0.006288      -0.002074        negative  Experiment37Selected
1         ETTh1      PatchTST      192    -1.676780     -0.009349      -0.004259        negative  Experiment37Selected
2         ETTh1      PatchTST      336    -1.466894     -0.008331      -0.004493        negative  Experiment37Selected
3         ETTh1      PatchTST      720    -3.931421     -0.022114      -0.014229        negative  Experiment37Selected
4         ETTh1        SegMoE       96    -1.052852     -0.006634      -0.002260        negative  Experiment37Selected
5         ETTh1        SegMoE      192    -2.264470     -0.013680      -0.008055        negative  Experiment37Selected
6         ETTh1        SegMoE      336    -2.288568     -0.014982      -0.009320        negative  Experiment37Selected
7         ETTh1        SegMoE      720    -6.796243     -0.051040      -0.038125        negative  Experiment37Selected
8         ETTh1     TimeMixer       96    -0.567222     -0.003480      -0.000890        negative  Experiment37Selected
9         ETTh1     TimeMixer      192    -0.640128     -0.006327       0.001269  nonsignificant  Experiment37Selected
10        ETTh1     TimeMixer      336    -1.529878     -0.011725      -0.004047        negative  Experiment37Selected
11        ETTh1     TimeMixer      720    -6.298939     -0.039244      -0.025174        negative  Experiment37Selected
12        ETTh1  iTransformer       96    -0.504197     -0.004286       0.000448  nonsignificant  Experiment37Selected
13        ETTh1  iTransformer      192    -1.458748     -0.009515      -0.002894        negative  Experiment37Selected
14        ETTh1  iTransformer      336    -1.785874     -0.012672      -0.004596        negative  Experiment37Selected
15        ETTh1  iTransformer      720    -5.876001     -0.035795      -0.023611        negative  Experiment37Selected
16  Electricity      PatchTST       96     0.839606      0.000628       0.001644        positive  Experiment37Selected
17  Electricity      PatchTST      192     0.445810      0.000320       0.001074        positive  Experiment37Selected
18  Electricity      PatchTST      336     0.820887      0.001008       0.001784        positive  Experiment37Selected
19  Electricity      PatchTST      720    -0.672307     -0.003120       0.000454  nonsignificant  Experiment37Selected
20  Electricity        SegMoE       96     0.519435      0.000453       0.000946        positive  Experiment37Selected
21  Electricity        SegMoE      192     0.278683      0.000296       0.000555        positive  Experiment37Selected
22  Electricity        SegMoE      336     0.293029      0.000348       0.000638        positive  Experiment37Selected
23  Electricity        SegMoE      720     0.347162      0.000160       0.001312        positive  Experiment37Selected
24  Electricity     TimeMixer       96     0.359394      0.000388       0.000724        positive  Experiment37Selected
25  Electricity     TimeMixer      192     0.462375      0.000610       0.000976        positive  Experiment37Selected
26  Electricity     TimeMixer      336     0.854897      0.001205       0.002058        positive  Experiment37Selected
27  Electricity     TimeMixer      720     0.290450     -0.000399       0.001674  nonsignificant  Experiment37Selected
28  Electricity  iTransformer       96     1.466603      0.003057       0.004786        positive    HistoricalRecovery
29  Electricity  iTransformer      192     0.962485      0.001830       0.003459        positive    HistoricalRecovery
30  Electricity  iTransformer      336     1.010948      0.002998       0.004982        positive    HistoricalRecovery
31  Electricity  iTransformer      720     0.089924      0.005771       0.008848        positive    HistoricalRecovery
32     Exchange      PatchTST       96     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
33     Exchange      PatchTST      192     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
34     Exchange      PatchTST      336     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
35     Exchange      PatchTST      720     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
36     Exchange        SegMoE       96     0.000000      0.000000       0.000000  nonsignificant  Experiment37Selected
37     Exchange        SegMoE      192     0.000000      0.000000       0.000000  nonsignificant  Experiment37Selected
38     Exchange        SegMoE      336     0.000000      0.000000       0.000000  nonsignificant  Experiment37Selected
39     Exchange        SegMoE      720     0.000000      0.000000       0.000000  nonsignificant  Experiment37Selected
40     Exchange     TimeMixer       96     1.767956      0.000952       0.002372        positive    HistoricalRecovery
41     Exchange     TimeMixer      192     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
42     Exchange     TimeMixer      336     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
43     Exchange     TimeMixer      720     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
44     Exchange  iTransformer       96     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
45     Exchange  iTransformer      192     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
46     Exchange  iTransformer      336     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
47     Exchange  iTransformer      720     0.000000      0.000000       0.000000  nonsignificant    HistoricalRecovery
48        Solar      PatchTST       96     1.623971     -0.001281       0.007369  nonsignificant    HistoricalRecovery
49        Solar      PatchTST      192     0.557470     -0.001870       0.003871  nonsignificant    HistoricalRecovery
50        Solar      PatchTST      336     1.889864      0.002087       0.005385        positive    HistoricalRecovery
51        Solar      PatchTST      720     2.116875      0.002738       0.006251        positive    HistoricalRecovery
52        Solar        SegMoE       96     3.983484      0.001619       0.013436        positive  Experiment37Selected
53        Solar        SegMoE      192     3.347685      0.000088       0.015300        positive  Experiment37Selected
54        Solar        SegMoE      336    14.495511      0.030525       0.049005        positive  Experiment37Selected
55        Solar        SegMoE      720    30.889498      0.108077       0.132303        positive  Experiment37Selected
56        Solar     TimeMixer       96     2.590790      0.000905       0.009791        positive    HistoricalRecovery
57        Solar     TimeMixer      192     4.150787      0.002735       0.016665        positive    HistoricalRecovery
58        Solar     TimeMixer      336     8.842038      0.016781       0.028967        positive    HistoricalRecovery
59        Solar     TimeMixer      720     5.192945      0.006902       0.019541        positive    HistoricalRecovery
60        Solar  iTransformer       96    10.467056      0.012270       0.030900        positive    HistoricalRecovery
61        Solar  iTransformer      192    12.877345      0.021953       0.041997        positive    HistoricalRecovery
62        Solar  iTransformer      336    13.990738      0.027903       0.043691        positive    HistoricalRecovery
63        Solar  iTransformer      720    10.861391      0.020249       0.035178        positive    HistoricalRecovery
64      Traffic      PatchTST       96     0.039601     -0.000009       0.000326  nonsignificant  Experiment37Selected
65      Traffic      PatchTST      192     0.062740      0.000143       0.000342        positive  Experiment37Selected
66      Traffic      PatchTST      336     0.038198      0.000079       0.000221        positive  Experiment37Selected
67      Traffic      PatchTST      720     0.011700      0.000029       0.000075        positive  Experiment37Selected
68      Traffic        SegMoE       96     0.031860      0.000070       0.000165        positive  Experiment37Selected
69      Traffic        SegMoE      192     0.014381      0.000034       0.000074        positive  Experiment37Selected
70      Traffic        SegMoE      336     0.007935      0.000024       0.000039        positive  Experiment37Selected
71      Traffic        SegMoE      720     0.034355      0.000122       0.000182        positive  Experiment37Selected
72      Traffic     TimeMixer       96     0.107804      0.000101       0.000951        positive  Experiment37Selected
73      Traffic     TimeMixer      192     0.195106      0.000530       0.001470        positive  Experiment37Selected
74      Traffic     TimeMixer      336     0.173904      0.000579       0.001273        positive  Experiment37Selected
75      Traffic     TimeMixer      720    -0.005637     -0.000317       0.000259  nonsignificant  Experiment37Selected
76      Traffic  iTransformer       96     0.344038      0.000970       0.001912        positive  Experiment37Selected
77      Traffic  iTransformer      192     0.160993      0.000121       0.001283        positive  Experiment37Selected
78      Traffic  iTransformer      336    -0.274877     -0.001933      -0.000587        negative  Experiment37Selected
79      Traffic  iTransformer      720     0.366302      0.001189       0.002284        positive  Experiment37Selected
80      Weather      PatchTST       96     1.503275      0.001320       0.003172        positive  Experiment37Selected
81      Weather      PatchTST      192     2.203907      0.003319       0.005325        positive  Experiment37Selected
82      Weather      PatchTST      336     2.267156      0.004242       0.006882        positive  Experiment37Selected
83      Weather      PatchTST      720     2.128003      0.005369       0.008341        positive  Experiment37Selected
84      Weather        SegMoE       96     1.300656      0.001284       0.002508        positive  Experiment37Selected
85      Weather        SegMoE      192     1.953638      0.002821       0.004668        positive  Experiment37Selected
86      Weather        SegMoE      336     2.533652      0.004779       0.007551        positive  Experiment37Selected
87      Weather        SegMoE      720     2.446979      0.006365       0.009370        positive  Experiment37Selected
88      Weather     TimeMixer       96     1.012234      0.001241       0.002063        positive  Experiment37Selected
89      Weather     TimeMixer      192     1.508428      0.002642       0.003721        positive  Experiment37Selected
90      Weather     TimeMixer      336     1.742619      0.003935       0.005290        positive  Experiment37Selected
91      Weather     TimeMixer      720     2.994619      0.008969       0.011685        positive  Experiment37Selected
92      Weather  iTransformer       96     4.201641      0.005587       0.009051        positive  Experiment37Selected
93      Weather  iTransformer      192     4.471502      0.008367       0.012079        positive  Experiment37Selected
94      Weather  iTransformer      336     4.336659      0.010366       0.014490        positive  Experiment37Selected
95      Weather  iTransformer      720     3.809215      0.011818       0.015599        positive  Experiment37Selected

Saved paper-ready CSV and LaTeX table.

/tmp/ipykernel_111196/1286238842.py:37: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  latex.to_latex(