# Experiment 42 — Direct Forecaster Absolute-Performance Audit

This notebook addresses the next reviewer-facing issue:

> The paper reports relative downstream gains, but a reviewer may ask whether the **direct forecasters
> themselves are genuinely strong baselines** and what the corresponding absolute MSE/MAE values are.

No model training is performed here.

## Goals

For the frozen 96 downstream conditions (`6 datasets × 4 backbones × 4 horizons`), recover and report:

- Direct forecaster MSE
- Final historical-memory-integrated MSE
- Absolute MSE difference
- Relative MSE gain
- Direct MAE and Final MAE, if those fields were retained by the original experiments

The notebook produces:

1. a 96-condition absolute-metric CSV,
2. appendix-ready per-dataset/backbone/horizon tables,
3. dataset/backbone mean summaries,
4. a consistency audit verifying that the reported percentage gain matches the absolute MSE values,
5. an explicit missingness report for MAE.

## Interpretation rule

Absolute performance is reported to establish the quality and scale of the frozen direct forecasters.
We do **not** claim new SOTA from this table. The downstream study remains a controlled within-backbone
test of whether historical memory adds value beyond each direct forecaster.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 280)
pd.set_option("display.max_rows", 200)

DATASETS = [
    "Solar",
    "Weather",
    "Electricity",
    "Traffic",
    "Exchange",
    "ETTh1",
]

BACKBONES = [
    "PatchTST",
    "iTransformer",
    "TimeMixer",
    "SegMoE",
]

HORIZONS = [96, 192, 336, 720]

ROOT_CANDIDATES = [
    Path("/data/dataset/strong_forecaster"),
    Path("/data/strong_forecaster"),
]

ROOT = next((p for p in ROOT_CANDIDATES if p.exists()), None)

if ROOT is None:
    raise FileNotFoundError(
        "Could not find strong_forecaster root. Tried:\n"
        + "\n".join(f" - {p}" for p in ROOT_CANDIDATES)
    )

OUT_DIR = ROOT / "direct_forecaster_absolute_performance"
OUT_DIR.mkdir(parents=True, exist_ok=True)

print("ROOT:", ROOT)
print("OUT_DIR:", OUT_DIR)

ROOT: /data/dataset/strong_forecaster
OUT_DIR: /data/dataset/strong_forecaster/direct_forecaster_absolute_performance

## 1. Load the frozen Experiment 37 selected-condition table

In [2]:
preferred = (
    ROOT
    / "four_backbone_dataset_meta_analysis"
    / "condition_level_selected.csv"
)

if preferred.is_file():
    condition_csv = preferred
else:
    hits = sorted(ROOT.rglob("condition_level_selected.csv"))

    hits = [
        p for p in hits
        if "significance_metadata_recovery" not in str(p)
        and "direct_forecaster_absolute_performance" not in str(p)
    ]

    if not hits:
        raise FileNotFoundError(
            "Could not find condition_level_selected.csv. "
            "Run Experiment 37 v3 first."
        )

    condition_csv = hits[0]

print("Using:", condition_csv)

conditions = pd.read_csv(condition_csv)

required = {
    "Dataset",
    "Backbone",
    "Horizon",
    "MSEGain_pct",
}

missing = required - set(conditions.columns)

if missing:
    raise ValueError(
        f"Missing required columns: {sorted(missing)}"
    )

conditions = conditions[
    conditions["Dataset"].isin(DATASETS)
    & conditions["Backbone"].isin(BACKBONES)
    & conditions["Horizon"].astype(int).isin(HORIZONS)
].copy()

conditions["Horizon"] = conditions["Horizon"].astype(int)

KEY = ["Dataset", "Backbone", "Horizon"]

if len(conditions) != 96:
    raise RuntimeError(
        f"Expected 96 selected conditions; found {len(conditions)}."
    )

if conditions.duplicated(KEY).any():
    raise RuntimeError(
        "Duplicate selected conditions found."
    )

print("Columns available:")
for c in conditions.columns:
    print(" -", c)

Using: /data/dataset/strong_forecaster/four_backbone_dataset_meta_analysis/condition_level_selected.csv
Columns available:
 - Dataset
 - Backbone
 - Horizon
 - ProtocolFamily
 - ExperimentFamily
 - Direct_MSE
 - Final_MSE
 - MSEGain_pct
 - Direct_MAE
 - Final_MAE
 - MAEGain_pct
 - FinalMeanAlpha
 - OracleHeadroom_pct
 - ValidationGain_pct
 - CI_Low
 - CI_High
 - SignificantPositive
 - SignificantNegative
 - SourcePath
 - SourceScore
 - RecoveredFamilyBonus
 - FinalSourceScore

## 2. Detect absolute-metric columns

Historical experiment families used slightly different column names.
This cell maps them conservatively.

In [3]:
def find_col(df, candidates):
    lookup = {
        str(c).lower().replace("_", "").replace("-", ""): c
        for c in df.columns
    }

    for name in candidates:
        key = (
            str(name)
            .lower()
            .replace("_", "")
            .replace("-", "")
        )

        if key in lookup:
            return lookup[key]

    return None


ALIASES = {
    "DirectMSE": [
        "DirectMSE",
        "Direct_MSE",
        "BaselineMSE",
        "BaseMSE",
        "MSE_Direct",
        "DirectTestMSE",
    ],
    "FinalMSE": [
        "FinalMSE",
        "Final_MSE",
        "ShrinkAdaptiveMSE",
        "AdaptiveMSE",
        "OursMSE",
        "MSE_Final",
        "FinalTestMSE",
    ],
    "DirectMAE": [
        "DirectMAE",
        "Direct_MAE",
        "BaselineMAE",
        "BaseMAE",
        "MAE_Direct",
        "DirectTestMAE",
    ],
    "FinalMAE": [
        "FinalMAE",
        "Final_MAE",
        "ShrinkAdaptiveMAE",
        "AdaptiveMAE",
        "OursMAE",
        "MAE_Final",
        "FinalTestMAE",
    ],
}

detected = {
    canonical: find_col(
        conditions,
        candidates,
    )
    for canonical, candidates in ALIASES.items()
}

print("Detected metric columns:")
for k, v in detected.items():
    print(f" - {k}: {v}")

Detected metric columns:
 - DirectMSE: Direct_MSE
 - FinalMSE: Final_MSE
 - DirectMAE: Direct_MAE
 - FinalMAE: Final_MAE

## 3. Build a first-pass absolute-metric table from Experiment 37

If MSE fields are already present, no provenance search is needed for those conditions.
If they are missing, the next section searches historical CSV artifacts.

In [4]:
absolute = conditions[KEY + ["MSEGain_pct"]].copy()

for canonical, source_col in detected.items():
    if source_col is None:
        absolute[canonical] = np.nan
    else:
        absolute[canonical] = pd.to_numeric(
            conditions[source_col],
            errors="coerce",
        )

absolute["MSESource"] = np.where(
    absolute["DirectMSE"].notna()
    & absolute["FinalMSE"].notna(),
    "Experiment37Selected",
    "Missing",
)

absolute["MAESource"] = np.where(
    absolute["DirectMAE"].notna()
    & absolute["FinalMAE"].notna(),
    "Experiment37Selected",
    "Missing",
)

print(
    "MSE pairs already present:",
    int(
        (
            absolute["DirectMSE"].notna()
            & absolute["FinalMSE"].notna()
        ).sum()
    ),
    "/96",
)

print(
    "MAE pairs already present:",
    int(
        (
            absolute["DirectMAE"].notna()
            & absolute["FinalMAE"].notna()
        ).sum()
    ),
    "/96",
)

display(
    absolute.sort_values(KEY).head(24)
)

MSE pairs already present: 72 /96
MAE pairs already present: 72 /96

        Dataset      Backbone  Horizon  MSEGain_pct  DirectMSE  FinalMSE  DirectMAE  FinalMAE             MSESource             MAESource
0         ETTh1      PatchTST       96    -1.090730   0.378632       NaN   0.400303       NaN               Missing               Missing
1         ETTh1      PatchTST      192    -1.676780   0.413694       NaN   0.420978       NaN               Missing               Missing
2         ETTh1      PatchTST      336    -1.466894   0.441984       NaN   0.441434       NaN               Missing               Missing
3         ETTh1      PatchTST      720    -3.931421   0.461510       NaN   0.473867       NaN               Missing               Missing
4         ETTh1        SegMoE       96    -1.052852   0.429677  0.434201   0.437933  0.441780  Experiment37Selected  Experiment37Selected
5         ETTh1        SegMoE      192    -2.264470   0.481695  0.492603   0.473062  0.480069  Experiment37Selected  Experiment37Selected
6         ETTh1        SegMoE      336    -2.288568   0.535394  0.547647   0.505612  0.512787  Experiment37Selected  Experiment37Selected
7         ETTh1        SegMoE      720    -6.796243   0.657350  0.702025   0.571758  0.593895  Experiment37Selected  Experiment37Selected
8         ETTh1     TimeMixer       96    -0.567222   0.388839       NaN   0.402163       NaN               Missing               Missing
9         ETTh1     TimeMixer      192    -0.640128   0.442255       NaN   0.429601       NaN               Missing               Missing
10        ETTh1     TimeMixer      336    -1.529878   0.517918       NaN   0.474665       NaN               Missing               Missing
11        ETTh1     TimeMixer      720    -6.298939   0.512187       NaN   0.484744       NaN               Missing               Missing
12        ETTh1  iTransformer       96    -0.504197   0.392303       NaN   0.407334       NaN               Missing               Missing
13        ETTh1  iTransformer      192    -1.458748   0.442639       NaN   0.434737       NaN               Missing               Missing
14        ETTh1  iTransformer      336    -1.785874   0.489263       NaN   0.461457       NaN               Missing               Missing
15        ETTh1  iTransformer      720    -5.876001   0.506507       NaN   0.492894       NaN               Missing               Missing
32  Electricity      PatchTST       96     0.839606   0.129638  0.128549   0.222790  0.222718  Experiment37Selected  Experiment37Selected
33  Electricity      PatchTST      192     0.445810   0.148802  0.148138   0.242637  0.242954  Experiment37Selected  Experiment37Selected
34  Electricity      PatchTST      336     0.820887   0.165312  0.163955   0.259284  0.259330  Experiment37Selected  Experiment37Selected
35  Electricity      PatchTST      720    -0.672307   0.202859  0.204223   0.291769  0.293104  Experiment37Selected  Experiment37Selected
36  Electricity        SegMoE       96     0.519435   0.131053  0.130373   0.225169  0.225389  Experiment37Selected  Experiment37Selected
37  Electricity        SegMoE      192     0.278683   0.148784  0.148369   0.242053  0.242182  Experiment37Selected  Experiment37Selected
38  Electricity        SegMoE      336     0.293029   0.166729  0.166240   0.261269  0.261459  Experiment37Selected  Experiment37Selected
39  Electricity        SegMoE      720     0.347162   0.210921  0.210188   0.301344  0.302073  Experiment37Selected  Experiment37Selected

## 4. Recover missing absolute metrics from historical CSV artifacts

This search is only a recovery pass. It excludes meta-analysis/recovery outputs to avoid circular provenance.

A historical row is eligible only if it contains an unambiguous dataset, backbone, horizon, and
Direct/Final metric pair.

In [5]:
def canon_dataset(x):
    s = str(x).strip().lower().replace("-", "").replace("_", "")

    return {
        "solar": "Solar",
        "solarenergy": "Solar",
        "weather": "Weather",
        "electricity": "Electricity",
        "ecl": "Electricity",
        "traffic": "Traffic",
        "exchange": "Exchange",
        "exchangerate": "Exchange",
        "etth1": "ETTh1",
    }.get(s, str(x).strip())


def canon_backbone(x):
    s = str(x).strip().lower().replace("-", "").replace("_", "")

    return {
        "patchtst": "PatchTST",
        "itransformer": "iTransformer",
        "timemixer": "TimeMixer",
        "segmoe": "SegMoE",
        "segmoeforecast": "SegMoE",
    }.get(s, str(x).strip())


def excluded_path(p):
    s = str(p)

    banned = [
        "four_backbone_dataset_meta_analysis/",
        "significance_metadata_recovery",
        "direct_forecaster_absolute_performance/",
    ]

    return any(token in s for token in banned)


historical_rows = []

for p in ROOT.rglob("*.csv"):
    if excluded_path(p):
        continue

    try:
        if p.stat().st_size > 500 * 1024 * 1024:
            continue
    except Exception:
        continue

    try:
        df = pd.read_csv(p)
    except Exception:
        continue

    c_dataset = find_col(
        df,
        ["Dataset", "Data"],
    )

    c_backbone = find_col(
        df,
        ["Backbone", "Model"],
    )

    c_horizon = find_col(
        df,
        ["Horizon", "PredLen", "pred_len", "H"],
    )

    c_direct_mse = find_col(
        df,
        ALIASES["DirectMSE"],
    )

    c_final_mse = find_col(
        df,
        ALIASES["FinalMSE"],
    )

    if None in {
        c_dataset,
        c_backbone,
        c_horizon,
        c_direct_mse,
        c_final_mse,
    }:
        continue

    c_direct_mae = find_col(
        df,
        ALIASES["DirectMAE"],
    )

    c_final_mae = find_col(
        df,
        ALIASES["FinalMAE"],
    )

    for idx, r in df.iterrows():
        dataset = canon_dataset(
            r[c_dataset]
        )

        backbone = canon_backbone(
            r[c_backbone]
        )

        try:
            horizon = int(
                r[c_horizon]
            )
        except Exception:
            continue

        if dataset not in DATASETS:
            continue

        if backbone not in BACKBONES:
            continue

        if horizon not in HORIZONS:
            continue

        dmse = pd.to_numeric(
            pd.Series([r[c_direct_mse]]),
            errors="coerce",
        ).iloc[0]

        fmse = pd.to_numeric(
            pd.Series([r[c_final_mse]]),
            errors="coerce",
        ).iloc[0]

        if pd.isna(dmse) or pd.isna(fmse):
            continue

        dmae = (
            pd.to_numeric(
                pd.Series([r[c_direct_mae]]),
                errors="coerce",
            ).iloc[0]
            if c_direct_mae is not None
            else np.nan
        )

        fmae = (
            pd.to_numeric(
                pd.Series([r[c_final_mae]]),
                errors="coerce",
            ).iloc[0]
            if c_final_mae is not None
            else np.nan
        )

        historical_rows.append({
            "Dataset": dataset,
            "Backbone": backbone,
            "Horizon": horizon,
            "DirectMSE_recovered": dmse,
            "FinalMSE_recovered": fmse,
            "DirectMAE_recovered": dmae,
            "FinalMAE_recovered": fmae,
            "RecoverySource": str(p),
            "RecoveryRow": int(idx),
        })

historical = pd.DataFrame(
    historical_rows,
    columns=[
        "Dataset",
        "Backbone",
        "Horizon",
        "DirectMSE_recovered",
        "FinalMSE_recovered",
        "DirectMAE_recovered",
        "FinalMAE_recovered",
        "RecoverySource",
        "RecoveryRow",
    ],
)

print(
    "Historical candidate rows:",
    len(historical),
)

if len(historical):
    display(
        historical.sort_values(KEY).head(100)
    )

Historical candidate rows: 229

         Dataset      Backbone  Horizon  DirectMSE_recovered  FinalMSE_recovered  DirectMAE_recovered  FinalMAE_recovered                                     RecoverySource  RecoveryRow
37         ETTh1      PatchTST       96             0.378632            0.382762             0.400303            0.405032  /data/dataset/strong_forecaster/three_backbone...           12
73         ETTh1      PatchTST       96             0.378632            0.382762             0.400303            0.405032  /data/dataset/strong_forecaster/three_backbone...           12
121        ETTh1      PatchTST       96             0.378632            0.382762             0.400303            0.405032  /data/dataset/strong_forecaster/cross_backbone...            8
145        ETTh1      PatchTST       96             0.378632            0.382762             0.400303            0.405032  /data/dataset/strong_forecaster/cross_backbone...            8
40         ETTh1      PatchTST      192             0.413694            0.420631             0.420978            0.429180  /data/dataset/strong_forecaster/three_backbone...           15
76         ETTh1      PatchTST      192             0.413694            0.420631             0.420978            0.429180  /data/dataset/strong_forecaster/three_backbone...           15
123        ETTh1      PatchTST      192             0.413694            0.420631             0.420978            0.429180  /data/dataset/strong_forecaster/cross_backbone...           10
147        ETTh1      PatchTST      192             0.413694            0.420631             0.420978            0.429180  /data/dataset/strong_forecaster/cross_backbone...           10
43         ETTh1      PatchTST      336             0.441984            0.448468             0.441434            0.448939  /data/dataset/strong_forecaster/three_backbone...           18
79         ETTh1      PatchTST      336             0.441984            0.448468             0.441434            0.448939  /data/dataset/strong_forecaster/three_backbone...           18
125        ETTh1      PatchTST      336             0.441984            0.448468             0.441434            0.448939  /data/dataset/strong_forecaster/cross_backbone...           12
149        ETTh1      PatchTST      336             0.441984            0.448468             0.441434            0.448939  /data/dataset/strong_forecaster/cross_backbone...           12
46         ETTh1      PatchTST      720             0.461510            0.479654             0.473867            0.489601  /data/dataset/strong_forecaster/three_backbone...           21
82         ETTh1      PatchTST      720             0.461510            0.479654             0.473867            0.489601  /data/dataset/strong_forecaster/three_backbone...           21
127        ETTh1      PatchTST      720             0.461510            0.479654             0.473867            0.489601  /data/dataset/strong_forecaster/cross_backbone...           14
151        ETTh1      PatchTST      720             0.461510            0.479654             0.473867            0.489601  /data/dataset/strong_forecaster/cross_backbone...           14
24         ETTh1     TimeMixer       96             0.388839            0.391045             0.402163            0.404818  /data/dataset/strong_forecaster/three_backbone...            7
39         ETTh1     TimeMixer       96             0.388839            0.391045             0.402163            0.404818  /data/dataset/strong_forecaster/three_backbone...           14
75         ETTh1     TimeMixer       96             0.388839            0.391045             0.402163            0.404818  /data/dataset/strong_forecaster/three_backbone...           14
42         ETTh1     TimeMixer      192             0.442255            0.445086             0.429601            0.435802  /data/dataset/strong_forecaster/three_backbone...           17
78         ETTh1     TimeMixer      192             0.442255            0.445086             0.429601            0.435802  /data/dataset/strong_forecaster/three_backbone...           17
45         ETTh1     TimeMixer      336             0.517918            0.525842             0.474665            0.484048  /data/dataset/strong_forecaster/three_backbone...           20
81         ETTh1     TimeMixer      336             0.517918            0.525842             0.474665            0.484048  /data/dataset/strong_forecaster/three_backbone...           20
48         ETTh1     TimeMixer      720             0.512187            0.544449             0.484744            0.513554  /data/dataset/strong_forecaster/three_backbone...           23
84         ETTh1     TimeMixer      720             0.512187            0.544449             0.484744            0.513554  /data/dataset/strong_forecaster/three_backbone...           23
38         ETTh1  iTransformer       96             0.392303            0.394281             0.407334            0.410792  /data/dataset/strong_forecaster/three_backbone...           13
74         ETTh1  iTransformer       96             0.392303            0.394281             0.407334            0.410792  /data/dataset/strong_forecaster/three_backbone...           13
122        ETTh1  iTransformer       96             0.392303            0.394281             0.407334            0.410792  /data/dataset/strong_forecaster/cross_backbone...            9
146        ETTh1  iTransformer       96             0.392303            0.394281             0.407334            0.410792  /data/dataset/strong_forecaster/cross_backbone...            9
41         ETTh1  iTransformer      192             0.442639            0.449096             0.434737            0.442669  /data/dataset/strong_forecaster/three_backbone...           16
77         ETTh1  iTransformer      192             0.442639            0.449096             0.434737            0.442669  /data/dataset/strong_forecaster/three_backbone...           16
124        ETTh1  iTransformer      192             0.442639            0.449096             0.434737            0.442669  /data/dataset/strong_forecaster/cross_backbone...           11
148        ETTh1  iTransformer      192             0.442639            0.449096             0.434737            0.442669  /data/dataset/strong_forecaster/cross_backbone...           11
44         ETTh1  iTransformer      336             0.489263            0.498000             0.461457            0.473326  /data/dataset/strong_forecaster/three_backbone...           19
80         ETTh1  iTransformer      336             0.489263            0.498000             0.461457            0.473326  /data/dataset/strong_forecaster/three_backbone...           19
126        ETTh1  iTransformer      336             0.489263            0.498000             0.461457            0.473326  /data/dataset/strong_forecaster/cross_backbone...           13
150        ETTh1  iTransformer      336             0.489263            0.498000             0.461457            0.473326  /data/dataset/strong_forecaster/cross_backbone...           13
47         ETTh1  iTransformer      720             0.506507            0.536269             0.492894            0.515912  /data/dataset/strong_forecaster/three_backbone...           22
83         ETTh1  iTransformer      720             0.506507            0.536269             0.492894            0.515912  /data/dataset/strong_forecaster/three_backbone...           22
128        ETTh1  iTransformer      720             0.506507            0.536269             0.492894            0.515912  /data/dataset/strong_forecaster/cross_backbone...           15
152        ETTh1  iTransformer      720             0.506507            0.536269             0.492894            0.515912  /data/dataset/strong_forecaster/cross_backbone...           15
25   Electricity      PatchTST       96             0.129977            0.129218             0.222527            0.222631  /data/dataset/strong_forecaster/three_backbone...            8
61   Electricity      PatchTST       96             0.129977            0.129218             0.222527            0.222631  /data/dataset/strong_forecaster/three_backbone...           36
97   Electricity      PatchTST       96             0.129977            0.129218             0.222527            0.222631  /data/dataset/strong_forecaster/three_backbone...           36
137  Electricity      PatchTST       96             0.129977            0.129218             0.222527            0.222631  /data/dataset/strong_forecaster/cross_backbone...           24
161  Electricity      PatchTST       96             0.129977            0.129218             0.222527            0.222631  /data/dataset/strong_forecaster/cross_backbone...           24
169  Electricity      PatchTST       96             0.146149            0.144746             0.242762            0.242602  /data/dataset/strong_forecaster/relevance_to_f...            0
217  Electricity      PatchTST       96             0.146149            0.144746             0.242762            0.242602  /data/dataset/strong_forecaster/electricity_th...            0
28   Electricity      PatchTST      192             0.149116            0.148559             0.242038            0.242267  /data/dataset/strong_forecaster/three_backbone...           11
64   Electricity      PatchTST      192             0.149116            0.148559             0.242038            0.242267  /data/dataset/strong_forecaster/three_backbone...           39
100  Electricity      PatchTST      192             0.149116            0.148559             0.242038            0.242267  /data/dataset/strong_forecaster/three_backbone...           39
139  Electricity      PatchTST      192             0.149116            0.148559             0.242038            0.242267  /data/dataset/strong_forecaster/cross_backbone...           26
163  Electricity      PatchTST      192             0.149116            0.148559             0.242038            0.242267  /data/dataset/strong_forecaster/cross_backbone...           26
170  Electricity      PatchTST      192             0.162966            0.162657             0.257936            0.258320  /data/dataset/strong_forecaster/relevance_to_f...            1
218  Electricity      PatchTST      192             0.162966            0.162657             0.257936            0.258320  /data/dataset/strong_forecaster/electricity_th...            1
31   Electricity      PatchTST      336             0.165690            0.164748             0.258694            0.259026  /data/dataset/strong_forecaster/three_backbone...           14
67   Electricity      PatchTST      336             0.165690            0.164748             0.258694            0.259026  /data/dataset/strong_forecaster/three_backbone...           42
103  Electricity      PatchTST      336             0.165690            0.164748             0.258694            0.259026  /data/dataset/strong_forecaster/three_backbone...           42
141  Electricity      PatchTST      336             0.165690            0.164748             0.258694            0.259026  /data/dataset/strong_forecaster/cross_backbone...           28
165  Electricity      PatchTST      336             0.165690            0.164748             0.258694            0.259026  /data/dataset/strong_forecaster/cross_backbone...           28
171  Electricity      PatchTST      336             0.182240            0.182183             0.277606            0.278836  /data/dataset/strong_forecaster/relevance_to_f...            2
219  Electricity      PatchTST      336             0.182240            0.182183             0.277606            0.278836  /data/dataset/strong_forecaster/electricity_th...            2
34   Electricity      PatchTST      720             0.203216            0.202541             0.292492            0.293962  /data/dataset/strong_forecaster/three_backbone...           17
70   Electricity      PatchTST      720             0.203216            0.202541             0.292492            0.293962  /data/dataset/strong_forecaster/three_backbone...           45
106  Electricity      PatchTST      720             0.203216            0.202541             0.292492            0.293962  /data/dataset/strong_forecaster/three_backbone...           45
143  Electricity      PatchTST      720             0.203216            0.202541             0.292492            0.293962  /data/dataset/strong_forecaster/cross_backbone...           30
167  Electricity      PatchTST      720             0.203216            0.202541             0.292492            0.293962  /data/dataset/strong_forecaster/cross_backbone...           30
172  Electricity      PatchTST      720             0.221973            0.222322             0.315620            0.318150  /data/dataset/strong_forecaster/relevance_to_f...            3
220  Electricity      PatchTST      720             0.221973            0.222322             0.315620            0.318150  /data/dataset/strong_forecaster/electricity_th...            3
27   Electricity     TimeMixer       96             0.153008            0.152757             0.245195            0.245418  /data/dataset/strong_forecaster/three_backbone...           10
63   Electricity     TimeMixer       96             0.153008            0.152757             0.245195            0.245418  /data/dataset/strong_forecaster/three_backbone...           38
99   Electricity     TimeMixer       96             0.153008            0.152757             0.245195            0.245418  /data/dataset/strong_forecaster/three_backbone...           38
173  Electricity     TimeMixer       96             0.172401            0.170351             0.265073            0.264429  /data/dataset/strong_forecaster/relevance_to_f...            4
221  Electricity     TimeMixer       96             0.172401            0.170351             0.265073            0.264429  /data/dataset/strong_forecaster/electricity_th...            4
30   Electricity     TimeMixer      192             0.167578            0.166584             0.257219            0.257526  /data/dataset/strong_forecaster/three_backbone...           13
66   Electricity     TimeMixer      192             0.167578            0.166584             0.257219            0.257526  /data/dataset/strong_forecaster/three_backbone...           41
102  Electricity     TimeMixer      192             0.167578            0.166584             0.257219            0.257526  /data/dataset/strong_forecaster/three_backbone...           41
174  Electricity     TimeMixer      192             0.177572            0.176864             0.271930            0.272231  /data/dataset/strong_forecaster/relevance_to_f...            5
222  Electricity     TimeMixer      192             0.177572            0.176864             0.271930            0.272231  /data/dataset/strong_forecaster/electricity_th...            5
33   Electricity     TimeMixer      336             0.186218            0.184431             0.275052            0.275120  /data/dataset/strong_forecaster/three_backbone...           16
69   Electricity     TimeMixer      336             0.186218            0.184431             0.275052            0.275120  /data/dataset/strong_forecaster/three_backbone...           44
105  Electricity     TimeMixer      336             0.186218            0.184431             0.275052            0.275120  /data/dataset/strong_forecaster/three_backbone...           44
175  Electricity     TimeMixer      336             0.198305            0.195778             0.291694            0.291688  /data/dataset/strong_forecaster/relevance_to_f...            6
223  Electricity     TimeMixer      336             0.198305            0.195778             0.291694            0.291688  /data/dataset/strong_forecaster/electricity_th...            6
36   Electricity     TimeMixer      720             0.224731            0.223184             0.312808            0.313286  /data/dataset/strong_forecaster/three_backbone...           19
72   Electricity     TimeMixer      720             0.224731            0.223184             0.312808            0.313286  /data/dataset/strong_forecaster/three_backbone...           47
108  Electricity     TimeMixer      720             0.224731            0.223184             0.312808            0.313286  /data/dataset/strong_forecaster/three_backbone...           47
176  Electricity     TimeMixer      720             0.243714            0.241618             0.331814            0.332615  /data/dataset/strong_forecaster/relevance_to_f...            7
224  Electricity     TimeMixer      720             0.243714            0.241618             0.331814            0.332615  /data/dataset/strong_forecaster/electricity_th...            7
26   Electricity  iTransformer       96             0.148275            0.146310             0.239707            0.239500  /data/dataset/strong_forecaster/three_backbone...            9
62   Electricity  iTransformer       96             0.148275            0.146310             0.239707            0.239500  /data/dataset/strong_forecaster/three_backbone...           37
98   Electricity  iTransformer       96             0.148275            0.146310             0.239707            0.239500  /data/dataset/strong_forecaster/three_backbone...           37
138  Electricity  iTransformer       96             0.148275            0.146310             0.239707            0.239500  /data/dataset/strong_forecaster/cross_backbone...           25
162  Electricity  iTransformer       96             0.148275            0.146310             0.239707            0.239500  /data/dataset/strong_forecaster/cross_backbone...           25
177  Electricity  iTransformer       96             0.179823            0.175950             0.268907            0.267909  /data/dataset/strong_forecaster/relevance_to_f...            8
225  Electricity  iTransformer       96             0.179823            0.175950             0.268907            0.267909  /data/dataset/strong_forecaster/electricity_th...            8
29   Electricity  iTransformer      192             0.165101            0.164833             0.256106            0.257408  /data/dataset/strong_forecaster/three_backbone...           12
65   Electricity  iTransformer      192             0.165101            0.164833             0.256106            0.257408  /data/dataset/strong_forecaster/three_backbone...           40
101  Electricity  iTransformer      192             0.165101            0.164833             0.256106            0.257408  /data/dataset/strong_forecaster/three_backbone...           40
140  Electricity  iTransformer      192             0.165101            0.164833             0.256106            0.257408  /data/dataset/strong_forecaster/cross_backbone...           27

## 5. Resolve historical duplicates by consistency with frozen MSEGain_pct

For each candidate metric pair,

\[
100\frac{\mathrm{DirectMSE}-\mathrm{FinalMSE}}
{\mathrm{DirectMSE}}
\]

must match the frozen Experiment 37 `MSEGain_pct`.

We therefore select the candidate with the smallest absolute gain mismatch.
This avoids relying on directory names alone.

In [6]:
gain_lookup = absolute.set_index(KEY)["MSEGain_pct"].to_dict()

resolved_rows = []

if len(historical):
    for key, g in historical.groupby(KEY):
        frozen_gain = gain_lookup.get(
            key,
            np.nan,
        )

        g = g.copy()

        g["RecoveredGain_pct"] = (
            (
                g["DirectMSE_recovered"]
                - g["FinalMSE_recovered"]
            )
            / g["DirectMSE_recovered"]
            * 100.0
        )

        g["GainMismatch"] = (
            g["RecoveredGain_pct"]
            - frozen_gain
        ).abs()

        g["PathLen"] = g["RecoverySource"].map(len)

        g = g.sort_values(
            [
                "GainMismatch",
                "PathLen",
                "RecoverySource",
            ]
        )

        resolved_rows.append(
            g.iloc[0].to_dict()
        )

recovered = pd.DataFrame(
    resolved_rows
)

print(
    "Resolved historical conditions:",
    len(recovered),
)

if len(recovered):
    display(
        recovered.sort_values(KEY).head(96)
    )

Resolved historical conditions: 72

        Dataset      Backbone  Horizon  DirectMSE_recovered  FinalMSE_recovered  DirectMAE_recovered  FinalMAE_recovered                                     RecoverySource  RecoveryRow  RecoveredGain_pct  GainMismatch  PathLen
0         ETTh1      PatchTST       96             0.378632            0.382762             0.400303            0.405032  /data/dataset/strong_forecaster/cross_backbone...            8          -1.090730  0.000000e+00      100
1         ETTh1      PatchTST      192             0.413694            0.420631             0.420978            0.429180  /data/dataset/strong_forecaster/cross_backbone...           10          -1.676780  0.000000e+00      100
2         ETTh1      PatchTST      336             0.441984            0.448468             0.441434            0.448939  /data/dataset/strong_forecaster/cross_backbone...           12          -1.466894  2.220446e-16      100
3         ETTh1      PatchTST      720             0.461510            0.479654             0.473867            0.489601  /data/dataset/strong_forecaster/cross_backbone...           14          -3.931421  0.000000e+00      100
4         ETTh1     TimeMixer       96             0.388839            0.391045             0.402163            0.404818  /data/dataset/strong_forecaster/three_backbone...            7          -0.567222  0.000000e+00       97
5         ETTh1     TimeMixer      192             0.442255            0.445086             0.429601            0.435802  /data/dataset/strong_forecaster/three_backbone...           17          -0.640128  0.000000e+00      100
6         ETTh1     TimeMixer      336             0.517918            0.525842             0.474665            0.484048  /data/dataset/strong_forecaster/three_backbone...           20          -1.529878  2.220446e-16      100
7         ETTh1     TimeMixer      720             0.512187            0.544449             0.484744            0.513554  /data/dataset/strong_forecaster/three_backbone...           23          -6.298939  8.881784e-16      100
8         ETTh1  iTransformer       96             0.392303            0.394281             0.407334            0.410792  /data/dataset/strong_forecaster/cross_backbone...            9          -0.504197  0.000000e+00      100
9         ETTh1  iTransformer      192             0.442639            0.449096             0.434737            0.442669  /data/dataset/strong_forecaster/cross_backbone...           11          -1.458748  0.000000e+00      100
10        ETTh1  iTransformer      336             0.489263            0.498000             0.461457            0.473326  /data/dataset/strong_forecaster/cross_backbone...           13          -1.785874  0.000000e+00      100
11        ETTh1  iTransformer      720             0.506507            0.536269             0.492894            0.515912  /data/dataset/strong_forecaster/cross_backbone...           15          -5.876001  8.881784e-16      100
12  Electricity      PatchTST       96             0.146149            0.144746             0.242762            0.242602  /data/dataset/strong_forecaster/relevance_to_f...            0           0.959915  1.203090e-01       92
13  Electricity      PatchTST      192             0.149116            0.148559             0.242038            0.242267  /data/dataset/strong_forecaster/three_backbone...           11           0.373992  7.181783e-02       97
14  Electricity      PatchTST      336             0.165690            0.164748             0.258694            0.259026  /data/dataset/strong_forecaster/three_backbone...           14           0.568902  2.519845e-01       97
15  Electricity      PatchTST      720             0.221973            0.222322             0.315620            0.318150  /data/dataset/strong_forecaster/relevance_to_f...            3          -0.157246  5.150608e-01       92
16  Electricity     TimeMixer       96             0.153008            0.152757             0.245195            0.245418  /data/dataset/strong_forecaster/three_backbone...           10           0.164148  1.952463e-01       97
17  Electricity     TimeMixer      192             0.177572            0.176864             0.271930            0.272231  /data/dataset/strong_forecaster/relevance_to_f...            5           0.398798  6.357643e-02       92
18  Electricity     TimeMixer      336             0.186218            0.184431             0.275052            0.275120  /data/dataset/strong_forecaster/three_backbone...           16           0.959694  1.047973e-01       97
19  Electricity     TimeMixer      720             0.224731            0.223184             0.312808            0.313286  /data/dataset/strong_forecaster/three_backbone...           19           0.688475  3.980242e-01       97
20  Electricity  iTransformer       96             0.148275            0.146310             0.239707            0.239500  /data/dataset/strong_forecaster/three_backbone...            9           1.325576  1.410271e-01       97
21  Electricity  iTransformer      192             0.186433            0.183813             0.275288            0.276009  /data/dataset/strong_forecaster/relevance_to_f...            9           1.405222  4.427373e-01       92
22  Electricity  iTransformer      336             0.179687            0.178503             0.272384            0.273237  /data/dataset/strong_forecaster/three_backbone...           15           0.659223  3.517244e-01       97
23  Electricity  iTransformer      720             0.217054            0.215217             0.304202            0.305317  /data/dataset/strong_forecaster/three_backbone...           18           0.845958  7.560341e-01       97
24     Exchange      PatchTST       96             0.088792            0.088792             0.208818            0.208818  /data/dataset/strong_forecaster/exchange_three...            0           0.000000  0.000000e+00       92
25     Exchange      PatchTST      192             0.194937            0.194937             0.316183            0.316183  /data/dataset/strong_forecaster/exchange_three...            1           0.000000  0.000000e+00       92
26     Exchange      PatchTST      336             0.346291            0.346291             0.428873            0.428873  /data/dataset/strong_forecaster/exchange_three...            2           0.000000  0.000000e+00       92
27     Exchange      PatchTST      720             0.858390            0.858390             0.692987            0.692987  /data/dataset/strong_forecaster/exchange_three...            3           0.000000  0.000000e+00       92
28     Exchange     TimeMixer       96             0.092543            0.090907             0.210600            0.208730  /data/dataset/strong_forecaster/exchange_three...            4           1.767956  4.507505e-14       92
29     Exchange     TimeMixer      192             0.177509            0.177509             0.299693            0.299693  /data/dataset/strong_forecaster/exchange_three...            5           0.000000  0.000000e+00       92
30     Exchange     TimeMixer      336             0.329322            0.329322             0.417432            0.417432  /data/dataset/strong_forecaster/exchange_three...            6           0.000000  0.000000e+00       92
31     Exchange     TimeMixer      720             1.149432            1.149432             0.800125            0.800125  /data/dataset/strong_forecaster/exchange_three...            7           0.000000  0.000000e+00       92
32     Exchange  iTransformer       96             0.098471            0.098471             0.223430            0.223430  /data/dataset/strong_forecaster/exchange_three...            8           0.000000  0.000000e+00       92
33     Exchange  iTransformer      192             0.182288            0.182288             0.305967            0.305967  /data/dataset/strong_forecaster/exchange_three...            9           0.000000  0.000000e+00       92
34     Exchange  iTransformer      336             0.346023            0.346023             0.426120            0.426120  /data/dataset/strong_forecaster/exchange_three...           10           0.000000  0.000000e+00       92
35     Exchange  iTransformer      720             0.832304            0.832304             0.690283            0.690283  /data/dataset/strong_forecaster/exchange_three...           11           0.000000  0.000000e+00       92
36        Solar      PatchTST       96             0.183429            0.180450             0.246145            0.243917  /data/dataset/strong_forecaster/solar_three_ba...            0           1.623971  3.019807e-14       89
37        Solar      PatchTST      192             0.188770            0.187718             0.240918            0.241148  /data/dataset/strong_forecaster/solar_three_ba...            1           0.557470  1.454392e-14       89
38        Solar      PatchTST      336             0.199593            0.195821             0.253637            0.250760  /data/dataset/strong_forecaster/solar_three_ba...            2           1.889864  0.000000e+00       89
39        Solar      PatchTST      720             0.213913            0.209384             0.260529            0.258027  /data/dataset/strong_forecaster/solar_three_ba...            3           2.116875  3.952394e-14       89
40        Solar     TimeMixer       96             0.195299            0.190239             0.241748            0.242083  /data/dataset/strong_forecaster/solar_three_ba...            4           2.590790  2.753353e-14       89
41        Solar     TimeMixer      192             0.228547            0.219061             0.269627            0.269107  /data/dataset/strong_forecaster/solar_three_ba...            5           4.150787  3.463896e-14       89
42        Solar     TimeMixer      336             0.255755            0.233141             0.288708            0.280964  /data/dataset/strong_forecaster/solar_three_ba...            6           8.842038  1.065814e-14       89
43        Solar     TimeMixer      720             0.253337            0.240181             0.286785            0.284330  /data/dataset/strong_forecaster/solar_three_ba...            7           5.192945  8.881784e-16       89
44        Solar  iTransformer       96             0.204083            0.182722             0.229920            0.228564  /data/dataset/strong_forecaster/solar_three_ba...            8          10.467056  0.000000e+00       89
45        Solar  iTransformer      192             0.244628            0.213126             0.263545            0.257533  /data/dataset/strong_forecaster/solar_three_ba...            9          12.877345  3.552714e-14       89
46        Solar  iTransformer      336             0.252072            0.216806             0.275291            0.265086  /data/dataset/strong_forecaster/solar_three_ba...           10          13.990738  2.131628e-14       89
47        Solar  iTransformer      720             0.252617            0.225179             0.275918            0.269137  /data/dataset/strong_forecaster/solar_three_ba...           11          10.861391  3.552714e-15       89
48      Traffic      PatchTST       96             0.424770            0.424145             0.270405            0.271309  /data/dataset/strong_forecaster/traffic_three_...            0           0.147163  1.075625e-01       91
49      Traffic      PatchTST      192             0.449518            0.448541             0.283630            0.283588  /data/dataset/strong_forecaster/traffic_three_...            1           0.217261  1.545209e-01       91
50      Traffic      PatchTST      336             0.489704            0.489129             0.299996            0.299841  /data/dataset/strong_forecaster/traffic_three_...            2           0.117494  7.929604e-02       91
51      Traffic      PatchTST      720             0.534620            0.534620             0.319903            0.319903  /data/dataset/strong_forecaster/traffic_three_...            3           0.000000  1.170005e-02       91
52      Traffic     TimeMixer       96             0.523414            0.523134             0.317731            0.317323  /data/dataset/strong_forecaster/traffic_three_...            4           0.053427  5.437709e-02       91
53      Traffic     TimeMixer      192             0.529957            0.529489             0.319745            0.319203  /data/dataset/strong_forecaster/traffic_three_...            5           0.088391  1.067142e-01       91
54      Traffic     TimeMixer      336             0.553444            0.553297             0.322842            0.322933  /data/dataset/strong_forecaster/traffic_three_...            6           0.026706  1.471982e-01       91
55      Traffic     TimeMixer      720             0.593822            0.593968             0.340982            0.341181  /data/dataset/strong_forecaster/traffic_three_...            7          -0.024633  1.899575e-02       91
56      Traffic  iTransformer       96             0.469074            0.466365             0.298172            0.295218  /data/dataset/strong_forecaster/traffic_three_...            8           0.577442  2.334039e-01       91
57      Traffic  iTransformer      192             0.487141            0.485127             0.304176            0.300709  /data/dataset/strong_forecaster/traffic_three_...            9           0.413422  2.524283e-01       91
58      Traffic  iTransformer      336             0.516307            0.513955             0.311595            0.309725  /data/dataset/strong_forecaster/traffic_three_...           10           0.455558  7.304351e-01       91
59      Traffic  iTransformer      720             0.558694            0.557582             0.331070            0.330294  /data/dataset/strong_forecaster/traffic_three_...           11           0.198942  1.673594e-01       91
60      Weather      PatchTST       96             0.149690            0.147440             0.197816            0.196418  /data/dataset/strong_forecaster/cross_backbone...           16           1.503275  2.220446e-16      100
61      Weather      PatchTST      192             0.194775            0.190482             0.240853            0.238072  /data/dataset/strong_forecaster/cross_backbone...           18           2.203907  0.000000e+00      100
62      Weather      PatchTST      336             0.246900            0.241303             0.281548            0.279920  /data/dataset/strong_forecaster/cross_backbone...           20           2.267156  8.881784e-16      100
63      Weather      PatchTST      720             0.320894            0.314066             0.334351            0.331704  /data/dataset/strong_forecaster/cross_backbone...           22           2.128003  0.000000e+00      100
64      Weather     TimeMixer       96             0.162069            0.160429             0.207950            0.207385  /data/dataset/strong_forecaster/three_backbone...           26           1.012234  0.000000e+00      100
65      Weather     TimeMixer      192             0.208661            0.205513             0.252553            0.251106  /data/dataset/strong_forecaster/three_backbone...           29           1.508428  0.000000e+00      100
66      Weather     TimeMixer      336             0.263268            0.258681             0.290729            0.289736  /data/dataset/strong_forecaster/three_backbone...           32           1.742619  2.220446e-16      100
67      Weather     TimeMixer      720             0.344638            0.334318             0.343332            0.339776  /data/dataset/strong_forecaster/three_backbone...           35           2.994619  0.000000e+00      100
68      Weather  iTransformer       96             0.173287            0.166006             0.212210            0.209350  /data/dataset/strong_forecaster/cross_backbone...           17           4.201641  0.000000e+00      100
69      Weather  iTransformer      192             0.224436            0.214400             0.257719            0.253501  /data/dataset/strong_forecaster/cross_backbone...           19           4.471502  0.000000e+00      100
70      Weather  iTransformer      336             0.282732            0.270471             0.299481            0.296607  /data/dataset/strong_forecaster/cross_backbone...           21           4.336659  8.881784e-16      100
71      Weather  iTransformer      720             0.357908            0.344274             0.349720            0.344686  /data/dataset/strong_forecaster/cross_backbone...           23           3.809215  0.000000e+00      100

## 6. Coalesce selected-table and recovered absolute metrics

In [7]:
if len(recovered):
    rec_cols = [
        "Dataset",
        "Backbone",
        "Horizon",
        "DirectMSE_recovered",
        "FinalMSE_recovered",
        "DirectMAE_recovered",
        "FinalMAE_recovered",
        "RecoverySource",
        "RecoveredGain_pct",
        "GainMismatch",
    ]

    rec = recovered[rec_cols].copy()
else:
    rec = pd.DataFrame(
        columns=[
            "Dataset",
            "Backbone",
            "Horizon",
            "DirectMSE_recovered",
            "FinalMSE_recovered",
            "DirectMAE_recovered",
            "FinalMAE_recovered",
            "RecoverySource",
            "RecoveredGain_pct",
            "GainMismatch",
        ]
    )

full = absolute.merge(
    rec,
    on=KEY,
    how="left",
    validate="one_to_one",
)

full["DirectMSE_final"] = (
    full["DirectMSE"]
    .combine_first(
        full["DirectMSE_recovered"]
    )
)

full["FinalMSE_final"] = (
    full["FinalMSE"]
    .combine_first(
        full["FinalMSE_recovered"]
    )
)

full["DirectMAE_final"] = (
    full["DirectMAE"]
    .combine_first(
        full["DirectMAE_recovered"]
    )
)

full["FinalMAE_final"] = (
    full["FinalMAE"]
    .combine_first(
        full["FinalMAE_recovered"]
    )
)

full["MSEMetricSource"] = np.where(
    full["DirectMSE"].notna()
    & full["FinalMSE"].notna(),
    "Experiment37Selected",
    np.where(
        full["DirectMSE_final"].notna()
        & full["FinalMSE_final"].notna(),
        "HistoricalRecovery",
        "Missing",
    ),
)

full["MAEMetricSource"] = np.where(
    full["DirectMAE"].notna()
    & full["FinalMAE"].notna(),
    "Experiment37Selected",
    np.where(
        full["DirectMAE_final"].notna()
        & full["FinalMAE_final"].notna(),
        "HistoricalRecovery",
        "Missing",
    ),
)

full["AbsoluteMSEImprovement"] = (
    full["DirectMSE_final"]
    - full["FinalMSE_final"]
)

full["RecomputedMSEGain_pct"] = (
    full["AbsoluteMSEImprovement"]
    / full["DirectMSE_final"]
    * 100.0
)

full["GainConsistencyError"] = (
    full["RecomputedMSEGain_pct"]
    - full["MSEGain_pct"]
).abs()

display(
    full.sort_values(KEY)
)

full.to_csv(
    OUT_DIR / "direct_final_absolute_metrics_96_conditions.csv",
    index=False,
)

,Dataset,Backbone,Horizon,MSEGain_pct,DirectMSE,FinalMSE,DirectMAE,FinalMAE,MSESource,MAESource,DirectMSE_recovered,FinalMSE_recovered,DirectMAE_recovered,FinalMAE_recovered,RecoverySource,RecoveredGain_pct,GainMismatch,DirectMSE_final,FinalMSE_final,DirectMAE_final,FinalMAE_final,MSEMetricSource,MAEMetricSource,AbsoluteMSEImprovement,RecomputedMSEGain_pct,GainConsistencyError
0,ETTh1,PatchTST,96,-1.090730,0.378632,NaN,0.400303,NaN,Missing,Missing,0.378632,0.382762,0.400303,0.405032,/data/dataset/strong_forecaster/cross_backbone...,-1.090730,0.000000e+00,0.378632,0.382762,0.400303,0.405032,HistoricalRecovery,HistoricalRecovery,-0.004130,-1.090730,0.000000e+00
1,ETTh1,PatchTST,192,-1.676780,0.413694,NaN,0.420978,NaN,Missing,Missing,0.413694,0.420631,0.420978,0.429180,/data/dataset/strong_forecaster/cross_backbone...,-1.676780,0.000000e+00,0.413694,0.420631,0.420978,0.429180,HistoricalRecovery,HistoricalRecovery,-0.006937,-1.676780,0.000000e+00
2,ETTh1,PatchTST,336,-1.466894,0.441984,NaN,0.441434,NaN,Missing,Missing,0.441984,0.448468,0.441434,0.448939,/data/dataset/strong_forecaster/cross_backbone...,-1.466894,2.220446e-16,0.441984,0.448468,0.441434,0.448939,HistoricalRecovery,HistoricalRecovery,-0.006483,-1.466894,2.220446e-16
3,ETTh1,PatchTST,720,-3.931421,0.461510,NaN,0.473867,NaN,Missing,Missing,0.461510,0.479654,0.473867,0.489601,/data/dataset/strong_forecaster/cross_backbone...,-3.931421,0.000000e+00,0.461510,0.479654,0.473867,0.489601,HistoricalRecovery,HistoricalRecovery,-0.018144,-3.931421,0.000000e+00
4,ETTh1,SegMoE,96,-1.052852,0.429677,0.434201,0.437933,0.441780,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.429677,0.434201,0.437933,0.441780,Experiment37Selected,Experiment37Selected,-0.004524,-1.052852,1.287859e-14
5,ETTh1,SegMoE,192,-2.264470,0.481695,0.492603,0.473062,0.480069,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.481695,0.492603,0.473062,0.480069,Experiment37Selected,Experiment37Selected,-0.010908,-2.264470,1.154632e-14
6,ETTh1,SegMoE,336,-2.288568,0.535394,0.547647,0.505612,0.512787,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.535394,0.547647,0.505612,0.512787,Experiment37Selected,Experiment37Selected,-0.012253,-2.288568,0.000000e+00
7,ETTh1,SegMoE,720,-6.796243,0.657350,0.702025,0.571758,0.593895,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.657350,0.702025,0.571758,0.593895,Experiment37Selected,Experiment37Selected,-0.044675,-6.796243,0.000000e+00
8,ETTh1,TimeMixer,96,-0.567222,0.388839,NaN,0.402163,NaN,Missing,Missing,0.388839,0.391045,0.402163,0.404818,/data/dataset/strong_forecaster/three_backbone...,-0.567222,0.000000e+00,0.388839,0.391045,0.402163,0.404818,HistoricalRecovery,HistoricalRecovery,-0.002206,-0.567222,0.000000e+00
9,ETTh1,TimeMixer,192,-0.640128,0.442255,NaN,0.429601,NaN,Missing,Missing,0.442255,0.445086,0.429601,0.435802,/data/dataset/strong_forecaster/three_backbone...,-0.640128,0.000000e+00,0.442255,0.445086,0.429601,0.435802,HistoricalRecovery,HistoricalRecovery,-0.002831,-0.640128,0.000000e+00
10,ETTh1,TimeMixer,336,-1.529878,0.517918,NaN,0.474665,NaN,Missing,Missing,0.517918,0.525842,0.474665,0.484048,/data/dataset/strong_forecaster/three_backbone...,-1.529878,2.220446e-16,0.517918,0.525842,0.474665,0.484048,HistoricalRecovery,HistoricalRecovery,-0.007924,-1.529878,2.220446e-16
11,ETTh1,TimeMixer,720,-6.298939,0.512187,NaN,0.484744,NaN,Missing,Missing,0.512187,0.544449,0.484744,0.513554,/data/dataset/strong_forecaster/three_backbone...,-6.298939,8.881784e-16,0.512187,0.544449,0.484744,0.513554,HistoricalRecovery,HistoricalRecovery,-0.032262,-6.298939,8.881784e-16
12,ETTh1,iTransformer,96,-0.504197,0.392303,NaN,0.407334,NaN,Missing,Missing,0.392303,0.394281,0.407334,0.410792,/data/dataset/strong_forecaster/cross_backbone...,-0.504197,0.000000e+00,0.392303,0.394281,0.407334,0.410792,HistoricalRecovery,HistoricalRecovery,-0.001978,-0.504197,0.000000e+00
13,ETTh1,iTransformer,192,-1.458748,0.442639,NaN,0.434737,NaN,Missing,Missing,0.442639,0.449096,0.434737,0.442669,/data/dataset/strong_forecaster/cross_backbone...,-1.458748,0.000000e+00,0.442639,0.449096,0.434737,0.442669,HistoricalRecovery,HistoricalRecovery,-0.006457,-1.458748,0.000000e+00
14,ETTh1,iTransformer,336,-1.785874,0.489263,NaN,0.461457,NaN,Missing,Missing,0.489263,0.498000,0.461457,0.473326,/data/dataset/strong_forecaster/cross_backbone...,-1.785874,0.000000e+00,0.489263,0.498000,0.461457,0.473326,HistoricalRecovery,HistoricalRecovery,-0.008738,-1.785874,0.000000e+00
15,ETTh1,iTransformer,720,-5.876001,0.506507,NaN,0.492894,NaN,Missing,Missing,0.506507,0.536269,0.492894,0.515912,/data/dataset/strong_forecaster/cross_backbone...,-5.876001,8.881784e-16,0.506507,0.536269,0.492894,0.515912,HistoricalRecovery,HistoricalRecovery,-0.029762,-5.876001,8.881784e-16
16,Electricity,PatchTST,96,0.839606,0.129638,0.128549,0.222790,0.222718,Experiment37Selected,Experiment37Selected,0.146149,0.144746,0.242762,0.242602,/data/dataset/strong_forecaster/relevance_to_f...,0.959915,1.203090e-01,0.129638,0.128549,0.222790,0.222718,Experiment37Selected,Experiment37Selected,0.001088,0.839606,2.142730e-14
17,Electricity,PatchTST,192,0.445810,0.148802,0.148138,0.242637,0.242954,Experiment37Selected,Experiment37Selected,0.149116,0.148559,0.242038,0.242267,/data/dataset/strong_forecaster/three_backbone...,0.373992,7.181783e-02,0.148802,0.148138,0.242637,0.242954,Experiment37Selected,Experiment37Selected,0.000663,0.445810,1.870726e-14
18,Electricity,PatchTST,336,0.820887,0.165312,0.163955,0.259284,0.259330,Experiment37Selected,Experiment37Selected,0.165690,0.164748,0.258694,0.259026,/data/dataset/strong_forecaster/three_backbone...,0.568902,2.519845e-01,0.165312,0.163955,0.259284,0.259330,Experiment37Selected,Experiment37Selected,0.001357,0.820887,5.051515e-14
19,Electricity,PatchTST,720,-0.672307,0.202859,0.204223,0.291769,0.293104,Experiment37Selected,Experiment37Selected,0.221973,0.222322,0.315620,0.318150,/data/dataset/strong_forecaster/relevance_to_f...,-0.157246,5.150608e-01,0.202859,0.204223,0.291769,0.293104,Experiment37Selected,Experiment37Selected,-0.001364,-0.672307,1.365574e-14
20,Electricity,SegMoE,96,0.519435,0.131053,0.130373,0.225169,0.225389,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.131053,0.130373,0.225169,0.225389,Experiment37Selected,Experiment37Selected,0.000681,0.519435,4.218847e-14
21,Electricity,SegMoE,192,0.278683,0.148784,0.148369,0.242053,0.242182,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.148784,0.148369,0.242053,0.242182,Experiment37Selected,Experiment37Selected,0.000415,0.278683,1.110223e-16
22,Electricity,SegMoE,336,0.293029,0.166729,0.166240,0.261269,0.261459,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.166729,0.166240,0.261269,0.261459,Experiment37Selected,Experiment37Selected,0.000489,0.293029,0.000000e+00
23,Electricity,SegMoE,720,0.347162,0.210921,0.210188,0.301344,0.302073,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.210921,0.210188,0.301344,0.302073,Experiment37Selected,Experiment37Selected,0.000732,0.347162,1.332268e-14
24,Electricity,TimeMixer,96,0.359394,0.156833,0.156269,0.247900,0.247884,Experiment37Selected,Experiment37Selected,0.153008,0.152757,0.245195,0.245418,/data/dataset/strong_forecaster/three_backbone...,0.164148,1.952463e-01,0.156833,0.156269,0.247900,0.247884,Experiment37Selected,Experiment37Selected,0.000564,0.359394,3.519407e-14
25,Electricity,TimeMixer,192,0.462375,0.170396,0.169608,0.260518,0.260731,Experiment37Selected,Experiment37Selected,0.177572,0.176864,0.271930,0.272231,/data/dataset/strong_forecaster/relevance_to_f...,0.398798,6.357643e-02,0.170396,0.169608,0.260518,0.260731,Experiment37Selected,Experiment37Selected,0.000788,0.462375,3.241851e-14
26,Electricity,TimeMixer,336,0.854897,0.186231,0.184639,0.276494,0.276796,Experiment37Selected,Experiment37Selected,0.186218,0.184431,0.275052,0.275120,/data/dataset/strong_forecaster/three_backbone...,0.959694,1.047973e-01,0.186231,0.184639,0.276494,0.276796,Experiment37Selected,Experiment37Selected,0.001592,0.854897,2.953193e-14
27,Electricity,TimeMixer,720,0.290450,0.226784,0.226125,0.310885,0.311662,Experiment37Selected,Experiment37Selected,0.224731,0.223184,0.312808,0.313286,/data/dataset/strong_forecaster/three_backbone...,0.688475,3.980242e-01,0.226784,0.226125,0.310885,0.311662,Experiment37Selected,Experiment37Selected,0.000659,0.290450,1.226796e-14
28,Electricity,iTransformer,96,1.466603,0.150067,0.147866,0.241682,0.241352,Experiment37Selected,Experiment37Selected,0.148275,0.146310,0.239707,0.239500,/data/dataset/strong_forecaster/three_backbone...,1.325576,1.410271e-01,0.150067,0.147866,0.241682,0.241352,Experiment37Selected,Experiment37Selected,0.002201,1.466603,1.887379e-14
29,Electricity,iTransformer,192,0.962485,0.163223,0.161652,0.253838,0.253938,Experiment37Selected,Experiment37Selected,0.186433,0.183813,0.275288,0.276009,/data/dataset/strong_forecaster/relevance_to_f...,1.405222,4.427373e-01,0.163223,0.161652,0.253838,0.253938,Experiment37Selected,Experiment37Selected,0.001571,0.962485,3.419487e-14
30,Electricity,iTransformer,336,1.010948,0.177195,0.175403,0.269127,0.269705,Experiment37Selected,Experiment37Selected,0.179687,0.178503,0.272384,0.273237,/data/dataset/strong_forecaster/three_backbone...,0.659223,3.517244e-01,0.177195,0.175403,0.269127,0.269705,Experiment37Selected,Experiment37Selected,0.001791,1.010948,2.220446e-16
31,Electricity,iTransformer,720,0.089924,0.216770,0.216575,0.303519,0.304858,Experiment37Selected,Experiment37Selected,0.217054,0.215217,0.304202,0.305317,/data/dataset/strong_forecaster/three_backbone...,0.845958,7.560341e-01,0.216770,0.216575,0.303519,0.304858,Experiment37Selected,Experiment37Selected,0.000195,0.089924,1.272593e-14
32,Exchange,PatchTST,96,0.000000,0.088792,0.088792,0.208818,0.208818,Experiment37Selected,Experiment37Selected,0.088792,0.088792,0.208818,0.208818,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.088792,0.088792,0.208818,0.208818,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
33,Exchange,PatchTST,192,0.000000,0.194937,0.194937,0.316183,0.316183,Experiment37Selected,Experiment37Selected,0.194937,0.194937,0.316183,0.316183,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.194937,0.194937,0.316183,0.316183,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
34,Exchange,PatchTST,336,0.000000,0.346291,0.346291,0.428873,0.428873,Experiment37Selected,Experiment37Selected,0.346291,0.346291,0.428873,0.428873,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.346291,0.346291,0.428873,0.428873,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
35,Exchange,PatchTST,720,0.000000,0.858390,0.858390,0.692987,0.692987,Experiment37Selected,Experiment37Selected,0.858390,0.858390,0.692987,0.692987,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.858390,0.858390,0.692987,0.692987,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
36,Exchange,SegMoE,96,0.000000,0.087003,0.087003,0.207546,0.207546,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.087003,0.087003,0.207546,0.207546,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
37,Exchange,SegMoE,192,0.000000,0.183186,0.183186,0.307153,0.307153,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.183186,0.183186,0.307153,0.307153,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
38,Exchange,SegMoE,336,0.000000,0.331033,0.331033,0.420178,0.420178,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.331033,0.331033,0.420178,0.420178,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
39,Exchange,SegMoE,720,0.000000,0.808399,0.808399,0.680196,0.680196,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.808399,0.808399,0.680196,0.680196,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
40,Exchange,TimeMixer,96,1.767956,0.092543,0.090907,0.210600,0.208730,Experiment37Selected,Experiment37Selected,0.092543,0.090907,0.210600,0.208730,/data/dataset/strong_forecaster/exchange_three...,1.767956,4.507505e-14,0.092543,0.090907,0.210600,0.208730,Experiment37Selected,Experiment37Selected,0.001636,1.767956,4.507505e-14
41,Exchange,TimeMixer,192,0.000000,0.177509,0.177509,0.299693,0.299693,Experiment37Selected,Experiment37Selected,0.177509,0.177509,0.299693,0.299693,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.177509,0.177509,0.299693,0.299693,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
42,Exchange,TimeMixer,336,0.000000,0.329322,0.329322,0.417432,0.417432,Experiment37Selected,Experiment37Selected,0.329322,0.329322,0.417432,0.417432,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.329322,0.329322,0.417432,0.417432,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
43,Exchange,TimeMixer,720,0.000000,1.149432,1.149432,0.800125,0.800125,Experiment37Selected,Experiment37Selected,1.149432,1.149432,0.800125,0.800125,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,1.149432,1.149432,0.800125,0.800125,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
44,Exchange,iTransformer,96,0.000000,0.098471,0.098471,0.223430,0.223430,Experiment37Selected,Experiment37Selected,0.098471,0.098471,0.223430,0.223430,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.098471,0.098471,0.223430,0.223430,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
45,Exchange,iTransformer,192,0.000000,0.182288,0.182288,0.305967,0.305967,Experiment37Selected,Experiment37Selected,0.182288,0.182288,0.305967,0.305967,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.182288,0.182288,0.305967,0.305967,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
46,Exchange,iTransformer,336,0.000000,0.346023,0.346023,0.426120,0.426120,Experiment37Selected,Experiment37Selected,0.346023,0.346023,0.426120,0.426120,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.346023,0.346023,0.426120,0.426120,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
47,Exchange,iTransformer,720,0.000000,0.832304,0.832304,0.690283,0.690283,Experiment37Selected,Experiment37Selected,0.832304,0.832304,0.690283,0.690283,/data/dataset/strong_forecaster/exchange_three...,0.000000,0.000000e+00,0.832304,0.832304,0.690283,0.690283,Experiment37Selected,Experiment37Selected,0.000000,0.000000,0.000000e+00
48,Solar,PatchTST,96,1.623971,0.183429,0.180450,0.246145,0.243917,Experiment37Selected,Experiment37Selected,0.183429,0.180450,0.246145,0.243917,/data/dataset/strong_forecaster/solar_three_ba...,1.623971,3.019807e-14,0.183429,0.180450,0.246145,0.243917,Experiment37Selected,Experiment37Selected,0.002979,1.623971,3.019807e-14
49,Solar,PatchTST,192,0.557470,0.188770,0.187718,0.240918,0.241148,Experiment37Selected,Experiment37Selected,0.188770,0.187718,0.240918,0.241148,/data/dataset/strong_forecaster/solar_three_ba...,0.557470,1.454392e-14,0.188770,0.187718,0.240918,0.241148,Experiment37Selected,Experiment37Selected,0.001052,0.557470,1.454392e-14
50,Solar,PatchTST,336,1.889864,0.199593,0.195821,0.253637,0.250760,Experiment37Selected,Experiment37Selected,0.199593,0.195821,0.253637,0.250760,/data/dataset/strong_forecaster/solar_three_ba...,1.889864,0.000000e+00,0.199593,0.195821,0.253637,0.250760,Experiment37Selected,Experiment37Selected,0.003772,1.889864,0.000000e+00
51,Solar,PatchTST,720,2.116875,0.213913,0.209384,0.260529,0.258027,Experiment37Selected,Experiment37Selected,0.213913,0.209384,0.260529,0.258027,/data/dataset/strong_forecaster/solar_three_ba...,2.116875,3.952394e-14,0.213913,0.209384,0.260529,0.258027,Experiment37Selected,Experiment37Selected,0.004528,2.116875,3.952394e-14
52,Solar,SegMoE,96,3.983484,0.189151,0.181617,0.232919,0.231696,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.189151,0.181617,0.232919,0.231696,Experiment37Selected,Experiment37Selected,0.007535,3.983484,8.881784e-16
53,Solar,SegMoE,192,3.347685,0.224613,0.217094,0.258155,0.261628,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.224613,0.217094,0.258155,0.261628,Experiment37Selected,Experiment37Selected,0.007519,3.347685,1.332268e-15
54,Solar,SegMoE,336,14.495511,0.274460,0.234675,0.286079,0.279171,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.274460,0.234675,0.286079,0.279171,Experiment37Selected,Experiment37Selected,0.039784,14.495511,1.598721e-14
55,Solar,SegMoE,720,30.889498,0.389844,0.269423,0.337040,0.303004,Experiment37Selected,Experiment37Selected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.389844,0.269423,0.337040,0.303004,Experiment37Selected,Experiment37Selected,0.120421,30.889498,1.065814e-14
56,Solar,TimeMixer,96,2.590790,0.195299,0.190239,0.241748,0.242083,Experiment37Selected,Experiment37Selected,0.195299,0.190239,0.241748,0.242083,/data/dataset/strong_forecaster/solar_three_ba...,2.590790,2.753353e-14,0.195299,0.190239,0.241748,0.242083,Experiment37Selected,Experiment37Selected,0.005060,2.590790,2.753353e-14
57,Solar,TimeMixer,192,4.150787,0.228547,0.219061,0.269627,0.269107,Experiment37Selected,Experiment37Selected,0.228547,0.219061,0.269627,0.269107,/data/dataset/strong_forecaster/solar_three_ba...,4.150787,3.463896e-14,0.228547,0.219061,0.269627,0.269107,Experiment37Selected,Experiment37Selected,0.009487,4.150787,3.463896e-14
58,Solar,TimeMixer,336,8.842038,0.255755,0.233141,0.288708,0.280964,Experiment37Selected,Experiment37Selected,0.255755,0.233141,0.288708,0.280964,/data/dataset/strong_forecaster/solar_three_ba...,8.842038,1.065814e-14,0.255755,0.233141,0.288708,0.280964,Experiment37Selected,Experiment37Selected,0.022614,8.842038,1.065814e-14
59,Solar,TimeMixer,720,5.192945,0.253337,0.240181,0.286785,0.284330,Experiment37Selected,Experiment37Selected,0.253337,0.240181,0.286785,0.284330,/data/dataset/strong_forecaster/solar_three_ba...,5.192945,8.881784e-16,0.253337,0.240181,0.286785,0.284330,Experiment37Selected,Experiment37Selected,0.013156,5.192945,8.881784e-16
60,Solar,iTransformer,96,10.467056,0.204083,0.182722,0.229920,0.228564,Experiment37Selected,Experiment37Selected,0.204083,0.182722,0.229920,0.228564,/data/dataset/strong_forecaster/solar_three_ba...,10.467056,0.000000e+00,0.204083,0.182722,0.229920,0.228564,Experiment37Selected,Experiment37Selected,0.021362,10.467056,0.000000e+00
61,Solar,iTransformer,192,12.877345,0.244628,0.213126,0.263545,0.257533,Experiment37Selected,Experiment37Selected,0.244628,0.213126,0.263545,0.257533,/data/dataset/strong_forecaster/solar_three_ba...,12.877345,3.552714e-14,0.244628,0.213126,0.263545,0.257533,Experiment37Selected,Experiment37Selected,0.031502,12.877345,3.552714e-14
62,Solar,iTransformer,336,13.990738,0.252072,0.216806,0.275291,0.265086,Experiment37Selected,Experiment37Selected,0.252072,0.216806,0.275291,0.265086,/data/dataset/strong_forecaster/solar_three_ba...,13.990738,2.131628e-14,0.252072,0.216806,0.275291,0.265086,Experiment37Selected,Experiment37Selected,0.035267,13.990738,2.131628e-14
63,Solar,iTransformer,720,10.861391,0.252617,0.225179,0.275918,0.269137,Experiment37Selected,Experiment37Selected,0.252617,0.225179,0.275918,0.269137,/data/dataset/strong_forecaster/solar_three_ba...,10.861391,3.552714e-15,0.252617,0.225179,0.275918,0.269137,Experiment37Selected,Experiment37Selected,0.027438,10.861391,3.552714e-15

## 7. Consistency and coverage audit

The absolute MSE pair is accepted only if it reproduces the frozen percentage gain.
A small tolerance is allowed for CSV rounding.

In [8]:
MSE_TOL_PCT = 0.01

mse_complete = (
    full["DirectMSE_final"].notna()
    & full["FinalMSE_final"].notna()
)

mae_complete = (
    full["DirectMAE_final"].notna()
    & full["FinalMAE_final"].notna()
)

bad_gain = full[
    mse_complete
    & (
        full["GainConsistencyError"]
        > MSE_TOL_PCT
    )
].copy()

print(
    "Complete MSE pairs:",
    int(mse_complete.sum()),
    "/96",
)

print(
    "Complete MAE pairs:",
    int(mae_complete.sum()),
    "/96",
)

print(
    "MSE gain consistency failures:",
    len(bad_gain),
)

if len(bad_gain):
    display(
        bad_gain[
            KEY
            + [
                "MSEGain_pct",
                "DirectMSE_final",
                "FinalMSE_final",
                "RecomputedMSEGain_pct",
                "GainConsistencyError",
                "MSEMetricSource",
                "RecoverySource",
            ]
        ]
    )

    raise RuntimeError(
        "Absolute MSE recovery contains gain-inconsistent rows."
    )

print("PASS: all recovered MSE pairs are consistent with frozen gains.")

Complete MSE pairs: 96 /96
Complete MAE pairs: 96 /96
MSE gain consistency failures: 0
PASS: all recovered MSE pairs are consistent with frozen gains.

## 8. Dataset × backbone summary

This is the most compact appendix-facing summary.

Because raw MSE scales differ by dataset, **we do not average MSE across datasets**.
Within each dataset/backbone, we report the four horizons separately and an average only across horizons.

In [9]:
summary_rows = []

for dataset in DATASETS:
    for backbone in BACKBONES:
        g = full[
            (full["Dataset"] == dataset)
            & (full["Backbone"] == backbone)
        ].sort_values("Horizon")

        row = {
            "Dataset": dataset,
            "Backbone": backbone,
            "MeanDirectMSE_overH": (
                float(g["DirectMSE_final"].mean())
                if g["DirectMSE_final"].notna().any()
                else np.nan
            ),
            "MeanFinalMSE_overH": (
                float(g["FinalMSE_final"].mean())
                if g["FinalMSE_final"].notna().any()
                else np.nan
            ),
            "MeanMSEGain_pct_overH": float(
                g["MSEGain_pct"].mean()
            ),
            "Wins": int(
                (g["MSEGain_pct"] > 0).sum()
            ),
            "Ties": int(
                (g["MSEGain_pct"].abs() <= 1e-12).sum()
            ),
            "Losses": int(
                (g["MSEGain_pct"] < 0).sum()
            ),
        }

        if g["DirectMAE_final"].notna().all():
            row["MeanDirectMAE_overH"] = float(
                g["DirectMAE_final"].mean()
            )
            row["MeanFinalMAE_overH"] = float(
                g["FinalMAE_final"].mean()
            )
        else:
            row["MeanDirectMAE_overH"] = np.nan
            row["MeanFinalMAE_overH"] = np.nan

        summary_rows.append(row)

summary = pd.DataFrame(summary_rows)

display(summary)

summary.to_csv(
    OUT_DIR / "dataset_backbone_absolute_summary.csv",
    index=False,
)

        Dataset      Backbone  MeanDirectMSE_overH  MeanFinalMSE_overH  MeanMSEGain_pct_overH  Wins  Ties  Losses  MeanDirectMAE_overH  MeanFinalMAE_overH
0         Solar      PatchTST             0.196426            0.193343               1.547045     4     0       0             0.250307            0.248463
1         Solar  iTransformer             0.238350            0.209458              12.049133     4     0       0             0.261168            0.255080
2         Solar     TimeMixer             0.233234            0.220655               5.194140     4     0       0             0.271717            0.269121
3         Solar        SegMoE             0.269517            0.225702              13.179044     4     0       0             0.278548            0.268875
4       Weather      PatchTST             0.228065            0.223323               2.025585     4     0       0             0.263642            0.261528
5       Weather  iTransformer             0.259591            0.248788               4.204754     4     0       0             0.279783            0.276036
6       Weather     TimeMixer             0.244659            0.239735               1.814475     4     0       0             0.273641            0.272001
7       Weather        SegMoE             0.223747            0.218869               2.058731     4     0       0             0.256018            0.254421
8   Electricity      PatchTST             0.161653            0.161216               0.358499     3     0       1             0.254120            0.254527
9   Electricity  iTransformer             0.176814            0.175374               0.882490     4     0       0             0.267041            0.267463
10  Electricity     TimeMixer             0.185061            0.184160               0.491779     4     0       0             0.273949            0.274268
11  Electricity        SegMoE             0.164372            0.163793               0.359577     4     0       0             0.257459            0.257776
12      Traffic      PatchTST             0.402308            0.402159               0.038060     4     0       0             0.271891            0.271951
13      Traffic  iTransformer             0.440202            0.439545               0.149114     3     0       1             0.293620            0.292964
14      Traffic     TimeMixer             0.497946            0.497372               0.117794     3     0       1             0.313164            0.312752
15      Traffic        SegMoE             0.398029            0.397940               0.022133     4     0       0             0.263695            0.263776
16     Exchange      PatchTST             0.372102            0.372102               0.000000     0     4       0             0.411715            0.411715
17     Exchange  iTransformer             0.364772            0.364772               0.000000     0     4       0             0.411450            0.411450
18     Exchange     TimeMixer             0.437201            0.436792               0.441989     1     3       0             0.431963            0.431495
19     Exchange        SegMoE             0.352405            0.352405               0.000000     0     4       0             0.403768            0.403768
20        ETTh1      PatchTST             0.423955            0.432878              -2.041456     0     0       4             0.434145            0.443188
21        ETTh1  iTransformer             0.457678            0.469412              -2.406205     0     0       4             0.449106            0.460675
22        ETTh1     TimeMixer             0.465300            0.476606              -2.259042     0     0       4             0.447793            0.459556
23        ETTh1        SegMoE             0.526029            0.544119              -3.100533     0     0       4             0.497091            0.507133

## 9. Appendix-ready horizon table

This table retains the actual direct and final MSE for every downstream condition.
It is the strongest way to show that the historical-memory result is measured against a concrete,
frozen direct forecast rather than an abstract percentage baseline.

In [10]:
paper = full[
    [
        "Dataset",
        "Backbone",
        "Horizon",
        "DirectMSE_final",
        "FinalMSE_final",
        "MSEGain_pct",
        "DirectMAE_final",
        "FinalMAE_final",
        "MSEMetricSource",
        "MAEMetricSource",
    ]
].copy()

paper = paper.sort_values(
    ["Dataset", "Backbone", "Horizon"]
)

display(paper)

paper.to_csv(
    OUT_DIR / "paper_absolute_metrics_96_conditions.csv",
    index=False,
)

latex = paper.copy()

for c in [
    "DirectMSE_final",
    "FinalMSE_final",
    "DirectMAE_final",
    "FinalMAE_final",
]:
    latex[c] = latex[c].map(
        lambda v: (
            ""
            if pd.isna(v)
            else f"{v:.4f}"
        )
    )

latex["MSEGain_pct"] = latex["MSEGain_pct"].map(
    lambda v: f"{v:+.3f}"
)

(OUT_DIR / "paper_absolute_metrics_96_conditions.tex").write_text(
    latex.to_latex(
        index=False,
        escape=False,
    ),
    encoding="utf-8",
)

print("Saved paper-ready CSV and LaTeX table.")

        Dataset      Backbone  Horizon  DirectMSE_final  FinalMSE_final  MSEGain_pct  DirectMAE_final  FinalMAE_final       MSEMetricSource       MAEMetricSource
0         ETTh1      PatchTST       96         0.378632        0.382762    -1.090730         0.400303        0.405032    HistoricalRecovery    HistoricalRecovery
1         ETTh1      PatchTST      192         0.413694        0.420631    -1.676780         0.420978        0.429180    HistoricalRecovery    HistoricalRecovery
2         ETTh1      PatchTST      336         0.441984        0.448468    -1.466894         0.441434        0.448939    HistoricalRecovery    HistoricalRecovery
3         ETTh1      PatchTST      720         0.461510        0.479654    -3.931421         0.473867        0.489601    HistoricalRecovery    HistoricalRecovery
4         ETTh1        SegMoE       96         0.429677        0.434201    -1.052852         0.437933        0.441780  Experiment37Selected  Experiment37Selected
5         ETTh1        SegMoE      192         0.481695        0.492603    -2.264470         0.473062        0.480069  Experiment37Selected  Experiment37Selected
6         ETTh1        SegMoE      336         0.535394        0.547647    -2.288568         0.505612        0.512787  Experiment37Selected  Experiment37Selected
7         ETTh1        SegMoE      720         0.657350        0.702025    -6.796243         0.571758        0.593895  Experiment37Selected  Experiment37Selected
8         ETTh1     TimeMixer       96         0.388839        0.391045    -0.567222         0.402163        0.404818    HistoricalRecovery    HistoricalRecovery
9         ETTh1     TimeMixer      192         0.442255        0.445086    -0.640128         0.429601        0.435802    HistoricalRecovery    HistoricalRecovery
10        ETTh1     TimeMixer      336         0.517918        0.525842    -1.529878         0.474665        0.484048    HistoricalRecovery    HistoricalRecovery
11        ETTh1     TimeMixer      720         0.512187        0.544449    -6.298939         0.484744        0.513554    HistoricalRecovery    HistoricalRecovery
12        ETTh1  iTransformer       96         0.392303        0.394281    -0.504197         0.407334        0.410792    HistoricalRecovery    HistoricalRecovery
13        ETTh1  iTransformer      192         0.442639        0.449096    -1.458748         0.434737        0.442669    HistoricalRecovery    HistoricalRecovery
14        ETTh1  iTransformer      336         0.489263        0.498000    -1.785874         0.461457        0.473326    HistoricalRecovery    HistoricalRecovery
15        ETTh1  iTransformer      720         0.506507        0.536269    -5.876001         0.492894        0.515912    HistoricalRecovery    HistoricalRecovery
16  Electricity      PatchTST       96         0.129638        0.128549     0.839606         0.222790        0.222718  Experiment37Selected  Experiment37Selected
17  Electricity      PatchTST      192         0.148802        0.148138     0.445810         0.242637        0.242954  Experiment37Selected  Experiment37Selected
18  Electricity      PatchTST      336         0.165312        0.163955     0.820887         0.259284        0.259330  Experiment37Selected  Experiment37Selected
19  Electricity      PatchTST      720         0.202859        0.204223    -0.672307         0.291769        0.293104  Experiment37Selected  Experiment37Selected
20  Electricity        SegMoE       96         0.131053        0.130373     0.519435         0.225169        0.225389  Experiment37Selected  Experiment37Selected
21  Electricity        SegMoE      192         0.148784        0.148369     0.278683         0.242053        0.242182  Experiment37Selected  Experiment37Selected
22  Electricity        SegMoE      336         0.166729        0.166240     0.293029         0.261269        0.261459  Experiment37Selected  Experiment37Selected
23  Electricity        SegMoE      720         0.210921        0.210188     0.347162         0.301344        0.302073  Experiment37Selected  Experiment37Selected
24  Electricity     TimeMixer       96         0.156833        0.156269     0.359394         0.247900        0.247884  Experiment37Selected  Experiment37Selected
25  Electricity     TimeMixer      192         0.170396        0.169608     0.462375         0.260518        0.260731  Experiment37Selected  Experiment37Selected
26  Electricity     TimeMixer      336         0.186231        0.184639     0.854897         0.276494        0.276796  Experiment37Selected  Experiment37Selected
27  Electricity     TimeMixer      720         0.226784        0.226125     0.290450         0.310885        0.311662  Experiment37Selected  Experiment37Selected
28  Electricity  iTransformer       96         0.150067        0.147866     1.466603         0.241682        0.241352  Experiment37Selected  Experiment37Selected
29  Electricity  iTransformer      192         0.163223        0.161652     0.962485         0.253838        0.253938  Experiment37Selected  Experiment37Selected
30  Electricity  iTransformer      336         0.177195        0.175403     1.010948         0.269127        0.269705  Experiment37Selected  Experiment37Selected
31  Electricity  iTransformer      720         0.216770        0.216575     0.089924         0.303519        0.304858  Experiment37Selected  Experiment37Selected
32     Exchange      PatchTST       96         0.088792        0.088792     0.000000         0.208818        0.208818  Experiment37Selected  Experiment37Selected
33     Exchange      PatchTST      192         0.194937        0.194937     0.000000         0.316183        0.316183  Experiment37Selected  Experiment37Selected
34     Exchange      PatchTST      336         0.346291        0.346291     0.000000         0.428873        0.428873  Experiment37Selected  Experiment37Selected
35     Exchange      PatchTST      720         0.858390        0.858390     0.000000         0.692987        0.692987  Experiment37Selected  Experiment37Selected
36     Exchange        SegMoE       96         0.087003        0.087003     0.000000         0.207546        0.207546  Experiment37Selected  Experiment37Selected
37     Exchange        SegMoE      192         0.183186        0.183186     0.000000         0.307153        0.307153  Experiment37Selected  Experiment37Selected
38     Exchange        SegMoE      336         0.331033        0.331033     0.000000         0.420178        0.420178  Experiment37Selected  Experiment37Selected
39     Exchange        SegMoE      720         0.808399        0.808399     0.000000         0.680196        0.680196  Experiment37Selected  Experiment37Selected
40     Exchange     TimeMixer       96         0.092543        0.090907     1.767956         0.210600        0.208730  Experiment37Selected  Experiment37Selected
41     Exchange     TimeMixer      192         0.177509        0.177509     0.000000         0.299693        0.299693  Experiment37Selected  Experiment37Selected
42     Exchange     TimeMixer      336         0.329322        0.329322     0.000000         0.417432        0.417432  Experiment37Selected  Experiment37Selected
43     Exchange     TimeMixer      720         1.149432        1.149432     0.000000         0.800125        0.800125  Experiment37Selected  Experiment37Selected
44     Exchange  iTransformer       96         0.098471        0.098471     0.000000         0.223430        0.223430  Experiment37Selected  Experiment37Selected
45     Exchange  iTransformer      192         0.182288        0.182288     0.000000         0.305967        0.305967  Experiment37Selected  Experiment37Selected
46     Exchange  iTransformer      336         0.346023        0.346023     0.000000         0.426120        0.426120  Experiment37Selected  Experiment37Selected
47     Exchange  iTransformer      720         0.832304        0.832304     0.000000         0.690283        0.690283  Experiment37Selected  Experiment37Selected
48        Solar      PatchTST       96         0.183429        0.180450     1.623971         0.246145        0.243917  Experiment37Selected  Experiment37Selected
49        Solar      PatchTST      192         0.188770        0.187718     0.557470         0.240918        0.241148  Experiment37Selected  Experiment37Selected
50        Solar      PatchTST      336         0.199593        0.195821     1.889864         0.253637        0.250760  Experiment37Selected  Experiment37Selected
51        Solar      PatchTST      720         0.213913        0.209384     2.116875         0.260529        0.258027  Experiment37Selected  Experiment37Selected
52        Solar        SegMoE       96         0.189151        0.181617     3.983484         0.232919        0.231696  Experiment37Selected  Experiment37Selected
53        Solar        SegMoE      192         0.224613        0.217094     3.347685         0.258155        0.261628  Experiment37Selected  Experiment37Selected
54        Solar        SegMoE      336         0.274460        0.234675    14.495511         0.286079        0.279171  Experiment37Selected  Experiment37Selected
55        Solar        SegMoE      720         0.389844        0.269423    30.889498         0.337040        0.303004  Experiment37Selected  Experiment37Selected
56        Solar     TimeMixer       96         0.195299        0.190239     2.590790         0.241748        0.242083  Experiment37Selected  Experiment37Selected
57        Solar     TimeMixer      192         0.228547        0.219061     4.150787         0.269627        0.269107  Experiment37Selected  Experiment37Selected
58        Solar     TimeMixer      336         0.255755        0.233141     8.842038         0.288708        0.280964  Experiment37Selected  Experiment37Selected
59        Solar     TimeMixer      720         0.253337        0.240181     5.192945         0.286785        0.284330  Experiment37Selected  Experiment37Selected
60        Solar  iTransformer       96         0.204083        0.182722    10.467056         0.229920        0.228564  Experiment37Selected  Experiment37Selected
61        Solar  iTransformer      192         0.244628        0.213126    12.877345         0.263545        0.257533  Experiment37Selected  Experiment37Selected
62        Solar  iTransformer      336         0.252072        0.216806    13.990738         0.275291        0.265086  Experiment37Selected  Experiment37Selected
63        Solar  iTransformer      720         0.252617        0.225179    10.861391         0.275918        0.269137  Experiment37Selected  Experiment37Selected
64      Traffic      PatchTST       96         0.371912        0.371764     0.039601         0.257690        0.257725  Experiment37Selected  Experiment37Selected
65      Traffic      PatchTST      192         0.391746        0.391500     0.062740         0.265278        0.265281  Experiment37Selected  Experiment37Selected
66      Traffic      PatchTST      336         0.406908        0.406753     0.038198         0.272371        0.272476  Experiment37Selected  Experiment37Selected
67      Traffic      PatchTST      720         0.438668        0.438617     0.011700         0.292223        0.292321  Experiment37Selected  Experiment37Selected
68      Traffic        SegMoE       96         0.366477        0.366360     0.031860         0.246580        0.246623  Experiment37Selected  Experiment37Selected
69      Traffic        SegMoE      192         0.383509        0.383454     0.014381         0.254759        0.254835  Experiment37Selected  Experiment37Selected
70      Traffic        SegMoE      336         0.399093        0.399062     0.007935         0.263841        0.263901  Experiment37Selected  Experiment37Selected
71      Traffic        SegMoE      720         0.443037        0.442885     0.034355         0.289602        0.289745  Experiment37Selected  Experiment37Selected
72      Traffic     TimeMixer       96         0.475976        0.475463     0.107804         0.302758        0.302222  Experiment37Selected  Experiment37Selected
73      Traffic     TimeMixer      192         0.485080        0.484134     0.195106         0.308746        0.308059  Experiment37Selected  Experiment37Selected
74      Traffic     TimeMixer      336         0.498642        0.497775     0.173904         0.314331        0.313919  Experiment37Selected  Experiment37Selected
75      Traffic     TimeMixer      720         0.532085        0.532115    -0.005637         0.326821        0.326809  Experiment37Selected  Experiment37Selected
76      Traffic  iTransformer       96         0.411162        0.409748     0.344038         0.280601        0.279565  Experiment37Selected  Experiment37Selected
77      Traffic  iTransformer      192         0.428237        0.427547     0.160993         0.286426        0.285632  Experiment37Selected  Experiment37Selected
78      Traffic  iTransformer      336         0.444337        0.445559    -0.274877         0.294481        0.294469  Experiment37Selected  Experiment37Selected
79      Traffic  iTransformer      720         0.477073        0.475326     0.366302         0.312972        0.312189  Experiment37Selected  Experiment37Selected
80      Weather      PatchTST       96         0.149690        0.147440     1.503275         0.197816        0.196418    HistoricalRecovery    HistoricalRecovery
81      Weather      PatchTST      192         0.194775        0.190482     2.203907         0.240853        0.238072    HistoricalRecovery    HistoricalRecovery
82      Weather      PatchTST      336         0.246900        0.241303     2.267156         0.281548        0.279920    HistoricalRecovery    HistoricalRecovery
83      Weather      PatchTST      720         0.320894        0.314066     2.128003         0.334351        0.331704    HistoricalRecovery    HistoricalRecovery
84      Weather        SegMoE       96         0.145017        0.143131     1.300656         0.188652        0.187870  Experiment37Selected  Experiment37Selected
85      Weather        SegMoE      192         0.189425        0.185724     1.953638         0.232275        0.230899  Experiment37Selected  Experiment37Selected
86      Weather        SegMoE      336         0.242209        0.236072     2.533652         0.274053        0.272572  Experiment37Selected  Experiment37Selected
87      Weather        SegMoE      720         0.318339        0.310549     2.446979         0.329092        0.326344  Experiment37Selected  Experiment37Selected
88      Weather     TimeMixer       96         0.162069        0.160429     1.012234         0.207950        0.207385    HistoricalRecovery    HistoricalRecovery
89      Weather     TimeMixer      192         0.208661        0.205513     1.508428         0.252553        0.251106    HistoricalRecovery    HistoricalRecovery
90      Weather     TimeMixer      336         0.263268        0.258681     1.742619         0.290729        0.289736    HistoricalRecovery    HistoricalRecovery
91      Weather     TimeMixer      720         0.344638        0.334318     2.994619         0.343332        0.339776    HistoricalRecovery    HistoricalRecovery
92      Weather  iTransformer       96         0.173287        0.166006     4.201641         0.212210        0.209350    HistoricalRecovery    HistoricalRecovery
93      Weather  iTransformer      192         0.224436        0.214400     4.471502         0.257719        0.253501    HistoricalRecovery    HistoricalRecovery
94      Weather  iTransformer      336         0.282732        0.270471     4.336659         0.299481        0.296607    HistoricalRecovery    HistoricalRecovery
95      Weather  iTransformer      720         0.357908        0.344274     3.809215         0.349720        0.344686    HistoricalRecovery    HistoricalRecovery

Saved paper-ready CSV and LaTeX table.

/tmp/ipykernel_111295/2673915562.py:48: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  latex.to_latex(

## 10. Reviewer-facing completion summary

Desired outcome:

- `Complete MSE pairs: 96/96`
- all gain consistency checks pass.

MAE may have lower coverage depending on which historical experiment family retained it.
That is acceptable: the paper can report full MSE coverage and explicitly state MAE coverage rather than
silently filling missing values.

If MSE reaches 96/96, the next manuscript revision should add:

1. a compact appendix table of Direct MSE → Final MSE,
2. one sentence in Section 6 clarifying that all percentage gains are computed against these frozen
   absolute direct-forecast errors,
3. a scope statement that these are controlled within-backbone comparisons, not a new cross-paper SOTA claim.

In [11]:
print("=" * 118)
print("EXPERIMENT 42 — DIRECT FORECASTER ABSOLUTE-PERFORMANCE AUDIT")
print("=" * 118)

print(
    f"Complete MSE pairs: "
    f"{int(mse_complete.sum())}/96"
)

print(
    f"Complete MAE pairs: "
    f"{int(mae_complete.sum())}/96"
)

print(
    "Maximum MSE-gain consistency error:",
    (
        float(
            full.loc[
                mse_complete,
                "GainConsistencyError",
            ].max()
        )
        if mse_complete.any()
        else np.nan
    ),
)

print("\nMSE source breakdown:")
print(
    full[
        "MSEMetricSource"
    ].value_counts(
        dropna=False
    ).to_string()
)

print("\nMAE source breakdown:")
print(
    full[
        "MAEMetricSource"
    ].value_counts(
        dropna=False
    ).to_string()
)

missing_mse = full[
    ~mse_complete
]

missing_mae = full[
    ~mae_complete
]

if len(missing_mse):
    print("\nMissing MSE conditions:")
    print(
        missing_mse[
            KEY + ["MSEGain_pct"]
        ]
        .sort_values(KEY)
        .to_string(index=False)
    )

if len(missing_mae):
    print(
        f"\nMAE missing for "
        f"{len(missing_mae)}/96 conditions."
    )

print("\nOutputs:")
for name in [
    "direct_final_absolute_metrics_96_conditions.csv",
    "dataset_backbone_absolute_summary.csv",
    "paper_absolute_metrics_96_conditions.csv",
    "paper_absolute_metrics_96_conditions.tex",
]:
    print(" -", OUT_DIR / name)

======================================================================================================================
EXPERIMENT 42 — DIRECT FORECASTER ABSOLUTE-PERFORMANCE AUDIT
======================================================================================================================
Complete MSE pairs: 96/96
Complete MAE pairs: 96/96
Maximum MSE-gain consistency error: 5.051514762044462e-14

MSE source breakdown:
Experiment37Selected    72
HistoricalRecovery      24

MAE source breakdown:
Experiment37Selected    72
HistoricalRecovery      24

Outputs:
 - /data/dataset/strong_forecaster/direct_forecaster_absolute_performance/direct_final_absolute_metrics_96_conditions.csv
 - /data/dataset/strong_forecaster/direct_forecaster_absolute_performance/dataset_backbone_absolute_summary.csv
 - /data/dataset/strong_forecaster/direct_forecaster_absolute_performance/paper_absolute_metrics_96_conditions.csv
 - /data/dataset/strong_forecaster/direct_forecaster_absolute_performance/paper_absolute_metrics_96_conditions.tex