# Long-horizon anchored-L2 on the frozen 24-condition benchmark

Matched protocol:
- 6 datasets × H={96,192,336,720}
- exact Exp33 frozen query/channel manifests
- same-channel memory
- train-only normalization
- L=96, memory stride=8, Top-K=10
- candidate future fully observed before the query memory boundary
- anchored L2 searches the full admissible same-channel memory

Anchored shape: \(\tilde x_t=x_t-x_L\). Candidates are ranked by squared
Euclidean distance between anchored past windows.

The notebook caches each condition and finally compares Anchored L2 with the
current stride-8 Pearson and full PRR frozen results.

In [1]:
from pathlib import Path
import io, time, gc
import numpy as np
import pandas as pd

DATASETS=("ETTh1","Weather","Electricity","Traffic","Exchange","Solar")
HORIZONS=(96,192,336,720)
L=96
MEMORY_STRIDE=8
TOP_K=10

manifest_candidates=[
    Path("/data/code/which_histories_matter_ext/results/exp33/final_eval_manifest"),
    Path("/data/code/stock_regime_retrieval/strong_forecaster/results/exp33/final_eval_manifest"),
]
for base in [Path("/data/code"),Path("/data")]:
    if base.exists():
        manifest_candidates += list(base.glob("*/results/exp33/final_eval_manifest"))
        manifest_candidates += list(base.glob("*/*/results/exp33/final_eval_manifest"))

MANIFEST_ROOT=next((p for p in manifest_candidates if p.exists()),None)
assert MANIFEST_ROOT is not None, "Exp33 frozen manifests not found"

PROJECT_ROOT=MANIFEST_ROOT.parents[2]
OUT_ROOT=PROJECT_ROOT/"results"/"anchored_l2_long_horizon_frozen24"
CACHE_ROOT=OUT_ROOT/"cache"
OUT_ROOT.mkdir(parents=True,exist_ok=True)
CACHE_ROOT.mkdir(parents=True,exist_ok=True)

print("MANIFEST_ROOT:",MANIFEST_ROOT)
print("OUT_ROOT:",OUT_ROOT)

MANIFEST_ROOT: /data/code/which_histories_matter_ext/results/exp33/final_eval_manifest
OUT_ROOT: /data/code/which_histories_matter_ext/results/anchored_l2_long_horizon_frozen24

In [2]:
EXPECTED={"ETTh1":7,"Weather":21,"Electricity":321,"Traffic":862,"Exchange":8,"Solar":137}

CANDIDATES={
  "ETTh1":[
    "/data/Time-Series-Library/dataset/ETT-small/ETTh1.csv",
    "/data/Time-Series-Library_v2/dataset/ETT-small/ETTh1.csv",
    "/data/dataset/ETT-small/ETTh1.csv","/data/dataset/ETTh1.csv"],
  "Weather":[
    "/data/Time-Series-Library/dataset/weather/weather.csv",
    "/data/Time-Series-Library_v2/dataset/weather/weather.csv",
    "/data/dataset/weather/weather.csv","/data/dataset/weather.csv"],
  "Electricity":[
    "/data/Time-Series-Library/dataset/electricity/electricity.csv",
    "/data/Time-Series-Library_v2/dataset/electricity/electricity.csv",
    "/data/dataset/electricity/electricity.csv","/data/dataset/electricity.csv"],
  "Traffic":[
    "/data/Time-Series-Library/dataset/traffic/traffic.csv",
    "/data/Time-Series-Library_v2/dataset/traffic/traffic.csv",
    "/data/dataset/traffic/traffic.csv","/data/dataset/traffic.csv"],
  "Exchange":[
    "/data/Time-Series-Library/dataset/exchange_rate/exchange_rate.csv",
    "/data/Time-Series-Library_v2/dataset/exchange_rate/exchange_rate.csv",
    "/data/dataset/exchange_rate/exchange_rate.csv","/data/dataset/exchange_rate.csv"],
  "Solar":[
    "/data/Time-Series-Library/dataset/Solar/solar_AL.txt",
    "/data/Time-Series-Library_v2/dataset/Solar/solar_AL.txt",
    "/data/dataset/Solar/solar_AL.txt","/data/dataset/solar_AL.txt"],
}

def resolve(name):
    for s in CANDIDATES[name]:
        p=Path(s)
        if p.is_file(): return p
    raise FileNotFoundError(name)

def clean(df):
    return (df.apply(pd.to_numeric,errors="coerce")
              .dropna(axis=1,how="all")
              .replace([np.inf,-np.inf],np.nan)
              .interpolate(axis=0,limit_direction="both")
              .ffill().bfill())

def load_data(name):
    p=resolve(name)
    if name=="Solar":
        df=pd.read_csv(p,header=None)
        if df.shape[1]==1:
            df=pd.read_csv(p,header=None,sep=r"\s+")
        num=clean(df)
    else:
        df=pd.read_csv(p)
        date=next((c for c in df.columns if str(c).lower() in {"date","datetime","timestamp","time"}),None)
        val=df.drop(columns=[date]) if date is not None else df.copy()
        if name in {"Weather","Electricity"} and "OT" in val.columns:
            val=val[[c for c in val.columns if c!="OT"]+["OT"]]
        num=clean(val)

    raw=num.to_numpy(np.float32)
    assert raw.shape[1]==EXPECTED[name],(name,raw.shape)
    n=len(raw)
    if name=="ETTh1":
        assert raw.shape==(17420,7)
        train_end,val_end=8640,11520
    else:
        train_end=int(0.70*n)
        val_end=n-int(0.20*n)
    mu=raw[:train_end].mean(0).astype(np.float32)
    sd=raw[:train_end].std(0,ddof=0).astype(np.float32)
    assert np.all(sd>1e-6)
    z=((raw-mu)/sd).astype(np.float32)
    return dict(path=p,z=z,n=n,channels=raw.shape[1],train_end=train_end,val_end=val_end)

DATA={d:load_data(d) for d in DATASETS}
display(pd.DataFrame([dict(dataset=d,rows=DATA[d]["n"],channels=DATA[d]["channels"],
                           train_end=DATA[d]["train_end"],val_end=DATA[d]["val_end"],
                           path=str(DATA[d]["path"])) for d in DATASETS]))

,dataset,rows,channels,train_end,val_end,path
0,ETTh1,17420,7,8640,11520,/data/Time-Series-Library/dataset/ETT-small/ET...
1,Weather,52696,21,36887,42157,/data/Time-Series-Library/dataset/weather/weat...
2,Electricity,26304,321,18412,21044,/data/Time-Series-Library/dataset/electricity/...
3,Traffic,17544,862,12280,14036,/data/Time-Series-Library/dataset/traffic/traf...
4,Exchange,7588,8,5311,6071,/data/Time-Series-Library/dataset/exchange_rat...
5,Solar,52560,137,36792,42048,/data/Time-Series-Library/dataset/Solar/solar_...

In [3]:
def load_manifest(dataset,horizon,split):
    p=MANIFEST_ROOT/f"{dataset}_H{horizon}_{split}.npz"
    assert p.exists(),p
    with np.load(p,allow_pickle=False) as z:
        a=np.asarray(z["anchor"],np.int64)
        c=np.asarray(z["channel"],np.int64)
    assert a.shape==c.shape and len(a)>0
    return a,c

audit=[]
for d in DATASETS:
    for h in HORIZONS:
        for split in ("val","test"):
            a,c=load_manifest(d,h,split)
            audit.append(dict(dataset=d,horizon=h,split=split,pairs=len(a),channels=len(np.unique(c))))
display(pd.DataFrame(audit))

        dataset  horizon split  pairs  channels
0         ETTh1       96   val   4096         7
1         ETTh1       96  test   8192         7
2         ETTh1      192   val   4096         7
3         ETTh1      192  test   8192         7
4         ETTh1      336   val   4096         7
5         ETTh1      336  test   8192         7
6         ETTh1      720   val   4096         7
7         ETTh1      720  test   8192         7
8       Weather       96   val   4096        21
9       Weather       96  test   8192        21
10      Weather      192   val   4096        21
11      Weather      192  test   8192        21
12      Weather      336   val   4096        21
13      Weather      336  test   8192        21
14      Weather      720   val   4096        21
15      Weather      720  test   8192        21
16  Electricity       96   val   4096       321
17  Electricity       96  test   8192       321
18  Electricity      192   val   4096       321
19  Electricity      192  test   8192       321
20  Electricity      336   val   4096       321
21  Electricity      336  test   8192       321
22  Electricity      720   val   4096       321
23  Electricity      720  test   8192       321
24      Traffic       96   val   4096       862
25      Traffic       96  test   8192       862
26      Traffic      192   val   4096       862
27      Traffic      192  test   8192       862
28      Traffic      336   val   4096       862
29      Traffic      336  test   8192       862
30      Traffic      720   val   4096       862
31      Traffic      720  test   8192       862
32     Exchange       96   val   4096         8
33     Exchange       96  test   8192         8
34     Exchange      192   val   4096         8
35     Exchange      192  test   8192         8
36     Exchange      336   val   3400         8
37     Exchange      336  test   8192         8
38     Exchange      720   val    328         8
39     Exchange      720  test   6384         8
40        Solar       96   val   4096       137
41        Solar       96  test   8192       137
42        Solar      192   val   4096       137
43        Solar      192  test   8192       137
44        Solar      336   val   4096       137
45        Solar      336  test   8192       137
46        Solar      720   val   4096       137
47        Solar      720  test   8192       137

In [4]:
def past_windows(z,ch,anchors):
    anchors=np.asarray(anchors,np.int64)
    idx=anchors[:,None]-L+np.arange(L)[None,:]
    return z[idx,int(ch)].astype(np.float32)

def future_residuals(z,ch,anchors,h):
    anchors=np.asarray(anchors,np.int64)
    idx=anchors[:,None]+np.arange(h)[None,:]
    fut=z[idx,int(ch)].astype(np.float32)
    cur=z[anchors-1,int(ch)].astype(np.float32)
    return (fut-cur[:,None]).astype(np.float32)

def anchored_shape(x):
    x=np.asarray(x,np.float32)
    return (x-x[...,-1:]).astype(np.float32)

def cache_path(d,h,split):
    return CACHE_ROOT/f"{d}_H{h}_{split}_anchored_l2.npz"

def evaluate_condition(dataset,horizon,split="test",query_chunk=128):
    qa,qc=load_manifest(dataset,horizon,split)
    p=cache_path(dataset,horizon,split)

    if p.exists():
        with np.load(p,allow_pickle=False) as zc:
            ca=np.asarray(zc["anchor"],np.int64)
            cc=np.asarray(zc["channel"],np.int64)
            af=np.asarray(zc["analog_mse"],np.float32)
            rf=np.asarray(zc["retrieval_forecast_mse"],np.float32)
            stride=int(np.asarray(zc["memory_stride"]).item())
        if np.array_equal(ca,qa) and np.array_equal(cc,qc) and stride==MEMORY_STRIDE:
            return dict(dataset=dataset,horizon=horizon,split=split,pairs=len(qa),
                        anchored_l2_analog_future_mse=float(af.mean()),
                        anchored_l2_retrieval_forecast_mse=float(rf.mean()),
                        seconds=0.0,cached=True)

    z=DATA[dataset]["z"]
    boundary=DATA[dataset]["train_end"] if split=="val" else DATA[dataset]["val_end"]
    af=np.full(len(qa),np.nan,np.float32)
    rf=np.full(len(qa),np.nan,np.float32)
    t0=time.perf_counter()

    for ch in np.unique(qc):
        rows=np.flatnonzero(qc==ch)
        mem_anchor=np.arange(L,boundary-horizon+1,MEMORY_STRIDE,dtype=np.int64)
        assert len(mem_anchor)>=TOP_K
        assert int(mem_anchor.max())+horizon<=boundary

        mp=past_windows(z,ch,mem_anchor)
        ms=anchored_shape(mp)
        mf=future_residuals(z,ch,mem_anchor,horizon)
        mnorm=np.sum(ms*ms,axis=1)

        for left in range(0,len(rows),query_chunk):
            rr=rows[left:left+query_chunk]
            q_anchor=qa[rr]
            qp=past_windows(z,ch,q_anchor)
            qs=anchored_shape(qp)
            qf=future_residuals(z,ch,q_anchor,horizon)

            qnorm=np.sum(qs*qs,axis=1,keepdims=True)
            d2=np.maximum(qnorm+mnorm[None,:]-2.0*(qs@ms.T),0.0)
            top=np.argpartition(d2,TOP_K-1,axis=1)[:,:TOP_K]

            chosen=mf[top]
            af[rr]=((chosen-qf[:,None,:])**2).mean(axis=2).mean(axis=1).astype(np.float32)
            mean_rel=chosen.mean(axis=1)
            rf[rr]=((mean_rel-qf)**2).mean(axis=1).astype(np.float32)

        print(f"{dataset:11s} H={horizon:3d} ch={int(ch):3d} pairs={len(rows):4d} memory={len(mem_anchor):5d}")

    assert np.isfinite(af).all() and np.isfinite(rf).all()

    np.savez_compressed(
        p,anchor=qa.astype(np.int64),channel=qc.astype(np.int16),
        analog_mse=af,retrieval_forecast_mse=rf,
        memory_boundary=np.asarray(boundary,np.int64),
        memory_stride=np.asarray(MEMORY_STRIDE,np.int64),
        top_k=np.asarray(TOP_K,np.int64),
        retrieval_name=np.asarray("last_value_anchored_L2_full_memory"),
    )

    return dict(dataset=dataset,horizon=horizon,split=split,pairs=len(qa),
                anchored_l2_analog_future_mse=float(af.mean()),
                anchored_l2_retrieval_forecast_mse=float(rf.mean()),
                seconds=float(time.perf_counter()-t0),cached=False)

In [5]:
rows=[]
for d in DATASETS:
    for h in HORIZONS:
        print("\n"+"="*90)
        print("Anchored L2",d,h)
        print("="*90)
        r=evaluate_condition(d,h,"test",128)
        rows.append(r)
        print("AFMSE =",f"{r['anchored_l2_analog_future_mse']:.6f}",
              "| RFMSE =",f"{r['anchored_l2_retrieval_forecast_mse']:.6f}")
        gc.collect()

l2_test24=pd.DataFrame(rows).sort_values(["dataset","horizon"]).reset_index(drop=True)
assert len(l2_test24)==24
display(l2_test24)
l2_test24.to_csv(OUT_ROOT/"anchored_l2_test_24conditions.csv",index=False)

==========================================================================================
Anchored L2 ETTh1 96
==========================================================================================
ETTh1       H= 96 ch=  0 pairs=1170 memory= 1417
ETTh1       H= 96 ch=  1 pairs=1170 memory= 1417
ETTh1       H= 96 ch=  2 pairs=1170 memory= 1417
ETTh1       H= 96 ch=  3 pairs=1170 memory= 1417
ETTh1       H= 96 ch=  4 pairs=1170 memory= 1417
ETTh1       H= 96 ch=  5 pairs=1171 memory= 1417
ETTh1       H= 96 ch=  6 pairs=1171 memory= 1417
AFMSE = 1.100985 | RFMSE = 0.737021

==========================================================================================
Anchored L2 ETTh1 192
==========================================================================================
ETTh1       H=192 ch=  0 pairs=1170 memory= 1405
ETTh1       H=192 ch=  1 pairs=1170 memory= 1405
ETTh1       H=192 ch=  2 pairs=1170 memory= 1405
ETTh1       H=192 ch=  3 pairs=1170 memory= 1405
ETTh1       H=192 ch=  4 pairs=1170 memory= 1405
ETTh1       H=192 ch=  5 pairs=1171 memory= 1405
ETTh1       H=192 ch=  6 pairs=1171 memory= 1405
AFMSE = 1.277228 | RFMSE = 0.828583

==========================================================================================
Anchored L2 ETTh1 336
==========================================================================================
ETTh1       H=336 ch=  0 pairs=1170 memory= 1387
ETTh1       H=336 ch=  1 pairs=1170 memory= 1387
ETTh1       H=336 ch=  2 pairs=1170 memory= 1387
ETTh1       H=336 ch=  3 pairs=1170 memory= 1387
ETTh1       H=336 ch=  4 pairs=1170 memory= 1387
ETTh1       H=336 ch=  5 pairs=1171 memory= 1387
ETTh1       H=336 ch=  6 pairs=1171 memory= 1387
AFMSE = 1.446432 | RFMSE = 0.896594

==========================================================================================
Anchored L2 ETTh1 720
==========================================================================================
ETTh1       H=720 ch=  0 pairs=1170 memory= 1339
ETTh1       H=720 ch=  1 pairs=1170 memory= 1339
ETTh1       H=720 ch=  2 pairs=1170 memory= 1339
ETTh1       H=720 ch=  3 pairs=1170 memory= 1339
ETTh1       H=720 ch=  4 pairs=1170 memory= 1339
ETTh1       H=720 ch=  5 pairs=1171 memory= 1339
ETTh1       H=720 ch=  6 pairs=1171 memory= 1339
AFMSE = 1.714012 | RFMSE = 1.041471

==========================================================================================
Anchored L2 Weather 96
==========================================================================================
Weather     H= 96 ch=  0 pairs= 390 memory= 5246
Weather     H= 96 ch=  1 pairs= 391 memory= 5246
Weather     H= 96 ch=  2 pairs= 390 memory= 5246
Weather     H= 96 ch=  3 pairs= 390 memory= 5246
Weather     H= 96 ch=  4 pairs= 390 memory= 5246
Weather     H= 96 ch=  5 pairs= 390 memory= 5246
Weather     H= 96 ch=  6 pairs= 390 memory= 5246
Weather     H= 96 ch=  7 pairs= 390 memory= 5246
Weather     H= 96 ch=  8 pairs= 390 memory= 5246
Weather     H= 96 ch=  9 pairs= 390 memory= 5246
Weather     H= 96 ch= 10 pairs= 390 memory= 5246
Weather     H= 96 ch= 11 pairs= 390 memory= 5246
Weather     H= 96 ch= 12 pairs= 390 memory= 5246
Weather     H= 96 ch= 13 pairs= 390 memory= 5246
Weather     H= 96 ch= 14 pairs= 390 memory= 5246
Weather     H= 96 ch= 15 pairs= 391 memory= 5246
Weather     H= 96 ch= 16 pairs= 390 memory= 5246
Weather     H= 96 ch= 17 pairs= 390 memory= 5246
Weather     H= 96 ch= 18 pairs= 390 memory= 5246
Weather     H= 96 ch= 19 pairs= 390 memory= 5246
Weather     H= 96 ch= 20 pairs= 390 memory= 5246
AFMSE = 0.839593 | RFMSE = 0.363358

==========================================================================================
Anchored L2 Weather 192
==========================================================================================
Weather     H=192 ch=  0 pairs= 390 memory= 5234
Weather     H=192 ch=  1 pairs= 391 memory= 5234
Weather     H=192 ch=  2 pairs= 390 memory= 5234
Weather     H=192 ch=  3 pairs= 390 memory= 5234
Weather     H=192 ch=  4 pairs= 390 memory= 5234
Weather     H=192 ch=  5 pairs= 390 memory= 5234
Weather     H=192 ch=  6 pairs= 390 memory= 5234
Weather     H=192 ch=  7 pairs= 390 memory= 5234
Weather     H=192 ch=  8 pairs= 390 memory= 5234
Weather     H=192 ch=  9 pairs= 390 memory= 5234
Weather     H=192 ch= 10 pairs= 390 memory= 5234
Weather     H=192 ch= 11 pairs= 390 memory= 5234
Weather     H=192 ch= 12 pairs= 390 memory= 5234
Weather     H=192 ch= 13 pairs= 390 memory= 5234
Weather     H=192 ch= 14 pairs= 390 memory= 5234
Weather     H=192 ch= 15 pairs= 391 memory= 5234
Weather     H=192 ch= 16 pairs= 390 memory= 5234
Weather     H=192 ch= 17 pairs= 390 memory= 5234
Weather     H=192 ch= 18 pairs= 390 memory= 5234
Weather     H=192 ch= 19 pairs= 390 memory= 5234
Weather     H=192 ch= 20 pairs= 390 memory= 5234
AFMSE = 0.785080 | RFMSE = 0.353403

==========================================================================================
Anchored L2 Weather 336
==========================================================================================
Weather     H=336 ch=  0 pairs= 390 memory= 5216
Weather     H=336 ch=  1 pairs= 391 memory= 5216
Weather     H=336 ch=  2 pairs= 390 memory= 5216
Weather     H=336 ch=  3 pairs= 390 memory= 5216
Weather     H=336 ch=  4 pairs= 390 memory= 5216
Weather     H=336 ch=  5 pairs= 390 memory= 5216
Weather     H=336 ch=  6 pairs= 390 memory= 5216
Weather     H=336 ch=  7 pairs= 390 memory= 5216
Weather     H=336 ch=  8 pairs= 390 memory= 5216
Weather     H=336 ch=  9 pairs= 390 memory= 5216
Weather     H=336 ch= 10 pairs= 390 memory= 5216
Weather     H=336 ch= 11 pairs= 390 memory= 5216
Weather     H=336 ch= 12 pairs= 390 memory= 5216
Weather     H=336 ch= 13 pairs= 390 memory= 5216
Weather     H=336 ch= 14 pairs= 390 memory= 5216
Weather     H=336 ch= 15 pairs= 391 memory= 5216
Weather     H=336 ch= 16 pairs= 390 memory= 5216
Weather     H=336 ch= 17 pairs= 390 memory= 5216
Weather     H=336 ch= 18 pairs= 390 memory= 5216
Weather     H=336 ch= 19 pairs= 390 memory= 5216
Weather     H=336 ch= 20 pairs= 390 memory= 5216
AFMSE = 0.594079 | RFMSE = 0.311249

==========================================================================================
Anchored L2 Weather 720
==========================================================================================
Weather     H=720 ch=  0 pairs= 390 memory= 5168
Weather     H=720 ch=  1 pairs= 391 memory= 5168
Weather     H=720 ch=  2 pairs= 390 memory= 5168
Weather     H=720 ch=  3 pairs= 390 memory= 5168
Weather     H=720 ch=  4 pairs= 390 memory= 5168
Weather     H=720 ch=  5 pairs= 390 memory= 5168
Weather     H=720 ch=  6 pairs= 390 memory= 5168
Weather     H=720 ch=  7 pairs= 390 memory= 5168
Weather     H=720 ch=  8 pairs= 390 memory= 5168
Weather     H=720 ch=  9 pairs= 390 memory= 5168
Weather     H=720 ch= 10 pairs= 390 memory= 5168
Weather     H=720 ch= 11 pairs= 390 memory= 5168
Weather     H=720 ch= 12 pairs= 390 memory= 5168
Weather     H=720 ch= 13 pairs= 390 memory= 5168
Weather     H=720 ch= 14 pairs= 390 memory= 5168
Weather     H=720 ch= 15 pairs= 391 memory= 5168
Weather     H=720 ch= 16 pairs= 390 memory= 5168
Weather     H=720 ch= 17 pairs= 390 memory= 5168
Weather     H=720 ch= 18 pairs= 390 memory= 5168
Weather     H=720 ch= 19 pairs= 390 memory= 5168
Weather     H=720 ch= 20 pairs= 390 memory= 5168
AFMSE = 0.769931 | RFMSE = 0.402153

==========================================================================================
Anchored L2 Electricity 96
==========================================================================================
Electricity H= 96 ch=  0 pairs=  26 memory= 2607
Electricity H= 96 ch=  1 pairs=  26 memory= 2607
Electricity H= 96 ch=  2 pairs=  26 memory= 2607
Electricity H= 96 ch=  3 pairs=  26 memory= 2607
Electricity H= 96 ch=  4 pairs=  26 memory= 2607
Electricity H= 96 ch=  5 pairs=  26 memory= 2607
Electricity H= 96 ch=  6 pairs=  26 memory= 2607
Electricity H= 96 ch=  7 pairs=  25 memory= 2607
Electricity H= 96 ch=  8 pairs=  25 memory= 2607
Electricity H= 96 ch=  9 pairs=  26 memory= 2607
Electricity H= 96 ch= 10 pairs=  25 memory= 2607
Electricity H= 96 ch= 11 pairs=  26 memory= 2607
Electricity H= 96 ch= 12 pairs=  25 memory= 2607
Electricity H= 96 ch= 13 pairs=  26 memory= 2607
Electricity H= 96 ch= 14 pairs=  25 memory= 2607
Electricity H= 96 ch= 15 pairs=  26 memory= 2607
Electricity H= 96 ch= 16 pairs=  26 memory= 2607
Electricity H= 96 ch= 17 pairs=  25 memory= 2607
Electricity H= 96 ch= 18 pairs=  26 memory= 2607
Electricity H= 96 ch= 19 pairs=  26 memory= 2607
Electricity H= 96 ch= 20 pairs=  26 memory= 2607
Electricity H= 96 ch= 21 pairs=  25 memory= 2607
Electricity H= 96 ch= 22 pairs=  25 memory= 2607
Electricity H= 96 ch= 23 pairs=  25 memory= 2607
Electricity H= 96 ch= 24 pairs=  26 memory= 2607
Electricity H= 96 ch= 25 pairs=  26 memory= 2607
Electricity H= 96 ch= 26 pairs=  26 memory= 2607
Electricity H= 96 ch= 27 pairs=  26 memory= 2607
Electricity H= 96 ch= 28 pairs=  25 memory= 2607
Electricity H= 96 ch= 29 pairs=  25 memory= 2607
Electricity H= 96 ch= 30 pairs=  25 memory= 2607
Electricity H= 96 ch= 31 pairs=  25 memory= 2607
Electricity H= 96 ch= 32 pairs=  26 memory= 2607
Electricity H= 96 ch= 33 pairs=  26 memory= 2607
Electricity H= 96 ch= 34 pairs=  26 memory= 2607
Electricity H= 96 ch= 35 pairs=  26 memory= 2607
Electricity H= 96 ch= 36 pairs=  25 memory= 2607
Electricity H= 96 ch= 37 pairs=  26 memory= 2607
Electricity H= 96 ch= 38 pairs=  26 memory= 2607
Electricity H= 96 ch= 39 pairs=  26 memory= 2607
Electricity H= 96 ch= 40 pairs=  26 memory= 2607
Electricity H= 96 ch= 41 pairs=  25 memory= 2607
Electricity H= 96 ch= 42 pairs=  26 memory= 2607
Electricity H= 96 ch= 43 pairs=  26 memory= 2607
Electricity H= 96 ch= 44 pairs=  26 memory= 2607
Electricity H= 96 ch= 45 pairs=  26 memory= 2607
Electricity H= 96 ch= 46 pairs=  25 memory= 2607
Electricity H= 96 ch= 47 pairs=  26 memory= 2607
Electricity H= 96 ch= 48 pairs=  25 memory= 2607
Electricity H= 96 ch= 49 pairs=  26 memory= 2607
Electricity H= 96 ch= 50 pairs=  25 memory= 2607
Electricity H= 96 ch= 51 pairs=  25 memory= 2607
Electricity H= 96 ch= 52 pairs=  26 memory= 2607
Electricity H= 96 ch= 53 pairs=  25 memory= 2607
Electricity H= 96 ch= 54 pairs=  26 memory= 2607
Electricity H= 96 ch= 55 pairs=  26 memory= 2607
Electricity H= 96 ch= 56 pairs=  26 memory= 2607
Electricity H= 96 ch= 57 pairs=  25 memory= 2607
Electricity H= 96 ch= 58 pairs=  25 memory= 2607
Electricity H= 96 ch= 59 pairs=  25 memory= 2607
Electricity H= 96 ch= 60 pairs=  25 memory= 2607
Electricity H= 96 ch= 61 pairs=  26 memory= 2607
Electricity H= 96 ch= 62 pairs=  25 memory= 2607
Electricity H= 96 ch= 63 pairs=  25 memory= 2607
Electricity H= 96 ch= 64 pairs=  25 memory= 2607
Electricity H= 96 ch= 65 pairs=  25 memory= 2607
Electricity H= 96 ch= 66 pairs=  25 memory= 2607
Electricity H= 96 ch= 67 pairs=  26 memory= 2607
Electricity H= 96 ch= 68 pairs=  25 memory= 2607
Electricity H= 96 ch= 69 pairs=  26 memory= 2607
Electricity H= 96 ch= 70 pairs=  26 memory= 2607
Electricity H= 96 ch= 71 pairs=  26 memory= 2607
Electricity H= 96 ch= 72 pairs=  26 memory= 2607
Electricity H= 96 ch= 73 pairs=  26 memory= 2607
Electricity H= 96 ch= 74 pairs=  26 memory= 2607
Electricity H= 96 ch= 75 pairs=  26 memory= 2607
Electricity H= 96 ch= 76 pairs=  26 memory= 2607
Electricity H= 96 ch= 77 pairs=  26 memory= 2607
Electricity H= 96 ch= 78 pairs=  26 memory= 2607
Electricity H= 96 ch= 79 pairs=  26 memory= 2607
Electricity H= 96 ch= 80 pairs=  25 memory= 2607
Electricity H= 96 ch= 81 pairs=  25 memory= 2607
Electricity H= 96 ch= 82 pairs=  25 memory= 2607
Electricity H= 96 ch= 83 pairs=  25 memory= 2607
Electricity H= 96 ch= 84 pairs=  25 memory= 2607
Electricity H= 96 ch= 85 pairs=  25 memory= 2607
Electricity H= 96 ch= 86 pairs=  25 memory= 2607
Electricity H= 96 ch= 87 pairs=  26 memory= 2607
Electricity H= 96 ch= 88 pairs=  25 memory= 2607
Electricity H= 96 ch= 89 pairs=  25 memory= 2607
Electricity H= 96 ch= 90 pairs=  26 memory= 2607
Electricity H= 96 ch= 91 pairs=  26 memory= 2607
Electricity H= 96 ch= 92 pairs=  26 memory= 2607
Electricity H= 96 ch= 93 pairs=  25 memory= 2607
Electricity H= 96 ch= 94 pairs=  26 memory= 2607
Electricity H= 96 ch= 95 pairs=  26 memory= 2607
Electricity H= 96 ch= 96 pairs=  26 memory= 2607
Electricity H= 96 ch= 97 pairs=  26 memory= 2607
Electricity H= 96 ch= 98 pairs=  25 memory= 2607
Electricity H= 96 ch= 99 pairs=  26 memory= 2607
Electricity H= 96 ch=100 pairs=  26 memory= 2607
Electricity H= 96 ch=101 pairs=  25 memory= 2607
Electricity H= 96 ch=102 pairs=  26 memory= 2607
Electricity H= 96 ch=103 pairs=  25 memory= 2607
Electricity H= 96 ch=104 pairs=  26 memory= 2607
Electricity H= 96 ch=105 pairs=  25 memory= 2607
Electricity H= 96 ch=106 pairs=  26 memory= 2607
Electricity H= 96 ch=107 pairs=  26 memory= 2607
Electricity H= 96 ch=108 pairs=  25 memory= 2607
Electricity H= 96 ch=109 pairs=  26 memory= 2607
Electricity H= 96 ch=110 pairs=  26 memory= 2607
Electricity H= 96 ch=111 pairs=  25 memory= 2607
Electricity H= 96 ch=112 pairs=  25 memory= 2607
Electricity H= 96 ch=113 pairs=  26 memory= 2607
Electricity H= 96 ch=114 pairs=  25 memory= 2607
Electricity H= 96 ch=115 pairs=  25 memory= 2607
Electricity H= 96 ch=116 pairs=  25 memory= 2607
Electricity H= 96 ch=117 pairs=  26 memory= 2607
Electricity H= 96 ch=118 pairs=  25 memory= 2607
Electricity H= 96 ch=119 pairs=  26 memory= 2607
Electricity H= 96 ch=120 pairs=  26 memory= 2607
Electricity H= 96 ch=121 pairs=  26 memory= 2607
Electricity H= 96 ch=122 pairs=  26 memory= 2607
Electricity H= 96 ch=123 pairs=  25 memory= 2607
Electricity H= 96 ch=124 pairs=  26 memory= 2607
Electricity H= 96 ch=125 pairs=  25 memory= 2607
Electricity H= 96 ch=126 pairs=  25 memory= 2607
Electricity H= 96 ch=127 pairs=  26 memory= 2607
Electricity H= 96 ch=128 pairs=  25 memory= 2607
Electricity H= 96 ch=129 pairs=  26 memory= 2607
Electricity H= 96 ch=130 pairs=  25 memory= 2607
Electricity H= 96 ch=131 pairs=  26 memory= 2607
Electricity H= 96 ch=132 pairs=  25 memory= 2607
Electricity H= 96 ch=133 pairs=  25 memory= 2607
Electricity H= 96 ch=134 pairs=  26 memory= 2607
Electricity H= 96 ch=135 pairs=  26 memory= 2607
Electricity H= 96 ch=136 pairs=  26 memory= 2607
Electricity H= 96 ch=137 pairs=  26 memory= 2607
Electricity H= 96 ch=138 pairs=  26 memory= 2607
Electricity H= 96 ch=139 pairs=  25 memory= 2607
Electricity H= 96 ch=140 pairs=  26 memory= 2607
Electricity H= 96 ch=141 pairs=  26 memory= 2607
Electricity H= 96 ch=142 pairs=  26 memory= 2607
Electricity H= 96 ch=143 pairs=  26 memory= 2607
Electricity H= 96 ch=144 pairs=  25 memory= 2607
Electricity H= 96 ch=145 pairs=  26 memory= 2607
Electricity H= 96 ch=146 pairs=  25 memory= 2607
Electricity H= 96 ch=147 pairs=  25 memory= 2607
Electricity H= 96 ch=148 pairs=  25 memory= 2607
Electricity H= 96 ch=149 pairs=  26 memory= 2607
Electricity H= 96 ch=150 pairs=  26 memory= 2607
Electricity H= 96 ch=151 pairs=  25 memory= 2607
Electricity H= 96 ch=152 pairs=  25 memory= 2607
Electricity H= 96 ch=153 pairs=  25 memory= 2607
Electricity H= 96 ch=154 pairs=  26 memory= 2607
Electricity H= 96 ch=155 pairs=  26 memory= 2607
Electricity H= 96 ch=156 pairs=  26 memory= 2607
Electricity H= 96 ch=157 pairs=  25 memory= 2607
Electricity H= 96 ch=158 pairs=  25 memory= 2607
Electricity H= 96 ch=159 pairs=  26 memory= 2607
Electricity H= 96 ch=160 pairs=  26 memory= 2607
Electricity H= 96 ch=161 pairs=  25 memory= 2607
Electricity H= 96 ch=162 pairs=  26 memory= 2607
Electricity H= 96 ch=163 pairs=  25 memory= 2607
Electricity H= 96 ch=164 pairs=  26 memory= 2607
Electricity H= 96 ch=165 pairs=  25 memory= 2607
Electricity H= 96 ch=166 pairs=  25 memory= 2607
Electricity H= 96 ch=167 pairs=  26 memory= 2607
Electricity H= 96 ch=168 pairs=  25 memory= 2607
Electricity H= 96 ch=169 pairs=  25 memory= 2607
Electricity H= 96 ch=170 pairs=  26 memory= 2607
Electricity H= 96 ch=171 pairs=  25 memory= 2607
Electricity H= 96 ch=172 pairs=  25 memory= 2607
Electricity H= 96 ch=173 pairs=  26 memory= 2607
Electricity H= 96 ch=174 pairs=  25 memory= 2607
Electricity H= 96 ch=175 pairs=  25 memory= 2607
Electricity H= 96 ch=176 pairs=  25 memory= 2607
Electricity H= 96 ch=177 pairs=  26 memory= 2607
Electricity H= 96 ch=178 pairs=  25 memory= 2607
Electricity H= 96 ch=179 pairs=  26 memory= 2607
Electricity H= 96 ch=180 pairs=  26 memory= 2607
Electricity H= 96 ch=181 pairs=  26 memory= 2607
Electricity H= 96 ch=182 pairs=  26 memory= 2607
Electricity H= 96 ch=183 pairs=  25 memory= 2607
Electricity H= 96 ch=184 pairs=  26 memory= 2607
Electricity H= 96 ch=185 pairs=  26 memory= 2607
Electricity H= 96 ch=186 pairs=  26 memory= 2607
Electricity H= 96 ch=187 pairs=  25 memory= 2607
Electricity H= 96 ch=188 pairs=  26 memory= 2607
Electricity H= 96 ch=189 pairs=  25 memory= 2607
Electricity H= 96 ch=190 pairs=  25 memory= 2607
Electricity H= 96 ch=191 pairs=  26 memory= 2607
Electricity H= 96 ch=192 pairs=  26 memory= 2607
Electricity H= 96 ch=193 pairs=  25 memory= 2607
Electricity H= 96 ch=194 pairs=  25 memory= 2607
Electricity H= 96 ch=195 pairs=  25 memory= 2607
Electricity H= 96 ch=196 pairs=  26 memory= 2607
Electricity H= 96 ch=197 pairs=  26 memory= 2607
Electricity H= 96 ch=198 pairs=  25 memory= 2607
Electricity H= 96 ch=199 pairs=  26 memory= 2607
Electricity H= 96 ch=200 pairs=  25 memory= 2607
Electricity H= 96 ch=201 pairs=  26 memory= 2607
Electricity H= 96 ch=202 pairs=  25 memory= 2607
Electricity H= 96 ch=203 pairs=  26 memory= 2607
Electricity H= 96 ch=204 pairs=  26 memory= 2607
Electricity H= 96 ch=205 pairs=  25 memory= 2607
Electricity H= 96 ch=206 pairs=  26 memory= 2607
Electricity H= 96 ch=207 pairs=  25 memory= 2607
Electricity H= 96 ch=208 pairs=  26 memory= 2607
Electricity H= 96 ch=209 pairs=  25 memory= 2607
Electricity H= 96 ch=210 pairs=  26 memory= 2607
Electricity H= 96 ch=211 pairs=  26 memory= 2607
Electricity H= 96 ch=212 pairs=  25 memory= 2607
Electricity H= 96 ch=213 pairs=  26 memory= 2607
Electricity H= 96 ch=214 pairs=  26 memory= 2607
Electricity H= 96 ch=215 pairs=  25 memory= 2607
Electricity H= 96 ch=216 pairs=  26 memory= 2607
Electricity H= 96 ch=217 pairs=  25 memory= 2607
Electricity H= 96 ch=218 pairs=  25 memory= 2607
Electricity H= 96 ch=219 pairs=  25 memory= 2607
Electricity H= 96 ch=220 pairs=  25 memory= 2607
Electricity H= 96 ch=221 pairs=  26 memory= 2607
Electricity H= 96 ch=222 pairs=  25 memory= 2607
Electricity H= 96 ch=223 pairs=  25 memory= 2607
Electricity H= 96 ch=224 pairs=  25 memory= 2607
Electricity H= 96 ch=225 pairs=  26 memory= 2607
Electricity H= 96 ch=226 pairs=  26 memory= 2607
Electricity H= 96 ch=227 pairs=  26 memory= 2607
Electricity H= 96 ch=228 pairs=  26 memory= 2607
Electricity H= 96 ch=229 pairs=  25 memory= 2607
Electricity H= 96 ch=230 pairs=  26 memory= 2607
Electricity H= 96 ch=231 pairs=  26 memory= 2607
Electricity H= 96 ch=232 pairs=  25 memory= 2607
Electricity H= 96 ch=233 pairs=  26 memory= 2607
Electricity H= 96 ch=234 pairs=  25 memory= 2607
Electricity H= 96 ch=235 pairs=  25 memory= 2607
Electricity H= 96 ch=236 pairs=  25 memory= 2607
Electricity H= 96 ch=237 pairs=  26 memory= 2607
Electricity H= 96 ch=238 pairs=  25 memory= 2607
Electricity H= 96 ch=239 pairs=  25 memory= 2607
Electricity H= 96 ch=240 pairs=  26 memory= 2607
Electricity H= 96 ch=241 pairs=  25 memory= 2607
Electricity H= 96 ch=242 pairs=  25 memory= 2607
Electricity H= 96 ch=243 pairs=  26 memory= 2607
Electricity H= 96 ch=244 pairs=  25 memory= 2607
Electricity H= 96 ch=245 pairs=  25 memory= 2607
Electricity H= 96 ch=246 pairs=  25 memory= 2607
Electricity H= 96 ch=247 pairs=  26 memory= 2607
Electricity H= 96 ch=248 pairs=  26 memory= 2607
Electricity H= 96 ch=249 pairs=  26 memory= 2607
Electricity H= 96 ch=250 pairs=  25 memory= 2607
Electricity H= 96 ch=251 pairs=  25 memory= 2607

,dataset,horizon,split,pairs,anchored_l2_analog_future_mse,anchored_l2_retrieval_forecast_mse,seconds,cached
0,ETTh1,96,test,8192,1.100985,0.737021,0.274296,False
1,ETTh1,192,test,8192,1.277228,0.828583,0.284617,False
2,ETTh1,336,test,8192,1.446432,0.896594,0.297704,False
3,ETTh1,720,test,8192,1.714012,1.041471,0.364680,False
4,Electricity,96,test,8192,0.703011,0.536853,1.920945,False
5,Electricity,192,test,8192,0.728439,0.552923,2.471330,False
6,Electricity,336,test,8192,0.768702,0.574455,3.384150,False
7,Electricity,720,test,8192,0.815970,0.601393,5.771160,False
8,Exchange,96,test,8192,0.186254,0.104771,0.134584,False
9,Exchange,192,test,8192,0.379211,0.220980,0.152838,False
10,Exchange,336,test,8192,0.684537,0.409079,0.173954,False
11,Exchange,720,test,6384,1.865029,1.220104,0.204552,False
12,Solar,96,test,8192,0.488054,0.265460,1.670214,False
13,Solar,192,test,8192,0.518212,0.283629,2.295770,False
14,Solar,336,test,8192,0.533977,0.292351,2.973766,False
15,Solar,720,test,8192,0.527471,0.288582,5.317584,False
16,Traffic,96,test,8192,1.420632,1.050291,3.575449,False
17,Traffic,192,test,8192,1.355879,1.010499,3.883743,False
18,Traffic,336,test,8192,1.424405,1.049620,5.738654,False
19,Traffic,720,test,8192,1.595257,1.197356,9.817089,False
20,Weather,96,test,8192,0.839593,0.363358,0.661295,False
21,Weather,192,test,8192,0.785080,0.353403,0.774913,False
22,Weather,336,test,8192,0.594079,0.311249,0.947468,False
23,Weather,720,test,8192,0.769931,0.402153,1.296651,False

In [6]:
REFERENCE_CSV = '''dataset,horizon,pearson,prr
ETTh1,96,1.6123,1.1643
ETTh1,192,1.8175,1.2229
ETTh1,336,1.9929,1.4816
ETTh1,720,2.2541,1.4618
Weather,96,1.1613,0.4316
Weather,192,1.0628,0.5147
Weather,336,1.2910,0.6748
Weather,720,1.2958,0.8130
Electricity,96,1.1796,0.7191
Electricity,192,1.1957,0.7345
Electricity,336,1.2418,0.7648
Electricity,720,1.2877,0.8602
Traffic,96,1.9738,1.4696
Traffic,192,2.0045,1.4508
Traffic,336,2.0636,1.5147
Traffic,720,2.1665,1.7351
Exchange,96,0.2133,0.1652
Exchange,192,0.4234,0.4116
Exchange,336,0.7643,0.8094
Exchange,720,1.8868,1.7770
Solar,96,0.5887,0.5087
Solar,192,0.5979,0.5406
Solar,336,0.6238,0.5701
Solar,720,0.6385,0.5507
'''
reference=pd.read_csv(io.StringIO(REFERENCE_CSV))
reference["dataset"]=reference["dataset"].str.strip()
reference["horizon"]=reference["horizon"].astype(int)

precise=PROJECT_ROOT/"results"/"stride8_revalidation"/"table1_stride8_revalidated.csv"
if precise.exists():
    tmp=pd.read_csv(precise)
    tmp["horizon"]=tmp["horizon"].astype(int)
    need={"dataset","horizon","pearson_analog_future_mse","prr_analog_future_mse"}
    if need.issubset(tmp.columns):
        reference=tmp[["dataset","horizon","pearson_analog_future_mse","prr_analog_future_mse"]].rename(
            columns={"pearson_analog_future_mse":"pearson","prr_analog_future_mse":"prr"}
        )
        print("[REFERENCE] precise stride-8 table:",precise)
    else:
        print("[REFERENCE] embedded paper-facing values")
else:
    print("[REFERENCE] embedded paper-facing values")

display(reference)

[REFERENCE] precise stride-8 table: /data/code/which_histories_matter_ext/results/stride8_revalidation/table1_stride8_revalidated.csv

        dataset  horizon   pearson     prr
0         ETTh1       96  1.612267  1.1643
1         ETTh1      192  1.817531  1.2229
2         ETTh1      336  1.992872  1.4816
3         ETTh1      720  2.254092  1.4618
4   Electricity       96  1.179589  0.7191
5   Electricity      192  1.195698  0.7345
6   Electricity      336  1.241844  0.7648
7   Electricity      720  1.287729  0.8602
8      Exchange       96  0.213266  0.1652
9      Exchange      192  0.423408  0.4116
10     Exchange      336  0.764282  0.8094
11     Exchange      720  1.886809  1.7770
12        Solar       96  0.588674  0.5087
13        Solar      192  0.597890  0.5406
14        Solar      336  0.623836  0.5701
15        Solar      720  0.638530  0.5507
16      Traffic       96  1.973787  1.4696
17      Traffic      192  2.004524  1.4508
18      Traffic      336  2.063635  1.5147
19      Traffic      720  2.166454  1.7351
20      Weather       96  1.161329  0.4316
21      Weather      192  1.062809  0.5147
22      Weather      336  1.290959  0.6748
23      Weather      720  1.295817  0.8130

In [7]:
comp=l2_test24.merge(reference,on=["dataset","horizon"],how="inner")
assert len(comp)==24
comp["anchored_l2"]=comp["anchored_l2_analog_future_mse"]

comp["l2_gain_vs_pearson_pct"]=100*(comp["pearson"]-comp["anchored_l2"])/comp["pearson"]
comp["prr_gain_vs_l2_pct"]=100*(comp["anchored_l2"]-comp["prr"])/comp["anchored_l2"]
comp["l2_gain_vs_prr_pct"]=100*(comp["prr"]-comp["anchored_l2"])/comp["prr"]

def summarize(x,name):
    x=np.asarray(x,float)
    return dict(
        comparison=name,
        W=int((x>1e-12).sum()),
        T=int((np.abs(x)<=1e-12).sum()),
        L=int((x<-1e-12).sum()),
        mean_gain_pct=float(x.mean()),
        median_gain_pct=float(np.median(x)),
    )

summary=pd.DataFrame([
    summarize(comp["l2_gain_vs_pearson_pct"],"Anchored L2 vs Pearson"),
    summarize(comp["prr_gain_vs_l2_pct"],"PRR vs Anchored L2"),
    summarize(comp["l2_gain_vs_prr_pct"],"Anchored L2 vs PRR"),
])

display(comp[["dataset","horizon","pearson","anchored_l2","prr",
              "l2_gain_vs_pearson_pct","prr_gain_vs_l2_pct"]])
display(summary)

comp.to_csv(OUT_ROOT/"anchored_l2_vs_pearson_prr_24conditions.csv",index=False)
summary.to_csv(OUT_ROOT/"anchored_l2_summary.csv",index=False)

,dataset,horizon,pearson,anchored_l2,prr,l2_gain_vs_pearson_pct,prr_gain_vs_l2_pct
0,ETTh1,96,1.612267,1.100985,1.1643,31.711976,-5.750732
1,ETTh1,192,1.817531,1.277228,1.2229,29.727267,4.253613
2,ETTh1,336,1.992872,1.446432,1.4816,27.419710,-2.431354
3,ETTh1,720,2.254092,1.714012,1.4618,23.959992,14.714712
4,Electricity,96,1.179589,0.703011,0.7191,40.402065,-2.288649
5,Electricity,192,1.195698,0.728439,0.7345,39.078333,-0.831999
6,Electricity,336,1.241844,0.768702,0.7648,38.099943,0.507613
7,Electricity,720,1.287729,0.815970,0.8602,36.634978,-5.420580
8,Exchange,96,0.213266,0.186254,0.1652,12.665825,11.304072
9,Exchange,192,0.423408,0.379211,0.4116,10.438392,-8.541067
10,Exchange,336,0.764282,0.684537,0.8094,10.433894,-18.240444
11,Exchange,720,1.886809,1.865029,1.7770,1.154324,4.720003
12,Solar,96,0.588674,0.488054,0.5087,17.092701,-4.230319
13,Solar,192,0.597890,0.518212,0.5406,13.326653,-4.320319
14,Solar,336,0.623836,0.533977,0.5701,14.404270,-6.764844
15,Solar,720,0.638530,0.527471,0.5507,17.392919,-4.403784
16,Traffic,96,1.973787,1.420632,1.4696,28.025073,-3.446925
17,Traffic,192,2.004524,1.355879,1.4508,32.359054,-7.000674
18,Traffic,336,2.063635,1.424405,1.5147,30.975895,-6.339113
19,Traffic,720,2.166454,1.595257,1.7351,26.365519,-8.766171
20,Weather,96,1.161329,0.839593,0.4316,27.704135,48.594122
21,Weather,192,1.062809,0.785080,0.5147,26.131676,34.439764
22,Weather,336,1.290959,0.594079,0.6748,53.981565,-13.587583
23,Weather,720,1.295817,0.769931,0.8130,40.583365,-5.593916

               comparison   W  T   L  mean_gain_pct  median_gain_pct
0  Anchored L2 vs Pearson  24  0   0      26.252897        27.561922
1      PRR vs Anchored L2   7  0  17       0.440643        -4.275319
2      Anchored L2 vs PRR  17  0   7      -3.656057         4.100012

In [8]:
ds=[]
for d,g in comp.groupby("dataset",sort=False):
    ds.append(dict(
        dataset=d,
        L2_vs_Pearson_W=int((g.l2_gain_vs_pearson_pct>0).sum()),
        L2_vs_Pearson_mean_pct=float(g.l2_gain_vs_pearson_pct.mean()),
        PRR_vs_L2_W=int((g.prr_gain_vs_l2_pct>0).sum()),
        PRR_vs_L2_mean_pct=float(g.prr_gain_vs_l2_pct.mean()),
    ))
ds_summary=pd.DataFrame(ds)
display(ds_summary)
ds_summary.to_csv(OUT_ROOT/"anchored_l2_dataset_summary.csv",index=False)

,dataset,L2_vs_Pearson_W,L2_vs_Pearson_mean_pct,PRR_vs_L2_W,PRR_vs_L2_mean_pct
0,ETTh1,4,28.204736,2,2.696560
1,Electricity,4,38.553830,1,-2.008404
2,Exchange,4,8.673109,2,-2.689359
3,Solar,4,15.554136,0,-4.929817
4,Traffic,4,29.431385,0,-6.388221
5,Weather,4,37.100185,2,15.963096

In [9]:
paper=comp[["dataset","horizon","pearson","anchored_l2","prr",
            "l2_gain_vs_pearson_pct","prr_gain_vs_l2_pct"]].copy()
for c in ["pearson","anchored_l2","prr"]:
    paper[c]=paper[c].map(lambda x:f"{x:.4f}")
for c in ["l2_gain_vs_pearson_pct","prr_gain_vs_l2_pct"]:
    paper[c]=paper[c].map(lambda x:f"{x:+.2f}%")

paper=paper.rename(columns={
    "dataset":"Dataset","horizon":"H","pearson":"Pearson",
    "anchored_l2":"Anchored L2","prr":"PRR (ours)",
    "l2_gain_vs_pearson_pct":"L2 gain vs. Pearson",
    "prr_gain_vs_l2_pct":"PRR gain vs. L2",
})
display(paper)
paper.to_csv(OUT_ROOT/"paper_table_anchored_l2_long_horizon.csv",index=False)

print("\nFINAL SUMMARY")
for r in summary.itertuples(index=False):
    print(f"{r.comparison}: {r.W}W/{r.T}T/{r.L}L | mean={r.mean_gain_pct:+.2f}% | median={r.median_gain_pct:+.2f}%")
print("\nSaved under:",OUT_ROOT)

,Dataset,H,Pearson,Anchored L2,PRR (ours),L2 gain vs. Pearson,PRR gain vs. L2
0,ETTh1,96,1.6123,1.1010,1.1643,+31.71%,-5.75%
1,ETTh1,192,1.8175,1.2772,1.2229,+29.73%,+4.25%
2,ETTh1,336,1.9929,1.4464,1.4816,+27.42%,-2.43%
3,ETTh1,720,2.2541,1.7140,1.4618,+23.96%,+14.71%
4,Electricity,96,1.1796,0.7030,0.7191,+40.40%,-2.29%
5,Electricity,192,1.1957,0.7284,0.7345,+39.08%,-0.83%
6,Electricity,336,1.2418,0.7687,0.7648,+38.10%,+0.51%
7,Electricity,720,1.2877,0.8160,0.8602,+36.63%,-5.42%
8,Exchange,96,0.2133,0.1863,0.1652,+12.67%,+11.30%
9,Exchange,192,0.4234,0.3792,0.4116,+10.44%,-8.54%
10,Exchange,336,0.7643,0.6845,0.8094,+10.43%,-18.24%
11,Exchange,720,1.8868,1.8650,1.7770,+1.15%,+4.72%
12,Solar,96,0.5887,0.4881,0.5087,+17.09%,-4.23%
13,Solar,192,0.5979,0.5182,0.5406,+13.33%,-4.32%
14,Solar,336,0.6238,0.5340,0.5701,+14.40%,-6.76%
15,Solar,720,0.6385,0.5275,0.5507,+17.39%,-4.40%
16,Traffic,96,1.9738,1.4206,1.4696,+28.03%,-3.45%
17,Traffic,192,2.0045,1.3559,1.4508,+32.36%,-7.00%
18,Traffic,336,2.0636,1.4244,1.5147,+30.98%,-6.34%
19,Traffic,720,2.1665,1.5953,1.7351,+26.37%,-8.77%
20,Weather,96,1.1613,0.8396,0.4316,+27.70%,+48.59%
21,Weather,192,1.0628,0.7851,0.5147,+26.13%,+34.44%
22,Weather,336,1.2910,0.5941,0.6748,+53.98%,-13.59%
23,Weather,720,1.2958,0.7699,0.8130,+40.58%,-5.59%

FINAL SUMMARY
Anchored L2 vs Pearson: 24W/0T/0L | mean=+26.25% | median=+27.56%
PRR vs Anchored L2: 7W/0T/17L | mean=+0.44% | median=-4.28%
Anchored L2 vs PRR: 17W/0T/7L | mean=-3.66% | median=+4.10%

Saved under: /data/code/which_histories_matter_ext/results/anchored_l2_long_horizon_frozen24